### ISSUE TITLE
Heroku Production Server

### ISSUE THREAD

**Issue by klinker41** [klinker-apps/messenger-issues#10]
We'll need to start paying for Heroku once we roll out the app to beta testers.

We'll need at least the "Standard" plan, which allows for simple horizontal scalability and multiple dynos.

![screen shot 2016-08-15 at 10 25 22 am](https://cloud.githubusercontent.com/assets/4501322/17669281/b3fbfbaa-62d2-11e6-9036-393d9153bc27.png)

One thing that it doesn't talk about on that site is whether or not we can set a max number of dynos and it would use less than that when we don't need them, saving us money. Hopefully that is the case, but definitely during beta testing we can just start with one and move up from there as needed. Each is $25 and we can definitely do more as we start to make more money from users.

They have an add-on for $18 a month that helps with scaling 1-4 dynos: https://elements.heroku.com/addons/adept-scale.

This would probably be worth it and save us money instead of just paying for the 2nd, 3rd or 4th dyno. Less worrying as well if we pick up traffic significantly. There are also different levels of this add-on that cost more when you have more dynos, so will be easy to scale when we need to.

**Comment by klinker24** [comment]
I have added the `adept-scaling` plugin to `Heroku`. Will be monitoring the performance over the next few hours/days.
