### ISSUE TITLE
Resend failed SMS

### ISSUE THREAD

**Issue by drewksparks** [klinker-apps/messenger-issues#100]
_Edited by @klinker24_

**Device with issue:** Android Devices
**App version:** 1.4.365
**Steps to reproduce:**

1. Turn on airplane mode
2. Try to send a message and watch it fail

**Possible solution:**

Add a "resend" option to the long click menu.

**Comment by klinker24** [comment]
Finished with: https://github.com/klinker41/messenger/commit/4893c8c226603d7ee4f765a82d7a2f79c639a7bb
