### ISSUE TITLE
Add support for smsto: protocol handling

### ISSUE THREAD

**Issue by jor77** [klinker-apps/messenger-issues#102]
One useful addition could be to make messenger app or site register itself for handling smsto: protocol, so we can have smsto: link on a webpage opening the app (is possible?) or the website, ready to send the message pepopulating message text or other properties...

Link would be something similar to : 
<a href="smsto:123456789?content=Happy%20New%20Year&scheduleat=31-12-2016:23:59">
   Send a "Happy New Year" message
</a>

Please see:
https://developer.mozilla.org/it/docs/Web-based_protocol_handlers

**Comment by klinker24** [comment]
Yes this should be possible, thanks: http://android-developers.blogspot.com/2013/10/getting-your-sms-apps-ready-for-kitkat.html

**Comment by klinker24** [comment]
An example jsfiddle to test: https://jsfiddle.net/3y00wxkg/

Messenger is able to handle the `Intent` currently, but doesn't populate the "to" field in the UI

**Comment by klinker24** [comment]
Seems like it is harder to get that number than I thought. This are the extras in the intent:

```
Intent action = android.intent.action.VIEW

// bundle contents (key = value)
org.chromium.chrome.browser.eenp = []
org.chromium.chrome.browser.user_gesture_token = [B@f93324b
com.android.browser.application_id = com.chrome.beta
```

I will have to see if the user gesture token contains any information on this that can be used. If not, then Android itself doesn't seem like it can handle this, which doesn't seem right, but I am not sure yet.

**Comment by klinker24** [comment]
So after some investigation with reflection, the `user_gesture_token` is simply a byte array. That isn't going to help us at all.

@jor77 do you know any apps that actually have this working? Seems to me as though Android (at least Chrome) doesn't have any way to forward us the phone numbers.

**Comment by klinker41** [comment]
Did you try turning the byte array into a string? `new String(byte[])` might work. I don't know what the encoding would be on the string though, you'd probably want to pass that into the constructor as well.

**Comment by klinker24** [comment]
All the `StandardCharset` just gave me garbage. This is a third party thing that has this intent extra... 

https://github.com/crosswalk-project/chromium-crosswalk/blob/master/chrome/android/java/src/org/chromium/chrome/browser/externalnav/IntentWithGesturesHandler.java

On this one, it is literally just a blank `byte` array with 32 slots. 

Not sure what to do about this one.

**Comment by klinker24** [comment]
Going to give another stab at this one, perhaps the data portion of the intent will contain the `smsto:xxxx` information?

http://stackoverflow.com/a/11465619

**Comment by klinker24** [comment]
There, done with: https://github.com/klinker41/messenger/commit/26f1e7c38d4b2847c1d2b63a9da2683741bca53f
