### ISSUE TITLE
Notifications don't display via Moto Display

### ISSUE THREAD

**Issue by nkm8** [klinker-apps/messenger-issues#104]
### Notifications don't display via Moto Display

**Device with issue:** Motorola Droid Turbo running Android 5.1
**Primary device:** Motorola Droid Turbo running Android 5.1
**App version:** 1.4.1.380
**Steps to reproduce:**
1. Receive a notification via Messenger
2. Phone vibrates and plays notification ringtone
3. Screen is off and device is locked
4. When activating Moto Display by moving hand towards phone, Moto Display does not show any available notifications to preview

**Additional information:**

Information is tough to find, but I found a few things to check:
1. Moto display only supports bitmap images, not vector
2. Call .setGroupSummary(true)
3. Notification cannot be permanent/persistent

I did confirm that Messenger notifications display properly in Ambient Display, so it is definitely a unique quirk with Moto Display.

Sources:
http://stackoverflow.com/questions/36372449/showing-notifications-on-motorola-active-display
http://stackoverflow.com/questions/36890362/notifications-in-moto-display
https://forums.lenovo.com/t5/MOTO-X-2nd-Gen/Some-notifications-not-appearing-on-Moto-Display/td-p/3051601

**Possible solution:**

Messenger Notifications work in Android Ambient Display as a workaround, but it would be awesome to get Moto Display working.

**Comment by klinker24** [comment]
I really don't know, sorry, I already do all of those things mentioned. Unless Moto has some specific documentation, your workaround may have to do the trick.

**Comment by klinker24** [comment]
Some users have mentioned that the summary notifications are displayed, which is interesting.

**Comment by klinker24** [comment]
I have actually made some changes for this. With the next version, whenever there is only a single notification, it will be set as the `groupSummary`.

This really isn't a good way to do this feature. Android Wear and Android Nougat have a very specific purpose for this group summary flag. It should work fine now (I hope), but I will monitor this for any adverse effects.

**Comment by nkm8** [comment]
@klinker24 Confirmed as fixed in the latest version of Pulse - thanks!

I agree; it is odd that this is required, but it is even more strange that Pulse is the only app that I have ever seen not work with Moto Display.  So, for whatever reason, most/all other apps are using `groupSummary` as well.

**Comment by klinker41** [comment]
No, most other apps have not upgraded to the most modern notifications is more likely. Moto needs to start supporting these better or else you'll start to see more apps not working.

**Comment by Groberto** [comment]
I have got exactly the same issue now: on my Moto X (2nd gen) with Motorola Active Display, Pulse is the only app where notifications don't appear on the lockscreen
