### ISSUE TITLE
Duplicate conversations with some contacts

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#106]
**Device with issue:** Android Phone
**App version:** 1.5.2
**Steps to Reproduce:**

(inconsistent)
1. Login to the app and sync your messages
2. Start a new conversation with the FAB
3. Select one of the contacts that already has a conversation
4. Notice that it doesn't open the conversation that is already active, but creates a new one
5. When you receive a reply, it goes to the original conversation, not the newly created one.

**Additional Information:**

I have not been able to reproduce this issue, but there is a conversation of it here: 
https://plus.google.com/116208058151828925820/posts/DEVK4EJseUL

![duplicate-convos](https://cloud.githubusercontent.com/assets/4874287/18953886/2ac017d8-8616-11e6-8d46-85572eefa1c6.png)

It seems as though the matching isn't working. Currently, we use the last 5 digits of the phone number to match against and find if the conversation is already started or not. Could there be spaces or other characters that are not being extracted from that last 5 characters from the compose screen? 

Extra characters that could be in a phone number include:

`()[] -+.`

**Possible solution:**

Use a regular expression to rip out any of these extra characters from the contacts number, on the compose screen.

**Comment by klinker24** [comment]
@klinker41 do you see any other way that this could be happening or know of any other special characters that can be contained in a phone number? I see we use an internal android method to clear out these characters (`PhoneNumberUtils#clearFormatting`) on the compose activity to get the phone numbers, which uses an internal android method.

Could this method return different results for what is stored in the contacts db vs what is received from the carrier?

**Comment by klinker41** [comment]
I've tried to think of different ways but haven't come up with anything yet.

**Comment by klinker24** [comment]
If it is an individual conversation, I might try to add a method to find the conversation id by conversation title, if it fails to find it by number. This would at least solve the problem for individual conversations, group conversations probably aren't a huge issue, because they are not recreated nearly as often, just out of convenience. 

This is a silly double check, I would rather find the root of the issue, but it will have to work for now.

**Comment by klinker24** [comment]
Implemented workaround with: https://github.com/klinker41/messenger/commit/5354cf4ee247c35f467458a41fe2f5a838331c28
