### ISSUE TITLE
Android material dark blue-grey color theme

### ISSUE THREAD

**Issue by dar-irl** [klinker-apps/messenger-issues#108]
I'd love to see a messenger theme that has more stock-based colors. The blue-grey theme is a step in the right direction, but the colors aren't quite right. Here are the dark blue-grey color codes according to Google's material design guidelines:

Primary Color: #263238
Secondary Color (Darker color, for status bar): #21272B

**Comment by klinker24** [comment]
Those are not the colors on their palette... https://material.google.com/style/color.html#color-color-palette

**Comment by klinker24** [comment]
Going to go ahead and close this one, unless you want to go into more detail about what you are looking for and why you want that color over the official ones?
