### ISSUE TITLE
Camera viewfinder does not expand

### ISSUE THREAD

**Issue by maguilar60** [klinker-apps/messenger-issues#111]
**Device with issue:** Nexus 6 running Android 6.0.1
**Primary device:** Nexus 6 running Android 6.0.1
**App version:** 1.6.0.448
**Steps to reproduce:**

1. Go into any conversation
2. Click on "Add media" button (paperclip)
3. Select Camera tab
4. Camera viewfinder does not expand to allow full view of picture to be taken

**Additional information:**

Issue applies to both back and front facing camera. Once picture is taken, it is shown in full resolution. Viewfinder preview is simply cropped and cannot be expanded.

**Possible solution:**

Allow expansion of viewfinder by pulling up within viewfinder region. Allow user to exit out of viewfinder without taking photo through exit button in corner

**Comment by klinker24** [comment]
Closed with: https://github.com/klinker41/messenger/commit/63df3707ae3595ac7ecc9703e611c09bfadae04e and https://github.com/klinker41/messenger/commit/a4e248ab9dbbf4834cc7f59771cd5822744c5e0f
