### ISSUE TITLE
Custom contact quick shortcut

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#115]
**Request:**

Android 7.1 adds the ability to do dynamic quick shortcuts from the pixel launcher (http://android-developers.blogspot.com/2016/10/android-71-developer-preview.html)

**Comment by klinker41** [comment]
I almost think that this would be better implemented as a quick shortcut in Android 7.1 (they can be defined dynamically as well as statically according to the blog post http://android-developers.blogspot.com/2016/10/android-71-developer-preview.html).

**Comment by klinker24** [comment]
Didn't see about the dynamic ones! Awesome!

I think I will still want to add a widget though too, just because I don't see too many people adopting the quick shortcuts all the soon

**Comment by klinker41** [comment]
Doesn't android already have a built in contact widget option though somewhere?

**Comment by klinker24** [comment]
Oh, as a matter a fact it does haha and it works. Will just change this to the quick shortcut then

**Comment by klinker41** [comment]
Done with https://github.com/klinker41/messenger/commit/355da8d2a18d2773651b9c5cf6dfdf0ca829b9be?

**Comment by klinker24** [comment]
Almost, it doesn't work perfect yet, I would like to see how Google suggests managing the intents, because they seem to lose their extras at times, with the dynamic shortcuts

**Comment by klinker24** [comment]
Now it is done: https://github.com/klinker41/messenger/commit/26588ffc79561844d093970159d531f57aff8143

Should use the data on the intent, rather than extras.
