### ISSUE TITLE
Open links in Chrome Custom Tabs

### ISSUE THREAD

**Issue by klinker41** [klinker-apps/messenger-issues#116]
**Request:**

We should try and keep users in the app as much as possible, meaning even when they open up web links so that they can quickly get back to the conversation and reply. This means that Chrome Custom Tabs are a good option.

**Implementation notes:**

https://developer.chrome.com/multidevice/android/customtabs

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/messenger/commit/eea334960a7fc74e0c53205efca34381ec30a892
