### ISSUE TITLE
Activity transition between message list and image viewer

### ISSUE THREAD

**Issue by klinker41** [klinker-apps/messenger-issues#117]
**Request:**

Smoothing out transitions is always important. Source and Talon both have a nice animation when images open where they expand from the original position in the list. We should do the same here.

**Comment by klinker24** [comment]
Here is a project that should be doing something similar: https://github.com/alexjlockwood/adp-activity-transitions

**Comment by klinker24** [comment]
I have not been able to get this to work, for the life of me... I am going to punt for now. The issue is that we are going to a `ViewPager`, from a `Fragment`. Especially since Glide isn't ready to display that image immediately.

**Comment by klinker24** [comment]
After doing a ton of this with Talon's new update, it just isn't worth it for me to add this. It doesn't work well all the time and there are issues around the paging and what images are animated
