### ISSUE TITLE
Conversation list should update after sending a message

### ISSUE THREAD

**Issue by klinker41** [klinker-apps/messenger-issues#118]
**Device with issue:** Mac Pro running OSX 10.11.6 and Chrome v53
**Primary device:** Nexus 6P running Android 7.0
**App version:** 1.7.507
**Steps to reproduce:**

1. Go into a conversation on the web or chrome app
2. Send a message
3. Observe that the conversation list on the left side did not update

**Additional information:**

I think that it would be fine to simply update the item that we are on to be read and the snippet to what we just sent. Alternatively, you could just clear the list and re-grab it from the server, but that might be a little slow (needs testing, don't know how fast it is). Benefit of the second option is it might be a little easier to implement and it will reorder the objects.

**Comment by klinker24** [comment]
It is very fast to update them, so it wouldn't be an issue to update the whole thing, but I would rather not do it that way. I'm sure that we can simply give it an id (if it doesn't have one), and just change the snippet's inner html.

It wouldn't update the order, but that doesn't matter, in my opinion

**Comment by klinker41** [comment]
Agreed that is a smoother way to do it.

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/messenger-web/commit/177e64252731034d36e216688b5345bb30c31686

**Comment by klinker24** [comment]
I also would like to make the title and snippet not bold anymore after sending

**Comment by klinker24** [comment]
Ok now done: https://github.com/klinker41/messenger-web/commit/c2e19fa5fe3778e40d585ea393461bf89b7cd668
