### ISSUE TITLE
Display toast instead of snackbar for mark as read information

### ISSUE THREAD

**Issue by klinker41** [klinker-apps/messenger-issues#119]
**Request:**

I think that it would clearer if we used an actual toast instead of the snackbar when long clicking on the mark as read button in the conversation list. This would help to differentiate between actually clicking the button and just getting information from it, since the wording is so similar currently.

(I do still think that this feature is also very confusing based on the fact that Inbox uses the same action to dismiss an item, which a user will probably be expecting here).

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/messenger/commit/987e70e28c98f6f2a9d688a04540a16bdec5a304
