### ISSUE TITLE
Support live updates (no refreshing)

### ISSUE THREAD

**Issue by klinker41** [klinker-apps/messenger-issues#12]
**Device with issue:** Mac Pro running OSX 10.11.6 and Chrome v53
**Primary device:** Nexus 6P running Android 7.0
**App version:** 1.0.180

**Information:**

We need to update the client live when possible. Polling the server is easy, but it uses power and server resources and this isn't what we want to spend our time on. There are two different options for this: FCM supports chrome apps so we can package as a chrome app, or we can use web sockets which are very well supported by Rails 5.

**Possible solution:**

A quick solution would be the chrome app (although firebase's documentation for this was very lacking). Long term, we need to support web sockets through the rails server. This will potentially be more expensive on huroku as it needs redis support, but those plans looked reasonably priced.

* [x] chrome app updates
* [x] chrome extension updates
* [x] chrome app notifications
* [x] chrome extension notifications
* [ ] web app updates

**Comment by klinker41** [comment]
https://firebase.google.com/docs/cloud-messaging/chrome/client

I think that the best way to start this is to implement it in the chrome app and extension. A lot of users will be using that anyways, adding the web socket support might be big enough to push off to after the public release. We really only need to handle the message added fcm notification in the app.

**Comment by klinker41** [comment]
Added support in the web app through https://github.com/klinker41/messenger-web/commit/14d4efcc96ea8f329ddbccdc4d6093cfe98e03f6 and https://github.com/klinker41/messenger-web/commit/3930f1d7955b97d7a620cb3980a856896d321d40

added support in the chrome app through https://github.com/klinker41/messenger-chrome/commit/b4c055f4cc480b1a268337eb154879719782423a

still need to implement in the chrome extension.

one problem though, we need to be able to decrypt messages to display notifications and the chrome app cannot currently do that. To implement it, we would be required to implement all of the encryption stuff that we currently have in the web app also in the chrome app, which is kind of a pain in the butt. One way around this is that we might just be able to load those scripts from the url into the `index.html` and then use them, however we'd still need to be getting the encryption keys through the site somehow and I'm not sure how secure the `postMessage` method is that I'm currently using to exchange the account id.

**Comment by klinker41** [comment]
@klinker24, after I finish the chrome extension, will you be able to push up updates to both?

**Comment by klinker24** [comment]
yes any time

**Comment by klinker41** [comment]
done with chrome extension live updates https://github.com/klinker41/messenger-chrome/commit/209832774f5af0948a05056195f9b51a3bbc6a90

**Comment by klinker41** [comment]
The only thing remaining for this issue is displaying notifications through the chrome app and extension when a new message arrives. A few notes on this functionality:

1. it should be implemented in the "messenger.js" file of the app. This is so that even when the app is closed, the script will be running in the background and will still display notifications. Inside this file, there is a method `chrome.app.runtime.onLaunched` at the top, this functionality should be implemented outside of that so that we don't care when the app launches. A simple message listener can be added at the bottom of the file:

```javascript
chrome.gcm.onMessage.addListener(function(message) {

});
```

2. a new background script will need to be added for the chrome extension. The chrome app's manifest has an example how to do this, but it might need to be modified.

3. messages will need to be decrypted before they are displayed. This will be tricky. Alongside requesting the account id from the webside, you'll also need the password hash and the salt that it stores in `localStorage`. These requests can be the same as the request for the account id, just need to happen after that to ensure that the account id exists first. For examples on how to actually decrypt the data, you can look in the web app's `resources/js/global.js` file. You'll also need to bring over the web app's `vendors/encrpytion` folder, this can just be copied directly into the app and extension's folders.

4. once the message is received and decrypted outside of the page load, displaying a notification is very easy: https://developer.chrome.com/apps/notifications

**Comment by klinker41** [comment]
I finished up support for notifications through the chrome app with https://github.com/klinker41/messenger-chrome/commit/d63eafbd616c22d7ecc495e248ab4dbba991c4a2

It should serve as a good example of how to do them in the chrome extension. However, some things will need to be changed in the extension. For example, the extension has to use `iframe` instead of `webview` and I'm not sure what the differences will be there. I also don't know how to open the chrome extension popup when clicking on a notification, so that will need to be figured out.

**Comment by klinker24** [comment]
Notifications on the chrome extension: https://github.com/klinker41/messenger-chrome/commit/9928c8e8480e503639811381eeb5adfd754c87db

**Comment by klinker41** [comment]
Moved websockets for webpage to https://github.com/klinker-apps/messenger-issues/issues/76, it will be a separate effort from this.
