### ISSUE TITLE
contact picture missing

### ISSUE THREAD

**Issue by omgpercy** [klinker-apps/messenger-issues#120]
I'm running on Android 6, I know that when there is no contact picture available, the first letter of the Sender's name would appear as contact picture, but in most messages I have, the contact picture on my conversation list would only show a circle with a solid color. Hope this gets fixed.

**Comment by klinker24** [comment]
Sorry but there isn't anything to fix on this, this is the way we have made it work, don't plan on removing the letter at this time

**Comment by omgpercy** [comment]
I am not saying that you should remove the letters lol what I was saying is that in most of my messages the 'letter' is missing woul only show circle with a solid color. What I was saying is that I hope that the missing letters for the contact picture would get fixed lol thanks

**Comment by klinker24** [comment]
Please provide more detail and follow the template described in the project's readme

**Comment by omgpercy** [comment]
Device: Flash Plus 2
OS: Android 6.0
Issue:
Some contacts only showing blank circles instead of A letter or a hash sign (if number only)

Troubleshooting done:
Install/Uninstall the app, clear cache and data

Screenshot
![img_20161013_105054](https://cloud.githubusercontent.com/assets/22805025/19335080/0e101f3e-9133-11e6-8395-9a1bd4421f5d.jpg)

**Comment by klinker24** [comment]
Thanks. For most of them, it isn't going to show a letter unless the conversation has a name rather than a number. The only exception to this is GRAB. I will have to see why that wouldn't show a letter.

**Comment by omgpercy** [comment]
Here is another screenshot. 
![screenshot_20161013-105628](https://cloud.githubusercontent.com/assets/22805025/19335191/0057e9ac-9134-11e6-8577-e04d8dc85dc4.png)

Thanks!

**Comment by klinker24** [comment]
Can you tell me what is shown in the drawer when you open a conversation like GLOBE? Just open the conversation and swipe out the navigation drawer.

As long as the title doesn't match the phone number, it should show a letter. However, I also know that some companies don't always have to include a phone number with their messages.

**Comment by omgpercy** [comment]
There you go

![screenshot_20161013-110256](https://cloud.githubusercontent.com/assets/22805025/19335299/d1f1d5c2-9134-11e6-86c5-0ded1f1aa92c.png)

**Comment by klinker24** [comment]
Yeah that is what I thought. Look for a fix in the next version.

**Comment by omgpercy** [comment]
Okay thanks
