### ISSUE TITLE
re: contact picture missing

### ISSUE THREAD

**Issue by omgpercy** [klinker-apps/messenger-issues#122]
This is in regards to my previous case that was closed. What I was saying is not to remove the letters from the Contact picture on the conversation list. What I was saying is that on most of my messages the contact picture is missing, and I think this is a bug an I hope that it gets fixed that all of my message would get a 'letter' as a contact picture instead of some, only getting a blank circle with a solid color. Thanks

**Comment by klinker24** [comment]
You can reopen the old one, there is no need for a duplicate. Please post a screenshot in the other thread.

**Comment by omgpercy** [comment]
I noticed on the Conversation list, there is an "F" contact picture and in the quickreply. It is no longer there. 

![screenshot_20161013-173330](https://cloud.githubusercontent.com/assets/22805025/19344104/88dfd460-916b-11e6-92e7-d6c32a57659a.png)
