### ISSUE TITLE
SMS that is sent by third party is not showing up in conversation

### ISSUE THREAD

**Issue by PlasmaEye** [klinker-apps/messenger-issues#123]
**Device with issue:** Nexus 6P
**Primary device:** Nexus 6P running Android 7.0
**App version:** 1.7.2.520
**Steps to reproduce:**
1. Setup IF by IFTTT to send a text to a number when leaving an area.
2. Leave the area and get a notification from IF that it has sent the text.
3. Check the conversation of the person that the text was sent to and the text is not there. Person does receive the message.

**Additional information:**

The text was sent to a number and not a contact as IF does not use the Contacts Activity to search for an available number. The person's reply to the text shows up in the conversation window like normal. 

This was a recipe for IF that sends a text of "On my way home" to my wife when I am leaving work. The number that was used did include the country number (1) whereas the contact information of my wife does not include the country number.

**Comment by klinker24** [comment]
Do they show up if you open the default SMS app on your phone (Google Messenger)?

**Comment by PlasmaEye** [comment]
Yes, it shows up in Google Messenger.

**Comment by klinker24** [comment]
Can you head to developer settings on the phone, then "View Running Processes", find our app, and tell me if a `ContentObserverService` is running and what the timer says for it?

**Comment by PlasmaEye** [comment]
Yes, it's running and the timer is 12:13:45 and counting.

**Comment by klinker24** [comment]
Hmm, ok will have to investigate this one, thanks for the help ;)

**Comment by klinker24** [comment]
Closing this in favor of how it is described in #141.
