### ISSUE TITLE
Clicking the same conversation you are already in reloads it

### ISSUE THREAD

**Issue by klinker41** [klinker-apps/messenger-issues#125]
**Device with issue:** Mac Pro running OSX 10.12.0 and Chrome v53
**Primary device:** Nexus 6P running Android 7.0
**App version:** 1.7.3.525

**Information:**

When using the app on the web, you click a conversation and can view all messages in it. You can also see the rest of the conversations on the left side of the screen. Clicking on any of those conversations loads them, which is the correct behavior, but there isn't a reason to reload the conversation you are currently in if you click on the same one again. 

We should remove the click listener from the current conversation on that list.

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/messenger-web/commit/98971c07331f3113ce7e27682e797b04ba460489
