### ISSUE TITLE
Horizontal and vertical scroll bars present

### ISSUE THREAD

**Issue by PlasmaEye** [klinker-apps/messenger-issues#126]
### Horizontal and vertical scroll bars present

**Device with issue:** Windows 7 x64 running Firefox 49.0.1
**Primary device:** Nexus 6P running Android 7.0
**Add-On version:** 1.3.0
**Steps to reproduce:**

1. Open the add on from the toolbar
2. Scroll bars are present

**Comment by klinker24** [comment]
Can you post a screenshot of this one?

**Comment by PlasmaEye** [comment]
![untitled](https://cloud.githubusercontent.com/assets/3521652/19584455/3adaa034-970a-11e6-84a1-877fcf71b547.png)

This is from my home computer running Windows 10, Firefox 49.0.1, and Firefox Add On version 1.3.0

**Comment by klinker24** [comment]
Got it, should be an easy fix, will look at this tomorrow hopefully

**Comment by klinker24** [comment]
Fixed this earlier this morning, will put up an update later

https://github.com/klinker41/messenger-chrome/commit/e08a3a21b05a536bbf3c7dcbdc5495e4d81943d1
