### ISSUE TITLE
Message list doesn't start at the bottom

### ISSUE THREAD

**Issue by PlasmaEye** [klinker-apps/messenger-issues#127]
### Upon clicking a conversation, does not go to bottom of conversation

**Device with issue:** Windows 7 x64 running Firefox 49.0.1
**Primary device:** Nexus 6P running Android 7.0
**Add-On version:** 1.3.0
**Steps to reproduce:**
1. Open the add on from the toolbar
2. Click on a conversation that has a lot of history
3. Have to scroll down in conversation to get to latest message.

**Comment by klinker24** [comment]
I think that this is much more about the images in the conversation, actually. When they are loaded it changes the height of the item and moves the whole list. Does this sound accurate? It seems to be a bug across all the web, not just Firefox

**Comment by PlasmaEye** [comment]
Yes, that's accurate.

**Comment by klinker24** [comment]
Ok, this may be useful for fixing: http://stackoverflow.com/questions/18614301/keep-overflow-div-scrolled-to-bottom-unless-user-scrolls-up

**Comment by klinker24** [comment]
I made some changes with this commit: https://github.com/klinker41/messenger-web/commit/13fe4cfd5c60c3275446329944a3e458fa0f79c5

I do not know if this will fix the issue or not, I think more testing will need to be done. 

@PlasmaEye let me know what behavior you see. You may have to refresh the page a few times to update the app cache with the css/js changes.

**Comment by PlasmaEye** [comment]
It's ending up lower in the in the conversation but not at the bottom. It's a little inconsistent in how it works though. Here's the process I use:

1. Open up Firefox.
2. Click on Messenger Add-On button.
3. Open conversation that has pictures in it but not in the latest message.
4. Conversation loads but is not at the bottom, maybe 2 or 3 messages from the bottom.
5. Go to different conversation.
6. Come back to conversation with the pictures, conversation opens up at the latest message.

If I continue to go between another conversation and the one with the pictures it does fine. But if I start looking at other conversations (3-4 others) then head back to the conversation with pictures, it will not load at the latest message and will be like in step 4 above. I'll keep working at it and see if I can get it to consistently fail or succeed.

**Comment by PlasmaEye** [comment]
Trying some more and it is pretty consistently missing the mark on the first load but then subsequent loads of that conversation go to the latest message. That was if I was constantly going back and forth between conversations. I just stopped to write this message and went back to the top most conversation that had pictures in it and it exhibited the bug again. 

I'll let it go for the night and try it again tomorrow to see if it was just the cache of the css/js that needed updating.

**Comment by klinker41** [comment]
If it's working on subsequent loads then it is probably because images are being loaded from the cache and not firebase, so it's much quicker to get access to them.

**Comment by klinker24** [comment]
This is finished and will be deployed with the next version. 

Switched the message list to show cropped images by default, on the web, you can click the image to open in full screen.
