### ISSUE TITLE
Emoji button gets cut-off

### ISSUE THREAD

**Issue by PlasmaEye** [klinker-apps/messenger-issues#128]
### Emoji button is cutoff by bottom of window

**Device with issue:** Windows 7 x64 running Firefox 49.0.1
**Primary device:** Nexus 6P running Android 7.0
**Add-On version:** 1.3.0
**Steps to reproduce:**

1. Open the add on from the toolbar
2. Click on a conversation
3. Emoji button is not completely visible.

**Comment by klinker24** [comment]
God I hate Firefox

**Comment by klinker24** [comment]
Fixed this last night with: https://github.com/klinker41/messenger-web/commit/3d6b3cbb4d6a06a4488f49ea450a0d825769f54e
