### ISSUE TITLE
No contacts in Chrome web app and website

### ISSUE THREAD

**Issue by jman025** [klinker-apps/messenger-issues#131]
### Cannot receive text messages on the Chrome web app. Cannot view contacts either.

**Device with issue:** 
HP Pavilion dv6, Chromium version 53.0.2785.143 Built on Ubuntu, running on Ubuntu 16.04 (64-bit)
**Primary device:** Samsung Galaxy Note 4, Android 6.0.1
**App version:** 1.7.5.569
**Steps to reproduce:**

1. "Click My Account"
2. See there are "0 Contacts"

**Additional information:**

I am not able to receive text messages through the Chrome app. I am however able to type in a recipients number, type a message, and then view it as a continued conversation on my phone. The only way to see messages on the web app is if I type in a name and send a message; not the contact's number. Typing the name is useless if it is not recognized as a contact.

PS. I used another computer with Windows and Chrome having the same results.

**Comment by klinker24** [comment]
How long have you had the app? A month ago, when I introduced the ability to have contacts, etc from the web, I said that you would have to recreate your account or else it wouldn't upload contacts.

**Comment by jman025** [comment]
As suggested, I recreated my account. Thank you!
