### ISSUE TITLE
Support viewing and adding scheduled messages

### ISSUE THREAD

**Issue by klinker41** [klinker-apps/messenger-issues#14]
**Device with issue:** Mac Pro running OSX 10.11.6 and Chrome v53
**Primary device:** Nexus 6P running Android 7.0
**App version:** 1.0.180

**Information:**
- [x] make base page for scheduled messages in ui
- [x] view scheduled messages through GET request in ui
- [x] delete scheduled messages through a POST request
- [x] add scheduled messages with ui and submit a POST request to server

**Comment by klinker24** [comment]
Finished with adding scheduled messages from the UI with these commits: https://github.com/klinker41/messenger-web/commit/08df334617aea7b2c11af5ad9bc0e8b3948e9260, https://github.com/klinker41/messenger-web/commit/ad34ed26d054f00711a827bd12419319b60a3bb5, https://github.com/klinker41/messenger-web/commit/cdb186f5be93028b7d9746742ca419ce1dc41c0b
