### ISSUE TITLE
Merge messages stored on the cloud with ones on the device

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#141]
**Device with issue:** Android
**App version:** 1.8.4
**Steps to reproduce:**

1. Uninstall the app for awhile
2. AWESOME NEW FEATURES ADDED!!! Reinstall the app
3. Sign in to your old account
4. All the messages that were imported are deleted in favor of the ones in the cloud

**Additional information:**

It would be expected that the app will pull in the old ones from the cloud, but also push up any new messages to the server.

Currently, the user has to delete the current account, clear the app's data (to go through the initial import again), then sign up for a new account.

**Possible solution:**

We should do this on a time based interval. When downloading the messages, get the very latest message on the cloud, then query the device for conversations with messages newer than that one.

With those conversations, we should then check the `id_matcher` column against the ones in the current database to combine the results.

After combining the results, we need to upload the new messages and conversations to the cloud.

This process could take some time, so we should also be sure to update the api download notification to alert the user when the app is "Merging with device database", then "Encrypting and uploading new messages"

**Comment by klinker41** [comment]
I also consitently run into the problem that after I reinstall, the app has automatically restored a bunch of my old messages, but all of the contact pictures are wrong and it isn't set up with my most current account. I almost think it would be best to disable the backup that Google Play Services now has in place since we have our own backup on the server that can be gotten just by signing in.

**Comment by klinker24** [comment]
Yeah I think that is a good idea. I was using some rules to try to stop the backup from getting your account earlier, but disabling it would be better for our case.

**Comment by klinker24** [comment]
This is actually not trivial at all to accomplish, basically, for every message, I would have to check whether or not a conversation exists, then either insert that message into the conversation or create the new conversation..

This would need to be done to keep the entity relationships in order. This would take a ton of time and processing power, it would need to be done for every message newer than the the latest message in the cloud. Wowza, that is rough, will have to consider this one further, I am going to take it off of the public release milestone for now....

**Comment by klinker24** [comment]
I guess that statement isn't completely true, the internal database still runs off of conversations, so we could create a mapping conversations from the internal database to conversations in our apps database, then process the messages all at once, against that mapping.

**Comment by klinker24** [comment]
This one could be pretty tightly coupled with this issue: https://github.com/klinker-apps/messenger-issues/issues/123

Here is how I see this one working:
- We need a way to load new messages from the internal database into the app
- Start a service whenever the main activity is created that will grab the latest message from our database, and use its timestamp to see if we are missing messages from the internal database.
- If we are missing messages, load them into the correct conversations and broadcast the conversation/message updated 
- This same service should also be started after a login
- We should still clear the database after a login, and download everything from the cloud, but then this service will go through and update the database to bring it up to date with the latest messages
- We should ensure that messages and any new conversations are uploaded to the backend as well

This will effectively kill both issues with one stone, which is great.

**Comment by toddmbloom** [comment]
Will this also include keeping messages synced with other SMS apps (like Google Messenger) too? I was going to submit a ticket but I wasn't sure if it matched this one when I searched. I noticed when I deleted a message on the web it was deleted in the Pulse Android app but not in Google Messenger. Sorry if this is a different issue - if so I'll make a new issue but I wasn't sure if was related or not.

**Comment by klinker24** [comment]
Yes that is the goal, as described in the last comment

**Comment by klinker24** [comment]
I have merged changes for this, they will be flagged off for a little while though, might roll them out to limited testing.

**Comment by klinker24** [comment]
I released a stable (?) version of this to beta testing this morning. Will give it a few days to propagate through, then try turning it on for users and hope that I don't hear anything at all. Some issues that could come up:

- duplicate messages
- the UI get stuck in a constant reloading state
- the process getting stuck and never finishing
- messages that were brought in don't get synced to the backend
- 15 second time offset causes issues
- probably some more that I will hear about, if there is an issue

**Comment by klinker24** [comment]
Update: I have turned this new method on for 50% of the users. Will wait to hear any complaints

**Comment by klinker24** [comment]
I did get one report that a group message that the user replied to, via the notification, actually went into a new conversation, as well as the original conversation. 

I suspect that this is the issue there, although I haven't heard back to be able to confirm yet. It looked like it was because the recipients list included himself, so I will ensure the current user's phone number gets stripped out of the import.

**Comment by klinker24** [comment]
Closing this one, have not heard of any beta issues, so going to push it to prod tomorrow and see what I hear.

**Comment by PlasmaEye** [comment]
This hasn't fully fixed the issue in #123. I had stopped using IFTTT to automatically send a text and have switched to Tasker which works just fine. The texts it sends do not show up in Pulse but do show up in Messenger (now Messages). The task is setup to save the text to the default messaging app.
![screenshot_20170224-154144](https://cloud.githubusercontent.com/assets/3521652/23322208/816d724a-faa8-11e6-96cf-dfa6dfdb549a.png)

Device: Nexus 6P running 7.1.1
Pulse Version: 2.0.2.1017

**Comment by klinker24** [comment]
Yeah I made changes that would have helped here, then actually reverted them, bit sure what I want to do about this one yet

**Comment by klinker24** [comment]
There are some improvements that can be made here, for 7.0+. I have posted them in #291. I am going to close this one out and use that method for the future
