### ISSUE TITLE
Cleanup old conversations

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#144]
**Request:**

Make a global option to cleanup old conversations. It should just be a `ListPreference` with a custom adapter to select one of the following:

* Never
* Messages older than:
  * One week
  * One month
  * Three months
  * Six months
  * One year

**Implementation notes:**

This would involve changes to the backend and android. Web/Chrome comes for free since our application is RESTful.

_Backend:_
- [x] Add an endpoint that just accepts a time and delete messages older than that time. It should then pass that message to all the devices with an FCM notification.

_Android:_
- [x] Make the preference as described above
- [x] Make a service that will run once every night, to clean up old messages. It should only run on the primary device (if the user has an account, if not, then just run it since it will always be the primary device)
- [x] If that service deletes messages, send the status up to the backend to remove messages from the web, and other devices
- [x] Implement the FCM receiver for removing messages on the other devices.

**Comment by klinker24** [comment]
Cleanup old messages endpoint, on backend: https://github.com/klinker41/messenger-server/commit/7edaa36c588b83bd360e6f50c60b716061246823

**Comment by pbanj** [comment]
figured i would ask here instead of a new issue as it is kind of the same thing. could you add the ability to delete messages after a certain amount? you could set it up so after say 100(or any number) messages it deletes the older ones

**Comment by klinker24** [comment]
Sorry that isn't planned. This will be based on time, not amount

**Comment by klinker24** [comment]
Database: https://github.com/klinker41/messenger/commit/b6b87286a1bc358e8fc34c83aecfee68adf051c5
Service: https://github.com/klinker41/messenger/commit/2dcd01912323b9a65c816356ceb671e4a340ef72
FCM Receiver: https://github.com/klinker41/messenger/commit/7a766fb834030c913143d3d8b082d08ccac5cd2b
