### ISSUE TITLE
Custom snooze timeouts

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#147]
**Request:**

I got a request to have custom snooze timeouts. I thought that there were plenty of default ones available, but, it would be pretty easy to add a custom option as well, and that is a pretty transparent feature, no setting or anything.

**Comment by DEADPOOL419809** [comment]
I look forward to this feature Being added!

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/messenger/commit/70e3532592d59c4150b7a95606cea836c2205a6e
