### ISSUE TITLE
Video message hiding reply input

### ISSUE THREAD

**Issue by aaronasmith** [klinker-apps/messenger-issues#149]
**Device with issue:** Unknown
**Primary device:** Unknown
**App version:** Unknown
**Steps to reproduce:**

I had a conversation with 2 videos in it and the reply text box would disappear after they loaded.  I deleted them and it started working again.

I sent another video to a different friend and when I scroll to the bottom of the conversation the reply box disappears.  It will show up when I scroll up a little on that message but not at the bottom where it should be.

**Comment by klinker24** [comment]
@klinker41 any idea on this one? I can confirm that it is happening, very easy to see. Just have a video in the conversation and it really will disappear when you scroll to the bottom

**Comment by klinker41** [comment]
Sorry no, I don't know what is wrong.

**Comment by klinker24** [comment]
I made some changes for this the other night, seems to be working for me. Going to close it out.
