### ISSUE TITLE
New message deletion and list updation. 

### ISSUE THREAD

**Issue by ashoksoni** [klinker-apps/messenger-issues#151]
Received a new message so its list got updates and the top conversion showed the header of that message. Went into that conversation and deleted that single new message, came out and the header was still shown at the top of the list as if not deleted though message was removed as could be confirmed by going again in conversation.

**Comment by ashoksoni** [comment]
so its list got updated*

**Comment by klinker24** [comment]
The conversation list won't get rearranged when you delete a message if that is what you are asking, sorry. If not, feel free to reopen with more information

**Comment by ashoksoni** [comment]
Conversation list is sorted by date, correct? So if I receive a message today, that list goes to top. If the second list has a message just minutes after that, deleting that new message from first list shld move it to second list and the second one to first so the sorting works, also if I remove that new message, if I come  back to conversation lists view, that list should have text from existed messages not the message I just received else it's a bug.

Correct me if I am wrong please.

**Comment by ashoksoni** [comment]
If the second list has a message just minutes before* that

**Comment by ashoksoni** [comment]
Along with this bug, I have a query that's not related to this bug. Hope it's ok. After installing the app, when I go to my account to sign up or sign in, app asks me to purchase a subscription even within trial period, shouldn't it give me an option to login directly?

**Comment by klinker24** [comment]
It is saying the play store cannot find your trial. You can always just cancel the old and sign up for another.

**Comment by ashoksoni** [comment]
What about the main question and how to cancel and sign up new one?

**Comment by klinker24** [comment]
You can cancel the subscriptions from the play store. I will have to look into the issue later, having a hard time following all the different things you are talking about. 

In the future, please use the issue template provided in the readme.

**Comment by ashoksoni** [comment]
Forget abt the subscription question, it's clear to me now. Just if you can, the main question.

**Comment by ashoksoni** [comment]
Let me repost again with template then. :)
