### ISSUE TITLE
Conversation list improvements for deleted messages

### ISSUE THREAD

**Issue by ashoksoni** [klinker-apps/messenger-issues#152]
### Conversation lists not sorting properly according to date if a new message is deleted thus new message deletion and lists don't get updated. 

**Device with issue:** OnePlus 2 (CM based rom v6.0)
**Primary device:** OnePlus 2 (CM based rom v6.0)
**App version:** 1.9.0.681
**Steps to reproduce:**

1. Receive a new message from an existing conversation contact. 
2. That list will go to top, go into that list and remove that new message. 
3. That conversation should sort itself out again by date but it stuck still to the top and it shows the contents of that deleted message in its header. 

**Additional information:**

Video to show what I am talking about. This happens even after I remove all messages inside a conversation. 

https://youtu.be/yCAGHQpEUQ8

**Possible solution:**

Can't find so far.

**Comment by klinker24** [comment]
Deleting a single message will update the conversation list, and the next time the conversations are queried, it will update the ordering: https://github.com/klinker41/messenger/commit/e08f03f3ba0cb7d13d7f21b09c0a6aefb5f9eb10

**Comment by ashoksoni** [comment]
Great, thanks.

**Comment by ashoksoni** [comment]
Still need to close and open the app to refresh conversations list.

**Comment by klinker24** [comment]
As I said, the next time the conversations are queried, it will update the order. Changing the order is low priority, sorry, it is working as designed.
