### ISSUE TITLE
Chrome Extension has the hamburger menu selected on initial click

### ISSUE THREAD

**Issue by ahatzz11** [klinker-apps/messenger-issues#154]
### Chrome Extension has the hamburger menu selected on initial click

**Device with issue:** Macbook Pro running OSX 10.11.6 and Chrome v55
**Primary device:** Google Pixel XL running Android 7.1
**App version:** 1.9.0.681
**Steps to reproduce:**

1. Click the chrome extension
2. Look at hamburger menu icon

![](https://puu.sh/slqp9/8fd8bf3f39.png)

**Additional information:**

**Possible solution:**

Remove the selection area.

**Comment by klinker24** [comment]
Finished with: https://github.com/klinker41/messenger-web/commit/b8b37cfc4f770b2400b26dc4a86ca61c7d9b35db

Will deploy in a bit.
