### ISSUE TITLE
Add a "Compact" Layout Mode for the Chrome App

### ISSUE THREAD

**Issue by bkromhout** [klinker-apps/messenger-issues#155]
### Request
I just started using Pulse, and immediately downloaded the Chrome App to take full advantage of the multi-platform functionality.

I was immediately struck by just how *huge* everything is when I have the window size fairly small (On my 15" rMBP, this takes up about a quarter of my screen):
<img width="752" alt="screen shot 2016-11-17 at 12 16 44 pm" src="https://cloud.githubusercontent.com/assets/4447359/20399783/4396ef90-acc0-11e6-9ed7-2b8e7a946b53.png">

While I definitely like that the Chrome app already has a reactive UI and hides some elements at a certain threshold (such as the nav drawer), it'd be really nice if we could also have a "compact mode" as well. For example, the amount of vertical padding in the conversation bubbles is a lot for the size of this window.

### Implementation Ideas
I'm mostly looking for less vertical padding all around, I think. Perhaps a bit of other padding adjustments as well.

In terms of "when to enable", it could be automatic based on size, or it could be a toggle—either seem like a sane idea.

**Comment by klinker41** [comment]
I don't follow what you want. You can resize the window to as small as you'd like and things will adjust appropriately. I don't see the message padding changing, it is designed purposefully that way.

**Comment by bkromhout** [comment]
I'm mostly just looking for a layout that gives me less vertical negative space, that way more messages can be seen

**Comment by klinker41** [comment]
I don't foresee that changing, sorry. I don't think fitting one extra message onto the screen is helpful enough to sacrifice message separation and distinction.

**Comment by bkromhout** [comment]
Makes sense. Thanks anyway!

**Comment by klinker24** [comment]
I have to agree with Jake on this one. I will consider it further in the future, but for now, going to close it
