### ISSUE TITLE
Chrome app doesn't handle new line characters

### ISSUE THREAD

**Issue by bkromhout** [klinker-apps/messenger-issues#156]
### New line characters cannot be typed in the compose area, nor are they rendered in conversation bubbles
**Device with issue:** rMBP running macOS 10.12.1 and Chrome v54
**Primary Device:** N/A
**Chrome App Version:** 1.4.1

**Steps to reproduce:**
For "Cannot type new line characters":
1. Open a conversation
2. Type something if you want
3. Do Shift+Enter
4. This should enter a new line character, but instead, it sends the message

For "Does not render new line characters":
1. Open the app on a phone and send a message containing new line characters in it
2. Open the applicable conversation in the Chrome app and observe that the new line characters are not preserved at all

**Additional Information**
While I did not test the website or the Chrome extension, my sneaking suspicion is that they likely suffer from the same issues.

**Comment by klinker24** [comment]
Closed both cases with: https://github.com/klinker41/messenger-web/commit/29ca72eee8b19030624f96f0d8bb363c7eed8812

`Shift+Enter` will insert a new line into your message, while only `enter` will continue to send.

This is not deployed yet, but will be live soon.
