### ISSUE TITLE
Chrome App has bad spacing on message bubbles when message is <4 characters.

### ISSUE THREAD

**Issue by ahatzz11** [klinker-apps/messenger-issues#157]
### Chrome Extension has the hamburger menu selected on initial click

**Device with issue:** Macbook Pro running OSX 10.11.6 and Chrome v55
**Primary device:** Google Pixel XL running Android 7.1
**App version:** 1.9.0.681
**Steps to reproduce:**

1. Go to conversation
2. Send a message with less than 4 characters
3. See bad spacing. The bubble and the arrow don't connect! 

![](https://puu.sh/sltvf/42d40c783c.png)

**Additional information:**

Emoji's work different, maybe because of their unicode value?

**Possible solution:**

**Comment by klinker24** [comment]
Good find, I had noticed this before, but hadn't been able to nail down what situation it happens in. And yes, emojis would run off of the unicode values

**Comment by klinker24** [comment]
Fixed with: https://github.com/klinker41/messenger-web/commit/ea390b92ea8c04004b87eb6e52f5a081cc465e26

Will deploy in a bit.
