### ISSUE TITLE
Support for sending a new message

### ISSUE THREAD

**Issue by klinker41** [klinker-apps/messenger-issues#16]
**Device with issue:** Mac Pro running OSX 10.11.6 and Chrome v53
**Primary device:** Nexus 6P running Android 7.0
**App version:** 1.0.180

**Information:**

We need to be able to compose a message to any contact from the web. Unfortunately, this will not be an easy change since there currently isn't a way to get all of the contacts for an account. To be able to support this, we'll have a few steps to take:

* [x] make table on server to house contacts for an account id
* [x] upload all "mobile" contacts to the server, ONLY from the primary device (name and phone number, both encrypted)
* [x] make server endpoint to query all contacts for an account id
* [x] allow for grabbing and decrypting contacts for an account id from the web client
* [x] Make a new route to only index names and phone numbers, this web view won't care about colors.
* [x] make ui for selecting contact and entering a message
* [x] make a route to send push notification to primary device to send the message
* [x] implement sending from the firebase receiver
* [x] upload changes to contacts when they are modified on the primary (a name is changed for example)

Currently in the app when sending a message to a new conversation, a few things happen:

1. the conversation is created so that a conversation id can be made
2. a message of type `Message.TYPE_INFO` is created that says "Looks like you don't have any messages with this person, time to start up a conversation!". It is then inserted into the conversation and uploaded
3. when the user sends the first message in the conversation, the info message is deleted

We may be able to skip the info message step on the web if we want to.

**Comment by klinker24** [comment]
Web portion: https://github.com/klinker41/messenger-web/commit/f8711d81815130d5aa9784f32dc221a56312d172

Note that the only way you can reach it is from the `/compose.html` page locally. It isn't deployed and the FAB does not send you there yet.

**Comment by klinker24** [comment]
Route to send push notifications: https://github.com/klinker41/messenger-server/commit/bb10b81af6b8909e35f65d136451304e68cdb543

**Comment by klinker24** [comment]
Route with simpler index (only grabs name and number), for contacts: https://github.com/klinker41/messenger-server/commit/6e79da27487c9a9989a8c90fb86031702e6b6773

**Comment by klinker24** [comment]
<img width="1279" alt="screen shot 2016-09-18 at 8 10 24 am" src="https://cloud.githubusercontent.com/assets/4874287/18615898/75e263a8-7d77-11e6-9ac1-8bbe5d7a7a65.png">

**Comment by klinker24** [comment]
Send messages from the phone: https://github.com/klinker41/messenger/commit/905ac369ecf4271db32587ed3a8ad8815b1e412f

**Comment by klinker24** [comment]
Final step is to sync contact changes (and new contacts) from the phone, but this doesn't have to be immediate.

I will deploy this version of the web app to prod, after the Android update has been out for a few days, since this web update depends on android functionality.

**Comment by klinker24** [comment]
I deployed this to prod this morning, along with the emoji keyboard

**Comment by klinker24** [comment]
Finished this one by uploading new contacts to our backend: https://github.com/klinker41/messenger/commit/71eea02e55f8898909be8590eedd08a54d50d54a

The service will run every 24 hours and find the changed contacts, then upload them so they can be used from the web interface.
