### ISSUE TITLE
Choose color for notification icons

### ISSUE THREAD

**Issue by jakecentric** [klinker-apps/messenger-issues#161]
I would love to be able to pick the color of the new text notification for each individual contact. For example, I have my wife's theme in purple. Instead of a white notification icon when she texts me, I'd like to be able to have it be purple. That way, just a glance at my notification bar lets me know who texted me. To take it a step further, if I get a text from my wife (purple) and a friend (orange), there would be a purple notification icon and an orange one. This feature is the only thing keeping me from making a permanent switch to Pulse, as my current app has this feature and it has become invaluable to me. I have assigned specific colors to specific contacts and I can instantly determine important texts from non-important texts.

**Comment by klinker41** [comment]
This goes against material design guidelines of white notification icons, it isn't something that will be implemented. Sorry.

**Comment by jakecentric** [comment]
Ah, so Textra, in doing this, isn't following the material design
guidelines? Interesting. I love Pulse and your other apps so I'm gonna try
it for awhile and see if I can live without that feature. Appreciate the
feedback!

**Comment by klinker24** [comment]
Not just material design. With android 4.4, Google said that there should only be white status bar icons, even going as far as for requiring them from OEMs to be able to distribute their devices with android.

Colored status bar icons are just not something you do anymore

**Comment by jakecentric** [comment]
Ahhhh, gotcha. Good to know! Thanks for the info! Love the apps, man.

**Comment by klinker24** [comment]
http://www.androidpolice.com/2013/12/11/googles-android-compatibility-definition-document-says-oems-must-use-white-icons-if-theyre-using-translucent-system-bars-but-will-they/

://developer.android.com/guide/practices/ui_guidelines/icon_design_status_bar.html
