### ISSUE TITLE
Enlarge entry text box on web

### ISSUE THREAD

**Issue by erikiksaz** [klinker-apps/messenger-issues#163]
Would it be possible to have at least a 2-3 row text entry box in the chrome extension?  Longer texts become difficult to compose when we can only see the first several words of the text.  

Otherwise, your app is great!  Thanks for your work.

**Comment by klinker24** [comment]
This changes the `input` to a `textarea`: https://github.com/klinker41/messenger-web/commit/a83836defae6a1677cd67dc11ec9f4ea2908b017

This updates the CSS to make it look better: https://github.com/klinker41/messenger-web/commit/852aeb05c9926d8e746b06cb2359dc0d26656d19

I have not deployed this change yet.

**Comment by erikiksaz** [comment]
Thanks for adding in the expanded text box!

Would it be too much to ask if you could make it a little bigger still? =p
 Something like 3-4 rows tall?

I appreciate your help,

Eric

**Comment by klinker24** [comment]
Sorry, right now, the two scrollable rows are all I am going to be able to provide.
