### ISSUE TITLE
Password protect private messages

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#167]
**Request:**

We already have the concept of private messages. Right now, it just hides the name/number within notifications, but it would be better if it actually password protected those conversations in the app as well.

This would work by showing some kind of password dialog, when the user tries to open the private conversation.

---

**Implementation Notes:**

**Android:**
This would require some sort of global password to be set up. It could be a separate setting in the global settings activity to "Secure Private Conversations". I don't want to make per conversation passwords of course.

I will use the fingerprint API when available, and fall back to a pin on other devices and the web.

To implement this on Android, I may add a new item to the navigation drawer, for "private conversations". This would fit in well with the folder support that is planned for the future (#298). If a conversation is marked as "private", it should get removed from the "conversation list" section of the drawer and moved to this separate inbox. 

In terms of password protection, they can turn that on from the advanced features page and it will prompt them to set up a password the first time they go to that "private conversations" section. It should be off by default, since the user would need to set up a password manually. The conversation list on this private conversations page should have a header element (similar to the one notifying the user about the ability to text from any device) that redirects them there to turn on the password protection.

* [x] Add drawer section for private conversations: https://github.com/klinker41/messenger/commit/1babe9e4708dbac9c6566c9f665e1f8ba6ab2240
* [x] Don't display the private conversations on the conversation list or anywhere else that is exposed outside the app (widget, share targets, etc): https://github.com/klinker41/messenger/commit/a3236b7322f73ea12d32cee60d9f50c5bb922678
* [x] sync passcode across devices: https://github.com/klinker41/messenger/commit/073bdb9ac79613ef7cdaf09426c70f6b37c14d3f
* [x] create dialog to set the password: https://github.com/klinker41/messenger/commit/00489a991f72e9bec9eb28bef41191644fa56355
* [x] create dialog to enter the password (or use the fingerprint): https://github.com/klinker41/messenger/commit/0fc546a733c703e6f5d067867bfe31f195734d11, https://github.com/klinker41/messenger/commit/572da29acd5ba1bf8e24df918fd26702d66f5401
* [x] Prompt for a password when the user hits the "private conversations" tab in the drawer: https://github.com/klinker41/messenger/commit/0fc546a733c703e6f5d067867bfe31f195734d11
* [x] In the `MessengerActivity#onPause`, if the current fragment is the `PrivateConversationListFragment`, exit out of that and go to the conversation list instead: https://github.com/klinker41/messenger/commit/5e6e1fb6f1b7af727b9386776add90b1807fbe26
* [x] Display a summary on the "private conversation" preference within a conversation's settings, to tell the user that this conversation will be moved out of the inbox and in to that other section: https://github.com/klinker41/messenger/commit/e72ffcf431bc8e0dd2f273918a3e4c22c93e2cbd
* [x] The empty screen (if they don't have any private conversations), should mention how to set up a private conversation: https://github.com/klinker41/messenger/commit/b2f4ea5242aca4cd1f1a6a198bfdfb3dc5c19764
* [x] When composing a new message, if the conversation the user is composing to is private, don't let them create the message. Redirect them to the private conversations tab instead: https://github.com/klinker41/messenger/commit/a3236b7322f73ea12d32cee60d9f50c5bb922678
* [x] When the user receives a message to a private conversation, the `ConversationListUpdatedReceiver` is going to be a bit weird. What will happen and how can I ignore the private conversations, there? https://github.com/klinker41/messenger/commit/1babe9e4708dbac9c6566c9f665e1f8ba6ab2240
* [x] Don't hide the content of the private conversations, from the conversation list anymore (since they will be back behind the lockcode anyways): https://github.com/klinker41/messenger/commit/47b25d70366fe219784f5d34580511c3dfe977dc
* [x] Remove the settings page link between the private conversation and the mute conversation toggles: https://github.com/klinker41/messenger/commit/f5323f3144e1661183c5eb5c573eb490cd33d5c9
* [x] Restore passcode on account login: https://github.com/klinker41/messenger/commit/eec01d98c8e2b760deed788d5afa9c1fd47e955a, https://github.com/klinker41/messenger/commit/7a5b3c638ba2759956e6e054527d1feab27b8762
* [x] Notify the user, the first time they enter the private conversations fragment, that they can set up a password for it: https://github.com/klinker41/messenger/commit/791f20976022e0bfbd114584b69ead58c9a9100f
* How should they reset their password if they forget it? 
  * If they don't have an account, they will need to clear the app data and set it up again
  * [x] If they do have an account, they will be able to enter their account credentials to get past the passcode screen: https://github.com/klinker41/messenger/commit/52f281cd1b11b8cb72bfaf5343ec5b479430d2d4

**Server/Integration:**
This would definitely have a web component as well. In the navigation drawer on the web, I would want to make a "private conversations" item. The private conversations would be removed from the simple index endpoint, then (which would also mean that I would need to implement this on iOS as well, since it uses that endpoint). These should be password protected in the future, as well.

* [x] Store the password to the `Account` table. If it exists, this option is turned on. If it is `null`, then they haven't protected the conversations: https://github.com/klinker41/messenger-server/commit/68ad99c9938e0bd61c159e74790dbf856ce417ab
* [x] Make an endpoint to return the private conversations. This endpoint should have a flag to return all the private conversations or the normal conversations. I don't want to change the current conversation index endpoint: https://github.com/klinker41/messenger-server/commit/a41829d10cac601a3f974c9e71fa918283687077
* [x] restore that password whenever the user logs in to the account: https://github.com/klinker41/messenger/commit/eec01d98c8e2b760deed788d5afa9c1fd47e955a, https://github.com/klinker41/messenger/commit/7a5b3c638ba2759956e6e054527d1feab27b8762
* [x] save the password to the account, whenever the user changes it: https://github.com/klinker41/messenger-server/commit/864d461d99785ae133b77e9671050a2497052141
* [x] We will need to push up whatever password is set by the user, when they create the account or refresh the account, since they could set up private conversations before resetting the account: https://github.com/klinker41/messenger-server/commit/68ad99c9938e0bd61c159e74790dbf856ce417ab, https://github.com/klinker41/messenger/commit/7a5b3c638ba2759956e6e054527d1feab27b8762
* [x] return the encrypted passcode with the `account#settings` endpoint: https://github.com/klinker41/messenger-server/commit/e2ef123dd65c9546928d477539799eed082a1704

**Web:**
* [x] create feature flag: https://github.com/klinker41/messenger-web/commit/c70bc416d7d3bba4a92dca543c4e3aff4449d5ba
* [x] add a `Private Conversations` page for the navigation drawer: https://github.com/klinker41/messenger-web/commit/a0c4376a8a6a8b98410f2931169a8735592daeee
* [x] query the `conversations#index_public_unarchived` from the `query_handler`, when the feature flag is `true`: https://github.com/klinker41/messenger-web/commit/ef03a6cd94febafbf129a613f0ae059d7635c0c6
* [x] require a password input before querying the conversations on the private conversations page: https://github.com/klinker41/messenger-web/commit/101bf4203e206498cbdb161ec0383108e003efbd
* [x] switch the text on the conversation settings page from `Private Notifications` to `Private Conversation`: https://github.com/klinker41/messenger-web/commit/0a106357565650b386fa41c0b879f79c683aebd1 

**Help Topics:**
* [x] what if I forget my password: https://github.com/klinker41/messenger-web/commit/c27d09032612fdea72325095611ae2ecafd389ae
* [x] How do I move a conversation into the private conversation list? (or move it out of the private conversation list): https://github.com/klinker41/messenger-web/commit/c27d09032612fdea72325095611ae2ecafd389ae
* [x] How does the private conversations section work? (password protection, removes those conversations from the conversation list and any folders): https://github.com/klinker41/messenger-web/commit/c27d09032612fdea72325095611ae2ecafd389ae

**Comment by Repooc** [comment]
Def think about using the fingerprint as an authentication option in Android devices please.  Love having private/hidden conversations...

**Comment by aswerdlow935** [comment]
I agree, fingerprint support (Samsung support) would be great, and a backup password for accessing on other devices would also be great.

**Comment by NovaViper** [comment]
You could use Google's API of the fingerprint support.. but goes up to Android 6+, as for anything below Android 6, you could take some of the APIs from manufacturers like Samsung and implement them, and as for the rest, just use pattern and pin. And speaking of which.. you could add a fourth option for gestures (might be asking about but just throwing some ideas out there 👍 )

**Comment by newstart** [comment]
May this be added to pulse?

**Comment by NovaViper** [comment]
@newstart I think this is going into Pulse

**Comment by NovaViper** [comment]
Has any progress been made to this?

**Comment by klinker24** [comment]
No, sorry. It is lower on my priority list right now

**Comment by NovaViper** [comment]
@klinker24 Ok, if you need, I can add in some code for a base

**Comment by klinker24** [comment]
No, I don't, I just am not ready to focus on this right now, sorry

**Comment by NovaViper** [comment]
@klinker24 Oh ok.

**Comment by doumhfr** [comment]
Can we have some news regarding this feature ?

I was using mood messenger, and I love how it's working, possibility to quickly hide/unhide conversation.

**Comment by klinker24** [comment]
What news do you want to hear? When I begin working on this feature, I will post updates here, as I do with all issues on this tracker.

I haven't started.

**Comment by doumhfr** [comment]
Great, this kind of news for example 😄

**Comment by NovaViper** [comment]
Glad to hear something on this, I've been somewhat anxious that it got abandoned unknowingly.

**Comment by klinker24** [comment]
I will close an issue if I do not plan to implement it. I cannot abandon something that I haven't even started

**Comment by klinker24** [comment]
This is finished and will be released with `v2.11.0`.
