### ISSUE TITLE
Love Pulse But A Few Things Needed

### ISSUE THREAD

**Issue by sacsmitty** [klinker-apps/messenger-issues#169]
Really dig Pulse however there are a few things that could make it even MORE amazing.

- Hide contacts without a mobile number
- Show mobile numbers for contacts only
- More customization for colors.  Not just themes but support to modify a theme and use other colors.
- Would be neat to get support for some different chat bubble options.  The current default is kinda square.

**Comment by sacsmitty** [comment]
The above feature request is for the Android version of the software in case that wasn't obvious.

**Comment by klinker24** [comment]
Hit the three dot overflow of the compose screen and you can limit it to only mobile, think this solves both one and two.

For the third, if you aren't using global themes, there are plenty of options available.. don't think that I will go more colors there, sorry

I will open a new, separate, issue later for your last request, but I don't know if this is something I will be doing or not.
