### ISSUE TITLE
Add new bubble styles

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#170]
**Request:**

Add an option for more round message bubbles.

**Implementation Notes:**

I don't know if I want to do this yet or not.

If I did, I could just take the drawables from the Google Messenger app. This would need to be a global setting and apply on the web as well.

**Comment by klinker41** [comment]
Blah

**Comment by klinker24** [comment]
Agreed.

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/messenger/commit/5e625af57d7cdb24ec3df799af42ad5f01f6248a
