### ISSUE TITLE
Background graphic not cleared

### ISSUE THREAD

**Issue by wyrn73** [klinker-apps/messenger-issues#171]
Very minor issue I noticed - assuming you archive all your current messages like I do, if you pick a message in archived conversations and reply to it in on the web interface, when you pull up your conversation list in the android app, initially the background graphic saying "no messages, have a good day" or whatever it says still stays present at least initially. 

Steps to reproduce:
1) Archive all your messages
2) Go into web interface and respond to an archived message
3) Open pulse on your phone

Not a huge deal but figured I'd report it. Love the app.

![screenshot_20161127-073547](https://cloud.githubusercontent.com/assets/24206645/20648454/6328be80-b475-11e6-8a5c-bf3bf09a6294.png)

**Comment by klinker24** [comment]
Should be fixed in the next version of the app (1.12.0), when I release it.

Here is the associated commit: https://github.com/klinker41/messenger/commit/df61942968e8a3d69f4c807186f75e5b7e5ca1cc

@wyrn73 if you could follow up and confirm whenever I update, that would be great, thanks.
