### ISSUE TITLE
Allow option to prefer normal (newline) keyboard

### ISSUE THREAD

**Issue by fnxweb** [klinker-apps/messenger-issues#177]
I'd very much like an option to use the normal version of the keyboard that has a newline button not an emoji one.

**Comment by fnxweb** [comment]
Sorry, don't know how to flag Android, Feature Request with the mobile version of the guthub site.

**Comment by klinker41** [comment]
Please follow the provided template for bug reports. 

This feature is dependent on the keyboard that you use, google keyboard has no problem displaying both

**Comment by klinker24** [comment]
Can't you just long click the emoji key? To be honest, making an option in settings for this is something I really want to avoid. I don't particularly want to fill the settings menu with so many tweak options.

**Comment by fnxweb** [comment]
Yes, I can do it with long clicks, so it's not a killer and won't stop me using it, it's just a bit of a PITA as I use newline in texts much more that emoji - I'm probably somewhat of an outlier in that respect!

Your app, your call.

**Comment by klinker24** [comment]
Sorry this isn't something that I am going to make an option for then, like I said, I really want to avoid that type of thing
