### ISSUE TITLE
Sending bug while offline

### ISSUE THREAD

**Issue by ram130** [klinker-apps/messenger-issues#178]
When you send a message while offline and having had signal for a while...the message will go into a "stuck" sending state. Never recovering or sending.  

I usually have to copy and paste the message again, delete the old one and hit send. But even doing that causes the new one to get stuck and take some time but will eventually send.

**Comment by klinker24** [comment]
Can you please add the requested information from the template? Would love those details on this one... Thanks

**Comment by klinker24** [comment]
Closing due to lack of response.. Need more information on this issue, feel free to reopen if you can provide it
