### ISSUE TITLE
Specify max MMS size

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#181]
**Device with issue:** Android app on foreign carriers
**App version:** 1.12.0
**Information:**

Some European carriers don't have standard MMS sizes. Our app currently assumes that all MMS need to be under 1MB.

We may have to add a settings option to put the max size of these messages.

**Comment by devantoine** [comment]
When I try to send a MMS over 1MB, I don't even get an error message. Everything seems to went fine but the contact never receive the MMS.

**Comment by klinker24** [comment]
@devantoine it probably sends fine on your end, but the other end's size limitation makes it fail there.

**Comment by klinker24** [comment]
This is done with: https://github.com/klinker41/messenger/commit/ed1c1aeea5cfd86dbcd170cfd7dbfed9fea8c90f
