### ISSUE TITLE
Search messages from the web

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#182]
**Request:** 

This would be neat to have. The Android app has some pretty awesome search functionality, I don't think that I would bring quite all of it to the web, at least to start. I would just like to search messages to begin with.

**Implementation Notes:**

Would need to make a new route for `Messages#search` that will just take a query and return the results of that query.

We can then pump that into the web app and just display the same message adapter

**Comment by klinker24** [comment]
Something to consider: the text is obviously not indexed.

This could be a pretty long running query for some users. Maybe it would make more sense to only allow it from a conversation?

I will probably just have to try it and see. Our database server may be able to handle it, just not sure.

**Comment by klinker24** [comment]
Well, added an endpoint here: https://github.com/klinker41/messenger-server/commit/ad68b94210f1ccd03d140eb2163149104f8e4498

This isn't going to work though. I realize that with the encryption, there is no way to search server side. Ugh. 

Obviously we could just search client side, over the latest 500 messages, but this would not work very well and would be very confusing to the user.

**Comment by aswerdlow935** [comment]
Do you think you could at least add search for contacts without creating a new message on chrome and the web platform? Just a name search would be soooo helpful so I don't have to search through contacts.

**Comment by klinker24** [comment]
Sorry I don't understand the usage. If you are looking for a conversation, just do `ctrl+f` to find it on the list, there isn't really a reason for me to implement a search for that..

**Comment by aswerdlow935** [comment]
I didn't think of that for the web version, but for the chrome extension and app, I tried that and It does not work. Would there be a way to implement a search for that?

**Comment by klinker24** [comment]
maybe, don't know if that is something i will add or not. Thanks for the suggestion.

**Comment by ugachmaaz** [comment]
+1 for searching contacts, would be useful. Right now, I have to scroll and search for the conversation/contact or just start a new message and type in the contact name.
