### ISSUE TITLE
Mouse wheel scrolling causes messaging view and conversation list to display simultaneously

### ISSUE THREAD

**Issue by farmerbb** [klinker-apps/messenger-issues#183]
**Device with issue:** Pixel C running Android 7.1.1
**Primary device:** Nexus 5X running Android 7.1.1
**App version:** 1.12.0.769 and earlier
**Steps to reproduce:**

1. Connect a mouse (Bluetooth, USB, etc) to your Android device
2. Open Pulse and select any conversation
3. Scroll down using the mouse wheel and the conversation list will scroll into view, underneath the currently active conversation

Please let me know if you need any more information, or if you'd like me to test any fixes.  Thanks!

**Comment by klinker24** [comment]
Thanks, I have heard about this one, but have not been able to find any headway on fixing it yet. Will continue digging

**Comment by klinker24** [comment]
When a message list is opened, I should start to disable scrolling on the conversation list: http://stackoverflow.com/a/34060065

Pretty easy with a `RecyclerView`.

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/messenger/commit/7421cde2eab6845cfb74c169add629470b0cc3c0

@farmerbb reopen if this is not working for you, after the next update. It will be live in 1.12.3
