### ISSUE TITLE
Screen does not turn on with notification

### ISSUE THREAD

**Issue by Nightshaxx** [klinker-apps/messenger-issues#184]
When I get a message, my screen does not turn on. This can be an issue if I am listening to something on my PC, and I am relying on the visual aid to know when I get a text. 

Android 6.1, Zenfone 2

**Comment by klinker41** [comment]
Are you talking about your computer screen turning on or your phone screen? Please be more specific and follow the provided template in the readme in the future.

If you're talking about the phone screen, please see https://github.com/klinker-apps/messenger-issues/issues/173

**Comment by klinker24** [comment]
Someone mentioned that the feature didn't work for them. I will fix it.

**Comment by klinker24** [comment]
https://github.com/klinker41/messenger/commit/c1404dcb12d871949b215f380921f29b47f83b0e
