### ISSUE TITLE
Screen stays on after receiving message 

### ISSUE THREAD

**Issue by PlasmaEye** [klinker-apps/messenger-issues#186]
### Screen stays on after receiving message 

**Device with issue:** Nexus 6P running Android 7.0
**Primary device:** Nexus 6P running Android 7.0
**App version:** 1.12.0.777
**Steps to reproduce:**

1. Set the Alert Types - Wake Screen setting to On.
2. Receive a message and immediately view it through the Firefox plugin 
3. Message notification clears from phone and the screen stays on

**Additional information:**

Firefox plugin is version 1.5.0. The use case is the phone sitting underneath my monitors at work, I see the screen come on and I go to the Pulse plugin in Firefox to view the message. This all happens within a few seconds of receiving the message. 

Just tested it and the screen stayed on for two minutes before I shut it off. My display sleep setting is set to one minute.

**Comment by klinker24** [comment]
Try on 1.12.0.780, should already be fixed for the prod rollout from this morning

**Comment by PlasmaEye** [comment]
Looks like it is fixed on 1.12.0.780. Nothing like having a negative bug response time.
