### ISSUE TITLE
Doesn't display received vcards

### ISSUE THREAD

**Issue by Nightshaxx** [klinker-apps/messenger-issues#191]
I was sent a contact info file, but the app did not display it. I can confirm it was received properly because Google messenger displayed it.

- Android 6.0.1
- Asus Zenfone 2
- App version 1.12.3.785

**Comment by klinker24** [comment]
Sounds like they are coming in with a mime type that is not supported by the app. We currently support `text/x-vcard` and `text/vcard`. If you can provide me with the mime type and how that contact card was generated, I can look into adding support.

**Comment by klinker24** [comment]
I added legacy `.vcf` mimetype support. In the future (not currently downloaded cards), the app will handle:

```
text/x-vcalendar
text/directory
text/directory;profile=vcard
application/vcard
```

If this doesn't work, you will have to provide more info for the future. Closing since I never heard back.

**Comment by wizard7926** [comment]
Hi Luke, I know that you usually shut down duplicate issues, so I'm adding to this one rather than open a new one with the same info. If this is wrong, please let me know for the future.

I received a contact info file, generated by an iPhone, of MIME type "text/x-vCard", which is said to be supported above. Pulse did receive the file, but it did not show the contact's name; rather, a generic face icon. Textra displays the contact name. Thanks Luke.

I'm on an Verizon LG VS987 (G5), Nougat 7.0.1, Pulse version 2.0.3.1023.

**Comment by klinker24** [comment]
It is working as expected. Click the icon and it will import the contact into your contacts app

**Comment by wizard7926** [comment]
It does import as expected. However, I don't even know what the contact is until I root through my phone list to find it. If it's something generic like "Joe from the Water Company", but she might have it as "Water Co - Joe", etc, it would be a lot easier to see the contact name within the message before importing. Would be a lot better user experience to see the name up front to allay confusion.

I understand this is probably low on your totem pole, and I appreciate your continued diligence to your users! Just putting in my two cents.

**Comment by wizard7926** [comment]
Any further thoughts on this? Android Messenger does it, Textra does it, GoSMS does it.. Evolve and Pulse are the only ones I have found that don't display the contact name..

**Comment by wizard7926** [comment]
Np, thank you for replying and for your hard work.

**Comment by karawhalin** [comment]
I am having trouble with my contact cards coming though correctly from my Pixel 3 phone using the Pulse app.   Please advise
