### ISSUE TITLE
Customize Vibration Notification

### ISSUE THREAD

**Issue by havanahjoe** [klinker-apps/messenger-issues#192]
I would love to be able to customize the vibration, mostly because I like a single short vibration for my texts. Even if it's just the addition of this option, it would make me very happy.

**Comment by klinker24** [comment]
I can add a single vibrate for you, but I don't have any plans to do custom ones, sorry.

**Comment by havanahjoe** [comment]
That would be awesome. Textra has this so I assume others would like this option.

Thank you!
