### ISSUE TITLE
Device management

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#193]
**Request:**

The "My Account" page on the web shows a number of statistics, including the number of devices set up with your account. For user piece of mind, they should probably be able to delete old devices.

**Implementation:**

I don't see a need for this on Android, so really, we just need a web page to display everything. A device record should show the id of the device, and the `info` column. If it is the primary device, it should also be shown at the top and marked as primary.

Clicking a device should just pop up with a dialog, asking if they want to remove it.

@klinker41 do you see any complications here?

**Comment by klinker41** [comment]
You'll just have to send a message to the deleted device and tell it to sign out I would say.
