### ISSUE TITLE
Delayed messages improvements

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#195]
**How they work right now:**

When you hit the send button, a progress bar comes up, that acts as a timer. The current message just sits in the text entry area. If you want to edit the message, you can. Otherwise, just wait for the timer to go off, then the message will be sent.

**Improvement Ideas:**

* [ ] ~Queue up more than one message~
* [ ] Ability to send the messages immediately

When you hit the "send" button, that message could move outside of the text entry and into a "queued" zone. It would have buttons to send and to edit. If the edit button is clicked, then the message should be cancelled and return to the text entry area. If the send button is clicked, the timeout should be cancelled and the message sent immediately.

**Implementation Notes:**

I still want to send all of the queued messages, immediately, when the user backs out of the conversation. Scheduled messages are the ones designed for longer periods of time. I want to warn them of this, though. "This message will be sent when you leave the conversation." It should have an opt-out button so that the warning can be shown only once, if the user wants that.

**Comment by NayBelle** [comment]
Hi, I would like to second this request. Any way to send an immediate response without waiting for the delayed message to be sent would be awesome. A button would be great, or perhaps just sliding along the timer bar to "fast forward" the message could work too... 

I hope you'll consider this request. Thanks for reading...

**Comment by jemhuntr** [comment]
It would be a pain in the ass to implement, but you could allow "scrubbing" on the input field to speed up or slow down the delayed sending.

Basically you just detect touch movements and add the touch displacement delta to the delay timeout. Would also be great if it was velocity-aware, so scrubbing faster would move the delay further.

**Comment by cjmueller1** [comment]
Thirding this issue. I'm a fan of how Textra handles this. If you hit the send button a second time while the delay is in progress, it does an immediate send.

**Comment by jrmasonaz** [comment]
Another vote for this feature. I have the delay set to work with longer texts, but it's usually too long. I've used Go SMS Pro for the last few years. I like how it's done there. When a text is sent it turns into a "bubble" and can no longer be edited. I can just press the actual text again to send it before the delay time is over. Works great.

**Comment by Compyooter** [comment]
I came here to suggest this feature, so adding to his thread.
I too would love a 'send now' option.

Another point on this topic:
When Delayed Sending is set, the current behavior of the app (currently v2.9.2.1974), and all previous versions I remember, will send it immediately if you exit the app. If you just hit your home button or go to another app from your notifications, the message will sent right then. The Delayed Sending feature will be complete when you have a 'send now' button, AND you can toggle On/Off this behavior of the app. With the current behavior of the the delay working only while you're in the app, and you cannot go do something else, the advantage of this feature is quite narrow. If I need to wait in the app for the delay to work, I can just as well wait and not send the message, think it over, and send when I'm sure. If I didn't need to wait for the delay (as Gmail's delay works), that's when the feature becomes useful.

**Comment by klinker24** [comment]
I don't see that change coming. Delayed sending is meant to give you time to edit the messages. If you exit the thread or close the app, you are not editing the message. This is working the way I have designed it and the way I want it to work. 

If you don't want to send it until later, create a scheduled message instead. That's what that feature is for. I don't want delayed messages to be the same as scheduled messages, there is no reason to duplicate that functionality.

**Comment by Compyooter** [comment]
@klinker24 Well, your work, you decide.
Anyway, thanks for the app, your time and effort. Great app.

**Comment by blockflote** [comment]
Love being able to text from the PC.  Thank you! For delayed sending in the Android app, could qued texts be visible entirely, as though the texts have been sent, rather than have them remain in the edit area.  Proofing would be much easier.

**Comment by jwulf1092** [comment]
My 2 cents...
I agree that putting the delayed text into the sent messages area with options to edit or send now would be a great improvement.
I agree with Compyooter on the idea that you should be able to leave the conversation and let the timer still continue to run. Scheduled messages (in my humble opinion) is too cumbersome to use consistently (See explanation below), and sometimes I want to go look at a picture on my phone, or at the text of an email, to make sure what I wrote is what I want to send, but I don't want to stop the timer by pressing the X and then leaving the conversation to do my research. I have a sense of how long the timer has left, and I typically can go take a quick peek at a pick or reread a line in the email in less time than the timer has, allowing me to go back to pulse and edit or stop the timer if needed, or determine what I wrote is fine and then I do not have to go back into pulse to restart the delay send timer.

EXPLANATION of cumbersome scheduled messages:
12 to 19 clicks and scrolls/swipes to compose a scheduled message is too many!
For me if I am in a conversation and want to send a message at a time later then the delay I have set up, then I click some 
1 to collapse the  message
1 to open 3 bars
1 scheduled messages
1 plus sign.
9 times if it is a number, or 2 to 3 to do a contact
1 to confirm the contact
1 for the date
2 scrolls/swipes around the clock for hours and minutes
1 to accept the time
NOW I can type my message. 
1 more to add the message to the que

I hope you will reconsider your position on this.
John Wulf

**Comment by klinker24** [comment]
`v4.6.1` of the app will allow skipping the delay, as well as scheduling messages, via a long click on the send button.
