### ISSUE TITLE
No results delivered when switching fullscreen camera to landscape during a picture

### ISSUE THREAD

**Issue by Repooc** [klinker-apps/messenger-issues#196]
Only note 5, add a picture via the camera, hit OK but no image there to send. Will attach screenshots of system info to help
![screenshot_20161219-164719](https://cloud.githubusercontent.com/assets/1479745/21330422/5c15ccf8-c60b-11e6-8cce-5becf2c6d7e7.png)
![screenshot_20161219-164704](https://cloud.githubusercontent.com/assets/1479745/21330431/679cb668-c60b-11e6-9226-f4fd7d841f81.png)

**Comment by klinker24** [comment]
It would be helpful to see a video, the screenshots of your system information are not really helpful in this.

Have you given the app all the requested permissions?

**Comment by Repooc** [comment]
I have given permissions when it was asked. Any recommended video recording program you would suggest. At work and don't want to browsing play store at work haha I ended up taking pictures with the camera then attaching it in the app since the camera didn't seem to work

**Comment by klinker24** [comment]
Sorry I only ever take videos from Android studio. Were you using the little camera that is in the message list, or did you hit the expand button to use the full screen camera in the app

**Comment by Repooc** [comment]
I hit expand for the Fullscreen camera

**Comment by klinker24** [comment]
Ok, does it with on the little camera?

**Comment by Repooc** [comment]
Just tested and worked fine with little camera

**Comment by klinker24** [comment]
So were you changing orientation or anything else I should know?

**Comment by Repooc** [comment]
Shoot didn't think about that but yes was in landscape mode...

**Comment by Repooc** [comment]
Just reproduced it in landscape... Leaving in protrait mode didn't have any issues but one I tried turning phone over and take a pic, it would not attach itself to the message

**Comment by Repooc** [comment]
See if you have access to this video here on my google drive https://drive.google.com/file/d/0B1qgi--EzuqGTTZ5TllzRWlkdnM/view?usp=drivesdk

**Comment by klinker24** [comment]
Ok thank you, I have found the issue, don't have a fix yet though.

**Comment by Repooc** [comment]
OK tyvm

**Comment by klinker24** [comment]
I finally found a good fix for this. That took entirely too long. Sorry about that.

https://github.com/klinker41/messenger/commit/4ef43119f92fbd4d1da92e897ebf2c07450b83c7
