### ISSUE TITLE
Latest messenges not syncing on app, web or extention.

### ISSUE THREAD

**Issue by Shadowonx** [klinker-apps/messenger-issues#197]
I logged out of Pulse a few weeks ago and uninstalled the app on Android. I re-installed it now and the latest messages is not syncing. It only synced messages from the last time I used Pulse. Texting and receiving new messages works fine. But there are no recent history in conversations. Only the old ones.

This goes for all the apps.

**Comment by klinker24** [comment]
Please see the FAQ: https://messenger.klinkerapps.com/faq.html
