### ISSUE TITLE
Contact photos?

### ISSUE THREAD

**Issue by Shadowonx** [klinker-apps/messenger-issues#198]
Am I missing something? Not syncing contact photos from my contacs list?

**Comment by klinker24** [comment]
You will have to be way more specific with what you are seeing... Sorry

**Comment by Shadowonx** [comment]
Wow, you're fast! Do you ever sleep? 😳

An update. Contact photos are showing on the phone, but not on web, ext... There I just see a circle where the photo should have been. Like this.
![lightshot](https://cloud.githubusercontent.com/assets/24480737/21437731/e6fee9b8-c885-11e6-97a9-82ef1ea82975.png)

**Comment by klinker41** [comment]
Contact photos are not shown currently on the web.

**Comment by Shadowonx** [comment]
Ok, thanks! I know who they are, so no big deal 😜

Any plans on implementing that in the future?

Anyways! Great app! Great support! And great... everthing! Awesome job! 😊

**Comment by klinker41** [comment]
Eventually hopefully, although there are other higher priorities right now.

**Comment by Shadowonx** [comment]
Thanks! I'm in no hurry! :)
