### ISSUE TITLE
Not showing new messages

### ISSUE THREAD

**Issue by rrhutch** [klinker-apps/messenger-issues#199]
I recently switched back to pulse. When I opened it showed all of my recent text messages. However, when I logged into Pulse it pulled all of them from the last time I used Pulse and doesn't show my new messages any longer. How can I get my new messages into Pulse now?

**Comment by klinker24** [comment]
Please see the faq in the "Message from Anywhere" section on this: https://messenger.klinkerapps.com/faq.html
