### ISSUE TITLE
Support GZIPing requests

### ISSUE THREAD

**Issue by klinker41** [klinker-apps/messenger-issues#2]
**Device with issue:** Nexus 6P running Android 7.0
**Primary device:** Nexus 6P running Android 7.0
**App version:** 1.0.180

**Information:**

Gzip can significantly compress file size when uploading large amounts of data, so it is ideal for mobile devices where transfer speed, memory, and bandwidth are limited. Our server should be able to accept gzipped requests from the android client, especially for the initial upload where thousands of messages and conversations could potentially be uploaded.

**Solution:**

I tried adding server support for this through a gem but could not get it working. In the `config/application.rb` file, there is a commented out line with the middleware that I wanted to use, `config.middleware.use Degzipper::Middleware`. When uncommented, the following error will be thrown:

```
No such middleware to insert before: ActionDispatch::ParamsParser
/usr/local/bundle/gems/actionpack-5.0.0/lib/action_dispatch/middleware/stack.rb:108:in `assert_index'
/usr/local/bundle/gems/actionpack-5.0.0/lib/action_dispatch/middleware/stack.rb:73:in `insert'
/usr/local/bundle/gems/railties-5.0.0/lib/rails/configuration.rb:69:in `block in merge_into'
/usr/local/bundle/gems/railties-5.0.0/lib/rails/configuration.rb:68:in `each'
/usr/local/bundle/gems/railties-5.0.0/lib/rails/configuration.rb:68:in `merge_into'
/usr/local/bundle/gems/railties-5.0.0/lib/rails/engine.rb:507:in `block in app'
/usr/local/bundle/gems/railties-5.0.0/lib/rails/engine.rb:504:in `synchronize'
/usr/local/bundle/gems/railties-5.0.0/lib/rails/engine.rb:504:in `app'
/usr/local/bundle/gems/railties-5.0.0/lib/rails/application/finisher.rb:37:in `block in <module:Finisher>'
/usr/local/bundle/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `instance_exec'
/usr/local/bundle/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `run'
/usr/local/bundle/gems/railties-5.0.0/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/local/bundle/gems/railties-5.0.0/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/bundle/gems/railties-5.0.0/lib/rails/application.rb:352:in `initialize!'
/messenger/config/environment.rb:5:in `<top (required)>'
/usr/local/bundle/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
/usr/local/bundle/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `block in require'
/usr/local/bundle/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
/usr/local/bundle/gems/railties-5.0.0/lib/rails/application.rb:328:in `require_environment!'
/usr/local/bundle/gems/railties-5.0.0/lib/rails/application.rb:448:in `block in run_tasks_blocks'
/usr/local/bundle/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:test:prepare => environment
```

I think that the gem has not been updated to support rails 5 yet. I commented out the gem in the `gemfile` for now.

Once server support is finished, there is a line that is currently commented out in the `Api` class:

``` java
httpClient.addInterceptor(new GzipRequestInterceptor());
```

Uncomment it and all of the requests will have their full bodies automatically gzipped.

**Comment by klinker41** [comment]
We now support this in the server with https://github.com/klinker41/messenger-server/commit/ced3b6a36f544279233bbff206ed2996a7763885

and in the android app with https://github.com/klinker41/messenger/commit/cb052b74d66611098bccf9498c74c79642d5d9d4

we'll need to test this in staging, but the android tests are passing and it should work correctly. Hopefully this will help with memory issues as well.

**Comment by klinker24** [comment]
If we push to the server, will it work for current users of the app or will nothing work until they update on the Android side too?

**Comment by klinker41** [comment]
It will only do anything if the header is there, so users not gzipping will
still work fine. So yes, old users will work fine.

**Comment by klinker41** [comment]
Tested and confirmed to be working now after a few tweaks.

**Comment by klinker41** [comment]
This worked in staging but did not work in prod. I disabled the gzipping in the client again and it worked fine, so my theory is that it may be too much of a load for the server to have to gunzip everything and it ends up not working correctly.

I sped up requests though in other ways, so leaving gzip disabled in the client should work fine for now.

**Comment by CorruptComputer** [comment]
Why not have a separate VPS just for the unzipping? This would stop the main server from getting backed up and you could easily make a priority based queue system for it with parameters like time sent, filesize (more messages, larger file), and time spent waiting. For example if it had 20 threads and you receive 30 requests, start with the largest 10, then span the rest out to the requests that were received first. this makes sure everyone gets their messages in a timely manner as 3 or 4 regular messages can probably finish in the time 1 large initial message dump can.

**Comment by klinker24** [comment]
@CorruptComputer I don't think gzip is what you are imagining it is. We aren't actually zipping the database or what is stored, we are gzipping the individual requests to make them smaller and make them faster: https://robots.thoughtbot.com/content-compression-with-rack-deflater

We have to do that within the same thread as the request comes in on, so that we can provide a gzipped response

**Comment by CorruptComputer** [comment]
Ah, I thought you were gzipping the actual contents of the messages, not just the requests. Might still be something worth looking into though.
