### ISSUE TITLE
Giffgaff Delivery Reports

### ISSUE THREAD

**Issue by theofficialknightvision** [klinker-apps/messenger-issues#203]
I would like it if Pulse had the option to automatically add the *0# shortcode at the start of a message like EvolveSMS does. I'd also like it (if possible) if the feature wasn't just limited to giffgaff, I know a few people who would like this feature but they don't have a giffgaff sim

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/messenger/commit/c80fa8d91329433ea4391b24a7d74a6774ba683d
