### ISSUE TITLE
AMOLED black background for auto day/night mode. 

### ISSUE THREAD

**Issue by roginfarrer** [klinker-apps/messenger-issues#206]
Currently auto mode defaults to a regular dark theme. Would be great to have an option to choose AMOLED instead.

**Comment by klinker24** [comment]
Sorry, making little options for this type of thing is something that I really am trying to avoid for this app... So right now, I am going to say no on this one. Android provides some very nice day/night functionality now, which we use, and I don't want to change the way that is handled or add another preference for something so small
