### ISSUE TITLE
Edit chat names without changing the actual contact in the phone

### ISSUE THREAD

**Issue by luiisalfonso** [klinker-apps/messenger-issues#208]
I love how there are customizable features. I think theres one lacking feature that very important, edit chat/text names. Sms apps will usually just make you edit the actual contact name on your contacts app but it would be amazing If pulse will let you edit it just on pulse itself

**Comment by klinker24** [comment]
Sorry, this isn't something I see happening, it just doesn't make all that much sense in my opinion.. You can edit the names of group conversations though, of course, which I think is a lot more helpful.

What is the use case for naming it anything other than the contact name?
