### ISSUE TITLE
Group message colors change with each open

### ISSUE THREAD

**Issue by VergilTheHuragok** [klinker-apps/messenger-issues#213]
Every time a group message is opened, the text colors corresponding with each contact in the group changes. Colors given in conversation settings appear to be ignored.

**Comment by klinker24** [comment]
How long have you had the app? This was changed, but initial beta testers would never have been migrated, I posted that you would have to recreate your account.

**Comment by VergilTheHuragok** [comment]
Wow, that was a fast reply. I got the app very soon after initial release. I must have missed that post, sorry. I'll be sure to recreate my account. Thank you!
