### ISSUE TITLE
MMS Doesn't display on Pebble Time Smart Watches

### ISSUE THREAD

**Issue by VergilTheHuragok** [klinker-apps/messenger-issues#214]
Any form of MMS notification from Pulse does not get displayed on my Pebble Time. SMS notifications are displayed fine and allow replies from the watch. Having looked up the issue, it appears there are many messaging apps with this problem although I could not find a solution short of installing a new app.

**Comment by klinker24** [comment]
I don't know that there is a solution on my end. Pebble should handle mirroring those notifications, there isn't anything that I do for that

**Comment by VergilTheHuragok** [comment]
Alright, thanks again. Love the app!

**Comment by VergilTheHuragok** [comment]
I have solved my issue! This seems to be an issue for a lot of messenger apps. For anyone else having this problem, in the pebble app settings, check "Disable built-in SMS notifications." I now receive MMS and can reply from my watch.
