### ISSUE TITLE
Add ability to change your account password

### ISSUE THREAD

**Issue by kennyjwilli** [klinker-apps/messenger-issues#217]
There is no way to change your password via the web UI or phone app.

**Comment by klinker24** [comment]
There won't be, please see the FAQ, with the encryption, this isn't going to happen

**Comment by kennyjwilli** [comment]
After reading the FAQ, I now understand why I cannot change my password. I think there should be a better user experience for something like this. Rather than directing me to the FAQ, which opens outside of the app, there should be an option to change your password in the app. When clicked, a dialog would open saying something like:
> Because all of your messages are end-to-end encrypted, you must deleted your account to change your password. This will not delete your messages from your phone.
> CANCEL or I UNDERSTAND

If the user clicks "I UNDERSTAND", then the account should be deleted and the new account dialog should pop up.

I think this will be a common question, and a change in UX could prevent this question.

**Comment by klinker24** [comment]
I actually have only been asked about it a few times, everyone else hits the "forgot password" link, in android or the web, and it takes you to the explanation page..

**Comment by klinker41** [comment]
![screenshot from 2017-01-03 13 46 53](https://cloud.githubusercontent.com/assets/4501322/21624254/21fa3b60-d1bb-11e6-97a2-8016792c124a.png)

Android is in a similar place, right under the password line if I remember right.

**Comment by klinker24** [comment]
![screenshot_20170103-174031](https://cloud.githubusercontent.com/assets/4874287/21627209/d5da2896-d1db-11e6-8bf1-90a1fb3ea6f3.png)

**Comment by kennyjwilli** [comment]
Oh sorry, I see the miscommunication. I am talking about changing your password _after_ you have already logged in. The "forgot password" link doesn't come to mind because I didn't **forget** my password, I want to **change** my password.

**Comment by klinker24** [comment]
Gotcha. Still wont ever happen, for the same reasons, sorry

**Comment by kennyjwilli** [comment]
I understand that it can't happen from an implementation perspective, I am merely suggestion an alternate user experience. My experience was quite confusing, and I'd bet others have had the same experience. Most users will not go out of their way to report it though.

**Comment by klinker24** [comment]
<img width="1016" alt="screen shot 2017-01-03 at 6 51 55 pm" src="https://cloud.githubusercontent.com/assets/4874287/21628537/e9001fde-d1e5-11e6-977b-cb529e447827.png">

Ok, here is a link on the web, now.

**Comment by kennyjwilli** [comment]
Looks good! After clicking the "Change Password" link and then hitting the back arrow on the web page, I am taken back to https://messenger.klinkerapps.com/conversations.html instead of https://messenger.klinkerapps.com/my_account.html. If I navigate back using Chrome's back button I am taken to the correct place.

Also, I think the same link belongs in the My Account page in the app, but that is up to you 😃
