### ISSUE TITLE
Improve web messenger SEO

### ISSUE THREAD

**Issue by kennyjwilli** [klinker-apps/messenger-issues#218]
After setting up my account on my phone, I was not able to find the link to open the web app. I tried Googling for "pulse sms" and "android pulse sms" but neither gave me the result I was looking for -- https://messenger.klinkerapps.com. 

My experience was confusing and I think it could be made better by: 

1. Improving the SEO of the web messenger app. You probably need some sort of landing page.
2. Provide a link to the web app from the phone. Also, you should give us a way to share that link to our computer. e.g. pushbullet, email, etc.

**Comment by klinker24** [comment]
There is a link in the about page on the app, not sure what to do for the search engine stuff, there is already a home page..

As for sharing that link, Google chrome does this already, after opening the link, hit the share button, or just open it on your computer based on your phone's history 

The link to the website is also in the FAQ, supported platforms, and on the play store description, not where else I can put it to be honest

If you have SEO tips, feel free to leave them here though

**Comment by kennyjwilli** [comment]
I suggest showing a dialog after you create your account that can let you open the link in Chrome. It wasn't clear to me that I needed to go to the About page of the app (a page which I would rarely visit anyway) in order to find the web app URL.

As for SEO, the Messenger app did not appear until the 8th result, and it was the FAQ page, not the landing page. Typically, I'd expect to find the web app landing page within the first couple of results, not the FAQ page at the bottom of the results list. 

There are loads of sites about SEO. I suggest going through a few of them to see if you are following Google's best practices 😃

**Comment by klinker24** [comment]
I don't want to interrupt the user with a pop-up, that one is out of the question, sorry. I feel as though the web is plenty visible between the play store, the app, and the apps documentation though, I don't want to overload it and make the user feel as though I am forcing that on them, since the web is only a part of the app.

You are the first person to ever tell me that they have had trouble finding it, so I feel as thought that is in an OK place..

I will see about the searching improvements though. Thanks.

**Comment by kennyjwilli** [comment]
Fair enough. 

You have to remember, most users won't take the time to report problems, confusion, etc. 😉

**Comment by klinker24** [comment]
Pretty sure that if they pay for a service, they will either ask, or find the link to that service

**Comment by kennyjwilli** [comment]
Right, which is what I had to do. I was just letting you know my experience was confusing and could easily be made better with some SEO 😃

**Comment by klinker24** [comment]
Ok, added more links to the homepage, changed the name, added alt descriptions for image.
