### ISSUE TITLE
Notifications aren't dismissed when reading a message

### ISSUE THREAD

**Issue by rushigan** [klinker-apps/messenger-issues#219]
Hey guys, loving the app, but am having an annoying issue with the notifications (it COULD be an issue with my notification settings, though).

**Device:** Galaxy S7 Edge running Android 6.0.1
**App version:** 1.13.2.834

This is happening intermittently and I can't always recreate. It seems to happen when there are multiple message threads with notifications as opposed to just one.

1) While my screen is locked, I receive one (or multiple) messages and get a notification without issue
2) After opening the app directly from the home screen (not by clicking the notification bar), the notification remains even if I read the message(s). I have to manually go and swipe away the notification on the read messages. 

The notification DOES go away automatically if I open the app directly from the notification itself. 

I have checked my settings and everything looks to be normal. I didn't have the issue when using Google Messenger. Thanks!

**Comment by klinker24** [comment]
If you can get steps to reproduce this, that would be great. I have not had this happen to me, so I am unable to confirm/fix at this time

**Comment by klinker24** [comment]
I have made some changes for the next version. I am going to close this issue, feel free to re-open if you can provide more detail after the next update
