### ISSUE TITLE
Force close from lacking permissions

### ISSUE THREAD

**Issue by 4rsenal** [klinker-apps/messenger-issues#22]
On my HTC 10 (VZW)[ROOTED] I get a crash right after I grant Messenger the permissions. (Log attached below)
[MessengerForceCloseRootedVerizonHTC10.txt](https://github.com/klinker-apps/messenger-issues/files/443656/MessengerForceCloseRootedVerizonHTC10.txt)

**Comment by klinker41** [comment]
Next time, please check the readme and follow the template we provided there.

Looks like a permissions issue, I'll look into it and see if I can get it worked out.

**Comment by klinker41** [comment]
Made changes to request phone permissions at startup along with contacts and sms. This will allow for the READ_PHONE_STATE permission to be accepted and should be good to go.

https://github.com/klinker41/messenger/commit/ecc9d929ede829d7a8c3c8c0c18dfe031f96c1d7

@4rsenal the new version will be 1.0.193 and should be up within a few hours, when you see that try it out and check back here to let me know if it is working or not!

**Comment by 4rsenal** [comment]
Yup all is good now @klinker41 ... Now have issue with some messages from a conversation showing in a separate conversation (same sender/receiver, just multiple conversations with messages split up). I was using airdroid which I thought was the issue so deleted it and reinstalled Messenger but no dice. Can provide logcat with the CORRECT format if necessary ;)

**Comment by klinker41** [comment]
Yeah, please start a new issue for that one now :)
