### ISSUE TITLE
Chrome apps ending in 2018. Standalone app?

### ISSUE THREAD

**Issue by kennyjwilli** [klinker-apps/messenger-issues#220]
Have you seen this? https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html

>Starting in late 2016, newly-published Chrome apps will only be available to users on Chrome OS. Existing Chrome apps will remain accessible on all platforms, and developers can continue to update them.
In the second half of 2017, the Chrome Web Store will no longer show Chrome apps on Windows, Mac, and Linux, but will continue to surface extensions and themes. In early 2018, users on these platforms will no longer be able to load Chrome apps.

Are you still going to have a standalone app when Chrome apps are killed off? I personally like having a standalone app instead of a tab always open in Chrome. 

Have you looked at [Electron](http://electron.atom.io/)?

**Comment by klinker24** [comment]
Yes, electron is planned
