### ISSUE TITLE
Messages not syncing across devices

### ISSUE THREAD

**Issue by heartlikedecember** [klinker-apps/messenger-issues#221]
### Messages not syncing across devices

**Device with issue:** Samsung Galaxy Tab A 10.1
**Primary device:** OnePlus 3t running Android 7.0
**App version:** 1.13.4.851

**Additional information:**

The app on my galaxy tab will not receive new messages unless I do a manual resync.  It is also unable to send any messages at all, they simply hang at the "sending" stage.

**Comment by klinker24** [comment]
Have you tried uninstalling and reinstalling on your devices?

**Comment by heartlikedecember** [comment]
I've tried uninstall and reinstall the app on my tablet several times with no success.

**Comment by heartlikedecember** [comment]
> Have you tried uninstalling and reinstalling on your devices?

I've tried uninstalling and reinstalling the app on my tablet several times with no success.

**Comment by klinker24** [comment]
Try the phone. Seems like the messages are not being delivered to your phone.

**Comment by heartlikedecember** [comment]
> Try the phone. Seems like the messages are not being delivered to your phone.

Tried reinstalling on my phone as well and that didn't fix the issue.  Messages are still being delivered to my phone, as well as the chrome app, perfectly fine, and I can still send messages from my phone with no issues.  It's just my tablet that won't of sync.

**Comment by klinker24** [comment]
Oh, you said you couldn't send from the tablet.

There is a devices link under "my account" on the web. See if your tablet shows up there

**Comment by heartlikedecember** [comment]
There are 3 SM-T580 devices listed, as well as my phone and the web app, so I assume those are just the different instances of the web client I've used?  No listing of my tablet on the list.

**Comment by klinker24** [comment]
The SM-T580 isn't your tablet? That seems like it would be a Samsung tablet

**Comment by heartlikedecember** [comment]
> The SM-T580 isn't your tablet? That seems like it would be a Samsung tablet

Oh you're right, it is my tablet.  Totally forgot to compare that to the device model number.  Should I try removing all 3 and reactivating it?

**Comment by klinker24** [comment]
Sure, yes

**Comment by heartlikedecember** [comment]
> Sure, yes

Removed all the devices, re-downloaded, and reactivated on my tablet and it still doesn't seem to be pulling in new messages.  Could it be a Samsung issue?  This is the only other android device I have to test on.

**Comment by klinker24** [comment]
What version of Android does it have, have you messed with any custom ROMs on it that would have messed up Google play services? Is Google play services up to date?

**Comment by heartlikedecember** [comment]
> What version of Android does it have, have you messed with any custom ROMs on it that would have messed up Google play services? Is Google play services up to date?

It's currently running 6.0.1 on the July security patch.  I have not installed any custom roms and I updated play services last night.

**Comment by klinker24** [comment]
Ok. The issue is that the device is not receiving notifications from Firebase Cloud Messaging. Why that would be, I cannot say, at this time. 

I have never heard from anyone else where clearing the app data, then logging in again, on the device, didn't fix it.

**Comment by heartlikedecember** [comment]
> Ok. The issue is that the device is not receiving notifications from Firebase Cloud Messaging. Why that would be, I cannot say, at this time.
> 
> I have never heard from anyone else where clearing the app data, then logging in again, on the device, didn't fix it.

Weird.  Think it must be a Samsung bug then?  If it's still working on my phone and the web...

**Comment by klinker24** [comment]
Yes, I would say it has something to do with the device.

**Comment by heartlikedecember** [comment]
> Yes, I would say it has something to do with the device.

Well that's unfortunate.  I bought Lifetime hoping I could use it there.  Oh well, guess I'll wait for a software update from Samsung and try again.

**Comment by klinker24** [comment]
Someone else reported an issue with this, when delivery reports were turned on. I don't know why or how that could possibly effect things, but is that the case with you @heartlikedecember?

**Comment by heartlikedecember** [comment]
@klinker24 glad to hear I'm not the only one. However,  delivery reports are not turned on on any of my devices. I've also noticed that while I can still receive messages on the chrome app,  I'm no longer able to send messages there. Don't know what could have changed

**Comment by ram130** [comment]
Does the application on the tablet have any old messages?

**Comment by heartlikedecember** [comment]
@ram130 it only has the messages from when i first logged in on it that it downloaded from my account.  If I do a manual redownload it will download all the messages up to date, but not receive any new messages until I redownload from settings again.

**Comment by klinker24** [comment]
What if you delete the device from the "My Account" -> "Devices" screen on the web, then clear the app data on the tablet and log back in. The other person had success doing this.

**Comment by klinker24** [comment]
Very interesting, thanks, for the follow up, will close out this issue
