### ISSUE TITLE
login not saved

### ISSUE THREAD

**Issue by pbanj** [klinker-apps/messenger-issues#223]
the firefox add-on doesn't save login info. the moment the add-on window is closed it logs you out.

relevant info:

- os: windows 10 64bit
- browser:  firefox nightly v53.0a1(2017-01-03)(64bit)
- add-on ver: 1.6.0

let me know if you need anymore info

**Comment by klinker24** [comment]
I am not able to confirm this..

**Comment by klinker24** [comment]
Yeah definitely not able to get this to happen.. How about if you are logged in on the web instead of the extension?

**Comment by pbanj** [comment]
web page is working. i will give stable firefox a try sometime tonight and get back to you.

**Comment by klinker24** [comment]
Did you ever try this again?

**Comment by klinker24** [comment]
Going to close this for not enough information... Please feel free to reopen if you find anything else to share. Thanks

**Comment by pbanj** [comment]
@klinker24 i started using it again. i had switched to verizon messaging but that works like crap so I'm switching back. the issue is still there but i thought of something i forgot about last time. i have my firefox clear cookies when i close it so i think that's what's doing it. so not really a bug.
