### ISSUE TITLE
Delete option missing in archived conversations

### ISSUE THREAD

**Issue by arvind-gr** [klinker-apps/messenger-issues#229]
After Achieving several conversions, I went to Archived conversions to delete some them. After selecting multiple items No Delete option is available. Only Move to Inbox icon was available. TO delete manually conversions needs swiping. Please implement Delete icon in top along with Move to Inbox icon when multiple items are selected...

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/messenger/commit/77f2acc3cb5cd8afd75f191505b40c1341816ea0
