### ISSUE TITLE
Allow archiving conversations

### ISSUE THREAD

**Issue by klinker41** [klinker-apps/messenger-issues#23]
**Device with issue:** Nexus 6P running Android 7.0
**Primary device:** Nexus 6P running Android 7.0
**App version:** 1.0.193

**Information:**

Archiving conversations would be a nice touch to keep the conversation list clean without deleting all of your messages. The background work here would not be difficult, we would just need to add a boolean column to the conversation table called `archived` and flip it to true or false accordingly.

The UI would be a little trickier, maybe we could swipe to delete in the opposite direction that we move to trash with. Displaying them could be as simple as extending the current ConversationListFragment and grabbing archived instead of non-archived. 

When a new message is received for an archived conversation, we would flip that conversation to not archived.

**Comment by klinker24** [comment]
- [ ] Migrate database on backend with new column. (default current conversations to 0/false)
- [ ] Add the swipe to delete in the other direction to archive
- [ ] toggle column for archive vs not archived on android
- [ ] only pull in unarchived to the main adapter on android
- [ ] Add a drawer section and new adapter for the archived messages on android
- [ ] Add an archived drawer item on the web
- [ ] Ensure conversations set to "not archived" when a new message arrives

**Comment by klinker24** [comment]
Merged in the android code: https://github.com/klinker41/messenger/commit/07d0646833115cb0f93f5a4e4317d6edca02bbe9
and deployed to the prod backend.

Last thing is the web, but we shouldn't deploy this until the app is released
