### ISSUE TITLE
Don't allow editing of message while delay send is counting down.

### ISSUE THREAD

**Issue by Fammy** [klinker-apps/messenger-issues#230]
**Device with issue:** Nexus 6P running Android 7.1.1
**Primary device:** Nexus 6P running Android 7.1.1
**App version:** 1.14.0.883
**Steps to reproduce:**

1. Enable Delayed Sending in Advanced Features
2. Compose a message and tap the Send icon
3. While the counter is counting down, edit the message
4. Message is sent abruptly when timer finishes its countdown, even if you are still editing.

**Possible solutions:**

Ideally, one of the following would occur:

1. The message textbox/`EditText` should be read-only once the user taps Send.
2. Cancel the delayed send request once the user edits the message.

**Comment by klinker24** [comment]
Actually, I purposely allow this, just for a quick edit, a single letter change doesn't always warrant a stop/restart of the delay, so I leave this all up to the user
