### ISSUE TITLE
Issues in messages received from bulk sender ID's

### ISSUE THREAD

**Issue by FatOrangutan** [klinker-apps/messenger-issues#232]
Can reliably reproduce on Xperia XA, Android v6.0, Pulse v1.13.4.851.

Steps to reproduce:

0. Have at least one message from DM-152484 (more details on this prerequisite below).
1. Try sending a message to either of the two (i.e., 52484 or +91 9880752484) Citibank numbers on [this page](https://www.online.citibank.co.in/products-services/online-services/citi-alert-on-demand.htm).
2. Message sending fails. Trying to resend doesn't help either.
3. Switch to (Google's) Messenger app, set it as default if needed, and repeat step 1 - the message gets sent successfully.

Likely cause:

1. In India, some messages that we receive do not have a number, but instead a name e.g. AD-650001. This is not the name of any saved contact, but for all practical purposes, the 'dummy number' from which these texts were sent.
2. I have messages from Citibank's DM-152484 in my inbox. When I try and send a message to 52484 or +91 9880752484 as per STR 1 above, Pulse opens the conversation with DM-152484 because apparently, that's the number that name is behind.
3. So Pulse effectively 'clubbed' the two 'proper' / textable numbers into this 'dummy number' and tried to send the message to DM-152484 but this doesn't work because that is not an actual number.
4. If I try and send the message (to 52484 or +91 9880752484 as per STR 1 above) from Google's Messenger app, it opens up a new conversation instead of trying to text back to DM-152484. As expected, the message is successfully sent.
5. If I go back to Pulse and delete all the messages from DM-152484 and then try and text (52484 or +91 9880752484) so that Pulse isn't aware of any DM-152484 and hence can't club them, the message is successfully sent.

Things I already checked / other relevant information:

1. Made sure the above number is not in my blacklist - I currently have an empty blacklist.
2. Pulse SMS is my default messaging app and has permissions for Contacts, SMS and Telephone. It can send other SMS' just fine.
2. My phone isn't rooted, I don't have a firewall, antivirus or anything that could be messing with Pulse.

**Comment by FatOrangutan** [comment]
More issues, all from messages from such 'dummy numbers' (I need a better name for these):

1. Weird background added to a message (screenshots 1 and 2), while the message displays fine in the stock Messaging app (screenshot 3). Pulse's settings for that message in screenshot 4:
![screenshot_20170104-051233](https://cloud.githubusercontent.com/assets/8336638/21931794/60bbf16c-d9c3-11e6-92b3-0215952ca6a6.png)
![screenshot_20170104-051243](https://cloud.githubusercontent.com/assets/8336638/21931801/6854fe82-d9c3-11e6-980f-8acf9febdba8.png)
![screenshot_20170104-051337](https://cloud.githubusercontent.com/assets/8336638/21931806/71b3e7ae-d9c3-11e6-9248-2910e54d60bf.png)
![screenshot_20170104-051306](https://cloud.githubusercontent.com/assets/8336638/21931813/76c0238e-d9c3-11e6-8448-7d61eebf8e37.png)

2. Pulse never received a message that the stock messaging app did. My blacklist and archived messages are empty, and the message in question was never deleted by me. Pulse wasn't the default messaging app for the duration, if that's relevant:
![screenshot_20170113-182839_censored](https://cloud.githubusercontent.com/assets/8336638/21932146/0c151e66-d9c5-11e6-85e6-c771e59c6ed6.png)
![screenshot_20170113-182828_cnesored](https://cloud.githubusercontent.com/assets/8336638/21932147/0f35c5aa-d9c5-11e6-9133-a2f23e56ef3f.png)

**Comment by klinker24** [comment]
For your first point, that is a description for the link, that isn't an MMS. If you receive an article, it would do the same thing.

**Comment by FatOrangutan** [comment]
In that case, shouldn't it be resized better? Right now, with the way it is cropped, it almost looks like a glitch instead of a useful feature.

**Comment by klinker24** [comment]
Maybe I am looking at something else, but I don't agree. It shows a preview image of the page, gives you a link to it, and gives you the content. All of it is lined up with the cropping of the image. I think it looks very nice, but to each his own.

**Comment by klinker24** [comment]
I have made changes for the next version of the app. It will be 1.14.1.

You will have to start a new conversation with both of these contacts though, the new methods cannot be applied to current conversations, so the current ones would have to be deleted. 

Please follow up when you get the update, will probably release it to beta tonight or tomorrow, after a bit more internal testing.

**Comment by pSatishC** [comment]
@klinker24 About the preview for links, I remember there was a setting to switch it off but can't find it now - neither in Global nor Advanced. Am I wrong or subsequent updates removed it?

**Comment by klinker24** [comment]
There isn't, hasn't, and won't be a setting for this, sorry...

**Comment by klinker24** [comment]
The change for this issue are currently in beta, if you would like to test them out.

**Comment by pSatishC** [comment]
Not sure how to get the beta. Playstore doesn't show Pulse in Beta category of My Apps. Is it an Open Beta that any user can join?

**Comment by klinker24** [comment]
Yes, there is an opt in at the bottom of the play store page.

**Comment by FatOrangutan** [comment]
Thank you for the quick fix. I would like to test things and report back to you, but would appreciate if you could help me a bit with some questions I had:

1) "You will have to start a new conversation with both of these contacts though, the new methods cannot be applied to current conversations, so the current ones would have to be deleted." Could you tell me if uninstalling and then reinstalling the app would allow it to apply the new methods to the current conversations? I don't mind losing access to my app settings, I can set it up again.

2) I know how to test issue 1 (the clubbing of numbers), but how do I test issue 3 (skipped message)? Could you tell me which messages were skipping the app?

3) I have been through all the popular SMS apps, and Pulse is the one I liked the most. I would eventually like to set Pulse as my default messaging app and disable the stock messaging app, but because I pretty much only use SMS' to inform me of purchases etc. and it missed one such message, I have a bit of a trust issue with the app. Could you tell me if, in the rare case, Pulse misses a message, that message would still *always* be received by my phone and would be in the SMS database, and the stock app would be able to read it? Also, does Pulse have its own messaging database or does it use the same one the stock app would be using?

Thanks.

**Comment by klinker24** [comment]
1) yes that will work as long as you don't have an online account.

2) if pulse isn't the default as you stated, then there is no guarantee that it will pull in the messages, sorry

3) I don't know how to answer this, if pulse is the default, it is the one saving the messages, there shouldn't be a case of it missing a message that gets saved to the default messaging app.

**Comment by FatOrangutan** [comment]
Just got the update. Can confirm, the issue is fixed. Thanks.
