### ISSUE TITLE
Notifications not cleared

### ISSUE THREAD

**Issue by rtorchia** [klinker-apps/messenger-issues#234]
### Notifications are not cleared after reading new SMS message

**Steps to reproduce:**

1. Received multiple SMS messages from different people
2. Pull down notification shade and tap on message to read it in Pulse app
3. Read other new messages in app
4. Notifications are not cleared.

**Comment by klinker24** [comment]
I have made changes for this in the next update. In the future, please provide more detail on your issue. There is a template in the readme here, that you could follow

**Comment by rtorchia** [comment]
Okay, no problem (and you have the record for the fastest response to an issue that I have ever have come across!)
