### ISSUE TITLE
Notifications persistent until dismissed

### ISSUE THREAD

**Issue by RuffWizard** [klinker-apps/messenger-issues#235]
Usually the notifications go away after clicking on them - especially after reading the messages. Now the notifications persist after clicking on them and reading the messages. I now have to manually dismiss the notification or it will constantly say I have unread messages even though they have been read.

**Comment by RuffWizard** [comment]
This happens on Moto G4 Plus Android 6.0.1

**Comment by klinker24** [comment]
I have already made changes for this for 1.14.0. it is currently in beta testing.
