### ISSUE TITLE
Add delete to notification actions 

### ISSUE THREAD

**Issue by pSatishC** [klinker-apps/messenger-issues#239]
### Delete action in Notification panel saves taps

**Android device:** Coolpad, CP8298_I00 running Android 5.1
**Pulse App version:** 1.14.0.898

Today, we see 'Reply', 'Call' and 'Read' actions on a text notification. It would be great to see a 'Delete' action too. For me personally, the 'Read' is not useful. I would rather have Delete there. There are many texts that are temporary in nature like a One Time Password to login to bank website or the second-factor authentication code for Google account login. These messages are relevant only for a few minutes and more often than not, the code sent is in the first line and can be read within the Notification area itself.

![notifs-actions](https://cloud.githubusercontent.com/assets/20694372/22142039/beecefbe-df1a-11e6-9152-6801ea97d5fa.png)

**Possible solution:**
1. Add **Delete** or a setting to toggle between Read and Delete
2. For the above use-case, I can read the code when the notification shows up, enter the code wherever I need to and Delete the message right from the notification shade.
3. This would save me a couple taps (tap to open Pulse, select the message and delete). The newer 'Swipe to delete' got these redundant taps down but still they are one too many.

**Comment by klinker24** [comment]
I don't know if this is something I want to add. I don't want to add settings like this into the app, but there is no other way to make a feature like this. 

I will leave it open, but right now, I cannot say whether it will happen or not. 

I understand the use-case, but that doesn't mean that it will be helpful for everyone and this app is not going to be about tweaking every little thing imaginable. That is just not the focus here

**Comment by pSatishC** [comment]
No problem. Coming from Evolve, I am just spoilt for customization options. The lack of Dual Sim support in Evolve is the only reason I had to look for alternatives.
The focus of this app has been clearly spelt out in the description. I just wanted to log this Feature Request, should it interest other users as well.

**Comment by klinker24** [comment]
Done with this: https://github.com/klinker41/messenger/commit/fe6ec7f329e224fe82709740a3db6619f409cc20

It is flagged off right now.
