### ISSUE TITLE
Easy to swipe away a conversation when opening the drawer

### ISSUE THREAD

**Issue by klinker41** [klinker-apps/messenger-issues#24]
**Device with issue:** Nexus 6P running Android 7.0
**Primary device:** Nexus 6P running Android 7.0
**App version:** 1.0.193

**Information:**

The swipe to delete and swipe to open drawer gestures are currently in the same direction. This could cause issues with trying to open the drawer and accidentally swiping to delete a conversation, which is not good. An easy fix would just be to reverse the direction of the swipe to delete action to go the opposite way.

**Comment by klinker24** [comment]
Implemented with https://github.com/klinker41/messenger/commit/2c48fe0017bfdc3d8ca3a3050e196ca547e168f4 and https://github.com/klinker41/messenger/commit/286768581e991852f26e9f39b5144e55eb9d38e6
