### ISSUE TITLE
Missing contact avatar

### ISSUE THREAD

**Issue by rejhgadellaa** [klinker-apps/messenger-issues#240]
I'm having an issue with one of my contacts. It's missing the 'avatar' icon/picture in the conversation list.

![nocontactpicture](https://cloud.githubusercontent.com/assets/4703109/22153226/bb6487ec-df26-11e6-9ec6-cc466cb69982.jpg)

The contact doesn't have a picture in my (google) contacts (it's just a color with the first letter of the name) but since this isn't a problem for other contacts (they show the color+letter) I'm not sure what's causing this?

**Comment by klinker24** [comment]
Is this a recent change, or what is the history here? 

To refresh the conversations icon, you should just be able to open that conversation. The next time the list is refreshed, it will change the picture. You could refresh the list by swiping the app out of recents and reopening it, or just hitting the "done" checkmark in the screenshot.

**Comment by klinker24** [comment]
Any updates on this, or my suggestion? Closing as not enough information right now. Please feel free to re-open with some more info, if applicable.

**Comment by rejhgadellaa** [comment]
Oh my bad somehow I've missed the email notifs about this issue's updates. Anyway. I'm on mobile right now so going into it deeply is a bit of a pain. Ill keep it short and come back to it tomorrow (european time).

I found the issue with more contacts. I think they're all contacts I removed the picture from in google contacts a while back, before I started using pulse. So issue probably g contacts related or even caused.

Clearing the app from recents doesn't solve it. Haven't tried clearing cache but since it's probably is a problem that occured since before me starting to use pulse i'd rather not try that (and probbaly lose all my messages?)

**Comment by klinker24** [comment]
Clearing the cache won't help, but it doesn't delete any messages. Messages are stored inside a database, not the apps cache. Cache would be images.

**Comment by rejhgadellaa** [comment]
I meant [clear] app data. That would clear the database, too, right?

Anyway, I did some further checking to see if it was related to Google Contacts issues. I haven't been able to find a real pattern yet. 

Like I said earlier, I thought it might've been caused by me removing contact images but now I noticed a few contacts that do have images set (the gmail/google avatar they set themselves, the one that also shows up in hangouts, g+, etc) that don't show up in Pulse.

There probably is no way to force Pulse to try and re-sync the contacts, is there?

In the meantime, I'll try installing it on one of my other devices and see how that goes. At least then I can rule out some of the possible causes. I hope.

**Comment by rejhgadellaa** [comment]
Riiight. After checking on my old device (and not having the issue there), I cleared app data, that did the trick. I remembered having some problems with google contacts sync a while back. Not sure if that was the case when I started using Pulse but it could be. Good thing is I didn't lose my messages so that's nice :D

**Comment by rejhgadellaa** [comment]
Anyway, thanks for the support :)
