### ISSUE TITLE
Have Chrome App's icon "jump" in macOS dock for new messages

### ISSUE THREAD

**Issue by bkromhout** [klinker-apps/messenger-issues#243]
### Have Chrome App's icon "jump" in macOS dock for new messages

**Applicable Device:** Any Mac (OS X/macOS) running the Chrome App

I think this is pretty self-explanatory, but just in case it isn't... if you've ever used the Hangouts Chrome App on a Mac, you'll know that its dock icon will "jump" if a new message comes in and you don't have the Hangouts window focused already. It'd be great if the Pulse Chrome App could exhibit this behavior as well.

It has occurred to me that the Hangouts Chrome App might, since it's made by Google, might be using some undocumented Chrome APIs to make this functionality happen. 
If that's the case, then I could understand not wanting to implement this feature into the Pulse Chrome App. (In _that_ case, then perhaps this request could be left open for the future, when the Chrome App is replaced by an Electron-driven app?)

**Comment by klinker24** [comment]
This will probably come almost for free, when Electron is used, but I am not finding any way to do it with the chrome apps, unfortunately. If you find something, feel free to reopen and I can try to implement it.
