### ISSUE TITLE
Missing contact names

### ISSUE THREAD

**Issue by simon65** [klinker-apps/messenger-issues#246]
### Missing contact names in android app and Desktop Chrome extension
**Device with issue:** Asus laptop running Linux Mint 17.3 64 & Kyocera Duraforce running 5.1.1
**Primary device:**  Kyocera Duraforce running 5.1.1
**App version:** 1.14.1.924
**Steps to reproduce:**

1. Conversation list just show an avatar with the phone number
2. In the compose view, you just see the phone number on the contact
3. A few contact show with names

**Additional information:**

![screenshot_2017-01-25-15-43-20](https://cloud.githubusercontent.com/assets/25354251/22309450/4b6f2248-e319-11e6-8662-faade9ee8136.png)

**Comment by klinker24** [comment]
Very interesting that pictures work but not names, they should be queried together. Thanks for the report.

**Comment by simon65** [comment]
And that 3 of the 118 contacts in the conversation list have their names listed instead of phone numbers.

**Comment by klinker24** [comment]
I have made changes for this, for the next update. Going to close this out, when you get the update, you will probably have to clear the app data to see any changes. Please do so, and if it still isn't working, come back here and re-open.

**Comment by simon65** [comment]
Just update to 1.14.1.930, did a force close, erase data. Then restart Pulse, but no change, still have the 3 same contacts with name and all the others only show the phone number.... These 3 contacts mystify me....

**Comment by klinker24** [comment]
It is android that is not returning any results for these contacts then, and I have no idea why, unfortunately.

**Comment by simon65** [comment]
Contacts that are local on my phone if I understand?

**Comment by klinker24** [comment]
Yes

**Comment by simon65** [comment]
I have just tried something : I changed a few settings in the contact app,
force stop again and clear datta of Pulse, clear the drawer menu then
restart Pulse.

On restart after loading the messages, no conversations show name. After
enabling view on any devices, the same 3 contacts show names...
