### ISSUE TITLE
Notification: duplicate alerts

### ISSUE THREAD

**Issue by ram130** [klinker-apps/messenger-issues#248]
I've notified when you have a unread message from a previous thread, this can be more than one thread, you get duplicate notifications alert when you get a new message from a different contact. 

Example: you get messages from 4 people today. Let's say you're ignoring one or two of those persons and left their threads unread. But you check everyone else messages. When one of those other persons send a new message. Notifications comes up again for everything that's unread. So you're alerted for those two unread messages again and the new message.

This is very noticeable on my **Fitbit Charge HR 2** and only happens with Pulse. I also seen it from the Pulse app itself. 

_New info:_

I've tested it on Hangouts, FB Messenger, Messenger, Textra and Mysms. I've only noticed a similar behavior with Mysms. Every other apps only notify for latest message received.  No new Pulse updates have improved this. 

Lastly, I notice lately when I get a message while unlocked and browsing my device, when I get a new message  I see notifications pop up for an old unread message thread first then the new one. It happens fairly fast and not all the time. I've tried capturing it on camera but failed. As for my fitbit, I can capture that on camera if you want.  

Pulse is sending the alert of all unread messages when a new unread message comes in.

Issue is annoying as it alerts me too many times for one new message than just one time. This causes extra battery drain on my Fitbit.

**Device**: Nexus 6P, Fitbit HR 2
**App version:** 1.14.1.930
**Android:** 7.1.1

**Steps to reproduce::** Leave multiple messages unread, monitor logs when a new messages comes. Put device to sleep, few mins later, unlock, when a new text comes in, you'll see notification for the old unread message first then new one.

**Comment by klinker24** [comment]
Sorry, I am having a hard time understanding the issue here. Notifications are grouped in Pulse, so yes, you will see all the other conversations as well as the new one. I don't really get it. I don't control the ordering of the messages in the notification panel, if that is what you are talking about.

**Comment by ram130** [comment]
No not the ordering, it`s the app refreshing the old unread messages to notify you again.. Let me try a simple way to explain it: 

You have 4 people texting you...

Msg 1, 
Msg 2. 
Msg 3. 
Msg 4. 

All unread. You only read Msg 1 and Msg 3 and replied to both.

 Msg 1 replies to you. The app notifies you of Msg 4, Msg 3, Msg 2, Msg 1, again. Msg 3 contact replies. The app notifies you have all messages again, Msg 4, Msg 3, Msg 1, Msg 3. Instead of only notifying you of  Msg 3.

**Comment by klinker24** [comment]
I have made some notification related changes for the next version. If I am understanding you correctly, this might help. Feel free to follow up again, when you get 1.15 and let me know. I can reopen this if it isn't changed.
