### ISSUE TITLE
Scheduled messages fail to send

### ISSUE THREAD

**Issue by ram130** [klinker-apps/messenger-issues#249]
It seems when you schedule a message from the tablet and put both devices (phone and tablet) to sleep, scheduled messages fail to send. 

These pics show it scheduled and time has past but messages were never sent.
![image](https://cloud.githubusercontent.com/assets/20274410/22401089/5d0ef1c6-e595-11e6-94f3-49289039c5ee.png)
![image](https://cloud.githubusercontent.com/assets/20274410/22401095/80d9dc1a-e595-11e6-8bbc-7641459b186e.png)

**Device**: Nexus 6P, Mediapad M3
**App version:** 1.14.1.930
**Android:** 7.1.1

**Steps to reproduce::** Schedule a message from a sync device 6hrs ahead. Put devices to sleep. After the time is past, see if it's sent.

**Comment by klinker24** [comment]
I have been unable to replicate any issues, however, I did make some changes to the background service, and scheduling it. If it was missing something before, it shouldn't miss them now.

Changes with this commit: https://github.com/klinker41/messenger/commit/470aa06892ddf56b95481d41f943be77c8014147
