### ISSUE TITLE
Blank text convos in Pulse when you lock your device

### ISSUE THREAD

**Issue by ram130** [klinker-apps/messenger-issues#250]
If you lock your device while on a text conversation. The app will be blank when you unlock until you hit back, there is no way to resume the convo until you back out. 

![image](https://cloud.githubusercontent.com/assets/20274410/22401113/f49a4bbc-e595-11e6-8d37-a38ad5fcbb89.png)

This seems to happen after a few minutes after your device is locked. You either have to FC the app or hit back until you back out of the app, then reopen and go back to the convo. 

![image](https://cloud.githubusercontent.com/assets/20274410/22401118/2846460a-e596-11e6-8d71-910c682b3766.png)

**Device**: Nexus 6P
**App version:** 1.14.1.930
**Android:** 7.1.1

**Steps to reproduce::** Put device in stand by while having a conversation open. Wait a few minutes and unlock.

**Comment by klinker24** [comment]
I have never seen this happen, nor have I heard from anyone else about this.. If you get some better reproduction steps, let me know.

**Comment by ram130** [comment]
Have you tried turning you device while on a text message then waking it up? I`ve been able to reproduce this on all my devices easily.

**Comment by klinker24** [comment]
Yes, of course.. that is something that I am sure everyone has done. Pretty common for a communication app and haven't heard of any issues in the 6 months the app has been out..

**Comment by ram130** [comment]
Understood, I never seen the issue on any other messaging app. Any thoughts on what`s causing it? Maybe doze closing the convo view?

**Comment by deibeljc** [comment]
I also have this issue. I haven't tried reproducing it. Will report back when I do

**Comment by ram130** [comment]
This seems improved in the latest update but it still happens.  It's harder to reproduce.

**Comment by ram130** [comment]
Thids just happened to me. Is there no logs you can see?

**Comment by ram130** [comment]
this happened again. I think I found reliable away to reproduce..

**Comment by ram130** [comment]
Updating with steps soon..need to test again

**Comment by klinker24** [comment]
I made some changes that will probably affect this issue. They have not been released yet, I will probably start rolling them out to some users, in the next few days. I will post here if I do.

**Comment by klinker24** [comment]
This is fixed with the latest release.
