### ISSUE TITLE
Messages stuck "Sending..."

### ISSUE THREAD

**Issue by ram130** [klinker-apps/messenger-issues#251]
More often than not, I've seen messages get 
stuck in "Sending." and never updating.  Most of these messages are sent as I get a reply from the recipient. Sometimes these fail to send but you never really know as the state fails to update and says "sending." When this happens, it happens to all message threads if I reply to anyone.  Even 8hours later it doesn't update but the issue goes away for new messages.

Today::
Decided to send a test msg to my other number, as you can see picture is stuck in a `Sending` state while other messages updated fine:

![image](https://cloud.githubusercontent.com/assets/20274410/22401920/ccfcec36-e5b3-11e6-9aa8-8d4a6736ef8a.png)

As you can see the receipt already got the picture:

![image](https://cloud.githubusercontent.com/assets/20274410/22401921/df1acb4a-e5b3-11e6-9f40-2bcfc48b89fa.png)

And this is from a few days. notice the time stamp of the message vs the current time the screenshot was taken:

![image](https://cloud.githubusercontent.com/assets/20274410/22401922/f289f9bc-e5b3-11e6-8eb1-ed6a854e5b8f.png)

**Device**: Nexus 6P, Mediapad M3
**App version:** 1.14.1.930
**Android:** 7.1.1

**Steps to reproduce::** it happens randomly, I'm usually seeing the issue when replying to someone from my tablet or after waking my device from doze. Again it's random but happens often.

**Comment by klinker24** [comment]
Can you follow the template in the readme for future reports? I would like to know device information, etc.

**Comment by ram130** [comment]
Gonna update all the posts I made with info shortly

**Comment by ram130** [comment]
I'm not able to "label" my posts properly. not sure why, might be permissions. Either I updated all posts.

**Comment by klinker24** [comment]
Only the owner can label issues

**Comment by ram130** [comment]
_pics added.._

**Comment by ram130** [comment]
This just happened to me.  And frankly it's happening right now.  Even though the receipt gets the message I sent. The app still says sending. And it does it for every message after.

**Comment by klinker24** [comment]
I made changes tonight.

**Comment by ram130** [comment]
Thanks. I was seeing it on the regular phone app too. Still says sending but the other messages updated. I'll look out for the update!

**Comment by klinker24** [comment]
I doubt anything is going to change on the phone, sorry, I rely completely on the carrier to provide that status, none of my infrastructure.

**Comment by ram130** [comment]
No worries, I just found it odd with this app.

**Comment by mlcsdk** [comment]
Hi klinker24. I am new to Pulse and expirience this issue as well. Was it solved? If so what do I need to do.

![image](https://user-images.githubusercontent.com/29433120/27135800-d1d3dd74-5119-11e7-92b7-ab34fa93d499.png)
