### ISSUE TITLE
"Sending..." Doesn't disappear.

### ISSUE THREAD

**Issue by anon0429** [klinker-apps/messenger-issues#253]
> When sending multiple messages from tablet or non-primary device the "Sending..." footnote for the earlier messages doesn't disappear, even though it did send.
![img_20170129_234444](https://cloud.githubusercontent.com/assets/15791763/22414475/f82178d6-e67c-11e6-9dbf-1ba2b924aebd.jpg)

**Comment by klinker24** [comment]
Duplicate: https://github.com/klinker-apps/messenger-issues/issues/251
