### ISSUE TITLE
Pulse MMS not notifying on Pebble

### ISSUE THREAD

**Issue by wizard7926** [klinker-apps/messenger-issues#258]
No clue if this is Pulse or Pebble related, but MMS used to notify my Pebble via Textra. Not sure what's going on, my Pebble should pick up all notifications I would think. Thanks.

**Comment by klinker24** [comment]
Pulse doesn't, and really shouldn't, do anything extra for pebble..

**Comment by wizard7926** [comment]
Oh, I know, Pulse works on the system level - it's just strange. Group texts and single-user picture messages don't seem to pass the notification on to Pebble. I'm pretty familiar with Android and notification permissions, etc, but this is perplexing me.

**Comment by wizard7926** [comment]
Looks like this was worked around by disabling the stock SMS handling in the Pebble app. Very strange, but thanks for humoring me!
