### ISSUE TITLE
iOS Emojis

### ISSUE THREAD

**Issue by fdabek1** [klinker-apps/messenger-issues#260]
Would it be possible to add an emoji section to the attach section of the reply/new message screen?  I am currently using Textra which provides the option to switch between Android/iOS emojis.  Since there are so many people on iOS I like to stick to the iOS emojis, so it would be possible to add this functionality into the app?  Sadly, it's the one thing keeping me from switching. :\

**Comment by klinker41** [comment]
We don't have plans on switching how emojis are handled in the app, they keyboard does a good job of handling this already.

You're aware that the emojis are the same across platforms, they just get displayed differently, correct? You can use any Android emoji and it will show up on an iOS device without issue.
