### ISSUE TITLE
Double SIM 

### ISSUE THREAD

**Issue by CobKurtain** [klinker-apps/messenger-issues#261]
Hi !
Thank you for this app, It's the best :)

The only thing missing for me is double SIM support. I need this for my job and It's the only reason for me that make me use another app 

Thanks again !

**Comment by klinker24** [comment]
What phone do you have? Pulse has dual SIM support for any devices that natively support it (Android 5.1+).

**Comment by CobKurtain** [comment]
Oh... 
OnePlus 3

**Comment by klinker24** [comment]
Others have said that if they go into the system settings and rename (?) the SIM cards and restart the phone, they show up. You aren't the first one to have issues with that device unfortunately. 

I am not sure why they changed the way they handle dual SIM support and why it is different from stock android.

**Comment by CobKurtain** [comment]
It's working, thank you 😀
I can use your fantastic app now :)

Thanks for help and how fast you reply !
