### ISSUE TITLE
sent timestamp by the sender

### ISSUE THREAD

**Issue by ArmaninyowPH** [klinker-apps/messenger-issues#264]
Hello dev! Please put an option to show time sent by the sender instead of the time received by me. Because everytime i turn off the airplane mode, i receive messages and it says that i receive them at that time. Thanks! Sorry for my english tho, hope you get it.﻿

**Comment by lahceneamine** [comment]
@ArmaninyowPH :
He is aware of that, but that not one of his priorities for now.
We discussed it [here ](https://github.com/klinker-apps/messenger-issues/issues/146):
