### ISSUE TITLE
Messages read status not syncing 

### ISSUE THREAD

**Issue by ram130** [klinker-apps/messenger-issues#265]
Read status is not being syncing between devices. If I read a message on one device, and use another device, the same messages remains unread. 

Can add pics if needed..

Device: Nexus 6P, MediaPad
App version: 2.0.0.993
Android: 7.1.1

Steps to reproduce:: Don't read the last three messages you got, or just leave some messages unread to test. Check on both devices. Then read a message, or all of them on one of the devices. The other device never updates the "read." state. Hours later, still the same.

**Comment by klinker24** [comment]
The message will be marked as read on other devices when you reply, or when you manually swipe the notification away and the list gets refreshed. This is currently working how I have designed it. I may look to improve or change this functionality it in the future, but for now, this is working as designed.

**Comment by ram130** [comment]
Understood. Thanks. It just gets tiring after a while to keep reading each one again.
