### ISSUE TITLE
New contacts take long to update

### ISSUE THREAD

**Issue by ram130** [klinker-apps/messenger-issues#266]
When adding a new contact. The app does not recognize the contact until after closing and reopening the app. 

As you can see in this group text where I've added Kathy a few minutes a go but still hasn't updated. 
![image](https://cloud.githubusercontent.com/assets/20274410/23050661/c7f25356-f491-11e6-9b31-c389599813c7.png)
![image](https://cloud.githubusercontent.com/assets/20274410/23050667/cd6d2842-f491-11e6-859b-27b496608e7d.png)

Device: Nexus 6P
App version: 2.0.0.993
Android: 7.1.1

Steps to reproduce: Have a new contact or number text you, add them as a contact with a name. Then open app. No update. Force close app, reopen it. It should now recognize the contact.

**Comment by klinker24** [comment]
The conversation title is updated whenever you open the conversation.

It will refresh itself whenever you refresh the list, for example, when you hit the done button on that section. This is working as expected. It will not refresh automatically, there are a few things preventing that, sorry.

**Comment by ram130** [comment]
Got it. Thanks.
