### ISSUE TITLE
Notification still alert when conversation is muted

### ISSUE THREAD

**Issue by abass** [klinker-apps/messenger-issues#267]
I have a group conversation muted and yet my phone keeps notifying me each time a message is received. It seems to happen when I have an "unread" message for a different conversation. From there it completely ignores the "mute" rule applied. It even drops down the message notification preview each time as well but shows the same unread message for the other conversation.

This has been happening for a while now, many versions and very frustrating.

**Comment by klinker24** [comment]
Yes I suppose it would. You should have said something sooner for this, will fix it, thanks.

**Comment by abass** [comment]
Thanks for being so responsive! I normally do reach out on these things but I wanted to be certain that it was a recurring bug first as to not waste your time or mine.

Thanks so much!

**Comment by klinker24** [comment]
Should be done with: https://github.com/klinker41/messenger/commit/dff4b7b0e193dbfa2f64bcdb795aa7e38e879453

@abass please follow up after the next update and confirm that it is working for you. Thanks again for the report.

**Comment by abass** [comment]
This is still happening. Have an unread message (sitting in the notification bar), and a silenced group chat gets a new message, my phone goes off like I got a new text. Even worse, I have a special tone set for the person whose message I have unread and it plays that tone each time a new message comes in from the silenced group.

Super confusing. This has been happening for a while now, was tough to find this issue to re-open it because I didn't remember if it was via a feedback email or where.

Please let me know if I can help test this further, it has been super frustrating :/

**Comment by klinker24** [comment]
Well I did ask you to follow up, would have looked at it again, much sooner, if you had. Sorry about the confusion

I will check it out again today, at some point. Thank you for the report

**Comment by abass** [comment]
Yep, sorry about that, think it was fixed though because I don't think it happened so I didn't have anything to report. Not sure if it was because it was fixed or if I just didn't encounter it in the meantime. I just started using my SMS more the past couple weeks so it stood out again.

I think I may have noticed last night too that it's not just for muted conversations triggering it, e.g. if you have an unread text with someone who you have a different tone, and receive a text, it plays that person's tone again instead of the normal text noise.

Thanks for being awesome about this!

**Comment by klinker24** [comment]
I have made changes with this commit: https://github.com/klinker41/messenger/commit/a1335379fc03c9e8323724433c7b8918968f1ab7

Please follow up, after the next update, to let me know how it goes. Thanks

**Comment by abass** [comment]
@klinker24 - will do! Thanks buddy!

**Comment by abass** [comment]
@klinker24 - Hey man, just tested it and it seems to no longer trigger when the other conversation is muted. Thanks for fixing it!

One other thing, not sure if it's even possible (might be a limitation) but if you have an unread text with someone who you have a different tone (Person A), and receive a text from someone else (Person B) before you read Person A's text, it plays person A's tone tone again instead of the normal text tone that is assigned to that person. (Sorry if that's confusing, tough to explain).

Appreciate it!
