### ISSUE TITLE
Add option to hide sms content in Chrome notifications

### ISSUE THREAD

**Issue by stephentward** [klinker-apps/messenger-issues#268]
I looked through the settings both on the chrome extension and on the phone app but couldn't find an option to hide text content in notifications. This would be particularly useful in the Chrome extension but would nice to have as an option in the phone app as well.

Thanks!

**Comment by klinker24** [comment]
If you set the "private notification" toggle within a conversation's settings, notifications will stop showing content. This is applied to the chrome extension as well.

**Comment by stephentward** [comment]
I would have to do these for each individual conversation? There is no way
to set this throughout all conversations?

**Comment by klinker24** [comment]
No, sorry, there won't be a global option for this, since Android pretty much has this ability, natively, with Android 6.0+.

**Comment by klinker24** [comment]
https://www.howtogeek.com/253076/how-to-hide-sensitive-notifications-on-your-android-lock-screen/

**Comment by stephentward** [comment]
I see. Yeah, I'm more concerned about hiding notification content in
notifications I get on my PC. Sometimes I'll have someone looking over my
shoulder at work and I'd prefer that they didn't read my texts. It's good
to know that I can do it, even if it will be a bit tedious. Thanks for
sending the link and I appreciate your response.
