### ISSUE TITLE
App not refreshing data on remix os 

### ISSUE THREAD

**Issue by mojopong** [klinker-apps/messenger-issues#269]
I have the app running on my remix os box and its not syncing new messages it works perfectly via the browser but the app itself keeps freezing up and not refreshing if not used for a period of time. Even after its open for a while it still doesnt sync all the messages in.

Thanks,

**Comment by klinker24** [comment]
Is that box always on? If not, or it goes to sleep, the app works off of push notifications. So when it does turn back on, it would receive a ton of notifications at once and probably overwhelm it for awhile yes.

I recommend just going to the web on the device instead, it sounds like it doesn't fit great into the use-case for the Android app.

**Comment by mojopong** [comment]
Ok thanks ill just use the web app then. the device does every so often get powered off but most of the time is turned on. Thanks for the quick response.
