### ISSUE TITLE
Add option to sync data only on Wi-Fi

### ISSUE THREAD

**Issue by lunim** [klinker-apps/messenger-issues#270]
**Request**
Add an option to only sync data (at least MMS) when on Wi-Fi.  This is to prevent use of cellular data.  Receiving a large number of MMS messages could result in high data usage.

**Comment by klinker24** [comment]
Sorry, I don't see this happening. To have a messaging app, real time, it requires always being connected. MMS are never more than a megabyte (most will only be 200-500 KB), so even if you get a few of them, they won't take that much data.
