### ISSUE TITLE
Contact color does not persist if conversation is deleted

### ISSUE THREAD

**Issue by lunim** [klinker-apps/messenger-issues#271]
**Device with issue:** Google Pixel XL running Android 7.1.1
**App version:** 2.0.1.1007
**Steps to reproduce:**

1. Receive a message from a contact
2. Set contact/conversation color
3. Delete the conversation
4. Receive a new message from same contact
5. Color is different from what was set previously

**Comment by klinker24** [comment]
This is working as designed. Colors run off of conversations, not contacts, so deleting that conversation will clear the color selection as well.

You may get some contacts that do persist their colors. They will, if they have an contact image with a unique color that can be pulled out.
