### ISSUE TITLE
Long time to sync new contacts to Pulse 

### ISSUE THREAD

**Issue by ram130** [klinker-apps/messenger-issues#273]
I'm seeing the app take a long time to update contacts I've added, even after closing and refreshing the app. 

![image](https://cloud.githubusercontent.com/assets/20274410/23107486/fec60f58-f6cb-11e6-97b2-cdce001e96ca.png)
![image](https://cloud.githubusercontent.com/assets/20274410/23107489/0314e7f0-f6cc-11e6-833e-f2c9db81d2e1.png)

Device: Nexus 6P
App version: 2.0.1.1007
Android: 7.1.1

Steps to reproduce:: Get a a text from a new number, or text a new number, add them to your contacts.  Wait for a few mins, Pulse never updates.

**Comment by klinker24** [comment]
Pulse will attempt to update the title whenever you open up the conversation. If it can find the contact, then it will show the new title when the list is updated.

**Comment by klinker24** [comment]
Going to close this, after my explanation, I guess.
