### ISSUE TITLE
Repeat notification when first opening Chrome

### ISSUE THREAD

**Issue by lunim** [klinker-apps/messenger-issues#274]
Device with issue: Chrome extension (not app)
**Primary device:** Google Pixel XL running Android 7.1.1
App version: 2.0.1.1007
Steps to reproduce:

1. Have the desktop Chrome browser closed
2. Receive a message from a contact
3. Read or reply to the message.
4. Open desktop Chrome browser
5. Pulse will display a notification of the last received message, even if it has been read previously in the app.

**Comment by klinker24** [comment]
If you can point me to an API to stop this, that would be great. I am telling chrome to cancel that notification, but it doesn't always work, for whatever reason. No clue what to say about this, to be honest.

**Comment by klinker24** [comment]
I made changes so that it should only show notifications for conversations that are marked as unread. For now, this is the best I am able to do.
