### ISSUE TITLE
Schedule a message inline

### ISSUE THREAD

**Issue by Mondschuhe** [klinker-apps/messenger-issues#275]
Can you implement a way to schedule a message directly from the new message / reply window? Going into a sub menu to schedule isn't very intuitive or user friendly, and the interface to select recipients and type the new message is drastically different from the rest of the app. 

Something closer to how Textra does scheduled messages.

**Comment by klinker24** [comment]
Within any conversation, you can hit the three dot overflow and click "schedule a message". I think this is as far as I want to go with this, I would prefer to keep scheduled messages separate from the other messages.

**Comment by Mondschuhe** [comment]
That's my point though. You have to go through several submenus and interface changes. It's obnoxious to the point that I don't use that feature, even though it is a feature I like

**Comment by klinker24** [comment]
It would be several interface changes no matter where you are. Scheduling messages and picking times is completely different from any other section of the app?
