### ISSUE TITLE
Option to persist Chrome extension notifications

### ISSUE THREAD

**Issue by RogerinNYC** [klinker-apps/messenger-issues#277]
**Device with issue:** Chrome App and Extension
**App version:** 1.6.0
**Request:**

I'm not always looking at my PC screen. It would be nice to have an option to have notifications stay on screen until dismissed -- as well as intermediate options, like 60 and 30 seconds. As of now, the pop-up notification on my PC disappears and cannot be found again after about 5 seconds.

**Comment by klinker41** [comment]
`NotificationOptions.requiresInteraction` seems appropriate. https://developer.chrome.com/apps/notifications#type-NotificationOptions

**Comment by RogerinNYC** [comment]
Sorry, not a coder or github user -- if I knew how to add it I would be glad to though! One other thought, is that if I manage to click reply before the notification disappears, it opens up your web app (I believe). It would be nice if it, instead, opened whichever platform you're actually using (i.e., PC App or Chrome Extension). Does that make sense? Should I open another issue?

**Comment by klinker41** [comment]
I'm just commenting as a mental note. Platform is closed source so you couldn't make pull requests even if you knew how.

**Comment by gormanlisa1** [comment]
Has anyone asked about flashing notifications on PC with Chrome extension? That would be convenient.

**Comment by klinker24** [comment]
Sorry I don't know what that means...

**Comment by gormanlisa1** [comment]
If the Pulse icon on my taskbar were to flash or change color after a notification goes away to indicate there's a message I haven't read yet.

**Comment by landalezjr** [comment]
I've noticed that notifications now stick around from the Chrome extension much longer now, probably around 25 seconds. Was that intentional? It is definitely much better than before where they seemed to be gone before you knew it. Are you still looking into the ability of custom control of this where we could have them not auto-dismiss unless they are interacted with or the message is read? A counter on the pulse extension icon would be handy as well.

**Comment by klinker24** [comment]
Add the option to persist notifications: https://github.com/klinker41/messenger-chrome/commit/75b630d3621509b40ae62c1d171cf560b2ca736f
Implementation of the option: https://github.com/klinker41/messenger-chrome/commit/8f7123a299cd9780789bf71fe7a9aaba45721515

This will be in the chrome and firefox extensions only, not the chrome app. Right click on the extension and go to "Options", after the next update.
