### ISSUE TITLE
Custom Vibration Pattern for Notifications

### ISSUE THREAD

**Issue by hrprplx** [klinker-apps/messenger-issues#278]
### Would be awesome to be able to set a custom vibrate pattern for notifications

**Primary device:** Pixel XL running Android 7.1.1
**App version:** 2.0.3.1023

**Suggestion/Request:**

Other apps I've used have done either a numerical entry corresponding to milliseconds off, milliseconds on to create a pattern, i.e. 0,500,250,1000 would 0 ms off, vibrate for 500ms, off for 250ms, vibrate for 1000ms.

One other app went further and used a touch interface where you tap "record and a timer starts, and it "records" a vibrate when you tap and hold on a button. The longer/shorter you hold or release, the longer/shorter the vibrate or pause. 

Love the app, really fantastic. Keep up the great work!  Sorry I couldn't find where to add post tags as a feature request.

**Comment by klinker24** [comment]
Sorry, this is something that I don't plan on doing.. there are only so many patterns and I feel like having the default pattern options is plenty for vibrations. They are still significantly different than the vibration patterns of other apps on your phone, so you can know that the notifications come from Pulse, which is really the only use-case I see for custom vibrations. Am I missing something?

**Comment by hrprplx** [comment]
Nope was just a thought. No worries.


--
Andrew Dickman 
andrew.s.dickman@gmail.com 

Sent from my Pixel


On Friday, February 24, 2017 at 5:49 PM Luke Klinker <notifications@github.com> wrote:

Sorry, this is something that I don't plan on doing.. there are only so many patterns and I feel like having the default pattern options is plenty for vibrations. They are still significantly different than the vibration patterns of other apps on your phone, so you can know that the notifications come from Pulse, which is really the only use-case I see for custom vibrations. Am I missing something?

**Comment by DragonMama** [comment]
As I commented on another thread, you are missing that this is an accessibility issue for deaf & hard-of-hearing people. People who can hear can customize every convo to a different sound. This commenter told you how competitors handle custom vibrations but did not express it as a disability need. Maybe if you realize that it is a universal design accessibility issue you will feel more motivated to put this feature in.
