### ISSUE TITLE
Light Mode not working

### ISSUE THREAD

**Issue by bell-steven** [klinker-apps/messenger-issues#28]
**Device with issue:** Nexus 5X running Android 7.0
**Primary device:** Nexus 5X running Android 7.0
**App version:** 1.0.193
**Steps to reproduce:**

1. open app
2. open settings
3. Even if night mode is set to "off" it is still active
**Additional information:**
If you toggle night mode on and then off again, it fixes it  until you open the app again.  This happens everytime I open the app.

**Comment by klinker41** [comment]
This is working as expected, it is not an issue.
