### ISSUE TITLE
Messages aren't syncing from PC to phone, but sync from phone to PC

### ISSUE THREAD

**Issue by wizard7926** [klinker-apps/messenger-issues#280]
Not sure what's going on. Android 7.0, Verizon LG G5 (VS987), latest Pulse build 2.0.3.1023.

Worked earlier today, but noticed in the late morning (3-4 hours ago) that texts I had sent via Pulse for Chrome weren't syncing to the phone app. Tried from a few different computers, and the messages sync across my Pulse account but not to the phone. Cleared cache and rebooted, let it sit in Airplane Mode to see if the signal needed a refresh, but no change yet.

**Comment by klinker41** [comment]
https://plus.google.com/+LukeKlinker/posts/jexeiY1mvJ1

**Comment by klinker24** [comment]
Unfortunately there isn't much we can do here. That link has a link to Amazon's status dashboard to monitor

**Comment by wizard7926** [comment]
Gotcha, didn't even think of that. Thanks dude.
