### ISSUE TITLE
Fails to save media

### ISSUE THREAD

**Issue by wizard7926** [klinker-apps/messenger-issues#282]
**Device with issue:** VS987 on Android 7.1
**App version:** 2.1.0
**Additional information:**

Works for the standard `/Downloads` folder, but when I change it to an SD card folder, it fails.

**Comment by klinker24** [comment]
Probably not able to access that location. Can you get a logcat please?

**Comment by wizard7926** [comment]
I might have to wait until I get home to do so (no SDK at work). 

I tried a reboot, and then setting the SD card folder back as the directory, and it said "Saved to downloads folder!" .. except that it saved it to /Downloads, not the actual directory I had set just moments before.

**Comment by klinker24** [comment]
Any updates on the logcat for this issue?

**Comment by wizard7926** [comment]
What's the most straightforward way to do a logcat without root?

**Comment by klinker24** [comment]
Sounds like you have the SDK, so just open up the "Android" tab in android studio and select "No filters". This will show you everything running through the logs.

**Comment by wizard7926** [comment]
Having some trouble recognizing my phone - hopefully I can get the log to you soon!

**Comment by klinker24** [comment]
Have we had any luck here?

**Comment by klinker24** [comment]
I am going to close this one for lack of info, sorry. Feel free to provide the logcat, and I can re-open
