### ISSUE TITLE
Imported Messages Not Sunk to Other Devices

### ISSUE THREAD

**Issue by tcgoetz** [klinker-apps/messenger-issues#284]
1. signed up on primary device
2. imported messages on primary device
3. signed in on Tablet and Chrome app
4. Table and Chrome app show no messages
5. Tried resync account on tablet, still no messages on tablet

**Comment by tcgoetz** [comment]
Sent a test message from my primary device (phone), it was received, but does not sync to tablet, Chrome app, or website.

**Comment by klinker24** [comment]
It should have imported your messages before you signed up. If you imported them again, then it wouldn't have worked, something is not in the right order.

You can delete your account from your phone, then clear the app data. This will put you through the initial import again. Now sign up for an account and it will put everything from your phone, to the cloud.
