### ISSUE TITLE
Long messages hide conversation content on web

### ISSUE THREAD

**Issue by force1164** [klinker-apps/messenger-issues#285]
**Device with issue:** Web
**Information:**

When writing longer messages on web or via browser extension, the field for it expands and gradually hides the conversation view, making it impossible to re-read last message in order to answer thoroughly.

**Additional Information:**

![2017-03-12 12_04_56-pulse](https://cloud.githubusercontent.com/assets/2920574/23831202/9d2cc186-071c-11e7-8988-ef6869a49efb.png)

**Possible solution:**

The conversation area should scroll so that all content is always visible and the reply text area should have a max height limitation at which a scrollbar appears too.

**Comment by klinker24** [comment]
This is now fixed: https://github.com/klinker41/messenger-web/commit/cad8f7952761875b8eabc102f132e695b4ba8666

It may take little while to propagate out.
