### ISSUE TITLE
Convert long messages to MMS after a selected number of messages

### ISSUE THREAD

**Issue by Pickles911** [klinker-apps/messenger-issues#286]
**Device with issue:** Nexus 6P Running Android 7.1.1
**Primary device:** Nexus 6P running Android 7.1.1
**App version:** 2.1.0.1039
**Feature Request:**

I am requesting a feature to be added that gives an option to convert long SMS messages to MMS after just 1 SMS (160 characters) instead of 3 SMS messages (480 characters).

Project Fi has strict handling of SMS where any text messages above 160 characters are sent broken up and sent as multiple SMS messages instead of converting MMS or coming in as one long message. This  causes those who receive them SMS messages from Project Fi users to come in out of order. 

To overcome this issue other messenger applications (Textra) allow the change for SMS to MMS above 1 SMS message. They have options for great than 1,2 or 3 sms messages.

**Comment by klinker24** [comment]
That actually isn't true about project Fi, I use it myself and have never had that happen...

**Comment by klinker41** [comment]
I have Fi and have never experienced what you describe here.

**Comment by Pickles911** [comment]
Interesting, it happens to some of my messages going out, but mostly going to Verizon users, they seem to complain the most that they come in broken up. Going to try to re-provision the device, clear the data of the application and give it a go again.

**Comment by klinker24** [comment]
I doubt that will change anything. The limit is probably on Verizon's side.

**Comment by Pickles911** [comment]
Ah ok. Well I tried it anyhow, cleared the app data and cache, re-provisioned Fi, no joy, they come in broken up still. 

Up to you guys, I understand if you don't want to implement something like this since it is a feature for a small issue.

**Comment by bkromhout** [comment]
Just wanted to speak up and say that while I also don't believe it's necessarily Fi's fault, I'm also on Fi and have been told by friends across many carriers that my messages come through broken up... So it would be great if this feature was implemented.

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/messenger/commit/d7cefb2b9a506efcae0950c2c4c03080491c2ca2
