### ISSUE TITLE
Tasker SMS' don't show up in Pulse. Every other SMS app shows them just fine.

### ISSUE THREAD

**Issue by coromd** [klinker-apps/messenger-issues#287]
I set a 15 minute auto texter script to pester someone to get something done and I couldn't see just how annoying it was cause it only shows the first message. If they reply then it'll show the first auto text after the reply but it won't show anything else.

**Comment by klinker24** [comment]
In the future, please check out the issue template in the readme.

I do know about this issue, I don't have a good fix. Pulse use a separate database, then writes back to the internal database. It does not find changes on the internal database, if another app inserts something and does not go through pulse.

**Comment by klinker24** [comment]
This issue would fix this bug: https://github.com/klinker-apps/messenger-issues/issues/141

So I am going to close this as a duplicate
