### ISSUE TITLE
Deleting an account does not delete the account

### ISSUE THREAD

**Issue by ddechant** [klinker-apps/messenger-issues#29]
### Deleting an account does not delete the account

**Device with issue:** Samsung Note 4 running Android 6.0.1
**Primary device:** Samsung Note 4 running Android 6.0.1
**App version:** 1.0.193
**Possible Steps to reproduce:**

1. Click on the Delete Account menu item
2. Logout
3. Login with the same credentials
4. Success?

**Additional Information:**
-The menu item states that it deletes the account from the server, yet you can still login using the web app.
-The messages are still stored on the server, or at least the web app says they are.
-Conversations DO appear to get deleted.

**Note: I was trying to fix the duplicate conversation issue I was having by wiping the entire account. Deleting my account should not be taken as a disliking for the app.**

**Comment by klinker41** [comment]
The server is having some timeout issues with removing the account, my guess is that is the issue.

**Comment by ddechant** [comment]
Probably too many messages to delete. I will stop for the night and give it another go tomorrow. Thanks for the quick response.

**Comment by klinker41** [comment]
Sounds good, thanks for the detailed bug report as well!

**Comment by klinker41** [comment]
Made changes to speed up this process drastically, the timeout should no longer occur with the next version.
