### ISSUE TITLE
Only imports the latest 500 messages

### ISSUE THREAD

**Issue by NicoNet** [klinker-apps/messenger-issues#292]
**Device with issue:** Pixel XL Android 7.1.1
**Primary device:** same
**App version:** 2.1.2.1057
**Steps to reproduce:**

1. Have more than 500 SMS messages with a single person.
2. Install Pulse
3. Can only see the newest 500 messages for that person.

**Possible solution:**

This seems like a hard coded value.  Perhaps this can be configured, or unlimited.

**Comment by klinker24** [comment]
Sorry, this is a hard limit right now, and not something that will be able to be changed
