### ISSUE TITLE
Show Chrome app icon on macOS menu bar

### ISSUE THREAD

**Issue by rnhurt** [klinker-apps/messenger-issues#293]
This is an enhancement request for the Chrome App running on macOS.

I would like to suggest adding an icon on the macOS menu bar for the Pulse Messenger Chrome App.  I've installed both the Chrome App and Chrome Extension and I like the App more but it's more difficult to get to.  If there could be a icon in the macOS menu bar (similar to the Hangouts one) it would be much more useful.  Not only could I get to it from places other than Chrome but you could add an "unread message" indicator as well.

**Comment by klinker24** [comment]
You can keep the icon for the chrome extension on the dock. If that is what you are talking about. Not sure why you would want the menu bar over the dock?

**Comment by rnhurt** [comment]
Yes, I have the Chrome extension on my Chrome dock, however I don't always
have Chrome up and visible.  So, for those times when I'm working on
something else (programming, email, etc.) and would like to respond/send a
text, I have to bring Chrome up and click on the Pulse app.  It would be
handy to have the ability to use Pulse from anywhere, not just from inside
Chrome.  :)

Thanx!

Richard Hurt
<http://www.facebook.com/rnhurt>  <http://www.twitter.com/rnhurt>
<http://www.linkedin.com/in/rnhurt>  <http://github.com/rnhurt>

**Comment by klinker24** [comment]
I am actually talking about having the chrome app in the Mac os dock

**Comment by rnhurt** [comment]
Ah, now I understand.  I generally don't have my dock visible as it takes
too much room on the screen for me.  For testing purposes I've pinned the
Pulse app to my dock and it seems to be working fine.  I can even launch it
from Spotlight without much trouble at all.  It might be valuable to add
the option of showing the icon in the dock or the menu bar.  I consider
Pulse a service that should always be running (like Dropbox, or SnappyApp)
so I like it to be unobtrusive yet available.

The only thing that I might be missing is the ability to have notifications
of past messages.  This is something that a menu icon would work well for.

BTW: Thanks for a great app.  Ever since Google announced their Hangouts
"strategy" I've been looking for a good replacement and Pulse seems to be
the best of the lot.


Richard Hurt
<http://www.facebook.com/rnhurt>  <http://www.twitter.com/rnhurt>
<http://www.linkedin.com/in/rnhurt>  <http://github.com/rnhurt>

**Comment by klinker24** [comment]
Thanks for the suggestions, going to close this issue, since the initial problem is fixed by pinning the chrome app. I will consider adding it to the menu bar in the future
