### ISSUE TITLE
Clip board image support

### ISSUE THREAD

**Issue by mattwbennett** [klinker-apps/messenger-issues#295]
**Device with issue:** Chrome v54+ browser
**Primary device:** Pixel XL on Android 7.1.2
**App version:** Pulse Extension 1.8.1
**Steps to reproduce:** copy image to clipboard, paste into sms/mms extension window

1. copy adorable cat picture to clipboard 
2. click sms/mms extension 
3. click on your friends cusins aunt twice removed on your daughter's side.
4. paste adorable cat picture into existing message thread

**Additional information:**

Greenshot(desktop app) is what i use to capture those images to clipboard easily [GreenShot](http://getgreenshot.org/downloads/)

**Possible solution:**
If you would be so kind to as integrate some image clipboard support that would be swell..

Love your stuff!

**Comment by klinker24** [comment]
Do you have any docs for something like this? Admittedly, I have no idea how this works

**Comment by mattwbennett** [comment]
Here is some documentation on it for HTML5.
[Paste from clipboard](https://codepen.io/netsi1964/pen/IoJbg)

**Comment by klinker24** [comment]
Cool, thank you. Will look into this, would be a neat feature

**Comment by mattwbennett** [comment]
Thank you!

**Comment by klinker24** [comment]
Done with this: https://github.com/klinker41/messenger-web/commit/4ba869e045dc64d972e0314e41f1a7805aebf99a

I will do a bit more testing, then roll it out to everyone.
