### ISSUE TITLE
Native apps

### ISSUE THREAD

**Issue by Talor-A** [klinker-apps/messenger-issues#296]
Electron would be a good candidate for integrating the existing web client with desktops. I've got a fair bit of experience with electron and I'd be willing to help develop and maintain it if there's a need for it.

**Comment by klinker41** [comment]
We've discussed this in a few places already, it won't work until firebase supports election or visa versa.

https://github.com/klinker-apps/messenger-issues/issues/272
https://github.com/klinker-apps/messenger-issues/issues/255
https://github.com/klinker-apps/messenger-issues/issues/220

**Comment by Talor-A** [comment]
How does the chrome app receive messages if you're not using websocket? And is any of your code open sourced? This is an awesome protect and I'd be happy to help out

**Comment by Serubin** [comment]
Out of curiosity, what would it take for the websocket api to be moved forward on your todo list?
It seems like a highly sought after feature for folks and would really bring the web app to the next level.

**Comment by klinker24** [comment]
Native apps are now finished: https://github.com/klinker41/messenger-chrome/tree/master/electron-app

I will look to release them later this week, after I test them a bit more myself.
