### ISSUE TITLE
Password sent in plain text for login in chrome extension

### ISSUE THREAD

**Issue by jeffshaver** [klinker-apps/messenger-issues#299]
**Device with issue:** MacBook Pro on MacOS 10.11, running Chrome 56.0.2924.87 (64-bit)
**Primary device:** Pixel XL on Android 7.1.2
**App version:** 1.8.1 of chrome extension, 2.2.3.1105 on phone
**Steps to reproduce:**

1. install chrome extension
2. open chrome extension
3. open menu and go to login
4. type in an email and password
5. open chrome developer tools
6. go to the network tab
7. hit log in in the chrome extension
8. click on the post request in the developer tools
9. see that the password is in plain text

**Additional information:**

Looking through the JS, it seems as though the password will be encrypted once the login works and then it is stored on the user's computer in that format, but the initial login is in plain text.

**Possible solution:**

Run the encryption before sending the post request

**Comment by klinker24** [comment]
It uses bcrypt on the backend: https://github.com/codahale/bcrypt-ruby

Everything is sent over SSL, no one can intercept your password
