### ISSUE TITLE
Preview image to be sent

### ISSUE THREAD

**Issue by Talor-A** [klinker-apps/messenger-issues#300]
**Device with issue:** Acer C720p Chromebook
**Primary device:** Nexus 6P, 7.1.2
**App version:** 2.2.3.1105
**Steps to reproduce:**

1. open a conversation in the chrome extension window
2. select an image from local files
3. confirmation box appears asking if the image should be sent

**Possible solution:**

show the image to be sent inside the confirmation box

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/messenger-web/commit/631cbcb408fe95336247cf69dd71cfbf07a3dddc

![screen shot 2017-11-30 at 1 55 40 pm](https://user-images.githubusercontent.com/4874287/33452058-833bc84c-d5d6-11e7-9050-3ed5585bd91d.png)
