### ISSUE TITLE
Messages not marked as read when app already open on thread

### ISSUE THREAD

**Issue by thepilch** [klinker-apps/messenger-issues#302]
**Device with issue:** Sony Z3C D5803 with android 6.0.1
**App version:** 2.2.3.1105
**Steps to reproduce:**

1. Have pulse open on conversation thread
2. Have phone locked (might happen unlocked too)
3. Receive new text to same thread
4. Click on notification or unlock phone, view message
5. Whilst pulse does sometimes mark as 'read' the alert keeps going off regularly and my car picks up the message as unread too
6. Alert continues until either:
  * "read" is selected on the notification 
  * Or pulse is closed, reopened and the thread is opened
  * Or a different thread is opened and then the original Re-opened
  * Or sometimes I just press the message to view the timestamp and that works, occasionally.

**Comment by klinker24** [comment]
By alert, do you mean that the notification comes in again, even if you have swiped it away? (or it goes away when the thread is opened)

**Comment by thepilch** [comment]
Yes,the notification comes back.

I know it's not read even when pulse marks it as such, because if I reboot my phone then the message is marked as unread again in pulse

---- Luke Klinker wrote ----


By alert, do you mean that the notification comes in again, even if you have swiped it away? (or it goes away when the thread is opened)

**Comment by klinker24** [comment]
Should be fixed with: https://github.com/klinker41/messenger/commit/42cedd28730beddc05823faa1096c9b8758e5319

I will probably put out a new version (2.2.5) in the next few days. Please let me know if you are seeing better results, when that version hits. Thanks!
