### ISSUE TITLE
Drafts not saved with images

### ISSUE THREAD

**Issue by globalbuckeye** [klinker-apps/messenger-issues#303]
**Primary device:** LeEco Le Pro 3, Android 6.0.1
**App version:** 2.2.4.1111
**Steps to reproduce:**

1. Write a new message and attach a picture to it. Don't send yet. 
2. Rotate phone from horizontal to vertical or vice versa.
3. Picture stays attached but written message disappears from the text entry box.

Very reproducible. Not sure how to record my screen, but happy to do so if you want to see how it happens.

**Comment by klinker24** [comment]
I have been trying to figure this out for quite awhile. I think that I finally found the issue. 

Do you have a pulse account? It seems like the phone is sending out the request to delete drafts on the backend, then it creates the new set on the phone, then the phone receives a push notification to delete the drafts, before the app can show the drafts that should be restored.

You can test this theory by simply disabling wifi and mobile data, and rotating the device a bunch. I can confirm that it works just fine for me, now that the phone cannot receive push notifications (no data connection).

Will have to think about how to fix this one. Guess it is a testament to how blazing fast our backend is, at least...

**Comment by globalbuckeye** [comment]
Yes, I have a Pulse account. I bought the lifetime membership. 

With data/wifi enabled I made the error happen. Deleted the draft. Went to airplane mode to disable connectivity. Composed a new draft. Rotated. Written message still disappeared. In my case, the data connection doesn't seem related.

**Comment by klinker24** [comment]
This should be done.

Backend: https://github.com/klinker41/messenger-server/commit/e01bfb105c3f6822b51be5a874fcad2916d0cc99
Android: https://github.com/klinker41/messenger/commit/36ae6c690c2ffd9efe8a914473d68d5ed4f21ef3

**Comment by globalbuckeye** [comment]
I have version 2.4.5.1341 on my phone now.  Not sure if it's the latest version, but the problem still exists for me. If a new version is being pushed out and it hasn't hit me yet, I'll update here.

**Comment by klinker24** [comment]
The changes are in the beta. 2.4.5.1352

**Comment by globalbuckeye** [comment]
Great! Looking forward to updating and testing it out then! Thanks for the responsiveness and support!
