### ISSUE TITLE
`smsto` Intent with no recipient shows an empty chat feed

### ISSUE THREAD

**Issue by laochiv** [klinker-apps/messenger-issues#304]
**Device with issue:** Android Droid Turbo 2 Running Android 7.0
**Primary device:** Android Droid Turbo 2 Running Android 7.0
**App version:** 2.2.4.1111
**Steps to reproduce:**

1. Set Pulse as your default sms app
2. Trigger an intent with the `smsto` scheme with no recipient. Such as 
```java
new Intent(Intent.ACTION_SENDTO, Uri.parse("smsto:"))
                    .putExtra("sms_body", body)
```
Following the instructions [here](https://developer.android.com/guide/components/intents-common.html#Messaging) but dropping the phone number

3. Pulse is opened to an empty feed to no one. With no text pre-populated.

**Possible solution:**

When handling a `smsto:` scheme check if the phone number portion is empty. If it is, show the user the same recipient chooser that is shown in the general `ACTION_SEND` intent handler.

**Comment by klinker24** [comment]
Any reason you are providing an `smsto` intent without the number? Why not just a generic share event instead?

I can fix this, but confused by the use case of this issue

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/messenger/commit/b744a1de9991374f0e4edabe79295fc2dfd779c2

I still think that you should be careful with how you structure that `URI` though, I don't think there should be any guarantee of any apps to handle the blank phone numbers
