### ISSUE TITLE
New messages indicator in web app title

### ISSUE THREAD

**Issue by pierremtb** [klinker-apps/messenger-issues#305]
It would be awesome to update the title of the webapp when new messages come in, like other messaging services do.

Keep up hard work! I suscribed for lifetime because this service is amazing :)

**Comment by klinker24** [comment]
Little confused what you mean by this. The title will go to bold to indicate a new message is in that conversation. The Android app doesn't display the number of new messages in each conversation though, and I don't think that will happen on the web app either

**Comment by pierremtb** [comment]
Sorry, this is indeed not clear. I mean on the webversion, at https://messenger.klinkerapps.com, I'd love the wepage title (in the tabbar for instance) to switch from "Pulse" to "Pulse (*)" or some indicator to say that there is a new message, like most messaging services do.

**Comment by klinker24** [comment]
The conversations are already bolded on the list though, what benefit does this request provide? I have never seen another service that adds to the message title to signify a new message... Email, pushbullet, etc.

**Comment by pierremtb** [comment]
For instance if you have Pulse opened as a tab in your web browser, but you are on another one, working on something else. In this case it would be nice if the Pulse tab title displayed in some way that there is a new message. It is usually achieved by a custom favicon or something like "Pulse (*)"

**Comment by klinker24** [comment]
Oh i see what you are saying. Sure, I should be able to add this pretty easily. I thought you were talking about the title on the app bar

**Comment by pierremtb** [comment]
I was waiting to get one hehe, I meant this kind of dynamic title:
![notif](https://cloud.githubusercontent.com/assets/10795683/25192998/b530f98c-2535-11e7-974b-0397046cac2b.PNG)

**Comment by klinker24** [comment]
I am not going to put the number, but I can put an indicator

**Comment by pierremtb** [comment]
Definitely, a favicon badge or a "(*)" is enough IMO

**Comment by klinker24** [comment]
Ok done with: https://github.com/klinker41/messenger-web/commit/9a6a559954d92bbb89ebe7786647900c175f002a

I will push it out later.

**Comment by pierremtb** [comment]
Thank you very much :)

**Comment by pierremtb** [comment]
It works perfectly, thanks again!
