### ISSUE TITLE
Support Samsung Watches with Tizen OS

### ISSUE THREAD

**Issue by Kaan73** [klinker-apps/messenger-issues#307]
**Device with issue:** Samsung Gear S3
**Primary device:** Samsung Galaxy S7
**App version:** 2.2.4.1125

We have an Android Wear app. In the future, there could be a Tizen one as well.

**Comment by klinker24** [comment]
While we do have the infrastructure to make this work, I don't have the time, yet, to plug into a brand new platform. 

Android Wear was easy, it used all the same code that the phone/tablet app uses. This is a completely different system, unfortunately. There would be nothing to start from, it would be a completely empty project

**Comment by Kaan73** [comment]
No problem, it didn't stop me from buying the lifetime subscription but it would be nice to have if there is enough demand.

**Comment by jblaker** [comment]
This would definitely be killer. The main reason I use the Samsung Messenger app is because I can send/receive from my Gear S3.

**Comment by Kaan73** [comment]
Pulse began working on my Gear S3 several months ago, so I'm quite pleased.  There isn't an official Gear app for Pulse, but SMS messages received via Pulse when it is my default messaging app now appear on the watch and I can reply to them from the watch. It works great.

**Comment by kevonha** [comment]
It does allow you do reply from quick reply, but to open a new sms you have to use the samsung sms app on the watch. Which prompts you every time to make it the default app which is quite annoying.

**Comment by eljeffe58** [comment]
Deal breaker topic for me. Need GearS3 functionality.

**Comment by klinker24** [comment]
Thanks for the feedback. 

Sorry, this isn't a top priority for me. It is a massive undertaking go make a new platform from complete scratch, and this one would only help a few hundred people, and that is probably a high estimate

It will come in the future, but it won't be the near future.

**Comment by gigneil** [comment]
Just to reiterate demand for the product.  Should it become needed I'd be happy to provide a watch for development purposes.  Android Wear is struggling. 

The ability to work either tethered to the phone or independently when using LTE is needed but I'm assuming same also for the Wear platform.

**Comment by mostlychris** [comment]
The messages appear on my watch but don't alert (no vibe or sound). Wonder if that is a known issue.

**Comment by klinker24** [comment]
@mostlychris since I don't have any Galaxy Gear integration, I doubt the issue is on my end. I just post a notification and your watch does what it will with that.

**Comment by mostlychris** [comment]
Thanks. This is an issue with a number of apps apparently. Ring is another example. The alerts show on the watch, but they don't do any kind of sound or vibe. It's confounding that they will get to the watch, but the watch somehow ignores them. I'll continue to dig into this on the watch side.

**Comment by z0oinks** [comment]
@mostlychris Post here (and tag me please) if you find an answer to this

**Comment by z0oinks** [comment]
I wanna throw my hat in for a Tizen app too. That and a UWP version for Windows/Xbox would be a dream

**Comment by eTron** [comment]
Love the android and Mac apps (lifetime subscriber). It works on the gear fit pro 2 to receive and reply but it does not use the editable list of quick replies from the gear app on the phone. Only 4 or 5 default watch ones. I hate to mention a competitor but somehow they enabled the use of the list in the gear app on the phone. Not a full blown app but having just that would be a huge help. Adds about another 30 replies roughly and makes using the device for messaging quite a bit more tolerable. Another vote for full support or at least access to the quick replies list from the gear app. Thank you for all your hard work and help!

**Comment by mostlychris** [comment]
@z0oinks After a software update, and apologies that I can't remember when, all my app notifications started working. I get audible/vibe notifications for all but weather underground now. Even that one shows up as a notification on my watch, but it doesn't make any sound or vibe. I can reply to texts as well. Seems it is working OK for me. I can't initiate a text if I don't have a notification, but for now that's fine.

**Comment by Crimsonzeles** [comment]
I found what was causing my issue, Pulse is working just fine I had another app that was interfering with the Gears ability to receive the notifications from my phone.

**Comment by klinker24** [comment]
This is finished. Over the coming weeks, I will open source it and work through the process of getting it up on the store for the galaxy watches.

https://github.com/klinker-apps/messenger-tizen
