### ISSUE TITLE
No notifications on new SMS 

### ISSUE THREAD

**Issue by aleslukek** [klinker-apps/messenger-issues#308]
**Device with issue:** <insert your device: "MacBook Pro on MacOS 10.12, running Chrome v54">
**Primary device:** <insert your phone: "Pixel XL on Android 7.1.2">
**App version:** <insert version: in "My Account" on the phone>
**Steps to reproduce:**

1. step 1
2. step 2
3. step 3

`... more steps`

**Additional information:**

Do you want to provide any other information? Device configuration, unique cases, anything that you think may be relevant.

**Possible solution:**

Do you have an idea of how to solve it? If not, that's fine, you can delete this section.

**Comment by klinker24** [comment]
Did you get it working then?
