### ISSUE TITLE
No notifications on new sms

### ISSUE THREAD

**Issue by aleslukek** [klinker-apps/messenger-issues#309]
**Device with issue:** <"HTC M9 gsm Android 7.0">
**Primary device:** <"stock HTC M9 gsm Android 7.0">
**App version:** <2.2.4.1125 "aleslukek" on the phone>
**Steps to reproduce:**

1. Don't get notifications when receiving SMS. SMS do arrive, just no notifications appear. Tried clearing cache, force stoping app, rebooting the phone, checking phone notification settings, logging out and back in. Nothing worked.
Seems that this occurred on the last update.

**Comment by klinker24** [comment]
Can you clear the app data and retry then? The newest update wouldn't have touched notifications

**Comment by aleslukek** [comment]
That solved the issue, even though i hated to do this. Had to set everything again:( 
When i signed in it tried to download all messages again so i stopped that. Will sign out from other devices and try to sign in again. Hope it will upload all messages instead of downloading them.

**Comment by klinker24** [comment]
Under my account, there is am option to resync messages

**Comment by aleslukek** [comment]
Found a new issue, when deleting a message (not a whole conversation) the message doesn't appear to be deleted in other messaging app - stock SMS app. 
And the last message (even if deleted) still appears on pulse first page (conversations lists with all contacts).
