### ISSUE TITLE
Sending from the web doesn't work when only one device is connected to your account

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#31]
**Device with issue:** Mac Pro running OSX 10.11.6 and Chrome v54
**Primary device:** Nexus 6P running Android 7.0
**No secondary device**
**App version:** 1.0.194
**Steps to reproduce:**

1. Remove your account to start clean
2. Install the app and sign in on your phone
3. Head to the [web](https://messenger.klinkerapps.com).
4. You will see all the conversations and be able to open them, type messages etc
5. Try to send a message
6. It won't come through to your phone (you should see it pop up in the message list immediately)
7. Install the app on a tablet and log in
8. Try to send another message, it will immediately go through as expected

**Additional Information**

I can investigate more to see if the exception is on the backend or if it is on the web side. Will post a log when/if this is necessary.

**Comment by klinker41** [comment]
Ahha, I know exactly why this is. I don't create an FCM notification group until more than 1 device is added to the account and I only send notifications to groups on the server. Therefore, there isn't a group so no notification will be sent to the phone to let it know it should send a message.

Might be a tricky fix, not sure yet.

**Comment by klinker41** [comment]
Should be fixed now... 

https://github.com/klinker41/messenger-server/commit/aebdf0cef20ee1c41188637f8d651b5a679a3ed1
https://github.com/klinker41/messenger-server/commit/3a1c2d44dc91583394b11da46859542033882026
https://github.com/klinker41/messenger-server/commit/fe1dfa294234472d9c9348bab9d34161b122b304
https://github.com/klinker41/messenger-server/commit/902cfb9ff488ff04031525061583762c9b51eccf
https://github.com/klinker41/messenger-server/commit/199983b7d084662c7b27607a7c27a469b37113e3
https://github.com/klinker41/messenger-server/commit/153cc9e46094fd154001a161781307843e03eb03
https://github.com/klinker41/messenger-server/commit/e0bb4f03785ece6e8a96969a1c7309abf3784470

oops, should have branched and crunched commits lol

**Comment by klinker24** [comment]
lol oh well, good work
