### ISSUE TITLE
Change conversation size when using smaller fonts

### ISSUE THREAD

**Issue by midenok** [klinker-apps/messenger-issues#310]
**Device with issue:** Zenfone 3
**App version:** 2.2.6.1131

For conversations list, pls make vertical interval betwen lines smaller for smaller font (as small as possible). Icons should be smaller too.

**Comment by klinker24** [comment]
I will consider lowering the padding, in the future. I won't make them as small as possible, there still needs to be padding around this items though.

**Comment by midenok** [comment]
I mean as small as possible in common sense of course. Thanks!

**Comment by midenok** [comment]
IMO, on normal font vertical spacing is unjustifiedly big too.

**Comment by klinker24** [comment]
Justification: https://material.io/guidelines/

**Comment by midenok** [comment]
It would be great pleasure for me to kill the inventor of Material Design. I would kill him slowly. Just for the note. Please delete the comment.

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/messenger/commit/4a224d20820a33e7895d1ef41083cf5055290a01
