### ISSUE TITLE
Quick scroll on message list

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#312]
**Device with issue:** Android Phones
**Request:**

Android Messages allows you to use a quick scroll bar on the message list, to get to different timestamps. This would be cool for Pulse as well:

![image](https://cloud.githubusercontent.com/assets/4874287/25529012/f16b4158-2be5-11e7-9d76-72786d80f74c.png)

**Comment by klinker41** [comment]
This would be cool.

**Comment by klinker24** [comment]
This library should emulate this functionality pretty well: https://github.com/turing-tech/MaterialScrollBar

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/messenger/commit/e4bf3411f7c8d0cb602b2b0bf28fd2e198863716
