### ISSUE TITLE
Auto dismiss chrome standalone app notifications

### ISSUE THREAD

**Issue by alexfournier** [klinker-apps/messenger-issues#315]
### Cannot automatically dismiss notifications

**Device with issue:** Mac Pro running OSX 10.12.3 and Chrome v 57.0.2987.133
**Primary device:** Nexus 5x running Android 7.0
**App version:** 2.2.6.1131
**Steps to reproduce:**

1. Receive a message in chrome standalone app
2. Notification is shown

**Additional information:**

**Possible solution:**

Offer option to set the duration of time that the notification is shown. Currently the notification can only be closed if the small 'x' is clicked or the notification its self is clicked, which bring the app into focus. But if I'm busy working on something else, I would prefer not to have to manually dismiss the notification.

**Comment by klinker24** [comment]
The chrome extension has a setting to turn on and off auto dismiss. Right click on the extension and hit "Options". The chrome app will only auto-dismiss. It doesn't have an options menu.

I don't think I will be setting an option for a specific timeout though, it is either auto-dismiss on or off. It is on by default
