### ISSUE TITLE
Contact photos in web/Chrome App version

### ISSUE THREAD

**Issue by kprym** [klinker-apps/messenger-issues#316]
I was wondering if you guys could try to incorporate kind of like the mock up I made below? :)

I love your Chrome app and this technology, so having my contact pics in there aswell, like the mobile app, would be amazing and take it to the next level. :)

![screen shot 2017-05-01 at 11 21 15 am](https://cloud.githubusercontent.com/assets/28265473/25586865/ee20f5f0-2e66-11e7-922b-8e6ed7ed7326.png)
![screen shot 2017-05-01 at 11 20 44 am](https://cloud.githubusercontent.com/assets/28265473/25586867/ee2c6714-2e66-11e7-9981-0d8d65ccf7d7.png)

**Comment by klinker24** [comment]
Yup, something like this will become possible after finishing up this issue: https://github.com/klinker-apps/messenger-issues/issues/133
