### ISSUE TITLE
Feature Request: Swipe to go back

### ISSUE THREAD

**Issue by pouyaman** [klinker-apps/messenger-issues#318]
**Device with issue:** N/A
**Primary device:** N/A
**App version:** 2.2.9.1157
**Steps to reproduce:**
N/A

**Additional information:**
Is it possible to add swipe on the chat to go back as an option?
Telegram and Textra (another SMS app) both have this feature.

**Possible solution:**
Either implement as an option to replace the current hamburger menu slide out (so one can choose which one they want to use)
or
Have it so that an edge swipe opens the hamburger menu (the app currently behaves like this) and a swipe from anywhere but the edge triggers a back function.

**Comment by pouyaman** [comment]
Just realized (by accident) that swipe up in chat menu performs this function.
For now this is enough. However it would be nice to have an option to switch between swipe up or left. 
Issue can be closed if dev is happy with current implementation (which is more than good enough).

**Comment by klinker24** [comment]
Swipe from the side isn't planned, sorry. We chose swipe from the bottom because that works with the expansion and style of the app.

**Comment by kathytu** [comment]
I know this was marked as won't fix a few years ago, but the default Android behavior now is swipe from the left side to go back for generally everything. Because of that, I keep forgetting to swipe up to go back in Pulse. Any chance we can have a swipe from the side to go back since all the menu items are available from the three dots menu anyway? Thanks!

**Comment by klinker24** [comment]
Sorry, there is no chance that this will be added, especially since Android does this natively. You can use the default android gestures to go back now, if you want to swipe from the sides.

**Comment by kathytu** [comment]
What I'm trying to say is that I do use the default Android gestures to go back, but Pulse doesn't allow me to because it opens up the menu instead. I just want to be able to continue to use the default Android gestures.

**Comment by klinker24** [comment]
I have no code in the app that would override the default side gestures. If you are seeing the app open the menu, then you have set up something at the system level or another app that is interfering with the gesture and opening the navigation drawer.

Sorry, I have no plans to change how this works within Pulse.
