### ISSUE TITLE
Feature Request: Auto save MMS content to device

### ISSUE THREAD

**Issue by pouyaman** [klinker-apps/messenger-issues#319]
**Device with issue:** N/A
**Primary device:** N/A
**App version:** 2.2.9.1157
**Steps to reproduce:**
N/A

**Additional information:**
Is it possible to add an option to auto save MMS content to device?
Textra (another SMS app) has a feature similar to this (although their implementation only works for photo/video).

**Possible solution:**

- Option in the settings to save MMS content to device.
- Option in setting to choose save location as well.

**Comment by klinker24** [comment]
It is already there. If you open up settings, and hit the "MMS configuration" option in the three dots overflow, you will find it

**Comment by klinker24** [comment]
It is already there. If you open up settings, and hit the "MMS configuration" option in the three dots overflow, you will find it

**Comment by pouyaman** [comment]
I completely missed that option in the menu.
 Perhaps that can be moved in the settings menu?

**Comment by klinker24** [comment]
I hide the MMS configuration on purpose, most people don't care about those options and don't understand them.

**Comment by pouyaman** [comment]
fair enough.
