### ISSUE TITLE
Replies received in Pulse Android app missing from same conversations in Web site, Windows App, Chrome App, Chrome Extension, and Firefox Extension

### ISSUE THREAD

**Issue by MartinesM3** [klinker-apps/messenger-issues#320]
**Device with issue:** Dell Inspiron 15, Windows 10
**Primary device:** Samsung Galaxy S7, Android 7.0
**App version:** Pulse 2.2.9.1157
**App version:** Pulse Windows App
**App version:** Chrome Extension 1.8.1
**App version:** Firefox Extension 1.8.0
**Steps to reproduce:**

1. Read conversations on Pulse Android App. Note inbound replies.
2. Observe replies present in Pulse Android App and missing from same conversations in Pulse Web account, Chrome App, Chrome Extension, and Firefox Extension.

**Comment by klinker24** [comment]
Can you open the conversation on the web, right click and hit "inspect"? If you could post a screenshot of the console, that would be good, if it shows any red

**Comment by MartinesM3** [comment]
Manny
MartinesM3@gmail.com

**Comment by klinker24** [comment]
Sorry I don't see an image attached there? Looks like it is just your email signature.

**Comment by MartinesM3** [comment]
It was attached after the signature (and not embedded before it. And, it
came back attached to your reply.

Perhaps your email client is filtering.


On May 9, 2017 08:40, "Luke Klinker" <notifications@github.com> wrote:

Sorry I don't see an image attached there? Looks like it is just your email
signature.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/klinker-apps/messenger-issues/issues/320#issuecomment-300150465>,
or mute the thread

**Comment by klinker24** [comment]
I am not looking at email, I am on GitHub. It isn't in the GitHub emails either. You can just drag the picture into the conversation here.

**Comment by MartinesM3** [comment]
This is the Web page Inspect:

![screenshot_kinkerpulse_web_inspect](https://cloud.githubusercontent.com/assets/4676549/25871638/3d7db910-34d6-11e7-837e-241a88d8625c.jpg)

**Comment by MartinesM3** [comment]
This is a screenshot from the Android App. 
Note the two messages time-stamped at or after: 2017 May 5 1314 (1:14 pm)
"Hey Dad, I got a job interview ..."
"Do you want to start driving ..."

![screenshot_klinkerpulse__android70](https://cloud.githubusercontent.com/assets/4676549/25871792/a982418a-34d6-11e7-9b6d-2fecd4b8c9a6.png)

**Comment by MartinesM3** [comment]
This is a screenshot from the Windows 10 app 
Note the absence of the two messages that were in the Android app, 
time-stamped at or after: 2017 May 5 1314 (1:14 pm)
"Hey Dad, I got a job interview ..."
"Do you want to start driving ..."

![screenshot_klinkerpulse_windows10](https://cloud.githubusercontent.com/assets/4676549/25871993/2f5cf048-34d7-11e7-8045-48b65b4fb634.png)

**Comment by MartinesM3** [comment]
This is a screenshot from the Chrome Extension. 
Note the absence of the two messages that were in the Android app, 
time-stamped at or after: 2017 May 5 1314 (1:14 pm)
"Hey Dad, I got a job interview ..."
"Do you want to start driving ..."

![screenshot_klinkerpulse_chromeextension](https://cloud.githubusercontent.com/assets/4676549/25872034/57e47360-34d7-11e7-9dbd-4a4ddfbf3857.png)

**Comment by MartinesM3** [comment]
This is a screenshot from the FireFox Extension
Note the absence of the two messages that were in the Android app, 
time-stamped at or after: 2017 May 5 1314 (1:14 pm)
"Hey Dad, I got a job interview ..."
"Do you want to start driving ..."

![screenshot_klinkerpulse_firefoxextension](https://cloud.githubusercontent.com/assets/4676549/25872093/80c45502-34d7-11e7-8340-9f3c4530e81b.png)

**Comment by klinker24** [comment]
All the web platforms will be the same, they all pull from the same place in real time. Looks like there aren't any errors on the console, so I would say that the message failed to upload to the server. Could have been due to a network blip or poor coverage. You could push them up with the "refresh push notifications" option in the account section of your phone.

**Comment by MartinesM3** [comment]
It worked. The messages were recovered.
Not an ideal solution. 
For anyone preferring the web, extension, or Chrome app versions, the missing messages can go completely unnoticed. I noticed the discrepancy only because I just installed he web version while the missing messages were still fresh in mind.
