### ISSUE TITLE
Auto Load / Preview Web links within conversations

### ISSUE THREAD

**Issue by Obsidiannite21** [klinker-apps/messenger-issues#322]
Device: Galaxy S8+
Feature Request:

When pasting a web link into a conversation it would be nice if it showed a preview of the link's content. iOS & Verizon Message+ do this and I think it's a nice feature. It would also be nice if when a web link was sent as a text the same preview would be generated.

**Comment by klinker24** [comment]
It already does this for received messages, if it determines it is an article and can parse the content.

This isn't planned for sent messages, it just takes up space, and you already know what you sent, the app shouldn't need to preview that for you

Recurved articles work on the web as well.
