### ISSUE TITLE
Attach Contacts from Conversation 

### ISSUE THREAD

**Issue by Obsidiannite21** [klinker-apps/messenger-issues#323]
Device: Galaxy S8+
Feature Request:

It would be helpful to tap the attach button in a conversation, tap on a contacts button, then bring up the contacts window so a contact could be sent quickly via text. You can do this from the Contacts screen itself, but it would be nice to be able to do it right from the texting app.

**Comment by klinker24** [comment]
This is already done: https://github.com/klinker-apps/messenger-issues/issues/263
