### ISSUE TITLE
Conversation list sections

### ISSUE THREAD

**Issue by Obsidiannite21** [klinker-apps/messenger-issues#324]
**Request:**

~~1. Contact pics would be nice.~~
~~2. It seems as if the conversations don't update when in a conversation. The only way they update live is when you are in the main menu. It would be helpful if they update when you are a conversation or a least received a visual notification (other than the pop up which can be missed) since that's probably where one will spend most of their time.~~
3. Minor but the ability to resize the conversation list so the conversation doesn't have to be so big to see the list.
4. Conversations broken down by received time / day like on the app.

**Comment by klinker24** [comment]
Thanks for the requests.

1. is already logged here: https://github.com/klinker-apps/messenger-issues/issues/133. When this gets done, this request will come with it.
2. No they don't. This is logged here: https://github.com/klinker-apps/messenger-issues/issues/76
3. You will have to tell me what you mean by this, maybe a screenshot would be helpful.
4. This will probably come in the future, yes

**Comment by Obsidiannite21** [comment]
Thanks for the quick response! Regarding #3, in short, I would like to be able to reduce the amount of real-estate the app takes up with still being able to see conversations & contacts. If I shrink the window down too far I loose the contact list on the left, whereas some other apps allow you to make it as small as you'd like but keep both open. Again its a super minor thing, but I like to leave this window open and accessible all the time so I need to fit it in with all of the other windows I have open. 

Other than that, I love your android app, I think its way better than many others that I have tried. It really has a great look & feel to it, without having to spend hours customizing the heck out of everything. I look forward to the improvements & features you are implementing!

**Comment by klinker24** [comment]
Conversation list sections have been added here: https://github.com/klinker41/messenger-web/commit/db9f29de0b7b091745f92329344d205a78f43e74

I will deploy them within the next few days, after finishing up my own testing.

I am going to close this out. The 3rd one changed with the new UI a few months ago, but I don't plan on adding a configurable size, at this point.
