### ISSUE TITLE
Unable to send text with android / tablet app

### ISSUE THREAD

**Issue by Obsidiannite21** [klinker-apps/messenger-issues#325]
**Device with issue:** Nvidia Shield K1 running Android 7.0
**Primary device:** Galaxy S8 +
**App version:** 2.2.10.1172

When I go into a conversion, and type a message, then hit the send icon nothing happens. The button depresses but that's about it. This only seems to happen on my tablet, it works fine on my phone. 

I have tried to force close the app, reboot, disconnect from the wired connection (I have an Ethernet adapter, I thought it may interfere since it looks like the device does not have wifi), and disconnected HDMI. I have also changed the orientation from landscape (default with HDMI) to portrait to see if that did anything and disconnected the mouse / keyboard. The text was also quite long so I reduced it to 1 character to see if that helped. That's the extent of my troubleshooting abilities.

**Comment by klinker24** [comment]
Could you try uninstalling and reinstalling the app? There is nothing that I can see that would stop the app from sending from a tablet.

**Comment by Obsidiannite21** [comment]
Sure, I'm out of the office now, but when I get back I will give that a try and report back.

**Comment by Obsidiannite21** [comment]
Uninstall / Reinstall did the trick.
