### ISSUE TITLE
Angle brackets don't render properly

### ISSUE THREAD

**Issue by reserad** [klinker-apps/messenger-issues#326]
**Device with issue:** HP laptop on Windows 10 Pro, running Chrome v58
**Primary device:** HTC 10 running Android 7.0
**App version:** 2.2.10.1172
**Steps to reproduce:**

1. Type a message in the extension and or mobile app in the format:
> < insert random text here > without the spaces

**Additional information:**

The text that you input does NOT render and shows up as a blank message bubble.

![example](https://cloud.githubusercontent.com/assets/11075801/26000841/6f977f5c-36f8-11e7-9787-078da2475f78.png)

**Comment by klinker24** [comment]
No, they don't. I will look to improve this in the future, but right now it is working the way I have designed it to work

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/messenger-web/commit/f3d2b542822cd19389a953a3a5c7d32f5da5f859
