### ISSUE TITLE
Sent messages marked as "Sending..." for minutes/hours

### ISSUE THREAD

**Issue by anstosa** [klinker-apps/messenger-issues#327]
**Device with issue:** Pixel XL on Android 7.1.2 
**Primary device:** Pixel XL on Android 7.1.2
**App version:** 2.2.10.1172
**Steps to reproduce:**

1. Send a text message
2. Message displays as "Sending..."
3. Recipient receives message
4. Message status is still sending for 30+mins after it was already sent.

**Additional information:**

Google Fi

**Comment by klinker24** [comment]
Sorry, I don't have control over this. It completely relies on the phone to provide the app with the sent status. Is this happening for every message, or just a few?

**Comment by anstosa** [comment]
Yeah I was afraid of that... Google Fi's SMS/MMS support has been less than ideal.

It's been happening with every message for the last 2 days.

**Comment by klinker41** [comment]
I'm guessing you've tried simply restarting your device? I have not had any issues on project fi myself.

**Comment by anstosa** [comment]
Yup, tried restarting and switching SMS apps. I'll reach out to Google Fi and see what they have to say. Either way, if it's not on your end, it's not on your end. Thanks for the help!
