### ISSUE TITLE
[Feature Request] Time on Main Page and Upgrade Look

### ISSUE THREAD

**Issue by smileyjpark** [klinker-apps/messenger-issues#328]
First time using Pulse and wanted to put in a feature request.

1) Showing time when last message sent or received. Only way to check this is opening the message.

2) If it can be in a list (without showing "yesterday," "last week," etc.), having that option would be nice.

**Comment by klinker24** [comment]
Sorry, right now, this is the style that I am going for with the app. Having these sections on conversion list allow me to now show the individual timestamps, as well as provide a quick way to mark everything as read.

**Comment by smileyjpark** [comment]
How about showing the time last received or sent message on the screen?

**Comment by klinker24** [comment]
Sorry, I put the sections in there so that I didn't have to show it on every message, that is what I am trying to avoid doing
