### ISSUE TITLE
Icon counter badge does not ignore muted conversations

### ISSUE THREAD

**Issue by midenok** [klinker-apps/messenger-issues#329]
**Device with issue:** Asus Zenfone 3
**App version:** 2.2.6.1131
**Steps to reproduce:**

1. Mute conversation
2. Wait for incoming SMS

### Result

App icon counter badge is increased.

### Expected

Counter badge should not change.

**Comment by klinker24** [comment]
This is actually working the way I would expect it to work.. it is still unread, regardless of it's muted status. Muted is about the notifications, not necessarily whether it is unread or not

**Comment by midenok** [comment]
As a matter of fact this counter disturbs me: I try to check whether something new have arrived. In such case, it would be good to have 3rd state for "mute" option: *ignore conversation*.

**Comment by klinker24** [comment]
Muted conversations won't count in unread count: https://github.com/klinker41/messenger/commit/85fdbca82c8812efc1c617dbc91e83e2482285dc

**Comment by midenok** [comment]
Thanks!
