### ISSUE TITLE
Improve in-conversation alerts for new messages

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#330]
**App version:** 2.3.0
**Steps to reproduce:**

1. Open a message thread
2. Scroll up so that you aren't at the bottom
3. Receive a new message into the thread

**Request:**

There is no notification that a new message came in, except for a "ding" sound. Some apps provide a toast-like message to alert a user to a new message coming into the conversation.

**Comment by Yozakgg** [comment]
You should do something like what Hangouts does: http://i.imgur.com/A4z7mqF.png
And when you don't have a new message, it acts as a return to bottom button: http://i.imgur.com/k7L6A53.png

**Comment by klinker24** [comment]
I don't plan on the return to bottom thing, sorry. I just think that is unnecessary. But yes, the new message toast is the goal.

**Comment by klinker24** [comment]
Some progress. 

* The initial implementation: https://github.com/klinker41/messenger/commit/9dc02a02f6132c555759ca17423194f88077df11
* Improvements to the animations, feature flag, and add action: https://github.com/klinker41/messenger/commit/87f2209965868ec1e62ad30728fba1b11de61260

Todo:
* [ ] don't show when the added message is sent one that the user just sent
* [ ] automatically dismiss the indicator when we reach the new message
