### ISSUE TITLE
Text messages not being received 

### ISSUE THREAD

**Issue by Obsidiannite21** [klinker-apps/messenger-issues#331]
Device with issue: Galaxy S8 +
App version: 2.3.0.1186

I noticed that Pulse was not receiving certain text messages so I decided to do a test. I used a texting app to send the numbers 1-23 as individual texts over the course of 2-3 minutes. As you can see from the screen shot 13 + 20 are missing. 13 was sent to the phone, 20 was sent from the stock texting app. If I were to open the stock texting app or another 3rd party app those two text messages appear so its strictly pulse that is not recognizing them. I've had to stop using Pulse for fear I will miss important messages.

![screenshot_20170515-222710](https://cloud.githubusercontent.com/assets/28603530/26104504/224f8002-3a0c-11e7-8590-a0b2214a772b.png)
![screenshot_20170515-222810](https://cloud.githubusercontent.com/assets/28603530/26104505/225832e2-3a0c-11e7-9c1c-ad56fc75fe95.png)

**Comment by klinker24** [comment]
For 20, I will never make any guarantees that the app will work if it isn't the default. Please tell me what you mean by 13 being sent to the phone. I don't understand that, sorry.

**Comment by Obsidiannite21** [comment]
I used another phone to text the numbers 1 - 23 to make sure all of the messages were being received by pulse. #13 never showed up in pulse but if I load the stock texting app or another 3rd party texting app its present. I attached both screen shots. I've noticed other messages missing which is why I ran this test.

**Comment by klinker24** [comment]
Then what was 20 supposed to be? I guess I am confused. Was Pulse the default when you were receiving all the messages or did you change it away from the default when you sent 20?

There is literally only one way to receive SMS, and it is handled by the system, the system just provides a callback for when a message is received: http://javapapers.com/android/android-receive-sms-tutorial/

**Comment by Obsidiannite21** [comment]
Yes pulse was the default, until I sent #20. 20 was a text sent from the S8+, using the stock app, to the phone that was sending test text messages. 

I have no idea how your app or the system works, just that there seems to be a bug somewhere that caused Pulse to miss one of the messages when other apps seem to be able to view it fine.

**Comment by klinker24** [comment]
Sorry, GitHub is traditionally a place for developers, I figured if you had an account, you were a developer.

I have a change I can make for the next version, to watch if another app receives a text and stops the broadcast from reaching Pulse. Your stock app could definitely do that.
