### ISSUE TITLE
SMS mirroring notifies of muted conversations

### ISSUE THREAD

**Issue by heliwh** [klinker-apps/messenger-issues#333]
**Device with issue:** ChromeBook running Chrome Version 57.0.2987.146 (64-bit)
**Primary device:** LG G4 running  Android 6.0
**App version:** 2.3.0.116 on Android, 1.7.0 on Chrome
**Steps to reproduce:**

1. Mute conversation
2. Receive message in muted conversation. The Chrome app will display a notification, but the Android app will correctly ignore the message

**Additional information:**

The Chrome app doesn't display the contents of the message, so it may just be handling muted and private conversations the same way. The conversation was archived as well as muted.

**Possible solution:**

**Comment by klinker24** [comment]
I will have a look. When you get a new message in a conversation, it gets removed from the archive, so that doesn't matter

**Comment by klinker24** [comment]
Fixed with: https://github.com/klinker41/messenger-chrome/commit/d02366e1bdd4ff3ab5b5356272f57b45815da97c

I will put up the updates to the chrome app and extension, as well as the firefox extension, later today.
