### ISSUE TITLE
RaspberryPi App

### ISSUE THREAD

**Issue by radio2ip** [klinker-apps/messenger-issues#334]
**Device with issue:** <RasberryPi>
**Primary device:** <Android Phone">
Is it possible to run Pulse natively on a RaspberryPi without a Web/Browser interface? I have a scenario were an Android phone would be the Primary device and it's texts would be show up on multiple RaspberryPis'. Your thoughts?

**Comment by klinker24** [comment]
What's wrong with just using the web interface? A raspberry pi app would end up looking the exact same as the web, and the web is already built out

**Comment by klinker24** [comment]
Going to go ahead and close this for lack of info, feel free to comment back here, and I will re-open if there is anything specific you want to see!
