### ISSUE TITLE
Keyboard not responding in popup window

### ISSUE THREAD

**Issue by zenbug** [klinker-apps/messenger-issues#335]
I can't type anything when I click the Pulse icon in the Chrome toolbar (desktop), so I can't log in, reply to texts, nothing. The keyboard just doesn't respond.

It does work if I detach the window using the little arrow-in-a-box icon.

I've tried logging out, uninstalling the extension, and reinstalling. Still no-go.

**Comment by klinker24** [comment]
Duplicate of https://github.com/klinker-apps/messenger-issues/issues/283
