### ISSUE TITLE
Still sending message

### ISSUE THREAD

**Issue by netmen5** [klinker-apps/messenger-issues#337]
**Primary device:** <Moto x Play on Android 6.0.1">
**App version:** <2.3.1.1196>
**Steps to reproduce:**

1. send a message. After click send minimalize app
2. Open app, send another sms and wait
3. Second sms is delivered first is sending
`... more steps`

**Comment by klinker24** [comment]
Not sure if I never saw this issue or why I never responded. This is pretty old though and I haven't seen or heard of any issues around this. There were changes awhile back around reading the sent status from Android, so I imagine that this is no longer an issue.
