### ISSUE TITLE
Some contact icons not showing up

### ISSUE THREAD

**Issue by smileyjpark** [klinker-apps/messenger-issues#338]
Since two updates, there has been a bug I've seen where some contact icons are not showing up on the app. It's always two or three missing when I know they do have contact pictures.

**Comment by klinker24** [comment]
It will refresh the contact image for a conversation, whenever you open the conversation. So I would just open it, then back out of the app and re-open it. 

This will all change when this gets done (https://github.com/klinker-apps/messenger-issues/issues/133), so I am going to close this as a duplicate
