### ISSUE TITLE
No error message during sign up 

### ISSUE THREAD

**Issue by marcuscbey** [klinker-apps/messenger-issues#34]
### No error message for invalid username 

**Device with issue:** Nexus 6P running Android 7.0
**Primary device:** Nexus 6P running Android 7.0
**App version:** 1.1.209
**Steps to reproduce:**

1. Open messenger app for first time 
2. Click sign up
3. Enter a username that is not an email address. The field says username and there is no error if you put in a non email, it just doesn't display the FAB

**Comment by klinker41** [comment]
Thanks for the report!

**Comment by klinker41** [comment]
Just a note for myself, this will also happen when the passwords do not match, the contact name is blank, or the phone number is blank.

**Comment by klinker41** [comment]
We should also change the login error message to something more meaningful if the email or password is wrong.

**Comment by klinker41** [comment]
done with https://github.com/klinker41/messenger/commit/43e9c1f220b1e5c090244645b4ea924985008c49

![device-2016-08-31-152508](https://cloud.githubusercontent.com/assets/4501322/18145132/7964d5ba-6f8f-11e6-8722-a69059c8d5a8.png)
