### ISSUE TITLE
Remove special characters from auto-save media

### ISSUE THREAD

**Issue by fourg** [klinker-apps/messenger-issues#340]
**Device with issue:** Pixel XL
**Primary device:** Pixel XL - Android O Beta (this issue appears agnostic to Android build)
**App version:** 2.3.2.1214
**Steps to reproduce:** 

1. have "Auto-save media" enabled under MMS Configuration
2. Receive MMS with images
3. See them saved as "May 27, 2017 1:50:19 PM.jpg"

**Additional information:**

Do you want to provide any other information? Device configuration, unique cases, anything that you think may be relevant.

Please remove (or give an option to remove) the special characters which are included anytime an image is auto-saved.  The comma and colon can cause other apps to behave badly and not open these images making it a manual process for us, the user, to manually remove those special characters.

Thanks!
-Brent

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/messenger/commit/9c33b71d3a6f3e3cced98beb948fc80a2620fdb9

They will look like `media-<timestamp>.png` instead of the date string
