### ISSUE TITLE
Support for additional color theming options.

### ISSUE THREAD

**Issue by IronPiston** [klinker-apps/messenger-issues#341]
The visual style for Pulse looks great, but I find the blue-grey dark theme(#374248 & 202B30) clashes compared to the dark themes of the other applications on my phone. Could you implement a "Grey-Dark" theme option with a color like #303030 & #212121? This is a mockup implementing the proposed color changes: http://imgur.com/a/sEYPE. These colors would extend across the entire UI, not just the messaging screen.

The selection for the main theme color also lacks fine-tuned control, unlike the expansive options for individual contact color selection

I know these are very minor complaints, but if they were implemented, I would be able to switch to Pulse from Textra

**Comment by klinker24** [comment]
At this point, I am not up to changing the dark theme color, sorry.

I may open up the global themes to more colors in the future as well, but at this point, it isn't set up to work that way, and I want to keep the global theme simpler than the fine grained control
