### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#344]
**Implementation Details:** [hotkeys.js](http://wangchujiang.com/hotkeys/)

## Currently Implemented Shortcuts

You cannot be focused on the message text entry area to use the navigation shortcuts.

#### MacOS

* `control + shift + left arrow` or `command + shift + left arrow`: page to the previous conversation.
* `control + shift + right arrow` or `command + shift + right arrow`: page to the next conversation.
* `control + backspace` or `command + backspace`: return from the message list, to the conversation list.
* `control + n` or `option + n`: create a new message.
* `control + e` or `option + e`: open emoji selector.
* Use the arrow keys (`up` and `down`) to page through contacts when creating a new message

#### Windows/Linux

* `ctrl + shift + left arrow` or `alt + shift + left arrow`: page to the previous conversation.
* `ctrl + shift + right arrow` or `alt + shift + right arrow`: page to the next conversation.
* `ctrl + backspace` or `alt + backspace`: return from the message list, to the conversation list.
* `ctrl + n` or `alt + n`: create a new message.
* `ctrl + e` or `alt + e`: open emoji selector
* Use the arrow keys (`up` and `down`) to page through contacts when creating a new message

**Comment by klinker24** [comment]
For the mouse events, this seems relevant: 

https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/buttons
https://superuser.com/a/1003565

**Comment by klinker24** [comment]
The mouse back button should be working on the desktop app now, so this should be finished. I will continue to update the list of shortcuts, as I get more of them.

**Comment by thefoodjunky** [comment]
CTRL Enter to send! Something that is very common. That way you can turn off 'enter to send' so you can create multi paragraph messages! It's very common in messenger and email clients surprise it's not supported or discussed.

**Comment by klinker24** [comment]
shift+enter

**Comment by thefoodjunky** [comment]
Interesting. Shift+enter creates a new line. Would prefer ctrl enter to send as it's how everything else works. But it's better then nothing.
