### ISSUE TITLE
First Message in Group Texts Missing

### ISSUE THREAD

**Issue by dgrahn** [klinker-apps/messenger-issues#345]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [x] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** Samsung Galaxy SG (SM-G920V) on Android 7.0
**Primary device:** Samsung Galaxy SG (SM-G920V) on Android 7.0
**App version:** 2.3.2.1207
**Steps to reproduce:**

1. Make friends with phones.
2. Have one friend text you and at least one other friend.
3. Wait for text. Nothing comes in.
4. Have other friend respond to group text.
5. 2nd text appears.

**Additional information:**

I don't think I have any additional information, but I am a software engineer... So I'm willing to help any way I can.

**Comment by klinker24** [comment]
I am tracking all MMS issues over here: https://github.com/klinker-apps/messenger-issues/issues/101

Thanks for the report on this one, it is now linked in that thread. If you want to check it out, our MMS implementation is open source: https://github.com/klinker41/android-smsmms
