### ISSUE TITLE
Swipe to Delete preference is ignored?

### ISSUE THREAD

**Issue by joshkendrick** [klinker-apps/messenger-issues#346]
**Device with issue:** Google Pixel Android 7.1.2
**Primary device:** Google Pixel Android 7.1.2
**App version:** 2.3.3.1217
**Steps to reproduce:**

1. Swipe a conversation away, notice that it's archived
2. Go to settings, turn on "Swipe to delete"
3. Swipe a conversation away, notice that it's still archived, not deleted

The app is archiving a conversation on swipe regardless of whether that setting is toggled on or off.

**Additional information:**

It's entirely possible that I'm misunderstanding the feature; I just downloaded and set the app up today. It's awesome! I've been looking for something like this ever since switching from iPhone (months).

I don't know how reproducible it is on a different device, but I can't get swipe to delete to work at all for me. I even tried the "refresh my account" thing under My Account -> Account Actions. I'm wondering if maybe it has something to do with once I created an account (signed up) my preferences are managed under a different name maybe? Syncing the prefs up to the chrome app seems to be working for the rounded corners option..

This is exactly what I've been looking for in a messaging app, no more, no less 👌 !

**Comment by klinker24** [comment]
The archive is always available on the swipe to delete

* If you swipe from the left side of the screen, you will see the archive activate
* If you swipe from the right side of the screen, when that option is on, you will see the delete "trash can" activate

**Comment by joshkendrick** [comment]
Yep. Completely missed that, my apologies! I'll close this issue.

Great app! Love it!
