### ISSUE TITLE
Message appearing multiple times

### ISSUE THREAD

**Issue by SuddenTurmoil** [klinker-apps/messenger-issues#347]
I am unsure how to reproduce it but it appears frequently. It MAY be relayed to sending messages with bad reception. 

LG G5 on Android 7.0, no web clients as of yet
App version 2.3.3.1217

Occasionally a conversation I have with someone will show multiple copies of the same message. The recipient receives only one copy. 
![screenshot_2017-06-01-20-34-16](https://cloud.githubusercontent.com/assets/4281297/26707360/e92e872c-4709-11e7-8fb4-46e775e26fb6.png)

**Comment by klinker24** [comment]
Is Pulse the default app? There is no automatic retry in Pulse, so I don't know that that is the issue.

**Comment by SuddenTurmoil** [comment]
Pulse is the default app (I checked, not just assuming).

**Comment by klinker24** [comment]
When you say it may have something to do with bad reception, do you get a failure notification for these messages, then use the retry button to resend them, or how do you resend them?

**Comment by SuddenTurmoil** [comment]
The messages don't fail to send, but the LTE or 3G meter shows no bars. I booted up SignalCheck Lite and grabbed a screen shot of the connection 
![screenshot_2017-06-02-09-01-55](https://cloud.githubusercontent.com/assets/4281297/26729189/595f9082-4772-11e7-95da-fb816527fa46.png)

**Comment by klinker24** [comment]
I don't think that that is the issue then, unless you have another app running that would pick up on those messages and try to resend them automatically

**Comment by SuddenTurmoil** [comment]
I don't have any such app that I am aware of. I switched over from Hangouts because it is loosing sms support. I previously had Sprint's Google Voice integration but properly disintegrated it when Voice MMS broke and Sprint dropped it as supported. Default messaging app and pushbullet (not configured for sms) are the only other apps that deal with sms on my phone that I know of.

**Comment by klinker24** [comment]
Do these multiple messages show up in the other messaging apps on your phone?

My other question is whether or not this is completely random. Do you just re-enter the app some time and they are duplicated, or are you doing anything in the background/interacting with anything inside or outside of Pulse, when you notice this?

I have never heard of anything like this, so I am a bit confused where they would be coming from. Any details you can provide me with are great for this issue.

**Comment by SuddenTurmoil** [comment]
The default Messages app does not show multiples. 
I think I will send a message and then hit home or app switch while the message is still in 'sending' and do something else not related to SMS and when I go back I to the conversation hours later I notice that the conversation has multiple copies posted. I think I have only ever experienced it with that one person but I text her orders of magnitude more than other people so it may simply not have happened yet. My second most used messaging thread is a group text which I think is using MMS and that has had no duplicates. 
Are there any logs or diagnostics I could provide for you? It's not an app breaking bug or anything but it is a bug so I figured I should report it.

**Comment by SuddenTurmoil** [comment]
The conversation that duplicates is pinned, and is my only pinned conversation

**Comment by klinker24** [comment]
Being pinned won't affect this. I will see if I can figure anything out.

**Comment by klinker24** [comment]
I had made some slight changes around sending message, in the current beta version. Do you think you could sign up, and let me know if you see any changes @SuddenTurmoil?

**Comment by SuddenTurmoil** [comment]
I have opted in to the beta and updated. I haven't seen the issue since the 1st of June but that might not mean it's gone. I'll let you know how the beta version works.

**Comment by klinker24** [comment]
Any updates on this? I haven't heard from anyone about issues here.

**Comment by SuddenTurmoil** [comment]
It is much more rare, and so far only doubles, but still happens. One instance recently was sent first at 5:58pm and didn't double till 8:03am. I think I hit the home button immediately after sending and didn't open Pulse till the next morning. I don't use any memory manager but maybe the built in one is aggressively killing Pulse?

**Comment by klinker24** [comment]
You don't have any other weird SMS apps on your phone that would be picking up messages that weren't sent by "them" and attempting to resend them, do you? This is just such a weird issue. I haven't had any other reports of it

**Comment by klinker24** [comment]
@SuddenTurmoil sorry to bug you, but do you have any follow up? If not, I am going to close this issue.

**Comment by SuddenTurmoil** [comment]
My phone went crazy and had to have several chips on it replaced so I was going to attribute it to whatever that was, but shortly after getting it back from the repair center it did it again; 
![image](https://user-images.githubusercontent.com/4281297/29275860-32959bf6-80d2-11e7-9183-9d533e54bef3.png)
I did have Hangout with SMS and Google Voice integration through Sprint, but I disabled that. Hangouts still occasionally tells me to download Android Messages to view SMS though so maybe it still has its fingers stuck in there somehow but I would imagine if it was that more people would have this issue. I'm perfectly fine with being that one weird case. It's not hampering my ability to use Pulse and I still love it (lifetime member now, using Pulse to restore my texts and MMS after the repair was AMAZING). As only me seems to have the problem out of 100,000 users I'm betting it is something odd on my end at this point, so feel free to close the issue as it doesn't seem to be an issue with your app.

**Comment by klinker24** [comment]
Ok, all of this conversation will stay here, so if things change in the future, we know where we were at. I am going to close this one out though

**Comment by ryantippery** [comment]
I've been having this identical issue for awhile now in multiple conversations. I've also been experiencing other issues specifically involving group chats.

**Comment by ryantippery** [comment]
Group chats will send me my messages in a separate "group" it lists all other recipients, but only shows my messages. I also know that when multiple people in the group send messages at the same time only one actually comes through on my end. This repetitive message issue happens in both group and non group conversations though.

**Comment by bisrama** [comment]
I am experiencing the same issue, any solutions?
![Capture](https://user-images.githubusercontent.com/51523319/59154814-2b95e400-8a49-11e9-9088-910cf0a9b576.PNG)

**Comment by bisrama** [comment]
I am experiencing the exact issue on my Thinkpad with Win10 and Chrome running off Samsung Note8 with PIE

![Capture](https://user-images.githubusercontent.com/51523319/59154879-4ddc3180-8a4a-11e9-84eb-1ae2eaa70d45.PNG)

**Comment by bjs03** [comment]
Have the same issue too but it only occurs when I send a text from the ios app you developed

When I'm using pulse on any other platform it doesnt occur. Is there a way to fix this?
