### ISSUE TITLE
FAB doesn't work when scheduling messages

### ISSUE THREAD

**Issue by sihartley** [klinker-apps/messenger-issues#349]
**Device with issue:** Galaxy Note 5 Android 7
**Primary device:** Pixel XL on Android 7.1.2
**Steps to reproduce:**

1. Choose conversation, select Schedule a Message and create a message....
2. After creating one message try talking the "+" bottom right corner. Will not create a new message, the button is dead.

**Comment by klinker24** [comment]
Thanks for the report, will fix this.

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/messenger/commit/b5827944f70dbc7eed632f9cc06386cab6ef2bfa
