### ISSUE TITLE
Feature Request - Full date and time display

### ISSUE THREAD

**Issue by alanwhiteman** [klinker-apps/messenger-issues#351]
- [ X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.

**Primary device:** Moto G 3rd - Android 6.0.1
**App version:** 2.3.4.1239

Hi,

Great messaging app!

I think the app would benefit by allowing a way to display the full date and time under each conversation bubble. As is right now, one has to tap the bubble to see just the time, or long-press and click on the info icon to see the full date and time. This is rather inconvenient when multiple messages come in and sometimes, for whatever reason, they come late or out of order. Moreover, it makes it a bit hard to reference specific bubbles in a group conversation.

Perhaps you can offer an option to either:
1) Always display the full date and time per bubble
2) Tap on bubble to display full date and time

Thank you.

**Comment by klinker24** [comment]
I don't plan to show the timestamp below every message by default, sorry. The timestamps are displayed if the previous message was more then 15 mins ago.

This is actually working the way that I would expect it to, already. For the date and time stamps on messages:

- if it is today: Pulse will show just the time (1:15 PM)
- if it is this week, Pulse will show the day of the week, and the time (Thu 1:15 PM)
- if it is later than that, Pulse will show the full date (Mar 15, 1:15 PM)

So I don't really see much use in putting the full timestamp (Mar 15, 1:15 PM) on every single message. Am I missing something that you are looking for? At this point, I would say that this is working as expected

**Comment by alanwhiteman** [comment]
OK. Your scheme sounds reasonable. Perhaps because I just installed the app and it's syncing with the old messages I can only see the time, no date, for messages sent yesterday.
