### ISSUE TITLE
Crash loop on Android O

### ISSUE THREAD

**Issue by anstosa** [klinker-apps/messenger-issues#355]
- [X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [x] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** Google Pixel XL
**Primary device:** Google Pixel XL 8.0.0 dev3
**App version:** 2.4.1.1281
**Steps to reproduce:** Open app

1. Wait a second or two
2. "Pulse keeps stopping"

**Additional information:**

I did "send feedback" so hopefully those logs are helpful

**Comment by klinker24** [comment]
You can just update to the latest version on the Play Store. I already fixed this, earlier this morning.

**Comment by anstosa** [comment]
🤦Yup that worked. Sorry for the noise!
