### ISSUE TITLE
Add Ability to lock conservations

### ISSUE THREAD

**Issue by NovaViper** [klinker-apps/messenger-issues#357]
Hey, I have one feature that I've been needing for a long time. And that is the ability to lock your conversations and even completely hide them from your messages page (and to access them, you must press a button and perform a gesture). In this locking mechanism, there should be the option to use either a pattern, pin or your fingerprint.

**Comment by klinker24** [comment]
This will definitely come in the future, yep: https://github.com/klinker-apps/messenger-issues/issues/167

**Comment by NovaViper** [comment]
Yes ^^
