### ISSUE TITLE
Increase thumbnail size of gifs in conversation view

### ISSUE THREAD

**Issue by Captainjman2** [klinker-apps/messenger-issues#36]
**Primary device:** Nexus 6P running Android 7.0
**App version:** 1.1.209

**Additional information:**

As it is now, the gif message thumbnail size is very small and very hard to see at first glance.

**Possible solution:**

Since this app is supporting gifs it would be best if the thumbnails were larger so users can see gifs easily and quickly at first glance without having to tap on the image to enlarge it.

**Comment by Captainjman2** [comment]
Made edits as this only applies to gifs.

**Comment by klinker41** [comment]
done with https://github.com/klinker41/messenger/commit/611b278f37094791506cabd2fd728fb71ac85fd8.

![screenshot_20160830-221947](https://cloud.githubusercontent.com/assets/4501322/18114836/10344542-6f00-11e6-8fd2-0b265499efe7.png)
