### ISSUE TITLE
Improve syncing "read" status on conversations

### ISSUE THREAD

**Issue by BatterBits** [klinker-apps/messenger-issues#361]
**Device with issue:** <All devices>
**Primary device:** <Samsung Galaxy S6>
**App version:** <2.3.4.1239>
**Steps to reproduce:**

1. Check message queue on any device. read, or mark as read - any message(s)
2. Check message queue on different device or web app
3.  Messages are displaying as unread

**Additional information:**

Thanks for a great app. I used to use another "multi device" messaging app - if you mark a message as read on one device, then it sync'd to the others almost instantly. I'd be grateful if you could make this (an option?) happen in Pulse too. I can't think of a scenario where you _wouldn't_ want this to happen - after all, it's a single app, with one list of messages - it just happens to be displayed in different places.

**Comment by klinker24** [comment]
Right now, your other devices will mark messages as read when the notification is dismissed, or you reply to that conversation. 

There are other dependencies in the way, preventing me from doing it across devices, immediately. Maybe someday this will be possible though.

**Comment by klinker24** [comment]
These commits should improve this: https://github.com/klinker41/messenger/commit/4e5d075462395311aac527630373cfd22b818dd3 & https://github.com/klinker41/messenger-server/commit/95ff5c037e24c7e016816d31be983b5eac431845
