### ISSUE TITLE
Create scheduled messages to a group

### ISSUE THREAD

**Issue by alextpedro** [klinker-apps/messenger-issues#362]
*Edited by @klinker24*

**Request:**

The web does not currently allow you to schedule messages to a group of contacts. 

![screenshot](http://i.imgur.com/dmkpmOf.png)

**Comment by klinker24** [comment]
Screenshots maybe? Group conversations are supported on the web too.

**Comment by alextpedro** [comment]
I've tested it again and it seems only scheduled messages aren't supported as group. Screenshot:
![screenshot](http://i.imgur.com/dmkpmOf.png)

**Comment by klinker24** [comment]
Yes, group messages on the web aren't support with scheduled messages yet. I will add this for the future.

**Comment by alextpedro** [comment]
Unfortunately, that's kind of a deal breaker and the only reason I wanted the web part of it. Does the extension work the same way?

**Comment by klinker24** [comment]
The only reason for the web was to create scheduled messages? You can always schedule them to a group from android.... The extension works the same way, yes.

**Comment by alextpedro** [comment]
Yes. The idea is to grab a bunch of phone numbers from a CSV file and paste them into the contacts field. These contacts are not always the same so making a group on Android would be an extra, unnecessary step. The point is to streamline the process.

**Comment by klinker24** [comment]
Alright, I have added it to the current milestone for you.

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/messenger-web/commit/54f62b87c9d73c6e9ac7806e4c6816e92ca6aa7a and https://github.com/klinker41/messenger-web/commit/343bf7874ddb73da918a1983273cc57b275e66dc

It may take an hour or so for it to become available on your browser.
