### ISSUE TITLE
MMS received when own number as contact are in separated thread

### ISSUE THREAD

**Issue by Cubox-** [klinker-apps/messenger-issues#364]
**Device with issue:** Nexus 6 running Android Nougat
**Primary device:** Nexus 6 running Android Nougat
**App version:** 2.3.4.1239
**Steps to reproduce:**

1. Add yourself as a contact
2. Receive MMS, it should be separated from the SMS thread (if you have one) and into a new thread between the sender, and your local number contact.
3. If you reply to the message, it will be sent to the original sender, and to your own number. Thread created will be "Original sender, local host, local host"

I have NOT tried reproducing this issue. However, upon deleting the local host contact (my own number), and re-synchronising texts from my mobiles database, the threads are fixed now.

**Comment by Cubox-** [comment]
I will try to reproduce and/or provide screenshots of needed.

**Comment by klinker24** [comment]
I am not able to reproduce this, I always have my number as a local contact and haven't seen this happen before. Is there any more information you can provide? Is it every single time, regardless of the conversation you receive the MMS to?

**Comment by klinker24** [comment]
I made some changes to contact matching in the latest update. Any way you could follow up on this one @Cubox-?

**Comment by Cubox-** [comment]
Hi,

Sorry for the incomplete issue, I was travelling and wanted to send the information I had before forgetting anything.
I will try to reproduce this issue using the latest build and give you all the information needed.

Since I fixed this issue on my phone I am not sure it can be reproduced, I will keep you updated.

**Comment by Cubox-** [comment]
In an attempt to see if my MMS setting for size was correct, I tried to send a photo to myself.
The photo received seems to have two destination numbers, mine two times.
On totally new MMS being received from numbers unknown to Pulse, the issue is still here. Group conversation between the sender, and my own number. This separated the MMS from the main discussion thread.

I will try to see what others text apps see my MMS as. If you need any kind of database dump from my phone, I am willing to do that. I'm rooted on LineageOS.

Screenshots included. My phone number is not censored, I know.

![screenshot_20170628-165454](https://user-images.githubusercontent.com/479129/27644019-ec8af260-5c22-11e7-8a6b-46408bd334cb.png)
![screenshot_20170628-165503](https://user-images.githubusercontent.com/479129/27644143-051c07a6-5c23-11e7-92da-7c5ebf817603.png)
![screenshot_20170628-170549](https://user-images.githubusercontent.com/479129/27644524-1461b796-5c24-11e7-99e3-ac3c8a228bb9.png)
![screenshot_20170628-170458](https://user-images.githubusercontent.com/479129/27644525-147c6366-5c24-11e7-875f-a3547deb3480.png)

**Comment by Cubox-** [comment]
My default SMS app do not have this issue. The problem seems specific to Pulse.
Screenshot of the conversation thread from that app included.
![screenshot_20170628-170839](https://user-images.githubusercontent.com/479129/27644782-aed6d78e-5c24-11e7-9e9e-9d573de0c1d4.png)

**Comment by klinker24** [comment]
Can you pull out the navigation drawer, on the main conversation list for the app, and post a screenshot of your number, which will appear there?

Some carriers do add your own number to a received MMS, but Pulse should be stripping that out. I am not sure why that isn't happening in your case. It seems like Pulse may not have the correct number assigned to you. It reads this number when the app is initially set up, but if your SIM card/phone report something incorrect, there may be a problem.

One more question: what is the situation for the first image, the brown conversation? How does that fit into this conversations? Sorry, not totally clear to me what that is from or how you got that image, and wanted to clarify, since it is definitely different than others.

**Comment by Cubox-** [comment]
Navigation drawer pulled:
![screenshot_20170628-211600](https://user-images.githubusercontent.com/479129/27656039-da1ce244-5c47-11e7-9c58-0f3c4248cc96.png)

The first image, shown as the brown conversation was me sending a picture to my own number. That was to show that the sent message is not in the same "thread" as the received message. Normal behaviour would be as shown in the picture with the default messaging app.

When Pulse tries to strip the user's own number from received MMS, do you check for the exact number, or exact number + possible international variant. (In my case, local is 0 and international is +33 for the prefix in the number)

**Comment by klinker24** [comment]
It should be checking for variants as well, but something is going wrong there I guess. I think I may know the issue, thanks for the help on this one

**Comment by klinker24** [comment]
@Cubox- can you try this version of the app and let me know if this is fixed?

[messenger-2.4.4.74-release.apk.zip](https://github.com/klinker-apps/messenger-issues/files/1110621/messenger-2.4.4.74-release.apk.zip)

**Comment by Cubox-** [comment]
I tried:
`<cubox@Sleipnir>-<~/Downloads> λ adb install -d messenger-2.4.4.74-release.apk
Failed to install messenger-2.4.4.74-release.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package xyz.klinker.messenger signatures do not match the previously installed version; ignoring!]
<cubox@Sleipnir>-<~/Downloads> λ adb install -r messenger-2.4.4.74-release.apk
Failed to install messenger-2.4.4.74-release.apk: Failure [INSTALL_FAILED_VERSION_DOWNGRADE]
`
![screenshot 29 jun 2017 03-20-07](https://user-images.githubusercontent.com/479129/27667284-0e3a16e6-5c7a-11e7-81bf-6939ff10984b.png)

**Comment by klinker24** [comment]
You will probably have to uninstall the current version of the app to install that one

**Comment by Cubox-** [comment]
The issue is indeed fixed with this update!

Thanks a lot for your very fast updates and replies, I'm glad to use your app!

:)

**Comment by Cubox-** [comment]
Just to add for your information, the old "bugged" MMS can be fixed by resyncing the app.

**Comment by klinker24** [comment]
Great, thanks for the help!

**Comment by dengm129** [comment]
#364
