### ISSUE TITLE
Adding timestamp to all messages

### ISSUE THREAD

**Issue by ben-lei** [klinker-apps/messenger-issues#365]
**App version:** 2.4.1.1307
**Request:**
Can there be an option to add a timestamp to all messages, instead of requiring to click on each message to seen when it was received/sent?

**Comment by klinker24** [comment]
Sorry, this is not planned. With this app, I want to avoid making little tiny tweak options and focus on the features and the design. 

I feel like clicking a message is pretty straight-forward and that there isn't all that much reason to show every single timestamp. It will display timestamps if the message is more than 15 mins newer than the previous message
