### ISSUE TITLE
Missing contact names caused by Country code

### ISSUE THREAD

**Issue by david-rocca** [klinker-apps/messenger-issues#367]
**Device with issue:** Nexus 6P running Android 7.0
**Primary device:** Nexus 6P running Android 7.0
**App version:** 2.4.2.1311

**Additional information:**

Contacts that have +1 country code in their number cause the contact name to not show up in the messages list. Instead their phone numbers appear. However, the phone number that is shown in the contact list does not have the +1.

Removing the +1 from the contacts, deleting the message thread, and starting a new thread with them fixes the issue.

**Comment by klinker24** [comment]
Can you try this version and let me know if it works? You could clear the app data to go through the import, and see if those contacts show up correctly. 

I am not able to replicate this issue on my phone.

[messenger-2.4.2.1312-release.apk.zip](https://github.com/klinker-apps/messenger-issues/files/1095660/messenger-2.4.2.1312-release.apk.zip)

**Comment by david-rocca** [comment]
That build fixes the issue.

**Comment by klinker24** [comment]
Thought it might, great. For the next update, that will be included, but it may be feature toggled off for just a bit, there are other complications that come with this though, so it will be a slower rollout, to ensure it works for everyone.

Thanks for the help!
