### ISSUE TITLE
Broken messages on the web page

### ISSUE THREAD

**Issue by roninkenji** [klinker-apps/messenger-issues#372]
**Device with issue:** All web browsers (Firefox, Safari, Chrome)
**Primary device:** Huawei P9 Plus (VIE-L29) on Marshmallow
**App version:** 2.4.2.1311
**Steps to reproduce:**

1. Receive /Save a message 
```
eCoupon Code:
=PWDYH=4LZ9D=
=CZ<B3=XT6<G=
=9P9MW=DDONC=
```
2. Access the message from the web
```
eCoupon Code:
=PWDYH=4LZ9D=
=CZ=9P9MW=DDONC=
```

3. Content Inspection shows this:
```
<br>
"=CZ"
<b3=xt6<g=<br></b3=xt6<g=<br>
=9P9MW=DDONC=
```

**Additional information:**

AFAIK, the &amp; entity is not properly escaped.
 
**Possible solution:**

Escaping / performing entity encoding is probably needed prior to rendering / sending to the browser

**Comment by klinker24** [comment]
I don't think that escaping is the issue, no. The issue is with the `<` character probably. I strip out HTML to prevent xss, something is probably wrong with the regex.

**Comment by roninkenji** [comment]
Well in this particular case, it shows that <BR> was appended to the end correctly. then auto tag closing occurred.
Might be better to actually do entity encoding on ```<``` as that might fix the current issue.

**Comment by klinker24** [comment]
Entity encoding did the trick. Finished with: https://github.com/klinker41/messenger-web/commit/cdaee0fd5495e595770fe0b075f9dc5127c1591b

Thanks for the help!

**Comment by roninkenji** [comment]
Yay! Thanks!
