### ISSUE TITLE
Contacts being mixed up with short numbers.

### ISSUE THREAD

**Issue by nolan-dickey** [klinker-apps/messenger-issues#375]
**Device with issue:** LG G6 on Android 7.0 and Nexus 5X on Android 7.1.2
**Primary device:** LG G6
**App version:** 2.4.3.1314
**Steps to reproduce:**

1. Receive SMS from short number (e.g. 1724 - a number T-Mobile uses to communicate with subscribers)
2. If a contact in your contacts contains that same sequence of numbers anywhere in their phone number, the app identifies the conversation as being with that contact. This prevents you from texting the person in question as their texts show up in that conversation, but you cannot send a message back.

**Possible solution:**

Set a requirement for matching contacts to conversations as having to match the **entire** number, rather than just matching that sequence of numbers within the contact's number.

**Comment by klinker24** [comment]
This shouldn't happen on the latest version, but it won't be able to automatically fix conversations that were previously affected. If you clear the app data, does the problem get fixed?

**Comment by nolan-dickey** [comment]
I just cleared the app data and logged back in. The conversation haven't been fixed. Would I have to delete these conversations for them to be reset?

**Comment by klinker24** [comment]
Oh yes, if you log in to your account, it will download everything from the cloud and you will be in the same place you were before. 

Deleting those conversations would reset them, yes. Sorry should have been clearer. Was it fixed before you logged in to the account though?

**Comment by nolan-dickey** [comment]
Ah - I see. That would make sense. Actually before I logged in the app said it was optimizing and importing the conversations (not from my account), and the conversations showed up just the same. I'll delete the conversations and see if it works correctly.

**Comment by klinker24** [comment]
Just the same, as in they were still combined?

**Comment by nolan-dickey** [comment]
I just deleted one of my conversations and when I opened a new conversation with that number it identified it as the same contact again.

**Comment by nolan-dickey** [comment]
And yes - the conversations were still combined before logging in.

**Comment by klinker24** [comment]
Can you please send me an email with a bit more information? 

I don't want you posting phone numbers here, but if you could send me an email with the tmobile number, and the person you are trying to text, and walk me through the steps of what you are doing, that would be really helpful. I think I am confused somewhere here.

**Comment by klinker24** [comment]
Closed with: https://github.com/klinker41/messenger/commit/3c5ada70beb1e88fbf4cb8f0e6f942559207e7c9
