### ISSUE TITLE
Syncing Issues

### ISSUE THREAD

**Issue by randokando** [klinker-apps/messenger-issues#376]
**Device with issue:** Macbook Pro (2015), macOS Sierra (10.12.5), Chrome: Version 59.0.3071.115 (Official Build) (64-bit)
**Primary device:** Nexus 5, Android 7.1.2
**App version:** 2.4.3.1314

**Additional information:**
Installed on phone.  
Used website app.  

Had prior issues with contacts Sync'ing.  
Luke said to resync account.  
Fixed issue.  

When sending issues from website,  
new messages do not appear on primary phone or arrive to recipient.
Tried 'Refresh Account'. No luck.  
Tried 'Resync Messages'.  No luck.  

On phone: device ID = X.
On website: 0 devices.

Tried switching to Chrome app.  No change in behavior, but:  

On phone: device ID = X.
On chromeapp: 1 devices: chrome app ID: Y.
On website: 1 devices: chrome app ID: Y.

Should website have ID?
Should website or chromeapp list phone ID?

**Comment by klinker24** [comment]
No the web won't have an id. If your phone doesn't show up on that devices page, then messages won't get sent through it. I would suggest just clearing the app data on the phone and logging in again, to see if it shows up then. Something must have gone wrong with all your resync and refresh attempts.

**Comment by randokando** [comment]
Cleared data; started app.  
Old SMSs appeared immediately.  

Clicked "Text from any device".  
Notification appears: "Old subscription found. Welcome back!"  
Login GUI still appears.  

Went back, tried again:  
Clicked "Text from any device".  
Notification appears: "Old subscription found. Welcome back!"  
Login GUI still appears.  

Clicked Login. Logged in.  
Downloading and decrypting media notification window appears.  
Disappears to pulldown notification instead.

Recent texts sent from app appear, stuck in "sending" status.  
Older texts permanently gone.

**Comment by randokando** [comment]
Also, all MMS have corrupted.

**Comment by klinker24** [comment]
When you log in, it downloads everything from the web to your device, so that is working as expected. It won't go back and send messages that were in the sending state.

Can you tell me if that solved the issue of not being able to send from the web?

**Comment by randokando** [comment]
Updated in prior comment.

**Comment by klinker24** [comment]
No problem, feel free to send me an email if you run in to anything else
