### ISSUE TITLE
On/off switch design mono moronia

### ISSUE THREAD

**Issue by midenok** [klinker-apps/messenger-issues#377]
What does mean left position and right position??! Fucking black-and-white mania goes more and more crazy!

**Comment by klinker24** [comment]
Sorry, what are you asking about here? I don't understand

**Comment by klinker24** [comment]
Going to close this with not enough information and lack of response

**Comment by midenok** [comment]
There is no clear visual and semantic distinction between light gray and white. Which one means 'On', which one means 'Off'? I can say *green* is On, I can say *red* is Off. I can easily distinguish between green and read. It is not hard to distinguish even blue and gray. But it's hard to distinguish light gray and white. Either visual designers are gone totally stupid these days or it is a sign to the nearby world's end. Or both. :D
