### ISSUE TITLE
Moto Display showing "read" parts of conversation

### ISSUE THREAD

**Issue by partounian** [klinker-apps/messenger-issues#378]
- [X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [X] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** Moto G5 Plus on Android 7.0
**Primary device:** See above
**App version:** 2.4.4.1328
**Steps to reproduce:**
1. Get text message
2. Read/reply
3. Get more text
4. Now when moto display is on it still shows read/replyed-to messages

**Additional information:**
This device is completely stock and running on the newest OTA at the time.

**Comment by klinker24** [comment]
By default, Android Nougat uses `MessagingStyle` notifications, which display history. I cannot control how Moto displays those notifications, but you can turn off the history in notifications, through settings
