### ISSUE TITLE
Message list get shown over the conversation list

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#38]
**Device with issue:** Unknown, reported to Google+
**App version:** 1.1.205
**Report Details:** https://plus.google.com/u/0/+ConnorB123/posts/8uGw9KW7rzY
**Steps to reproduce:**

_I have been unable to reproduce myself, but could occur if a device is slower and need more time to load the message list?_

1. Quickly touch a conversation, then scroll up or down
2. The message list will appear on top of the conversation list.

**Possible solution:**

Perhaps we could add a background to the list view? Seems to be transparent and depend on the fragments background, although I am not sure about it.

**Comment by klinker41** [comment]
Adding a background would provide overdraw issues I think.

**Comment by klinker24** [comment]
I am kind of expecting that some of my smoothness changes today to opening a conversation can mark this as done. Since there won't be near the latency, there shouldn't be enough time to "swipe" the conversation list underneath, it should open instantly, and wait on the message list if needed.

Will monitor this one, but I think it should be fixed.

**Comment by klinker24** [comment]
This has been fixed over the following commits:

https://github.com/klinker41/messenger/commit/a9c0be48740590fb6bdb9bffa673f7004235a59a
https://github.com/klinker41/messenger/commit/27d3c9c1096b7137a411b3395e26c40cfe079272

**Comment by klinker41** [comment]
I made a few changes that should also help this when the user clicks one conversation and then quickly clicks another before the animation finishes: https://github.com/klinker41/messenger/commit/f688e6a8e4e50059969b3e305c5869b993ec5d59
