### ISSUE TITLE
Receiving duplicate MMS much later

### ISSUE THREAD

**Issue by ppoutine** [klinker-apps/messenger-issues#380]
- [ x ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [  ] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** Samsung Galaxy S7 & web messenger
**Primary device:** Samsung Galaxy S7, Android 7.0
**App version:** 2.4.4.1328

**Additional information:**

Since switching to Pulse a couple months ago, I have been getting duplicate / repeated MMS messages.

1. I receive an MMS / picture message

2. One or two days later, I receive another copy of the same MMS

This happens with most MMS that I receive. It only happens with MMS, never SMS.

**Possible solution:**

Is there any kind of logging I can do to help troubleshoot this? I'm at a loss.

Thanks

**Comment by klinker24** [comment]
Thanks for the report, we are going to tag all MMS issues in this thread #101.

I am closing this one, it has been linked in that thread.
