### ISSUE TITLE
Cannot send messages and push notifications not working

### ISSUE THREAD

**Issue by jdrosick** [klinker-apps/messenger-issues#381]
I am currently running a beta version of Android O and the pulse app does nothing when you click send on messages, so you literally cannot text.  And if you receive a text message, there is no notification

**Comment by klinker24** [comment]
Push notification are much different than notifications for receiving a text message. Is it just the notification for receiving messages that you are not getting? Push notifications would be device to device communication.

Are you talking about the phone app for the first question? Any detail you could give on this would be great.

**Comment by jdrosick** [comment]
It's just notifications for receiving the text that are not working.  So,
not push notifications.  My bad.

**Comment by klinker24** [comment]
I am guessing that you aren't on the latest beta for Android O. If you have an app targeting SDK 26 like Pulse, on beta 2, notifications won't be shown, regardless of your notification channel settings. There was some kind of disconnect there that must have slipped past Google. I am fairly confident that is the notification issue.

Can you tell me more about that other issue though? I don't really understand what you mean

**Comment by jdrosick** [comment]
Yeah, I can check what I am on for Android O, as I have a google pixel xl
so I assumed it just pushed the release to me.  On the app, when I hit the
triangle to send a message, nothing happens.  Literally, the message just
stays as a draft and does not send.

**Comment by klinker24** [comment]
Ok. Update the phone, then let me know if that changes as well.

**Comment by jdrosick** [comment]
Worked. Updating the beta was all it needed.  Thank you!

**Comment by klinker24** [comment]
Great!
