### ISSUE TITLE
Bitmoji support

### ISSUE THREAD

**Issue by rnhurt** [klinker-apps/messenger-issues#382]
**Chrome Extension Version**: 1.8.6

**Feature Request Details**
It would be nice to be able to insert [Bitmoji](https://www.bitmoji.com) (or similar services) into my messages.  Currently, I have to save my Bitmoji image to the computer and then drag it into my Pulse message but it would be handy to be able to just directly select a Bitmoji from within Pulse.  I'm thinking this would be similar to how the Android version of Pulse allows you to "attach" different types of media (pictures, videos, animated Gifs, etc.)

**Comment by klinker41** [comment]
I feel like if you have their android app installed, then you can probably share images to other apps from it. Try it out by pressing the attach button in Pulse and tapping the first tile. This should open an image picker up and you'll be able to pick which app you want to take the image from.

**Comment by klinker24** [comment]
You can copy any images and just do a Ctrl+v to paste them into the compose screen. Doesn't that work for this case? No need to save anything.

**Comment by rnhurt** [comment]
Well, shut my mouth and cover me in biscuits.  You **can** cut and paste images from Bitmoji to Pulse!

![bitmoji](https://render.bitstrips.com/v2/cpanel/9073886-268002383_2-s1-v1.png?transparent=1&palette=1&width=246)
