### ISSUE TITLE
Displaying the Timestamp for Messages within a conversation via the web interface

### ISSUE THREAD

**Issue by jrmarsh** [klinker-apps/messenger-issues#383]
**Device with issue:** Lenovo X220 running Windows 10 Pro Version 1703 and Chrome Version 59.0.3071.115 (Official Build) (64-bit)
**Primary device:** OnePlus 3T running Android 7.1.1
**App version:** 2.4.5.1341

On my phone, sometimes it seems that the timestamps on some messages in a conversation appear automatically but other times they don't.  I don't understand the logic behind when they appear and when they don't but regardless this isn't a problem in that the timestamp visibility can be toggled on and off on a per message basis by tapping on the message.  The problem arises in that when I load a conversation on my computer in Chrome it seems to show or not show the timestamps based on the default state (the logic behind which I haven't been able to figure out).  Hence the timestamps on some messages in the conversation are visible while others are not.  However unlike the phone app, I can't toggle the timestamp by clicking on the message on the web.  

In fact, I can find a way to display the timestamp for a particular message within a conversation on the web if it is not displayed by default.  As it is typically very important to me to be able to check the timestamp of a particular message this drastically decreases the usability of the web interface and I find that even though I'm sitting in front of my computer I need to dig out my phone to pull up the conversation there to check the message timestamps.  

![screenshot](https://user-images.githubusercontent.com/30158609/28184741-cc9f666a-67d1-11e7-8e70-c62947b5bd47.jpg)

**Comment by klinker24** [comment]
There isn't a way to turn them all on for the web. This is a feature request.

If the messages are more than 15 mins apart, it will display the timestamp on both the web and Android.

**Comment by Serubin** [comment]
Timestamps could be easily added as "title text." I intend to work this into my client over the weekend.

**Comment by klinker24** [comment]
As @Serubin said, easy to add as title text. I have done that, here: https://github.com/klinker41/messenger-web/commit/fa98b258bee9b7a143b2fbba0b1551bbadf97ff0

You can now hover over any message to get the timestamp.
