### ISSUE TITLE
Chrome App Scrolls to top after sending

### ISSUE THREAD

**Issue by brentluna** [klinker-apps/messenger-issues#384]
Device: MacBook Pro 2016 10.11
Primary: Pixel XL 7.1.2

When sending a message via enter key or the submit button it Scrolls to top. Of the conversation thread. Feel like this should scroll to bottom to put most recent send in view

**Comment by klinker24** [comment]
Hmm, I am not able to replicate this at all. It should definitely scroll to the bottom. Is this a new thing? What browser are you using? Does it happen every time?

Any info would be good here.

**Comment by brentluna** [comment]
Yeah, thought it was weird. I checked the source files and looks like it's calling windows #scrollToBottom. It's chrome canary, I think version 60. I'll play around with it some more and see if I can get any more info 

_Sent from my Google Pixel XL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Serubin** [comment]
This line (thread.js:520) is likely part of the issue.

```
if (!(($("#message-list").height() - $(window).height() - 400) > $("#message-list-wrapper").scrollTop()) || force_jump_to_bottom) {
     scrollToBottom()
    return
}
```

This would be a partial fix: https://github.com/Serubin/PulseClient/blob/devel/resources/js/Thread.js#L617

And also this should work as a fairly universal scrollToBottom method.
https://github.com/Serubin/PulseClient/blob/devel/resources/js/Helper.js#L202

`if (typeof $list != 'undefined' && typeof $cont != 'undefined') {` seems to return false when it shouldn't.

**Comment by klinker24** [comment]
His issue is that it is scrolling to the top, not the bottom, so I don't think that's the problem.

**Comment by Serubin** [comment]
I was having similar issues - I think I've fixed it in my fork with the above. Could be wrong. I'll get a test version up and @brentluna can give it a try.

**Comment by brentluna** [comment]
The theme thought is interesting, as when I went to try and play around with it last night I wasn't having the issue, however the theme did change to night theme, where I was having the issue on the day theme. I'm almost at work and will check that snippet. I see it's calling scrollTop but not sure what element it's calling it on

_Sent from my Google Pixel XL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by klinker24** [comment]
I actually had pushed some changes last night for it. So I imagine that it was fixed, actually. Day vs night wouldn't affect this at all

@Serubin i use the window's [scrollTo](https://www.w3schools.com/jsref/met_win_scrollto.asp) method, which is more universal:

```javascript
window.scrollTo(0, document.body.scrollHeight);
```

**Comment by Serubin** [comment]
But not nearly as pretty as `animate` ;)

Jquery should implement the window.scrollTo behind the scenes so it shouldn't matter either way.

**Comment by brentluna** [comment]
Playing around with it some more and it seems to be working  fine now.
