### ISSUE TITLE
MMS delivery reports 

### ISSUE THREAD

**Issue by krwilson8** [klinker-apps/messenger-issues#385]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [x] If this is an issue, and not a request, I have verified that this is something that is reproducible

MMS messages do not have delivered reports. They appear to be working just fine for SMS. I'm close to switching back to my old messaging app since some pictures sent to my wife didn't actually get sent until I restarted my phone and I had no idea. I'm not sure if that was a glitch with my phone or another issue regarding Pulse, but a delivery receipt would certainly help. 

**Device with issue:** Pixel XL on Android 7.1.2
**Primary device:** Pixel XL on Android 7.1.2
**App version:** 2.4.5.1341

**Steps to reproduce:**

1. Send an MMS
2. Verify no delivered receipt

**Comment by klinker24** [comment]
We track all MMS issues in this thread #101. I am going to close this one, it is linked over there now
