### ISSUE TITLE
Messages Arrive Out of Order

### ISSUE THREAD

**Issue by mostlychris** [klinker-apps/messenger-issues#386]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [x] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** Windows 10 on Mac Hardware running Chrome Version 58.0.3029.110 (64-bit)
**Primary device:** Pixel Android Version 7.1.2
**App version:** 2.4.5.1341
**Steps to reproduce:**

1. Have a conversation
2. Send a message using web app.
3. Recipient replies but message doesn't show up until sending another message or a random amount of time has elapsed.

**Comment by klinker24** [comment]
Pulse checks every twenty seconds for new messages. At this time, that is how it has to work. There are other issues open about making this instant

**Comment by mostlychris** [comment]
Thanks for the quick response. Apologies for not finding the other related issues.
