### ISSUE TITLE
Conversation list screen partially disappears

### ISSUE THREAD

**Issue by edwardcnc** [klinker-apps/messenger-issues#388]
When returning to the conversation list after sending a message, sometimes the screen space previously occupied by the keyboard is completely blank and non responsive. Messages cut off there as if the keyboard were still being displayed. 

**Device with issue:** Huawei Nexus 6P, running Android 7.1.2 
**Primary device:** Huawei Nexus 6P, running Android 7.1.2 
**App version:** 2.4.6.1355
**Steps to reproduce:**

(this only happens occasionally, it's inconsistent) 

1. Go into a conversation 
2. Send a message 
3. Return to the conversation list

**Additional information:**

Like I said, this does not happen every time, I can't seem to find a definite trigger, but it does happen fairly often. It also doesn't seem to ever happen when I go into a conversation to just check it and return to the conversation list without sending a new message. But if I send a message, I'd say about 25% of the time, the blank section appears. 

To restore the area, I have to enter another conversation or screen, like the Global settings menu, but, it has to be a screen with something displayed down in the lower half (where the keyboard would pop up). For example, Global settings will do the trick, but Advanced features won't because that menu only has 3 items at the top of the screen, so it's like the bottom portion of the screen isn't getting refreshed.

**Comment by klinker24** [comment]
You can back out of the app to fix it too. I don't know why this happens at this point. It seems to happen more often with some keyboards than others as well.

**Comment by klinker24** [comment]
This should be fixed with: https://github.com/klinker41/messenger/commit/a6418ca3986eaa188c384db6845dc32f68c822a5

It will roll out with the next release. Please follow up if you get the chance to confirm
