### ISSUE TITLE
Default new conversation color seems to be the unreadable yellow

### ISSUE THREAD

**Issue by wizard7926** [klinker-apps/messenger-issues#389]
Not really sure where else to put this, but the default color for new conversations seems to be bright yellow, which is very difficult to read, especially the white text on yellow. I don't want to have to manually change each new conversation scheme. Is there a way to have a darker default new conversation color?

**Comment by klinker24** [comment]
The default color is just randomly picked from the material design colors: https://material.io/guidelines/style/color.html

Not every new conversation will get set to yellow, but yes, some of them could

**Comment by klinker41** [comment]
Luke can correct me on this, but conversations are assigned a random material design color scheme when you create them if the contact does not have a profile image we can extract a main color from. This can then change this in that conversation's settings.

Also, please use the provided template next time, it really does help us to keep things straight.

**Comment by klinker24** [comment]
Actually I don't look at the main color in profile pictures anymore, because so many of them just looked terrible and gross. All the colors are randomized based on the material design color scheme now
