### ISSUE TITLE
 Application closed in background

### ISSUE THREAD

**Issue by Oliv4945** [klinker-apps/messenger-issues#390]
**Primary device:** Xiaomi Mi4c on Android 5.1.1 LMY47V, MIUI 7.3"
**App version:** 2.4.5.1341
**Steps to reproduce:**

1. Open the app, use it
2. Use another app or lock the phone
3. After 5 to 15 minutes, if a SMS is received it will not be forwarded to the website nor any apps. Also, if I send an SMS from the website it never reaches my phone.
4. When looking to "running apps" in Android menu Pulse does not appears, while using the key to switch between apps (task manager) shows it opened.

I tried to "lock" the application in task manager but it did not helped, also I have a lot of free RAM.
Any other data that can help you to troubleshot it ? It seems to be a really nice app but I can not use it i this state :/

Thank you

**Comment by klinker24** [comment]
Pulse doesn't need to appear there, it will wake up when necessary. It sounds like you disabled background data for the app or it is restricted.

When sending from the web, your phone will get a push notification and that wakes it up. If background data is restricted, you won't get that push notification.

When receiving a message, the app wakes up and POSTs to the backend, if it is able to access the data.

I have never heard of anyone having an issue like this, unless they were rooted, or restricting background usage.

**Comment by Oliv4945** [comment]
F**k I never saw this parameter but it exists... I will close the issue in two days if it works, thank you !!

For future reference, it is located in `Settings >> Additional Settings >> Battery >> Manager Apps Battery Usage >> Choose Apps >> Pulse>> Custom >> Background Network`.

By the way, why the application needs localization authorization ?

**Comment by klinker24** [comment]
Because you can share your location

**Comment by Oliv4945** [comment]
Hi, it was not that: today I still have the issue while background data are allowed to the app, and all memory/power consumption optimizations are disabled.

>Because you can share your location

Ok, thanks

**Comment by klinker24** [comment]
There is something on your phone preventing background usage, that is the issue here, but I don't have your device, so I won't be able to tell you where to look, unfortunately

**Comment by Oliv4945** [comment]
>There is something on your phone preventing background usage, that is the issue here

If you say so, but I disabled it following you first message, and all other applications using data in background have no troubles.
Moreover, after more tests and from time to time, sending an sms from website does not work even if the phone is not locked and the application is opened.

In the logcat I can see the following lines, can it be relevant ?
```
07-21 12:23:14.602 I/ActivityManager( 1039): Process xyz.klinker.messenger (pid 12997) has died
07-21 12:23:14.602 I/ActivityManager( 1039): Process xyz.klinker.messenger (pid 12997) has died and do not allow restart
```

**Comment by klinker24** [comment]
No, those lines wouldn't be relevant. That is the `ActivityManager`. These work off services that will be woken up in the background.

**Comment by klinker24** [comment]
Are you still having issues around this? The past few versions have made numerous changes to how the background communication works. It still works off of the same system, but it may have an effect on your issues.

**Comment by Oliv4945** [comment]
Hi I will give it another try. Just for you information Pushbullet is working with same parameters on my phone without any issue.
You labeled the issue "Not enough information", what do you need ?

**Comment by klinker24** [comment]
Something on your phone is preventing it from running in the background. I don't know the right questions to ask, sorry. Android has so many options, configurations, and apps available.

**Comment by klinker24** [comment]
I am going to close this one. There simply isn't enough information and I do not have a whole lot of control over the reception of push notifications in the background. 

I did make some changes this morning as to how the push notification receiver works. It no longer starts a separate service. Perhaps that is what was causing this issue, but I don't know that that is likely: https://github.com/klinker41/messenger/commit/8aeedc278668b16e5ee095b2d78e6c0e66ef8101

**Comment by Oliv4945** [comment]
Sorry my phone died so I did not test last version, nevertheless all other apps requiring background data worked.
By the way your link is not working, it seems that the `messenger` repository is not created

**Comment by klinker24** [comment]
The public doesn't have access to the repo, it is private. That is a note for me.
