### ISSUE TITLE
Hiding sensitive notification content still shows contact names

### ISSUE THREAD

**Issue by jimmyfnugent** [klinker-apps/messenger-issues#391]
**Device with issue:** Pixel on Android 7.1.2
**App version:** 2.4.6.1355
**Steps to reproduce:**

1. Go to system settings -> Device -> Notifications -> gear icon in top right.
2. Set "On the lock screen" to "Hide sensitive notification content".
3. Receive SMS messages from your favorite friends.
4. Note that the lockscreen shows your friends' names, e.g. "2 new conversations / Arthur Dent, Trillian Astra".

Other messaging apps (e.g. Hangouts, Facebook Messenger, Android Messages) don't show any names with this setting on, and I think that would be expected behavior.

**Comment by klinker24** [comment]
Can you post a screenshot? It shouldn't show names, no.

**Comment by jimmyfnugent** [comment]
Looks like it happens when there are unread messages from more than one person (or, at least, it happens with 2 people).

![screenshot_20170724-224941](https://user-images.githubusercontent.com/10333544/28553594-b9ee75fc-70c2-11e7-814b-e35d9449456d.png)

**Comment by klinker24** [comment]
Fixed with: https://github.com/klinker41/messenger/commit/9ba7544cf94ff64778a9034ad7e10e1e3ea80f1e

I will release it in the next beta version of the app. Maybe later today, not sure. It seems to be working fine for me, but if you could follow up, that would be great.
