### ISSUE TITLE
New message appears in conversation list on web but not in conversation view until force refresh

### ISSUE THREAD

**Issue by anstosa** [klinker-apps/messenger-issues#395]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [x] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** Google Chrome (app and web)
**Primary device:** Pixel XL, Android 8.0.0, Patch level July 5
**App version:** 2.4.7.1370
**Steps to reproduce:**

1. Open a conversation on the Chrome app
2. Receive a text in that conversation
3. Observe that the conversation is updated in the conversation list sidebar but the new message does not appear in the current view until you click to a new conversation and back again

**Comment by klinker24** [comment]
Will be solved with #76. I am working on it now, actually.
