### ISSUE TITLE
Messages sent from web are never actually sent

### ISSUE THREAD

**Issue by anstosa** [klinker-apps/messenger-issues#396]
**Device with issue:** Google Chrome (app and web)
**Primary device:** Pixel XL, Android 8.0.0, Patch level July 5
**App version:** 2.4.7.1370
**Steps to reproduce:**

1. Open a conversation on the Chrome app
2. Send a message
3. Observe that the recipient does not receive the message but it looks like it was sent
4. Observe that refreshing the page and logging out/in does not clear the message or cause it to send
5. Send the same message from the Android app
6. Observe that the recipient now receives the message
7. Observe that the message is now duplicated on the web but not on the Android app

**Comment by klinker24** [comment]
Try opening the "My Account" section on the Android phone app and using "refresh account".

**Comment by anstosa** [comment]
Ah! That solved it (however some random historic messages are now blank chat bubbles on web)

**Comment by klinker24** [comment]
They are likely MMS. The refresh account option will only reupload the latest 20 MMS messages

**Comment by anstosa** [comment]
Are some messages classified as MMS even when they don't have to be? The blanks that I noticed immediately are all well within the last 20 messages sent or received globally and all of them are less than 10 words with no emoji, pictures, or any other media attached.
