### ISSUE TITLE
Messages not appearing on second device

### ISSUE THREAD

**Issue by ReflectiveBrands** [klinker-apps/messenger-issues#398]
**Device with issue:** Samsung Tab S3 with 4G LTE on Android 7.0
**Primary device:** Samsung Note 5 on Android 7.0
**App version:**  Tab S3 and Note 5 running 2.4.6.1355
**Steps to reproduce:**

1. Running conversation with multiple text messages being exchanged at fast pace.
2. Both tablet and phone being used back and forth, but mainly using Tablet to send messages.

Result:
Random messages are not appearing on the tablet(secondary device), breaking the logic of the conversation and causing confusion. When I go back to check the thread on the on phone(primary device) the missing messages are there. Seems like rapid conversations causes missed messages. This has happened enough times to me now that I create a Github account just to report it!

**Additional information:**

I am in love with this app. This is the only issue I experience on a regular basis.

**Comment by klinker24** [comment]
Today's update would have addressed problems like this. If you could try it out for awhile, it would be nice to hear those results.

Do the missing messages appear on the web client?

**Comment by ReflectiveBrands** [comment]
Been out of town, so pardon my late reply. I haven't noticed the error recently, yet don't feel like I have been in the same situation yet. I will continue to look for the error and report back in about a week. 

As for web client, before today I have never used the web client. At this point I don't remember what the missing messages were.

**Comment by klinker24** [comment]
I am going to go ahead and close this out. Please feel free to come back and post if you start seeing issues.
