### ISSUE TITLE
Sending multiple pictures shows them as all the same locally

### ISSUE THREAD

**Issue by uudruid74** [klinker-apps/messenger-issues#399]
**Device with issue:** OnePlus One w/HyperUnicorns(AEX based), OnePlus 3T w/VertexOS(AOSP), Remix OS (android x86)
**Primary device:** Oneplus 3T
**App version:** 2.4.7.1376 (and earlier)
**Steps to reproduce:**

1. Open conversation
2. Tap paperclip
3. Select first image
4. Tap paperclip
5. Select second image
6. Tap Send

**Additional information:**
After the above, everything looks good.  Wait until both files finish sending and suddenly one of the two will change so that it matches the other.  Files are sent correctly, web display is correct, local display is wrong only after send.

**Comment by klinker24** [comment]
Is this repeatable for you? I am not able to make it happen.

**Comment by uudruid74** [comment]
yeah, happens almost every time.  Its hard to say if it's EVERY time since I don't usually send multiple pics at once.

Would a log help?

On Jul 30, 2017, Luke Klinker <notifications@github.com> wrote:
>Is this repeatable for you? I am not able to make it happen.

-- Sent with K-@ Mail - the evolution of emailing.

**Comment by klinker24** [comment]
No, not in this case. Thanks for the report, I will explore this further.

**Comment by timfacchin** [comment]
I've had this exact issue for some time as well.  Almost every time I send multiple pics. Not sure if recipient sees correct images or not at this point. I can send screenshots if needed.

**Comment by timfacchin** [comment]
Checked with recipient. They see the correct photos. I see the same photo twice.

**Comment by klinker24** [comment]
I made changes for this, here: https://github.com/klinker41/messenger/commit/a62e23e92285dcb1f2bbdb7967ab7778a708f5f9

They will be released in the next beta version for `2.5.5`, probably tomorrow. If someone could follow up, that would be helpful.

**Comment by timfacchin** [comment]
Thanks for looking into the issue. Just got the update and gave it a shot. Looks like you got it. Thanks again!

**Comment by timfacchin** [comment]
Bad news. Just happened again. Two pics. While sending, they show differently. After sent, they appear the same.

**Comment by timfacchin** [comment]
Bad news. Just happened again. Two pics. While sending, they show differently. After sent, they appear the same.

**Comment by klinker24** [comment]
Ok thanks.

**Comment by klinker24** [comment]
Ok, fixed for real with this commit: https://github.com/klinker41/messenger/commit/d5d736362ebbb0890857aaea5c72cc5fe1c463bc
