### ISSUE TITLE
Android Wear/TV app support

### ISSUE THREAD

**Issue by klinker41** [klinker-apps/messenger-issues#4]
**Device with issue:** LG Watch Urbane
**Primary device:** Nexus 6P running Android 7.0
**App version:** 1.0.180

**Information:**

Currently, we support replying to messages through your voice on android wear with a notification button. Like EvolveSMS, we should have a fully-fledged Android Wear app that supports messaging through viewing conversations and your voice.

**Comment by klinker41** [comment]
This wear app should be implemented as a standalone app, since android wear now supports networking directly. We can grab the account id and password hash/salt from the device so that we don't have to log in on that device.

I also personally would like an Android tv app that I can view conversations on, send messages with voice and see notifications (like my old pushbullet app did).

**Comment by klinker41** [comment]
* [ ] add `activate` table on server with `activation_code`, `account_id`, and `expiration_time`
* [ ] add an endpoint on server `activate#add` that accepts an account id and activation code and writes a new entry to the `activate` table with an expiration time of 5 minutes from now
* [ ] add an endpoint on server `activate#check` that accepts an activation code and checks whether there is one stored in the database or not. If so and we are before the expiration time, return the account info. Delete the activate entry after processing
* [ ] add UI to web client at `https://messenger.klinkerapps.com/activate.html` that checks if a user is logged in (if not, redirect to the login page) and then allows them to enter an activation code and link their account id to it for the next 5 minutes
* [ ] add activity to `api_implementation` android model that displays an activation code and checks the `activate#check` server endpoint every 5 seconds for a status update. If not found in 5 minutes, quit out. If found, save the account info, add the device to the account and make the initial download of messages and media
* [ ] add an android tv layout
* [ ] add an android wear layout

**Comment by klinker41** [comment]
One thing to note: standalone wear apps are not supported until Android Wear 2.0, which hasn't officially launched yet. It is scheduled to launch this summer, but hasn't been heard of for quite a while. 

I think that it would still be fine to just target these devices, it wouldn't be worth the time to implement the deprecated bind listener APIs that we've used in the past for just a little bit of benefit before the new update rolls out. @klinker24 thoughts?

**Comment by klinker24** [comment]
Yeah I think that is just fine.

**Comment by klinker41** [comment]
Documentation on android wear 2.0: https://developer.android.com/wear/preview/api-overview.html

There are some nice pictures on that page of what a potential messaging app could look like, I think it would be a good place to look for designing our wear app.

At the bottom, it talks about standalone apks:

```
For delivery to a watch, an Android Wear app is currently embedded in its corresponding phone app. This delivery method can result in an increased download size for users, regardless of whether they have an Android Wear device.

With standalone devices, the Multi-APK delivery method will be used. Developers will have the ability to release Android Wear apps independently of the corresponding phone apps. Please stay tuned for more information about this change.
```

So no news yet on how to implement this, but I'm hoping that it is similar to android tv where you can simply add a new activity to your app and declare it as a wearable activity in the manifest so that it only shows on the phone. That way all three apps can be bundled together and we won't have to make separate modules for the data source and things like that.

**Comment by klinker41** [comment]
added the activate table with https://github.com/klinker41/messenger-server/commit/22c09def62d82caea950af7a81e0f2935eb7667b

added the server endpoints at `/activate` and `/activate/add` with https://github.com/klinker41/messenger-server/commit/dfdb1428ce61231d1d3d75f67830e3ef348f2449

**Comment by klinker41** [comment]
added the web ui with https://github.com/klinker41/messenger-web/commit/f73aba86ce5efb61603bcaae2b6b88762dc9c073

![download](https://cloud.githubusercontent.com/assets/4501322/18570430/9ecb5f06-7b5e-11e6-86af-eb1d5988fd3d.png)

**Comment by klinker41** [comment]
Added an activation activity that checks our server every 5 seconds until it sees that the user has activated the account on the site, or it times out after 5 minutes.

![device-2016-09-15-211645](https://cloud.githubusercontent.com/assets/4501322/18575205/ce88b362-7b89-11e6-8f90-86c92683c0a7.png)

Next I need to add a password confirmation page since we directly use the password for encryption and have no way of providing it from the server. I'll have to then download the devices for the account and try and decrypt them with the provided password. If it works successfully, then I'll add this device as a new device to the account and start syncing. If it doesn't work, then I'll tell them the password is incorrect and they need to enter it again.

**Comment by klinker41** [comment]
More work on the TV app this evening, branched it off to https://github.com/klinker41/messenger/tree/activate_screen

Some screenshots:

![device-2016-09-16-001754](https://cloud.githubusercontent.com/assets/4501322/18578276/ebedb8ac-7ba3-11e6-9502-5a5c5e00b429.png)
![device-2016-09-16-001827](https://cloud.githubusercontent.com/assets/4501322/18578281/ee298fa6-7ba3-11e6-9226-07072d4c3acc.png)
![device-2016-09-16-001845](https://cloud.githubusercontent.com/assets/4501322/18578285/f1a02ed8-7ba3-11e6-9ace-13e8d820916b.png)
![device-2016-09-16-001937](https://cloud.githubusercontent.com/assets/4501322/18578286/f3afa546-7ba3-11e6-87e2-c27bbff33923.png)
![device-2016-09-16-002333](https://cloud.githubusercontent.com/assets/4501322/18578287/f4e31826-7ba3-11e6-843e-df6cd0367b0e.png)

**Comment by klinker41** [comment]
Marking the TV portion of this completed now, merged into master. I improved the navigation slightly by highlighting the items that you are on. I also implemented notifications that should show in the bottom right corner of the screen. However, Android TV no longer allows the permissions for this to be displayed, so there isn't a way to get it to work :(

Some information on this issue: http://mattiesworld.gotdns.org/weblog/2016/04/26/android-tv-marshmallow-and-overlay-permission/

**Comment by klinker24** [comment]
I started the Android Wear app.

- [x] get login working
- [x] get password validation working
- [x] get initial download working
- [ ] display conversation list
- [ ] display message list when conversation is clicked
- [ ] reply to conversations
- [ ] start new conversations

This is a stand-alone app. So fully compliant with Android Wear 2.0 and will only be available on Android Wear 2.0. When I added it, I think it is still including it in the android app though, because the build size for the `apk` increased dramatically (4 mb -> 11 mb). I need to fix that

**Comment by klinker41** [comment]
Are you recreating a lot of the logic or just moving it over into a shared module? Also, my understanding is that this apk should be completely separate from the current one and uploaded separately, not included in it.

**Comment by klinker24** [comment]
Yes, I am pulling it out, not recreating anything (except for the initial load activity, which took some changes and I couldn't think of a good way to pull it out). 

And yes, it should be completely separate, I don't think i need the `wearApp project(':wear') ` within the `build.gradle` for the app. The instructions weren't very clear on this, so testing the build now, without that in the app's `build.gradle`.

**Comment by klinker24** [comment]
Yep, removing the `wearApp project(':wear')` still builds everything correctly and the APK of the app is back down to `4.80 MB`, so that isn't required to build the wear app, only including it in the phone APK.

**Comment by klinker24** [comment]
So close to done with the wearable app. Just need to implement replies.

It does everything basically the same way as the normal android app:
- Theming
- Day/Night mode
- Round bubbles
- Article viewer
- Conversation list sections
- youtube previews (it can't play them, due to android wear restriction)
- Automatic refreshes with the broadcast receivers
- Notification replies

Some things that it could implement in the future:
- More actions on the conversations. Right now it is just reply. Could do delete and archive to start with
- Compose new conversations

Things that aren't possible, right now, due to android wear restrictions:
- FCM data store, so no MMS images at this time

Screenshots:
![conversation list](https://cloud.githubusercontent.com/assets/4874287/22614790/15448e52-ea4d-11e6-8897-758f9fbde596.png)
![message list](https://cloud.githubusercontent.com/assets/4874287/22614792/17e20c98-ea4d-11e6-9f7f-998052284bdc.png)
![notification](https://cloud.githubusercontent.com/assets/4874287/22614794/1a2631c8-ea4d-11e6-97b8-632c1ec2ca52.png)
![reply options](https://cloud.githubusercontent.com/assets/4874287/22614822/b8a9c710-ea4d-11e6-82e8-03447e9115c2.png)
![article](https://cloud.githubusercontent.com/assets/4874287/22614814/83c7a5c6-ea4d-11e6-8e81-3671c961cc3c.png)

**Comment by klinker24** [comment]
I have now enabled voice replies. The final thing before closing this specific issue, in favor of smaller issues with specific wearable features, is supporting replies via the keyboard input

**Comment by klinker24** [comment]
![activate](https://cloud.githubusercontent.com/assets/4874287/22615279/09a3e6ce-ea57-11e6-93c3-f95978949ca8.png)

**Comment by klinker41** [comment]
Need to change that URL to something else?

**Comment by klinker24** [comment]
Lol didn't even consider that, done: 
![wear1](https://cloud.githubusercontent.com/assets/4874287/22618790/9e12abe8-eaab-11e6-9a63-a99c3bb5c648.png)

**Comment by klinker24** [comment]
I have finished with the wearable reply. I open sourced the implementation as a library: 

https://github.com/klinker24/wearable-reply

![library](https://raw.githubusercontent.com/klinker24/wearable-reply/master/artwork/feature.png)
