### ISSUE TITLE
Higher quality MMS don't always send

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#40]
_I got this report over email._

**Device with issue:** Note 5
**Primary device:** Note 5 with Android 6.0 (July security patches)
**Carrier:** Verizon
**App version:** 1.1.209
**Steps to reproduce:**

1. Download a low quality image off the internet and it will send successfully
2. Try sending an image from the Note 5 camera and it will only occasionally go through

**Additional information:**

I know that images are downscaled if they are over the 1MB threshold, but it seems to not always work quite as expected.

**Comment by klinker41** [comment]
Could be caused by any number of things, poor internet, timeout, etc. None of which I have much control over except for the size.

We can lower the scaling down to something like .8 mb so that it always makes it under that 1Mb limit, but that's about it.

**Comment by klinker41** [comment]
Changed the size to 900kb, won't really see a change in quality but should ensure it is under the limit if the carrier enforces 1mb.

https://github.com/klinker41/messenger/commit/3e3c8ce3711050edb540e1ad4a23ca27e6160659
