### ISSUE TITLE
Long pressing send button crashes application

### ISSUE THREAD

**Issue by JoshuaGarrison27** [klinker-apps/messenger-issues#402]
**Device with issue:** Huawei, Nexus 6P, Stock Version 7.1.2
**Primary device:** Huawei, Nexus 6P,  Stock Version 7.1.2
**App version:** 2.4.9.1391
**Steps to reproduce:**

1. Open application and the open a conversation
2. (Optional) Type something into the text field. Not required, happens either way.
3. Long press the send button
4. Application give crash pop-up

**Additional information:**

I did submit the crash report so if your developer console in google is not overflowing with errors then you should get some additional system info.

No additional information at this time. I will provide anything needed and within reason upon request.

**Comment by klinker24** [comment]
Thanks, I have fixed it. Please follow up when the next version is released, for confirmation.
