### ISSUE TITLE
Use Emoji One on the web

### ISSUE THREAD

**Issue by graywolf336** [klinker-apps/messenger-issues#403]
**Device with issue:** Ubuntu 16.04 running Chrome v60
**Primary device:** Pixel XL on Android 7.1.2
**App version:** 2.4.9.1391
**Steps to reproduce:**

1. Send or receive a text with an emoji
2. Open the Pulse Chrome App
3. View the text message
4. See intelligible emojis

**Additional information:**

Ubuntu doesn't support a lot of the emojis and especially the modern ones super easily, displays :man_shrugging: as boxes.

**Possible solution:**

Why not replace the emojis in the text with emoji one (assuming that's what you're using on the web apps) so they are intelligible and also consistent with the style picked via the emoji picker on the Chrome App.

**Visual Aid:**

Chrome App:
![image](https://user-images.githubusercontent.com/850391/29139954-5f306000-7d0e-11e7-82ae-64cc1dd3d8c4.png)

Android App:
![image](https://user-images.githubusercontent.com/850391/29140049-b2f199ac-7d0e-11e7-81ed-52d4c429ffe7.png)

**Comment by graywolf336** [comment]
Another place to use Emoji One on the web is in contact names.

** Visual Aid: **
Chrome App:
![image](https://user-images.githubusercontent.com/850391/29242634-10f18a6e-7f56-11e7-994e-02120202bcb8.png)

Android App:
![image](https://user-images.githubusercontent.com/850391/29242675-a84d4e66-7f56-11e7-9c30-a7e75cebecea.png)

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/messenger-web/commit/b582ba179106c55081920d2e352ed2e7abb2ba2d

They will be on the messages, titles, and conversation snippets. Thanks for the prompt to get this one done, I had no emoji one integration before on any of the web/chrome platforms. They all just used whatever emojis your computer had.

**Comment by graywolf336** [comment]
Awesome, thanks for adding this so quickly. :+1: I look forward to it!

**Comment by klinker24** [comment]
@graywolf336 they make it really easy, I have no excuse not to have used it before haha

**Comment by graywolf336** [comment]
@klinker24 Yeah they do and I've heard they make things easy in Android apps as well :thinking: we use it a lot over at Rocket.Chat :)

**Comment by klinker24** [comment]
I was looking at it the other day actually, for the Android support. I don't want to include the font in my app, it's 6 MB, but I was looking into making use of the new downloadable fonts and font providers. Something to think about for the future at least.

Not sure how to create a font provider package at this point. Google's documentation isn't all that clear.
