### ISSUE TITLE
Long/unsplit messages error

### ISSUE THREAD

**Issue by jleslie97** [klinker-apps/messenger-issues#404]
When I send SMS that counts as more than roughly 5 or so texts worth of characters then it is converted to MMS. Most text messaging apps have a text splitter for this case as it is fairly common for carriers (I'm on 3) to do SMS using this type of system. So when I send a SMS using pulse that is really long then it is detailed as sent but the recipient will never receive it. 

I'm currently on the 3 month subscriber plan and I'm interested in buying lifetime support but without this it would be a deal breaker. Otherwise pulse has been really great. Thank you for developing such an awesome app. Will help as much as I can but I'm not a programmer.  

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by klinker24** [comment]
By default, Pulse switches to MMS after 3 messages. You can configure this, or disable the switch to MMS from the "MMS Configuration" section of settings.

**Comment by jleslie97** [comment]
Sorry about that. Thanks for your help though :)

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
