### ISSUE TITLE
Web app notifications

### ISSUE THREAD

**Issue by psun03** [klinker-apps/messenger-issues#405]
**Device with issue:** Web Version Windows 10 using Chrome (Version 60.0.3112.90 (Official Build) (64-bit))

It would be nice to have a notification when a new message comes in. If a new message comes in, then the title bar blinks and a very distinct sound plays for each message. The bar will stop blinking after the message has been seen. The sound should be unique to Pulse. For example, Facebook chat has a different sound than Skype or Google Hangout when a new message comes in. This would be nice to know that I am getting a text message SPECIFICALLY from Pulse.

**Comment by Serubin** [comment]
The official messenger likely wont support this.
https://pulse.serubin.net does however. You can change the option in the settings menu.

**Comment by klinker24** [comment]
I plan to add this to the official client.

**Comment by psun03** [comment]
One thing I noticed is. I do see that there is an asterisk in the title of
the page for new messages, but only for new messages that I am not
currently on. So for example, I have Person A's message currently selected
and another person sends a text message I see an asterisk. I know that
there is a new message but from another person. However, if Person A sends
a new message I can't tell if a new message came in.

I just purchased to access the web app so I am getting use to it. I use to
us a program called mysms. I like/familiar with the notification system
they have but don't like their service.

I love pulse and plan on using it from now on.

**Comment by klinker24** [comment]
This is now done: https://github.com/klinker41/messenger-web/commit/b9cfeb1d2b19da9df2a2563b01116985bb3a415f

I have pushed it up, so it should start rolling out. I am not going to roll it out to everyone until after the weekend. If you want to forcefully turn it on, just add `?notifications=true` as a url parameter to the `messenger.klinkerapps.com` link: 

`https://messenger.klinkerapps.com?notifications=true`

That will give you the notification access request right when you get to the page. As long as the browser is open and has a connection to the web socket, it should provide the notifications.

It will handle the `Private Conversations` and `Muted Conversations` accordingly.
