### ISSUE TITLE
SMS giving no indications of failure to send

### ISSUE THREAD

**Issue by sgonzalez-huge** [klinker-apps/messenger-issues#407]
At least once a day my MMS & SMS fail to send. They just stuck on "Sending". When I open Google Message, it says those messages just fail to no indication that they didn't didn't get sent.

**Comment by klinker24** [comment]
Are you sure this is both MMS and SMS?

We will track issues with MMS at #101. I recommend trying to lower the max size of the attachment as a first debugging step.

For SMS, I rely completely on Android to send, and update the app with the status of sent/error, if they aren't doing that, there isn't much I can do here... Maybe you can provide me with more information on the issue?

**Comment by klinker24** [comment]
@sgonzalez-huge do you have any more info on this issue, or is it only MMS that you are asking about here? If so, I will close this in favor of #101.

**Comment by sgonzalez-huge** [comment]
That works for me.
