### ISSUE TITLE
Messages failing from chrome app due to country code not being detected

### ISSUE THREAD

**Issue by vlinus** [klinker-apps/messenger-issues#409]
**Device with issue:** Windows 10 laptop, running Chrome version 60 (Official Build) (64-bit)
**Primary device:** LG v20 on Android 7.0

**Steps to reproduce:**

1. Create a new contact in your phone with country code ,say UK, +44 7815 674320
2. Dont send any message from phone. Directly go to chrome app and select this contact, you can see that the number selected is 7815 674320 without the country code
3. Send the message, the message will not be sent and will fail.

Please note that if you start the message on phone, it will correctly detect country code. Then you can continue the conversation from chrome app, but if you start a fresh conversation in chrome app by selecting the contact, it will not detect country code.

**Comment by klinker24** [comment]
I had always wondered how well this worked. For the most part, I don't touch the formatting of phone numbers, they should come straight from the contacts provider. In the case of the web though, I did add a bit of formatting to them, which is a mistake given my experience...

I have made changes with: https://github.com/klinker41/messenger/commit/0d6e158df60cda9f51d9d5e0b1e7e3876ea75d8f

They will come out in the next update. When I do get the update out, you can go to "My Account" -> "Resync Messages" on the phone to push up the contacts to the web again, which should resolve this issue. Please let me know if it does not. Thanks for the help!
