### ISSUE TITLE
Prevent multiple instances of the login activity spawning

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#41]
**Device with issue:** Nexus 6P
**Primary device:** Nexus 6P running Android 7.0
**App version:** 1.1.209
**Steps to reproduce:**

1. Open up the app as a new install or after clearing the app data
2. You are presented with the login screen.
3. Rotate your device
4. Continue with login or create an account
5. After it is done and that login screen closes, a second login screen is underneath it 

**Additional information:**

If you skip the login on the second screen, the "My Account" section in the app will just have the "Setup Account" button, and not your account details. 

If you click the "Setup Account" button on that screen, then it will allow you to log in just fine, destroy your database, and pull in the same database again from the cloud, which works as expected, which is good.

I have not tested what happens if you go ahead and log in a second time with the duplicated dialog. At first thought, i figured it would pull in duplicate conversations, but, since the primary key fields on the duplicates that would be downloaded to your device are the same as the ones currently on the device for the messages, I do not actually think it would insert duplicate conversations.

**Possible solution:**

A quick fix would simply be to lock orientation on the login screen.

This will lock the orientation to whatever the user opens the activity on:

```java
int currentOrientation = getResources().getConfiguration().orientation;
if (currentOrientation == Configuration.ORIENTATION_LANDSCAPE) {
     setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_SENSOR_LANDSCAPE);
} else {
     setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_SENSOR_PORTRAIT);
}
```

**Comment by klinker41** [comment]
I think a better fix would be to change the manifest launch mode to something like single top. This also happens if you try and log in on your pixel C without the keyboard connected. When you press a button to wake up the keyboard, it will recreate the activity.  We need to worry about recreating the activity as well because it is started for a result and we process that result in the login activity.

Or, we could just set the manifest to handle all orientation and screen size changes ourselves so that the system does not recreate it when we do one of those things. Just locking the orientation won't fix the problem unfortunately.

**Comment by klinker24** [comment]
I think single instance or single top in the manifest would be our best bet here. That sounds like a good idea

**Comment by klinker41** [comment]
But will that keep the same instance or create a new one and kill the old? If it creates a new one and kills the old, then we won't ever get the results in the initial start activity and it will be like the user pressed the skip button instead

**Comment by klinker24** [comment]
Looks as though we want `singleTop`: https://www.mobomo.com/2011/06/android-understanding-activity-launchmode/

Will test and try this out.

**Comment by klinker41** [comment]
just finished implementing, working fine now on rotation, although I didn't test with keyboard changes. https://github.com/klinker41/messenger/commit/837ae70b61975125fa5d9f9bc77cbdd868e8b763

**Comment by klinker24** [comment]
Nice, yes it is working.
