### ISSUE TITLE
Ability to type messages without selecting a contact.

### ISSUE THREAD

**Issue by vlinus** [klinker-apps/messenger-issues#410]
Android Feature request 

I have seen this functionality provided only by a few messenger applications but I think its quite useful in some scenarios. It used to be one of the selection criteria for me when using sms apps :)
In pulse android app, it seems its mandatory to select a contact before typing the message which means you cant create a draft message. If selecting a contact is made optional before typing a message, it would reduce the risk of accidentally sending an unformatted/partial message which sometimes can be costly from a cost ( for international messages) and from a content perception perspective. I am not sure whether its quite a widely used feature but I think it can be a nice handy feature.

**Comment by klinker24** [comment]
I guess I don't quite understand. Even after selecting a contact, you still get the chance to type and edit the messages, so how does that reduce the risk of sending a bad message? It is really the same thing, just in a different order.

In Pulse, drafts are always attached to conversations, so to be honest, I don't see this one coming to my app

**Comment by klinker24** [comment]
Do you have any feedback regarding my comment? I would be interested in hearing the use-case compared to what I am imagining, or if I am off-base with what is in my head

**Comment by klinker24** [comment]
I can understand the use case of changing the person you are sending to, after you have typed the message, but I don't think that this would prevent any misspelling or sending any bad messages. You would still need to review the messages before sending them when they are on the same page as the contact entry..

I don't think that this is something that I am going to change though, admittedly. Currently, the contact selection as a separate page is the style that I am looking for. It provides an easy walk-through of how the conversation creation process works and gives me a bit more freedom for how I want to display the recent conversation
