### ISSUE TITLE
Menu order

### ISSUE THREAD

**Issue by krayakin** [klinker-apps/messenger-issues#412]
**Device with issue:** Nexus 6p
**Primary device:** Nexus 6p - purenexus 7.1.2
**App version:** 2.4.9.1391
**Steps to reproduce:** 
3 button menu and pullout menu items are not ordered the same.

http://i.imgur.com/PbWaL74.png
http://i.imgur.com/wGzDLWm.png

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/messenger/commit/99242f82278d7cf55aff0892a25b56006a2c3036
