### ISSUE TITLE
Long press app version

### ISSUE THREAD

**Issue by krayakin** [klinker-apps/messenger-issues#413]
**Device with issue:** Nexus 6p
**Primary device:** Nexus 6p - purenexus 7.1.2
**App version:** 2.4.9.1391
**Steps to reproduce:** 
Can you make long pressing the app version in about copy it to clipboard. Would make filling out these issues slightly easier

**Comment by klinker24** [comment]
It would probably be even easier to fill them out on a computer, which this won't help. Haha

Done with: https://github.com/klinker41/messenger/commit/c85af3a33d51b5a2a4c3b746109f1af43aef0c41
