### ISSUE TITLE
Keep receiving messages / MMS several times 

### ISSUE THREAD

**Issue by konsti23** [klinker-apps/messenger-issues#414]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [x] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** <insert your device: "MacBook Pro on MacOS 10.12, running Chrome v54">
**Primary device:** <insert your phone: "HTC 11U with Android 7.1.1">
**App version:** <insert version: 2.5.0.1426>
**Steps to reproduce:**

1. It happens that I keep receiving some messages and/or MMS messages more than once. I can not make out any rhythm, suddenly already received messages arrive again. I have set PULSE as my primary message app.
2. step 2
3. step 3

`... more steps`

**Additional information:**

Do you want to provide any other information? Device configuration, unique cases, anything that you think may be relevant.

**Possible solution:**

**Comment by klinker24** [comment]
Thanks for the report, we track all MMS issues here: #101
