### ISSUE TITLE
[Feature] Privacy Box

### ISSUE THREAD

**Issue by NovaViper** [klinker-apps/messenger-issues#415]
This is a feature that I find to be very important, and rare to find on apps like this. The privacy box should have the ability to be locked with a PIN, Pattern (one that you can change the size for in instances for those with small fingers or constantly using the thumb to draw the pattern) and with the help of Android 6.0+, the fingerprint. Also, there should be an option to actually hide the box from the drawer (like in GOSMS) and have the ability to customize the notifications that comes out of the box either for _all_  messages or per-conversation as decided by the user. This feature _should_  be on __all__  of the platforms.

I would highly appreciate if this gets added, I really enjoy using the app (overall the best SMS app I've ever used since 8sms)

_Sent from my Samsung SM-G925P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by klinker24** [comment]
This is what is planned around this request: https://github.com/klinker-apps/messenger-issues/issues/167

You can watch that issue for any update on progress or implementation
