### ISSUE TITLE
Pulse Icon Non-Clickable With Select Cursor

### ISSUE THREAD

**Issue by TerrapinPi** [klinker-apps/messenger-issues#417]
**Device with issue:** PC on Windows 10 Professional x64 running Chrome Version 60.0.3112.101 (Official Build) (64-bit)
**Primary device:** SAMSUNG SM-G891A on Android 7.0
**App version:** 2.4.9.1391
**Steps to reproduce:**

1. Open web-app
2. Hover over Pulse icon at top left

**Additional information:**

Edit: On further testing I was able to get the icon to toggle the left menu, however in this case the whole screen was grayed out and I was unable to click ANY of the links (conversation links or otherwise). A refresh of the page (F5) returned the page to behavior previously mentioned. 

Edit 2: I figured how to get the icon active. Resizing the browser window making it small enough, the icon changes to the menu icon. Make the browser window large again and the Pulse icon reappears and is active, allowing toggling of the left menu, however no other link is active when menu is toggled on.

**Possible solution:**

Update page removing link from icon or add link to icon to target URL.

**Comment by klinker24** [comment]
Clicking the icon will now return you to the conversation list: https://github.com/klinker41/messenger-web/commit/b6ad6a5d58fbf8acc503ebc0f7e89966d07ca575
