### ISSUE TITLE
Refresh Settings From Phone In Web-App Removes Hyperlink From URLs

### ISSUE THREAD

**Issue by TerrapinPi** [klinker-apps/messenger-issues#419]
**Device with issue:** PC on Windows 10 Professional x64 running Chrome Version 60.0.3112.101 (Official Build) (64-bit)
**Primary device:** SAMSUNG SM-G891A on Android 7.0
**App version:** 2.4.9.1391
**Steps to reproduce:**

1. Send message with link from web-app. Link is active and may be clicked to open.
2. On phone update app theme for Pulse
3. In web-app go to Settings and click "Refresh settings from phone"
4. Go to conversation with message containing link. The link is no longer active.

**Comment by klinker24** [comment]
Maybe the link color is just not right? If you check out the beta, it drastically changes how themes work and it applies to the web too.

There is probably an issue here, yes, but I doubt that it is something I am going to fix, since the old method will be deprecated in a few days anyways

**Comment by TerrapinPi** [comment]
Thanks for the quick responses and the fix on the icon, Luke!

Looking forward to seeing what's in store with the update that's in beta.

Thank you!
