### ISSUE TITLE
Repeat notifications going off for messages marked as read

### ISSUE THREAD

**Issue by jmdodge** [klinker-apps/messenger-issues#420]
**Device with issue:** Samsung Galaxy S8+
**Primary device:** Samsung Galaxy S8+
**App version:** 2.4.9.1391
**Steps to reproduce:**

1. Receive a message, see a notification for it pop up.
2. Mark it as 'read'.
3. Wait several minutes.
4. Observe another notification for the same message. Click it. Observe that no new message exists.
5. Repeat 2 or 3 times.

**Additional information:**
Seems to occur for both individual messages and group messages.
I have gotten the same notification for a message as many as 4, maybe 5 times.
Does not happen for all messages. I'm not sure if there is a pattern with certain senders or not, it's possible but I haven't noticed for sure.
My carrier is T-mobile.

**Comment by klinker24** [comment]
Are you marking as read from the notification button? Do you have the repeat notifications settings turned on? I can't say that I have heard about this. I assume that the notification doesn't show any new content, just the old content?

**Comment by jmdodge** [comment]
Yes, I am marking it as read from the notification button. I am also visiting the full thread from within the app.
Where is the "repeat notifications settings"? I couldn't find anything like that.
Correct - the notification doesn't show any new content, it shows exactly as it did the first time.

**Comment by klinker24** [comment]
It is under `Alert Types` in settings.

**Comment by jmdodge** [comment]
Oh, I remember this now.
I did have "every five minutes" selected for the "repeat alert" type.

I disabled it, I'll let you know if that resolves the issue - however, it sounds like perhaps that feature is not working as intended as I would expect to only get the repeated alerts if I had not dismissed the initial alert or read the message.

I would actually like the alert repeated if I didn't acknowledge it the first time, but for now it will certainly be an improvement if this resolves the redundant repeats.

**Comment by klinker24** [comment]
Yes I agree that that is how it should work.

**Comment by klinker24** [comment]
There were some changes that I made around this, for `v2.5.3` that I will be releasing in a few hours. Specifically around opening the thread from the UI, like you said that you did some times. If you could test this version out a bit and follow-up, that would be great. Thanks!

**Comment by klinker24** [comment]
@kg9034 MMS issues can be documented in #101. For this one, has it happened since the release of `v2.5.3`? I am also rolling out `v2.5.4` this morning, which has other changes around this issue.

**Comment by klinker24** [comment]
Closing for lack of response. It should be fixed.
