### ISSUE TITLE
Heads up from sender pop up when in a conversation with sender

### ISSUE THREAD

**Issue by Puck101** [klinker-apps/messenger-issues#421]
**Device with issue:** <insert your device: "LG G5">
**Primary device:** <insert your phone: "LG G5 on Android 7.0">
**App version:** <insert version: in "2.4.9.1391>
**Steps to reproduce:**

1. step 1: App open in a conversation and screen is on
2. step 2: Receive a new message from the same sender
3. step 3: heads up is displayed on top of conversation. 

Thank you, it's a great app

**Comment by klinker24** [comment]
Shouldn't be. Does the notification stay stick around? It should just update the message list. I haven't heard of any issues around this before.

**Comment by Puck101** [comment]
I run a few test and everything seems to work. Thanks.
