### ISSUE TITLE
Huawei Mate 9

### ISSUE THREAD

**Issue by JPD48** [klinker-apps/messenger-issues#422]
Pulse has never worked on My Huawei Mate9. It works on my other, Oneplus 3T and Sony Xperia Z. No sms or mms send and receive

**Comment by JPD48** [comment]
Pulse has never worked on My Huawei Mate9.  It works on my other, Oneplus 3T and Sony Xperia Z.  No sms or mms send and receive

**Comment by klinker24** [comment]
You are going to have to give me more info than that, sorry. 

I assume that this device is a tablet, so are you trying to use it to send through your phone or does it have its own phone number? 

What have you tried? Does it download and see the messages in your account? 

Do the messages show up on the web correctly?

What version of Android is it on, do you use a custom ROM?

Right now, I have nothing to go off if for this, so there isn't much I can do debugging wise...

**Comment by JPD48** [comment]
Hi,
It's a cell phone.  AT&T will be selling this brand next year.  
I've uninstalled and reinstalled it.  Could be a permission issue?  
Works fine on my other cell phones and on the web.
Other sms apps also work fine on the phone I'm having trouble with.
Thanks!
--
Best Regards,
Jim Smith
smith.2016@my.com
---
Download myMail and grab your short and cool email address @my.com! Sunday, 20 August 2017, 04:02PM -04:00 from Luke Klinker  notifications@github.com :

**Comment by JPD48** [comment]
apologize for another email, the app also never sent a failed to send text for all the texts I tried to send.  I did get them on my other phone when I turned it on.
--
Best Regards,
Jim Smith
smith.2016@my.com
---
Download myMail and grab your short and cool email address @my.com! -------- Forwarded Message --------
From: Jim Smith  smith.2016@my.com To: klinker-apps/messenger-issues  reply@reply.github.com Date: Monday, 21 August 2017, 11:59AM -04:00
Subject: Re[2]: [klinker-apps/messenger-issues] Huawei Mate 9 (#422)

**Comment by klinker24** [comment]
So does the phone app display them as sent, the recipient just never gets the message?

I am confused by your last statement:

> I did get them on my other phone when I turned it on

So were you sending messages from the Huawei phone, to your other phone, and when you turned the other phone on, the messages got received? I am having a bit of difficulty following you, sorry. If you could go into detail about how you are using the app and what you are expecting, that might be helpful for me.

**Comment by JPD48** [comment]
Yes the phone app display them as se­nt, the recipient ju­st never gets the me­ssage.  I also do not get a message that it failed. 
When I went to use my main phone for this app I see the messages failed.  I was always use my SIM card on ATT lte network.
Hope that clears it up.
--
Best Regards,
Jim Smith
smith.2016@my.com
---
Download myMail and grab your short and cool email address @my.com! Monday, 21 August 2017, 01:04PM -04:00 from Luke Klinker  notifications@github.com :

**Comment by klinker24** [comment]
Sorry I am still not sure I am following everything. What does the main phone have to do with this? 

Are you using the Huawei phone as a secondary device on your account, to send the messages through the other phone, or are you using the SIM card on your Huawei phone to send the messages?

**Comment by JPD48** [comment]
Yes,  sending  the messages through  the SIM card on my Huawei phone to send the messages.  
I have two cell phones that I use on different occasions.  That is what is confusing.   I found out the messages failed when I place my sim card in my other phone  and powered up
--
Best Regards,
Jim Smith
smith.2016@my.com
---
Download myMail and grab your short and cool email address @my.com! Monday, 21 August 2017, 01:21PM -04:00 from Luke Klinker  notifications@github.com :

**Comment by klinker24** [comment]
Yes, that is confusing, but I see what you mean, now.

Is this a dual SIM device, or anything like that?

To be honest, I don't really get to control the sending or the receiving process. Android provides a callback to any apps that are listening when a message is received, and all I am able to do is hand the messages off to the system to get sent from there. Android also provides a callback for whether or not the message is sent or if it fails, so all of that information is coming to the app directly from the phone. Pulse is not creating or managing any of those states itself.

**Comment by klinker24** [comment]
Closing due to lack of response on dual SIM question and not enough information.
