### ISSUE TITLE
Link colors should not be accent color.

### ISSUE THREAD

**Issue by dponinski** [klinker-apps/messenger-issues#423]
**Device with issue:** Nexus 5X
**Primary device:** Nexus 5X
**App version:** 2.4.9.1391
**Steps to reproduce:** 

1. Open App
2. Open Conversation
3. Look for anytime a link was shared. 

**Additional information:**

It's hard to read the links in some cases depending on the color combo. The issue arises mostly from recipient texting back and the accent color is inside a primary color. This is an accessibility issue.

**Possible solution:**

I would recommend the links should just match the the rest of the text (white or black) with an underline or figure out a better way to display the links like iMessage or the reader feature that is built into Pulse could essentially just replace the link and display a nice layout inside the bubble. I wish I could code Java and I'd help out but alas I am a designer and Sketch is my thing. I could however design a screen to illustrate options that could resolve this, if that is something you'd like. I have attached some examples of the issue to show how hard it is to read the links.

![screenshot_20170820-145138](https://user-images.githubusercontent.com/342822/29497972-2ecf9a54-85b8-11e7-9ee8-20f5513bddaf.png)
![screenshot_20170820-145207](https://user-images.githubusercontent.com/342822/29497973-2ed0ada4-85b8-11e7-8f2c-47cc52d505f6.png)

**Comment by klinker24** [comment]
Sorry, this is not something that I am going to change. While I understand not all color combos work great, you can change the accent color to anything you want. Using an accent color for links is extremely common in Android and on the web. Underlining the text is not nearly enough, in my opinion.

**Comment by dponinski** [comment]
Uninstalled. I'll give my money to a dev that cares about it's users. Thanks.

**Comment by klinker24** [comment]
You serious? I responded with valid reasons as to why this isn't going to be available within a few minutes. On a Sunday. You won't find a dev that does more to show that they care about their product and users. 

I am not going to be able to put in every single request, sorry. I have to be the one to decide what is going to be best for the app and what isn't. Adding a toggle for every single little tweak is not at all the direction that I want to go. It clutters the app and takes away from the user experience when people can't find what they are looking for. Your request would have effected every single user of the app, and I don't think that it would be the right move, for the reasons I gave above. 

Sorry you feel this way, but if that is honestly what you think, please feel free to look through these issues and the Google+ page, then I dare you to tell me I don't implement requests and that I don't care about my users. Have a great day.

**Comment by dponinski** [comment]
What you provided was a lazy excuse as to why you didn't want to fix this. This is not a feature request. This is a bug. The bug is that I, as a user, can't read links in most conversations. There is not a single reputable SMS app on the market that does this because of accessibility issues. I didn't even recommend an extra setting. What I recommended was pulling links out of the accent color and underlining it, because, you know, it works better than your current implementation. I never said the accent color need to be removed altogether. It's obvious you didn't read my whole issue or you would have known this. My issue is that you would rather defend an accent color than your users ability to read their text messages. This is why I uninstalled and this is why I will take my money elsewhere.

**Comment by klinker24** [comment]
No, this is a feature request, this is in no way a bug. It is a UI decision that I clearly made, and that I gave any user the option to choose for themselves. Don't like the color clash, pick a different color then.. there is a crazy amount of options available to you.

And I also never said anything about the accent color being removed altogether, no clue where you got that. I understood your request perfectly and my response stands, as-is.

If this is really the way you feel, then I am sorry. Have a good one, and good luck with your quest for the ~perfect developer~ right app.
