### ISSUE TITLE
URLencoded phone numbers are not being interpreted properly by Pulse Android

### ISSUE THREAD

**Issue by danielling23** [klinker-apps/messenger-issues#426]
**Device with issue:** <Google Nexus 6P>
**Primary device:** <Nexus 6P with 7.1.2 Aug5 Update>
**App version:** <2.5>
**Steps to reproduce:**

1. Use any app or web site to send a phone number to the app
2. Pulse receives it as %2BCCNNNNNNN where CCNNNNN is the country code and number 

Tested the same with the current version of Google Messenger and ChompSMS which does not exhibit this behavior

Do you want to provide any other information? Device configuration, unique cases, anything that you think may be relevant.

**Possible solution:**

Do you have an idea of how to solve it? If not, that's fine, you can delete this section.
I think you might want to check the string being parsed for the "%" character in front, and if it is, use a URLdecode function to decode the URLencoded string. I am not an Android Developer but I do build apps on other platforms. Hope this will be helpful. Love the Pulse app and would like it to be better.

**Comment by klinker24** [comment]
When do you receive a message with a URL encoded phone number? I guess I don't really understand where that would ever come from? 

What carrier are you on and who are these messages coming from?

**Comment by danielling23** [comment]
Thanks for the prompt response. 

My version is 2.5.1.1452 if that helps. 

I use some apps to send messages through my SMS Provider. When I select it, I get the option of using 
- Pulse
- ChompSMS
- Google Messenger
- CSipSimple


All of them are able to receive the phone number fine with the exception of Pulse which is receiving it as %2BCCNNNNNNN instead of +CCNNNNNNN . Right now I have to do the following which is a little painful : 

- Share to ChompSMS
- At ChompSMS select it as default SMS provider
- Send the message
- Go back to Pulse
- Set it as default

Carrier is M1 located in Singapore. My language is English (US) if that helps.

**Comment by klinker24** [comment]
So this isn't a message you are receiving, it is a message that you are basically sharing through another app? It would be useful to know which app.

**Comment by danielling23** [comment]
No, not sharing a message, I was trying to get another app ie. the browser to send the phone number to the messaging app to send messages out with the messaging app. I could do it from try to do it from Gmail/Browser.

**Comment by danielling23** [comment]
Receiving messages are all working fine. I am about to upgrade to O, not sure if I should troubleshoot this with you before doing so. How can I send you catlog securely as I am not comfortable sending it over github.

**Comment by klinker24** [comment]
So I assume this is done through a link. Can you just paste an example link here? A log isn't going to help me here

**Comment by klinker24** [comment]
I am deploying some changes tomorrow for this. If they are the `sms:` and `smsto:` links that I asked about, then it will be fixed. If not, please follow up and describe how I can reproduce this problem.

https://github.com/klinker41/messenger/commit/949f43e33647fa3546f47ac89109b84c3c513026

**Comment by danielling23** [comment]
Hi, awesome to hear that, I am not sure if they are sms: or smsto: links as they are not apparent to me. When I click on those buttons, only the following apps will show as options in the list : 

- CSipSimple
- Pulse
- Google Messenger
- ChompSMS

I only have the issue with Pulse at the moment. The "+" character is showing up fine in the other 3 apps in the list above. 

I can try to log the message using catlog if you need to but as I mentioned earlier. Would prefer to send it to you in a more secure manner other than over Github for confidentiality reasons.

**Comment by klinker24** [comment]
Like i said, a log won't do anything here, sorry

If it is on the browser, just long click the button and use the "copy link" option

**Comment by danielling23** [comment]
I really think it's the URLencoded chars of "+" being taken as %2B causing this. I have just installed Signal which also exhibits the same issue. 

Google Messenger actually strips out the +CC and goes straight to NNNNNN when it detects that the message is to be sent to the same country.

**Comment by klinker24** [comment]
Yes, I understand that. I am asking you to provide me with a way to replicate it so I know where that is coming from. There are many different entry points when dealing with sharing from other apps. If you could just provide me with some way to make this happen, we would definitely be done here already...

**Comment by danielling23** [comment]
the sms: and smsto: seems to be correct

From catlog, I found an error related to the Pulse process when the SMS is triggered. I checked that PID 21023 is 
u0_a425      21023   582 2353496  87688 SyS_epoll_wait 76055b41d4 S xyz.klinker.messenger

08-24 11:07:56.754 E/SQLiteDatabase(21023): Error inserting snippet= pinned=false read=true color=-769226 private_notifications=false color_dark=-3790808 image_uri=null id_matcher=CCNNNNNNN color_accent=-11309570 led_color=-1 ringtone=null color_light=-1074534 mute=false archive=false title=%2BCCNNNNNNN phone_numbers=%2BCCNNNNNNN _id=335867720078437 timestamp=1503544074849

**Comment by danielling23** [comment]
Trying my best to figure it out too at the moment.

**Comment by klinker24** [comment]
That error isn't really related to this. That is a duplicate SMS that fails to get inserted from some of the backend synchronization.

If you could just copy that link, that is really all I need here. You can strip out any of the personal data, it will just be in a Uri format. As long as I can understand the base schema still. Just long click the button and copy the link as described

**Comment by danielling23** [comment]
Upon further testing today, it seems that this is only affecting Application sharing of SMS and somehow, browser links of sms: and smsto: are all parsed properly. Not sure why it is only affecting Pulse and not affecting the other SMS apps.

**Comment by danielling23** [comment]
Inside the conversation view of Pulse where the title is %2BCCNNNNNNNN when I select "View contact", it will correctly parse it as +CCNNNNNNNN . Not sure if this might help somewhat. 

"Conversation information" shows : 

Name : %2BCCNNNNNNNN
Phone number : %2BCCNNNNNNNN
Date : looks normal
Message Count : 1

**Comment by danielling23** [comment]
Signal also has this issue flagged as a bug in their issue tracker by another user. Will let you know if they have fixed it too. Everything else is working just great on Pulse.

**Comment by danielling23** [comment]
Just received your new app update. This issue has been resolved in your latest build. Great work!

**Comment by danielling23** [comment]
Thanks Luke!

**Comment by klinker24** [comment]
No problem, enjoy the app
