### ISSUE TITLE
Attach contact as plain text

### ISSUE THREAD

**Issue by talha131** [klinker-apps/messenger-issues#429]
**Device with issue:** LG G4
**Primary device:** LG G4
**App version:** 2.5.1.1452
**Steps to reproduce:**

1. Start composing a message
2. Click on attach icon
3. Select Contact
4. Enter any contact name 

Contact is attached and sent as a VCard.

Kindly add an option or global setting to always send contacts as text.

**Additional information:**

EvolveSMS has this feature. It offers option to send as VCard or plain text.

**Use Cases**

1. Sometimes the receiver does not have MMS enabled 
1. MMS does not work properly on a network in my country
1. It is cheaper to send SMS than MMS
1. SMS backup archive is searchable
1. MMS backup does not always work

**Comment by klinker24** [comment]
Thanks for the request, I will consider adding this for you.

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/messenger/commit/3c089018aadac20dc41c19f473ef38168d80fe87

It will be released with `v2.6.0`.
