### ISSUE TITLE
Update text colors on web

### ISSUE THREAD

**Issue by DiverAllen** [klinker-apps/messenger-issues#430]
**Device with issue:** Windows 10 PC
**Primary device:** Samsung Galaxy 7
**App version:** 2.5.1.1452
**Additional information:**

Messages in Yellow background have white text and this is difficult to read.  On mobile device yellow background messages have black text which is easy to read.

**Comment by howieweiner** [comment]
Just installed the Mac OS X app (great app BTW!), and also immediately looked to change colour settings. White text on purple, grey text on orange, grey background. I guess some themes would be good.

**Comment by klinker24** [comment]
It follows the same themes you set up on your phone, so not sure I understand what you mean

**Comment by howieweiner** [comment]
Oh. So it does. Oddly the contrast is not as good on the desktop (retina MB Pro). The white message block background is hard to distinguish from the grey.

Also, the message input box does not have a white background like the mobile app.
<img width="223" alt="screen shot 2017-09-29 at 18 57 47" src="https://user-images.githubusercontent.com/955237/31029087-4d5ed1c4-a548-11e7-8070-db65e6b6ab9d.png">

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/messenger-web/commit/d92d872100a2e6dc57dadce8436560e653f5f2fc

Will push it out the beginning of the week some time.

**Comment by DiverAllen** [comment]
Thanks.  Will look forward to it.
Allen
