### ISSUE TITLE
Images do not show up on Mac Chrome App

### ISSUE THREAD

**Issue by mitchmeyer1** [klinker-apps/messenger-issues#431]
BUG ON: MacBook Pro on MacOS 10.12.6, running Chrome v60.0.3112.101
PHONE: Samsung Galaxy S8 Android 7.0 Sangsung Experience Version  8.1
APP VERSION: 2.5.0

Easy to reproduce for me.  I dont get any image attachments to show up on my Chrome App version.  Only on my phone. They all just show the default 'broken image'

<img width="627" alt="screen shot 2017-08-25 at 10 56 34 am" src="https://user-images.githubusercontent.com/5130046/29719457-1833d060-8984-11e7-8b38-fac4a95ba3f9.png">

**Comment by klinker24** [comment]
Pulse will only upload the latest 20 images, when you set up an account. Is this what you are running into, or are new images not displaying either?

**Comment by mitchmeyer1** [comment]
I bought the infinity package (Lifetime subscription) a few days ago.  This text was from today!

**Comment by klinker24** [comment]
Interesting, thanks for the report. Anything red in the "Inspect" -> "Console" tab when loading the thread? If you could just copy and paste the output of that console, it might be interesting to me, actually.

Have you had any images come through since the initial upload?

**Comment by mitchmeyer1** [comment]
Nothing red in the console. I just got one from a different contact and it worked.  Not 100% failure anymore

**Comment by mitchmeyer1** [comment]
Maybe the chrome app was closed when i recieved the SMS, then i opened it and it didnt have it?

**Comment by klinker24** [comment]
That shouldn't make a difference, it pulls them from the backend whenever they are requested, the Chrome app doesn't persist any of your conversations

**Comment by klinker24** [comment]
Is this still an issue for you, or are the images coming through correctly?

**Comment by klinker24** [comment]
Some recent changes would affect this issue as well. They will be released to production with the next version and affected the thread safety of the app: https://github.com/klinker41/messenger/pull/32

**Comment by klinker24** [comment]
More changes with this: https://github.com/klinker41/messenger/commit/a28887ab76ff2eb52e2346adf88553ba78304d22

I am going to mark this as finished.
