### ISSUE TITLE
Draft indicator

### ISSUE THREAD

**Issue by DavidCao22** [klinker-apps/messenger-issues#432]
**Primary device:** Google Pixel
**App version:** 2.5.2.1459

**Feature Request:**
I sometimes make drafts and return to them later to finish typing and send the message. In Google Messages and Textra, conversations with drafts are pushed to the top of the conversations list, regardless of how recent the conversation is. These conversations are also visually marked as having drafts by adding an indicator like italics, a 'draft' prefix, ect... And, there's a preview of the message being drafted. 

This feature would definitely help me visually distinguish at a glance which conversations I still need to respond to. Currently, I just pin those draft conversations to keep track of them. But, this feature would definitely be useful for keeping track of those conversations. I don't use the web app or any browser extensions yet, so I don't know if this is already implemented on those platforms. 

Here are pictures of the feature on Google Messages and Textra:
![screenshot_20170827-023703](https://user-images.githubusercontent.com/10539139/29747996-ab90397c-8ad1-11e7-8c0d-2e96f103362f.png)
![screenshot_20170827-024239](https://user-images.githubusercontent.com/10539139/29747997-ab9c50f4-8ad1-11e7-9e84-36fd9ab1c647.png)

Here's a link to the [Textra Feature Request](https://textra.uservoice.com/forums/208555-feedback/suggestions/6938848-indicator-for-draft-messages-not-yet-sent-in-the-g) for the same feature.

**Comment by klinker24** [comment]
I don't think I will move them to the top. I could add some indicator of them though, for the future.

**Comment by klinker24** [comment]
This is done with: https://github.com/klinker41/messenger/commit/89bb534cf2005f2be3e32860e1c05a1a89d0ebc9

I will plan the full rollout for v3.1.0 in the coming months, after testing.

A message of `Draft: message here...` will be displayed on the conversation list. It will take the current timestamp for the draft and use that timestamp for the conversation. When the draft is removed, it will revert to the timestamp of the last message and the snippet will revert to the last message.
