### ISSUE TITLE
The App doesn't function in Vivaldi

### ISSUE THREAD

**Issue by NovaViper** [klinker-apps/messenger-issues#433]
**Device with issue:** Windows 10 64 bit Home Edition, running Vivaldi 1.11.917.43
**Primary device:** Samsung S6 Edge, Android 7.0
**App version:** 2.5.3.1.1471
**Steps to reproduce:**

1. Install Vivaldi
2. Install Pulse App
3. Open Pulse App in [chrome://apps/]

**Additional information:**

When opening the app, the tab that it opens is completely blank. However, when I use the Pulse Extension, it works just as it would in Chrome

**Comment by klinker24** [comment]
It is a bug on their end: https://forum.vivaldi.net/topic/10103/chrome-webview-based-apps-won-t-work/2

<img width="643" alt="screen shot 2017-08-27 at 7 15 17 am" src="https://user-images.githubusercontent.com/4874287/29749696-8c3586e2-8af7-11e7-813b-ba6e14505168.png">

Pulse has the `webview` permission. 

```
{
  ...
  "permissions": [
    "https://klinkerapps.com/",
    "https://*.klinkerapps.com/",
    "https://messenger.klinkerapps.com/",
    "webview",
    "storage",
    "gcm",
    "notifications",
    "background"
  ],
  ...
}
```
