### ISSUE TITLE
Pulse crashes on long pressing status bar icons

### ISSUE THREAD

**Issue by amard33p** [klinker-apps/messenger-issues#436]
**Device with issue:** Nexus 4
**Primary device:** Nexus 4 on Android version 6.0.1
**App version:** 2.5.3.1475
**Steps to reproduce:**

1. Open Pulse. Long press any conversation > few icons will appear under the status bar.
![2](https://user-images.githubusercontent.com/13570034/29813259-3efeaba2-8cc7-11e7-85bf-cec7bea2d85d.png)

2. Long press any icon. 
Desired behavior > Show a toast message about what pressing the icon will do.
Observed > Pulse crashes.

**Additional information:**

This behavior is not seen inside a conversation with individual messages.
![4](https://user-images.githubusercontent.com/13570034/29813469-cfec0376-8cc7-11e7-9d55-f50ae19d02d3.png)

**Comment by klinker24** [comment]
Thanks, will fix this

**Comment by klinker24** [comment]
Fixed with: https://github.com/klinker41/messenger/commit/6de5c36700025132cf6ad072b848093657fc4ed8
