### ISSUE TITLE
Pin and Mute Status bar icons should change based on context

### ISSUE THREAD

**Issue by amard33p** [klinker-apps/messenger-issues#437]
**Primary device:** Nexus 4 on Android version 6.0.1
**App version:** 2.5.3.1475
**Feature Details:**

1. Long press a pinned conversation.
Expected behavior > Status bar icon should show "Unpin"
Observed > Status bar icon shows "Pin"
![screen](https://user-images.githubusercontent.com/13570034/29814491-22b5c2ba-8ccb-11e7-9fea-30e069642c36.png)

Similar behavior is observed with the "Mute" icon.

**Comment by klinker24** [comment]
I don't think that this one will change, to be honest. While I understand what you are looking for, these icons are basically toggling the current setting. If you were to select more than one conversation, say one pinned and one unpinned, you could still use that pin button to switch the status of both of them, so what would the icon be in that case? I just think that it would be pretty weird to switch that icon in some cases but not others. Do you agree?

**Comment by amard33p** [comment]
I agree. I checked Textra and Inbox by Google. Did not like either implementation of this feature. Guess it will have to be this way.
