### ISSUE TITLE
Change individual senders colors

### ISSUE THREAD

**Issue by JoshuaGarrison27** [klinker-apps/messenger-issues#438]
Currently there is no way to change the colors of individuals in a conversation (at least not on Android devices). It would be cool if there was a way to change them in case two people's colors are very similar or the same. Or if by chance you just dont like the color that was randomly selected.

**Comment by klinker24** [comment]
You can change them by changing that user's individial conversation colors

**Comment by JoshuaGarrison27** [comment]
Even in a group conversation? Thats what I am referring to. Sorry, I should have been more clear.

**Comment by klinker24** [comment]
I understood you. Changing the users indivudal conversation colors will change their color in the group message. There were changes around this for the latest beta `2.5.4`.

**Comment by JoshuaGarrison27** [comment]
Ah okay. I am not running beta. I am running 2.5.3.1475. Thank you for the information.
