### ISSUE TITLE
When you deselect a message/conversation, the selection popup should close

### ISSUE THREAD

**Issue by Yozakgg** [klinker-apps/messenger-issues#439]
OnePlus 3T, LineageOS 7.1.2

**Steps to reproduce:**

1. Select a message or conversation
2. Tap it again to deselect it

Ideally when you deselect the message/conversation the selection popup would close.

**Comment by klinker24** [comment]
Sure, I can change this. Thanks for the suggestion.

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/messenger/commit/3b29dbaa61075321b86db06ff36870a635c903c2

**Comment by Yozakgg** [comment]
I see it is fixed for selecting messages, but can you do the same for conversation selection.

**Comment by klinker24** [comment]
It is already applied to both.

**Comment by Yozakgg** [comment]
On the latest beta it only works for selecting messages inside a conversation
