### ISSUE TITLE
[Feature] Option to mark as read when notification is dismissed

### ISSUE THREAD

**Issue by Yozakgg** [klinker-apps/messenger-issues#440]
It would be very convenient to have an option in settings to automatically mark a message as read when the notification is dismissed, or an option to just remove unread indicators altogether.

**Comment by klinker24** [comment]
Sorry, I don't see this ever happening, since a notification button already exists for this functionality. I really want to stay away from filling up the settings menu with little tweaks and duplicate options, in this app.

**Comment by myspivey** [comment]
@klinker24 it might be useful to change the the button to "MARK READ" as I was confused about that till reading this thread. I believed I clicked that to open the message to read in full not mark as read.

**Comment by klinker24** [comment]
I don't think that is likely. Many devices and configurations would only show "mark ..." Instead of "mark read".
