### ISSUE TITLE
Sharing image from another application shows 'null' in message field

### ISSUE THREAD

**Issue by JoshuaGarrison27** [klinker-apps/messenger-issues#441]
**Device with issue:** Nexus 6P
**Primary device:** Nexus 6P - Android 7.1.2
**App version:** 2.5.4.1497
**Steps to reproduce:**

1. Go to a picture in your phone and click to share it.
2. In the share slideup select "Pulse"
3. Type in a name or select an existing contact conversation
4. Conversation opens with `null` in the message box instead of the image

**Additional information:**

Not running any beta version of this application. My specific instance happened when sharing a screenshot. But it can be repeated in any other application that has sharing.

**Comment by klinker24** [comment]
Ok thanks.

**Comment by klinker24** [comment]
Fixed with: https://github.com/klinker41/messenger/commit/63878a5ed6f0f31454112d4a6d21628da5d68688
