### ISSUE TITLE
Sending messages with enter on mobile

### ISSUE THREAD

**Issue by drag0micr0** [klinker-apps/messenger-issues#442]
- [✓ ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [ ] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** <Moto Z Force on 7.1.1>
**Primary device:** <Moto Z Force on 7.1.1>
**App version:** <2.5.4.1497>

I would just like the option to press enter to send a message

**Comment by klinker24** [comment]
You can do this. Head to `Global Settings` -> `Keyboard Layout`
