### ISSUE TITLE
Max File size on Android is 10MB but on desktop it is 1MB

### ISSUE THREAD

**Issue by mitchmeyer1** [klinker-apps/messenger-issues#443]
BUG ON: MacBook Pro on MacOS 10.12.6, running Chrome v60.0.3112.101
PHONE: Samsung Galaxy S8 Android 7.0 Sangsung Experience Version 8.1
APP VERSION: 2.5.0

On the Android app, there is a setting to change 'max image size upload' up to 10MB.  On Mac this does not exist.  It is always 1MB.  You can 'refresh settings from phone' but it doesnt change anything.  Would like to be able to use the computer to send decent sized files

**Comment by klinker24** [comment]
Thanks for the suggestion, I think I will bundle this one with #226 and do them together. This issue is now linked over there, so you will be able to watch the progress on that guy.
