### ISSUE TITLE
Sharing Images shows "null"

### ISSUE THREAD

**Issue by uudruid74** [klinker-apps/messenger-issues#444]
- [X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [X] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** OnePlus 3T / Vertex EAS OS
**Primary device:** same
**App version:** 2.5.4.1497
**Steps to reproduce:**

1. Open a gallery app (tried 2) and select image
2. Click Share and select Pulse
3. Select Contact
4. Image just shows as a text that says "null"

**Additional information:**
This seems to be something changed recently as this used to work fine before.

**Possible solution:**
Revert a change?

**Comment by klinker24** [comment]
Duplicate #441
