### ISSUE TITLE
Revamp the internal camera

### ISSUE THREAD

**Issue by uudruid74** [klinker-apps/messenger-issues#445]
*Edited by @klinker24. Original: Some force close issues with the camera. There are many issues with the current camera implementation. The best course of action is to completely revamp it.*

**Device with issue:** OnePlus 3T
**Primary device:** Same
**App version:** 2.5.4.1497
**Steps to reproduce:**

1. Click Paperclip
2. Click Camera and snap image
3. Repeat

At this point, I only get a spinning cursor and the second image won't attach.

**Additional information:**

A friend of mine gets a force close with similar steps.  I believe they might have clicked send between images, but not sure.   They used the release version from Play, downloaded today, Galaxy 5 device I think.

**Comment by klinker24** [comment]
Thanks, I probably need to redo the internal camera a bit. It seems to work well for most people, but not for everyone and not in all cases.

**Comment by klinker24** [comment]
This is done

https://github.com/klinker41/messenger/commit/4eeeeeebca6621552e962d3ae2a8c25b9d886686

I will roll out this slowly, over the next few updates.
