### ISSUE TITLE
Make it easier/possible to start a group text from the chrome extension

### ISSUE THREAD

**Issue by oliverdain** [klinker-apps/messenger-issues#448]
**Device with issue:** Chome extension on Chrome 60.0.3112.113  on both OS-X and Linux
**Primary device:** Google Pixel on Android O
**App version:** 1.9.0 of the Chrome extension
**Steps to reproduce:**

1. You want to start an MMS to be sent to more than 1 person
2. Click on the big "+" icon in the Chrome extension to start a conversation.
3. Type in the name of the first person who should receive the text
4. Try to add additional recipients

For me, step 4 fails. As far as I can tell, I have to start the group text on my phone. I can then use the conversation view in the extension to find the conversation and I can add to it from the extension. However, it seems like it's not possible to actually start it from the extension.

**Possible solution:**

The Android app makes this really easy. You add one recipient and you can then add others. A similar UI for the Chrome extension would be great.

**Comment by klinker24** [comment]
On the web platforms, you can just put a comma or semi colon, then it will start auto completing the next contact. It doesn't have the chips UI, but this is the same thing as how the Android app works

**Comment by oliverdain** [comment]
Thanks for the quick response! IHMO it's not quite as intuitive as it might be but very nice to know that it's possible.
