### ISSUE TITLE
Battery drain: MarkAsSentJob wakelock

### ISSUE THREAD

**Issue by vincentvidal** [klinker-apps/messenger-issues#449]
**Primary device:** Xiaomi Mi5 on Android 7.0
**App version:** 2.5.5.1504

With a moderate usage of Pulse (with text from everywhere feature, less then 50 messages a day), I get a very high battery drain due to the following wakelock (info from app Wakelock Detector):

*job*/xyz.kliner.messenger/.shared.service.jobs.MarkAsSentJob

WLD reports that my device is kept awake during 1h43 with only 27 calls to that wakelock.

**Additional information:**

Here is a screenshot: ![screenshot_2017-09-05-08-35-50-844_com uzumapps wakelockdetector](https://user-images.githubusercontent.com/24563559/30048237-95d0142c-9215-11e7-8dff-66c2cb25895e.png)

cheers
Vincent

**Comment by klinker24** [comment]
Oops. Always finish your jobs: https://developer.android.com/reference/android/app/job/JobService.html#jobFinished(android.app.job.JobParameters, boolean)

Fixed with: https://github.com/klinker41/messenger/commit/92402906805e1e23837beef76dc52cfa238cd4ee

Will release with next version `v2.5.6`.
