### ISSUE TITLE
Display contact picture in message list somewhere

### ISSUE THREAD

**Issue by klinker41** [klinker-apps/messenger-issues#45]
**Device with issue:** Nexus 6P running Android 7.0
**Primary device:** Nexus 6P running Android 7.0
**App version:** 1.1.209

**Information:**

Many people are asking for the contact picture on the message list. I don't think we should put it on the list, but it could find a spot on the toolbar (right side) or above the name and number in the drawer. If a picture is not available for this person, we shouldn't display anything.

**Comment by klinker24** [comment]
I would say to put them in the drawer, I am not a fan of avatars in the `Toolbar` like some apps have done. Just is a bit messy looking, especially when they are on the right side of the toolbar

**Comment by klinker41** [comment]
Agreed

**Comment by klinker41** [comment]
done with https://github.com/klinker41/messenger/commit/18a7dd1251be8e8d6b350e6bd1cd5e3198b8d52e

![device-2016-08-31-164730](https://cloud.githubusercontent.com/assets/4501322/18147882/41ffad5e-6f9c-11e6-8293-c2138dbbf0e1.png)
![device-2016-08-31-165255](https://cloud.githubusercontent.com/assets/4501322/18147888/496ae4a0-6f9c-11e6-8f86-949c08d0bdc9.png)

Its a shame we can't get higher res contact images. Or at least my phone doesn't have those saved
