### ISSUE TITLE
Can not import whole conversation from device.

### ISSUE THREAD

**Issue by Skullmonkey** [klinker-apps/messenger-issues#450]
- [X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [X] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** 
Pixel XL
**Primary device:** 
Pixel XL on Oreo 8.0
**App version:** 
2.5.5.1504

**Steps to reproduce:**

1. Run through initial setup and import.
2. Checked conversation that I would like to have entire history of.
3. Notice only ~50 show up start.

**Additional information:**

Do you want to provide any other information? Device configuration, unique cases, screenshots, anything that you think may be relevant.

It seems to happen to only 1 conversation. I have tried to go back and resync messages in account settings. It does the same thing. I have gone back and checked the stock messaging app and they are all still in the conversation there along with all the new ones since I have started using this app this morning. Granted, there are thousands of messages if that makes a difference. I would like them all to be backed up though. If this is too much of a burden on the server or space, I can continue to use the method I use now.

**Comment by klinker24** [comment]
Pulse will import a max  of 250 conversations and 500 messages per conversation on the initial import. Sorry, this is a hard limit, and will not be something that I will change at this

**Comment by Skullmonkey** [comment]
I do respect your decision on this matter but I am curious as to the reasoning behind this hard limit.

**Comment by klinker24** [comment]
Performance, import time, and upload time

**Comment by MitchyD89** [comment]
Just came across this myself when trying to import messages. So it's designed to be like this? I want to use Pulse (including paying for the web access) but I'll stick with Textra + Join in that case, I understand where you're coming from (and I agree with the uploading part of your reasoning) but I'm not going to switch to an app that doesn't bring all of my messages across.

**Comment by 722C** [comment]
@klinker24, is the limit something that could be worked around via the `Resync Messages` functionality (or something similar) that the user initiates?

**Comment by klinker24** [comment]
The limit is something that I created, and I did so on purpose... A workaround is not currently planned, sorry.
