### ISSUE TITLE
Switching back to Pulse sometimes opens random conversation thread

### ISSUE THREAD

**Issue by wizard7926** [klinker-apps/messenger-issues#452]
**Device with issue:** Verizon LG G5 running 7.0
**App version:** 2.5.5.1504
**Steps to reproduce:**

1. Switch out of Pulse to another application, either from a conversation or from the conversation list
2. Use other application (or minimize entirely to home screen and turn screen off)
3. When I re-open Pulse, sometimes it will pull open a conversation seemingly at random, often not even from that day. This happens probably.. <10% of the time? If I had to guess?

I can't get it to reproduce on a consistent basis, but it happens enough that I wanted to mention it here. Thank you.

**Comment by klinker24** [comment]
I haven't heard of this before.

Does it display that conversation as already open, or do you see the opening animation when you return to the app?

Unfortunately I will probably need some steps to reproduce it before I have any idea where it is coming from..

**Comment by wizard7926** [comment]
It shows the opening animation as I'm returning to the app. 

Sorry I don't have more specific info, but I'll keep a closer eye on it and see if I see any patterns.

**Comment by klinker24** [comment]
Sorry, that isn't really what I mean. When you click a conversation to open it in Pulse, it will animate open. I am wondering if you see that animation when you return to the app, or if it is just there, like the conversation opened in the background.

**Comment by wizard7926** [comment]
Yep, that's what I meant! When I return to the app, it's as though I'm catching it in the act of opening a random conversation. It's almost like the act of pressing Pulse on the Recent Apps screen is actually pushing a specific conversation.

**Comment by wizard7926** [comment]
Gotta head out - I'll try to update if I have any more clues. Hope that helps.

**Comment by klinker24** [comment]
Unfortunately it doesn't help much.. I will need more information to solve this.

**Comment by klinker24** [comment]
I made some changes here to ensure the extras on the intents are always getting cleared after they are used.

https://github.com/klinker41/messenger/commit/967c9ef442eec41e192cbee5d1ad48fc4c66ae33

This may or may not be the issue. I wasn't seeing the case where it could affect this issue, but there isn't really anywhere else that could be causing it. It will be released with the next version. You can close it if you think this is finished.

**Comment by klinker24** [comment]
This was released in yesterday's update. If you could try it over the next few days @wizard7926 and let me know if it is fixed, that would be great.

**Comment by wizard7926** [comment]
Hey there, apologies for not checking in, been on vacation. Unfortunately I haven't noticed a change - still popping up here and there. It's not the end of the world, just can't seem to put a finger on a pattern or why it's still doing it. Thanks for dedicating some time to work on this.

**Comment by klinker24** [comment]
Thanks for the follow up, I will continue to watch this and dig into it to see if I can come up with more information.
