### ISSUE TITLE
Duplicate messages on long conversations

### ISSUE THREAD

**Issue by Flameslicer** [klinker-apps/messenger-issues#453]
**Device with issue:** LG V20 on Android 7.0
**Primary device:** LG V20 on Android 7.0
**App version:** 2.5.6.1518

**Steps to reproduce:**
1. Enter a conversation with a large amount of messages (bit over 30k in my case)
2. Send a new message

**Additional information:**
Exiting the conversation or sending another message fixes it temporarily until I send another message, and it doesn't seem to show up on the chrome app when I use that.
![capture _2017-09-09-17-08-56](https://user-images.githubusercontent.com/8893110/30244347-2274e8fe-958a-11e7-8ba9-55154e7978b0.png)

**Comment by klinker24** [comment]
I don't have a conversation with 30k messages, so can you describe this a bit more? They aren't duplicated until you send a message? How many get duplicated? I only see the one. You will need to provide more information on this

**Comment by Flameslicer** [comment]
A couple short videos to better explain what I'm trying to describe. Sorry for the added step.
[Bug Report.zip](https://github.com/klinker-apps/messenger-issues/files/1290137/Bug.Report.zip)

**Comment by Flameslicer** [comment]
Also, both the "reply soon", and the "and GOOD" messages in the screenshot in my initial report are duped.

**Comment by klinker24** [comment]
That is interesting. There is actually a newer beta available now. Could you try with that? 

I assume that this is a new issue with the beta, that you hadn't seen before. I made changes around long conversations for `2.5.6`.

**Comment by Flameslicer** [comment]
It just started on 2.5.6.1518. And the latest beta update seems to have made it so now I see dupes on my end of the conversation as well.

**Comment by Flameslicer** [comment]
Though it is very possible I've simply not been noticing the ones on my end prior to this. Also, these fake dupes don't appear when using the pulse website on my phone. Only the app.

**Comment by klinker24** [comment]
Yes, this would only affect Android devices

**Comment by Flameslicer** [comment]
Seems to only happen on my one extremely long conversation as well, shorter ones don't seem to have the problem.

**Comment by klinker24** [comment]
I have fixed it with this commit: https://github.com/klinker41/messenger/commit/e359ad5c1bff27aa1906c49c6053fdb29130f3d3

I will put it out with the next version of Pulse, thanks for the help on this.

**Comment by Flameslicer** [comment]
No problem

**Comment by Flameslicer** [comment]
Though it is very possible I've simply not been noticing the ones on my end prior to this. Also, these fake dupes don't appear when using the pulse website on my phone. Only the app.
