### ISSUE TITLE
Default device tone used when in thread and a new message arrives for that thread

### ISSUE THREAD

**Issue by tickko** [klinker-apps/messenger-issues#454]
**Device with issue:** Pixel XL
**Primary device:** Pixel XL, 8.0.0
**App version:** 2.5.5.1504
**Steps to reprod:** 

1. Open a conversation thread
2. Receive a message from a member of the thread you are viewing and the tone will be the device default tone, not the tone that was assigned in Android 8.0 Notification Settings for Default Conversation Notifications.

**Comment by klinker24** [comment]
Fixed with: https://github.com/klinker41/messenger/commit/0d1a05776dcad4c0be36555743c6befd95833712
