### ISSUE TITLE
MMS receiving issues for Xiaomi phones under MIUI

### ISSUE THREAD

**Issue by vincentvidal** [klinker-apps/messenger-issues#456]
**Device with issue:** Xiaomi Mi 5
**Primary device:** Xiaomi Mi 5
**App version:** 2.5.6.1536

**Problem:**

MMS cannot be received: they do not appear anywhere and are completely lost. I did not put that message in the existing MMS issues thread as it seems to very specific to Xiaomi phones.

**Potential cause:**

After googling a lot, this problem is related to all Xiaomi phones under MIUI roms: most third-party messaging apps do not receive MMS.

**Potential solution:**

However, Textra SMS manages to receive MMS. There are two settings for handling SMS defined in the parameters: "System" and "Heritage". "System" does not work at all even for sending MMS, but "Heritage" works well. In this mode, the APNs can be redefined just as in Pulse, but this is not useful: everything works well without redefining them.

They probably implemented some kind of workaround, or used a different method, I don't know, but it would be great if a similar solution could be implemented in Pulse. Xiaomi users are more and more numerous ;-)

cheers
Vincent

**Comment by klinker24** [comment]
I am going to link this to the other MMS issue instead. 

Pulse does have a method to input your own APN settings and it will attempt to send the MMS itself. If that isn't working, it isn't really a device specific issue, it is just an issue with the SMS/MMS library we made: https://github.com/klinker41/android-smsmms

#101
