### ISSUE TITLE
Conversation not re-opening on orientation changes

### ISSUE THREAD

**Issue by ACE3CGL** [klinker-apps/messenger-issues#458]
**Device with issue:** <Samsung Galaxy S8+ on Android 7.0: "MacBook Pro on MacOS 10.12, running Chrome v54">
**Primary device:** < Samsung Galaxy S8+ on Android 7.0"Pixel XL on Android 7.1.2">
**App version:** <2.5.5.1504: in "My Account" on the phone>
**Steps to reproduce:**

1. Open conversation
2. Begin typing message
3. Change screen orientation. This exists the conversation and goes to conversation list instead of allowing you to continue your message.
 
**Possible solution:**

Make it so that changing orientation doesn't exit your conversation.

**Comment by klinker24** [comment]
The conversation should be reopened and the draft reapplied.

**Comment by ACE3CGL** [comment]
Is there any way to change this? My phone's native messenger does not do this.

**Comment by klinker24** [comment]
Change what? This isn't an SMS feature. The design of Pulse is what causes this behavior.

**Comment by ACE3CGL** [comment]
So it was done intentionally? I know it's a minor issue, but I prefer to read my messages in one orientation and type them in a different orientation, and I can't see how its current design boasts user functionality compared to just allowing me to resume my message.

**Comment by klinker24** [comment]
The first thing I said was that it is supposed to reopen the conversation. Could you respond on that comment?

The way the app is designed, with fragments inside the activity is what gives it it's entire feel, with animations, swiping to get out of the conversations, and more. That won't be something I am willing to re-architect. That style is what makes Pulse feel unique, polished, and why so many people have latched on to it.

**Comment by ACE3CGL** [comment]
No, it does not reopen the conversation.

I understand and agree whole heartedly. I purchased the lifetime subscription because I believe in the product. I'm not asking you to re-architect the app over an annoyance I admitted was minor. I don't develop, so I didn't know if it was something that could be resolved by a few lines of code or not.

**Comment by klinker24** [comment]
If it isn't reopening the conversation, then this is simply a bug. Thank you for the report.

**Comment by klinker24** [comment]
This should be fixed with: https://github.com/klinker41/messenger/commit/8da4f7c8676e60399aa6f3e448d057132f79e267

It will be released with the next version of the app.
