### ISSUE TITLE
Received messages switching to sent (specific scenario)

### ISSUE THREAD

**Issue by AjaiRup** [klinker-apps/messenger-issues#46]
**Device with issue:** Nexus 5X running Android 7.0
**Primary device:** Nexus 5X running Android 7.0
**App version:** 1.1.216
**Steps to reproduce:**

1. Receive a SMS message right-before/while sending a MMS message (within the same conversation)
2. Received SMS message shows notification, but then appears on sent side

**Additional information:**
This has happened three times so far; all three times it was the same exact scenario.

**Comment by klinker41** [comment]
fixed with https://github.com/klinker41/messenger/commit/c96828c6be443b2ff3ed6a61f9a6bf7b5d60c718
