### ISSUE TITLE
View contact information

### ISSUE THREAD

**Issue by r41lblast** [klinker-apps/messenger-issues#460]
*No description provided. Description created by @klinker24*

On the web, there is no way to get conversation information, such as the phone number of the user. Since this is available on Android, it should also be made available on the web.

**Comment by klinker24** [comment]
Added a "Conversation information" item in the three dot overflow of the web, similar to Android: https://github.com/klinker41/messenger-web/commit/8a5295d995b12fdcd89b78d49dbec583d90f5033

It has the title and the phone numbers involved in the conversation, right now.
