### ISSUE TITLE
Display the SIM card that a message was received to

### ISSUE THREAD

**Issue by r41lblast** [klinker-apps/messenger-issues#464]
*No description provided. Description created by @klinker24*

On Android, we can see which SIM card a message was received to, right next to the timestamp. The web should also have this functionality. It could be placed in the `title text`, similar to the timestamp (#383)

Todo: 
- [x] track the SIM stamp on the backend
- [x] display it on the web front end
- [x] Android: send the SIM stamp within the requests

**Comment by klinker24** [comment]
Track the SIM stamp on the backend and provide it across devices: https://github.com/klinker41/messenger-server/commit/dcb1741b45b139c1ad6854336ad06c581b549eb4
If a SIM stamp exists, display it on the web: https://github.com/klinker41/messenger-web/commit/bc21beda6bf7ce757f80648659d2ee9a5b3acef8
Send up the sim information from android: https://github.com/klinker41/messenger/commit/81d957193b8aeff9348a847a7fb03d9e8d30dad8

This will be released with the next version of the Android app.
