### ISSUE TITLE
Hide menu bar until "alt" is pressed on Windows

### ISSUE THREAD

**Issue by JacobDB** [klinker-apps/messenger-issues#466]
**Device with issue:** Surface Laptop on Windows 10 Pro 1703 (OS Build 15063.608)
**Primary device:** Pixel XL on Android 8.0.0
**App version:** v1.0.0-beta1
**Steps to reproduce:**

1. Open the new native client on Windows 10 desktop
2. Observe the toolbar

**Additional information:**

Many modern applications now hide the menu bar by default, until pressing the alt key. See Firefox for example. 

**Possible solution:**

I'm unable to find documentation on how to achieve this, but I did find [this related issue for Atom](https://github.com/atom/atom/issues/2914). As it's also built on Electron, I imagine a similar approach can be taken.

**Comment by klinker24** [comment]
Hmm, I will consider adding this. That seems very strange to me, to be honest. I highly doubt that very many people know to press "alt" to show the menu bar. There is extremely low visibility around that.

**Comment by JacobDB** [comment]
Fair point. I'm nitpicky with UI stuff, and menu bars look ugly/unnecessary to me. Additionally, that portion of the UI is used so little that I don't think it make a whole lot of sense for there to be a dedicated section always displaying it. If it's possible, maybe a setting to toggle this would be better. That, or moving these controls in the Settings area of the app.

**Comment by klinker24** [comment]
Finished with: https://github.com/klinker41/messenger-chrome/commit/5e31d5dba320e286171cb34c8d516b6283650c59

It will come out with `1.0.0-beta3`.
