### ISSUE TITLE
Submit to the Windows Store

### ISSUE THREAD

**Issue by JacobDB** [klinker-apps/messenger-issues#467]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [x] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** Surface Laptop on Windows 10 Pro 1703 (OS Build 15063.608)
**Primary device:** Pixel XL on Android 8.0.0
**App version:** v1.0.0-beta1
**Steps to reproduce:**

1. Open the store on Windows 10
2. Search "Pulse SMS"
3. Observe lack of application results

**Additional information:**

I wouldn't expect this to happen until it's out of beta, but wanted to pre-emptively log an issue for tracking purposes. Putting it in the store would be great to increase visibility.

If you do decide to put it in the store, it'd be awesome if you could make the Windows version use a "Modern" icon (i.e. Windows-style), as just the white SMS text bubble, with the lines cut out to be transparent. See the Windows 10 Mail app for example.

I was able to extract an SVG of your logo from the web interface, and created a "Windows-style" icon for you, which I've attached below (note I used black for the PNG for visibility; the proper color is white, as in the SVG); I'd say this would be best used for the Store version of the app, leaving the EXE as-is.

![pulse-metro_dark-demo](https://user-images.githubusercontent.com/1123997/30649803-e0f9dce4-9de6-11e7-93f1-2af48dd8d295.png)

GitHub won't let me actually upload an SVG, so code for it is below.

    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 128 128">
        <title>Pulse SMS</title>
        <path fill="#FFFFFF" d="M116.7,0H11.3C5.1,0,0.1,5.1,0.1,11.3V74v54l28.1-28.3h88.6c6.2,0,11.3-5.1,11.3-11.3V11.3 C127.9,5.1,122.9,0,116.7,0z M46.4,81H18.9V66.8h41.8L46.4,81z M70.5,57H18.9V42.9h65.9L70.5,57z M94.8,32.9h-76V18.8H109 L94.8,32.9z" />
    </svg>

**Possible solution:**

Submit to the Windows Store upon final release

**Comment by klinker24** [comment]
Sorry, that isn't planned, at this point. I am just going to be distributing it myself, rather than managing it on the Windows Store. That is just one more place to manage and distribute the app, and there isn't a whole lot of incentive in that. It doesn't provide any extra visibility, since the user needs to install the Android app and go through my web interface anyways. Having it distributed on the stores would just lead to confusion about what is required and how to use the app.

I will just be distributing the installation files on my own, right now.

**Comment by JacobDB** [comment]
That makes sense, thanks for the expination.
