### ISSUE TITLE
Error when returning from hibernation

### ISSUE THREAD

**Issue by JacobDB** [klinker-apps/messenger-issues#468]
**Device with issue:** Surface Laptop on Windows 10 Pro 1703 (OS Build 15063.608)
**Primary device:** Pixel XL on Android 8.0.0
**App version:** v1.0.0-beta1
**Steps to reproduce:**

1. Open Pulse SMS desktop client on Windows 10
2. Put the machine into hibernation (i.e. close the laptop lid for a few moments)
3. Log back into the PC and see error pasted below.

**Additional information:**

Do you want to provide any other information? Device configuration, unique cases, screenshots, anything that you think may be relevant.

![image](https://user-images.githubusercontent.com/1123997/30659100-7464d5b8-9e02-11e7-8d6a-ccdf92088e25.png)

**Comment by jwkicklighter** [comment]
Same issue on MacOS
![screen shot 2017-09-20 at 19 23 00](https://user-images.githubusercontent.com/1447947/30672222-22ea500a-9e39-11e7-9287-bd97ab6e4ced.png)

**Comment by klinker24** [comment]
Fixed with: https://github.com/klinker41/messenger-chrome/commit/4e09947e92287a076f1d5c319332138b21dd83f6
