### ISSUE TITLE
Notification opening second instance of application

### ISSUE THREAD

**Issue by timmytot666** [klinker-apps/messenger-issues#473]
**Device with issue:** Ubuntu Linux Desktop Client
**App version:** Desktop Beta 2
**Steps to reproduce:**

1. Have Pulse native running,
2. Get a message pop up in the notification center,
3. Click Message
4. Another instance of Pulse SMS opens up instead of opening the current process.

**Comment by klinker24** [comment]
Does this happen every single time for you? I am not able to reproduce it

**Comment by timmytot666** [comment]
Yes.

**Comment by klinker24** [comment]
What version of Ubuntu are you on?

**Comment by timmytot666** [comment]
16.0.4.3 let's xenial

**Comment by captnpineapple** [comment]
I also get this on Windows 10 client, same steps as above.

**Comment by klinker24** [comment]
Fixed with: https://github.com/klinker41/messenger-chrome/commit/0b543bbba8dbdc5d9e3dbfd0d106410bdc642610

It will be released with `v1.0.0-beta3`.
