### ISSUE TITLE
View bottom is not bound to screen height

### ISSUE THREAD

**Issue by tannerhallman** [klinker-apps/messenger-issues#474]
**Device with issue:** Regular Pixel Android 8.0
**Primary device:** Regular Pixel Android 8.0
**App version:** 2.5.7.1591
**Steps to reproduce:**

1. app in foreground
2. Switch apps so that its in background again
3. Come back to app using double tap on apps button (software bottom right square button)
4. Fragment or container that's holding the main content body loses its height and cuts off content. Content in main container still scrolls, but the bottom of the view no longer matches the constraint of the whole screen. It looks like it's lost its link with the view and is floating in the middle.

`... more steps`

**Additional information:**

Do you want to provide any other information? Device configuration, unique cases, screenshots, anything that you think may be relevant.

![screenshot_20170928-104001](https://user-images.githubusercontent.com/10327491/30972918-e4506364-a439-11e7-907d-32f146f0fa5d.png)

![screenshot_20170928-104309](https://user-images.githubusercontent.com/10327491/30972930-e8e9f5a2-a439-11e7-8fb0-16f86edba508.png)

**Comment by klinker24** [comment]
This should already be fixed for the next version of the app, thank you for the report. It will be `2.5.8`, when it is released.
