### ISSUE TITLE
Unable to log into Pulse when multiple accounts exist on Android device

### ISSUE THREAD

**Issue by nblyumberg** [klinker-apps/messenger-issues#475]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [x] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** HTC 10 on Android N
**Primary device:** Pixel XL on Android O
**App version:** 2.5.7.1591
Attempt to set up "Message from any device"

1. Add multiple accounts to a device
2. Open Pulse
3. Attempt to use "Text from any device" functionality
4. Follow through prompts

When trying to set up Text from any device there's no option to pick which Google account on the device you want to use. There's no way to log if you already have a subscription.

**Comment by klinker24** [comment]
That isn't really the way that the Play Store works. All I can do is ask them if you have purchased the app, they handle which accounts are checked, etc. If you check out this FAQ topic, it walks through the steps to take if Google doesn't notify the app about your subscription:

![screenshot_20170928-121904](https://user-images.githubusercontent.com/4874287/30980699-87f9a068-a447-11e7-9aca-8502a46ba73d.png)

There isn't really anything I can do to "solve" this problem. I don't have direct access to purchases and rely on the Play Store to provide all of that. Unfortunately, they really suck at it sometimes. Not sure if their servers go down or are overloaded of what. You can find countless stories from developers struggling with restoring purchases.

**Comment by nblyumberg** [comment]
If you download and look at how News Republic handles this, they appear to enumerate the accounts available on the device and prompt which account should be validated against Google's subscription services. It's looks like it's possible to select which account is used for validation. 

![Image of New Republic implementation](https://imgur.com/a/Jk5LT)

**Comment by klinker24** [comment]
You image doesn't work. Admittedly, that isn't really something I am interested in. This is a bug on Google's end and they don't have any documentation around querying the accounts or validating against specific accounts, so that is definitely something I would be extremely hesitant to rely on

**Comment by nblyumberg** [comment]
Sending the image directly and hope it works

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
