### ISSUE TITLE
Firefox Plugin Slightly Too Zoomed In

### ISSUE THREAD

**Issue by DavidCao22** [klinker-apps/messenger-issues#476]
- [X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [X] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** Firefox 56.0, Windows 10
**Primary device:** Google Pixel, Android 8.0.0
**App version:** 2.5.7.1591

**Steps to reproduce:**
1. Install Pulse SMS extension on Firefox
2. Log in to extension
3. Extension is too zoomed in

**Additional information:**
While it is too zoomed in, it is still usable. The extra zoom is very small UI issue and honestly not that big a deal. 

The Settings page ends a little too close to the bottom.
![zoomedpluginsettings](https://user-images.githubusercontent.com/10539139/31060755-67be4878-a6de-11e7-8013-59d24fe291f2.png)

The create new message button is cut off a little at the bottom.
![zoomedpluginmessages](https://user-images.githubusercontent.com/10539139/31060753-67bd9982-a6de-11e7-8afd-c351c2863488.png)
![zoomedpluginscheduled](https://user-images.githubusercontent.com/10539139/31060754-67be21ea-a6de-11e7-93d8-5a4fc6484c8b.png)

**Possible solution:**
Probably just need to zoom out a little.

**Comment by klinker24** [comment]
It isn't zooming. It is the options bar at the top of the screen. You should just disable it. I don't know why firefox treats the layout differently than Chrome.

**Comment by DavidCao22** [comment]
Ah, disabling the options bar in the Addons Manager solved the issue. Thanks!
