### ISSUE TITLE
Compact Theme ER

### ISSUE THREAD

**Issue by dougjt** [klinker-apps/messenger-issues#477]
**Device with issue:** N/A
**Primary device:** "nexus 6p on LinneageOS 14.1"
**App version:** 2.5.7.1591

Enhancement Request for compact theme - higher density conversation list  with reduced line spacing. Desirable for all platforms, but obviously, priority highest for phone itself. See gmail browser interface settings for an example ("comfortable," "cozy," "compact")

**Comment by klinker24** [comment]
To be honest, I don't see this ever coming. By squeezing the padding, you might get one extra conversation to show up on the list, but that isn't worth it for me.

With Pulse, I don't want an app that you need to go into settings and tweak every little UI detail exactly the way you like it. That distracts from the goal of the app, which is to provide an awesome feature set. Digging through settings menus to set up the app is not at all an ideal situation for the vast majority of users.

The padding I use across the different platforms comes from the Material Design guidelines, recommendations
