### ISSUE TITLE
Add a chrome extension

### ISSUE THREAD

**Issue by klinker41** [klinker-apps/messenger-issues#48]
**Device with issue:** Nexus 6P running Android 7.0
**Primary device:** Nexus 6P running Android 7.0
**App version:** 1.0.2

**Information:**

Some users want a chrome extension alongside the chrome app... ok I suppose we can do that. Will be hopefully as easy to whip up as the chrome app was, just a simple web wrapper again should do it.

**Comment by klinker41** [comment]
This will also be nice for once Chrome no longer supports Chrome Apps outside of Chrome OS.

**Comment by klinker41** [comment]
done with https://github.com/klinker41/messenger-chrome/commit/1e6d8dcc886989ffd885058e22f5823d440f8485.

![screen shot 2016-09-01 at 11 58 46 am](https://cloud.githubusercontent.com/assets/4501322/18176579/c8fbd05e-703b-11e6-8c84-301235eb7dd9.png)

Luke, can you put this up for me?

**Comment by klinker24** [comment]
In the process of uploading now.

**Comment by klinker24** [comment]
Live here: https://chrome.google.com/webstore/detail/messenger/jjbjdleccaiklfpcblgekgmjadjdclkp

**Comment by klinker24** [comment]
I do want to add some more visibility for this and the chrome app to our website as well, so that users go toward them instead of the web, if possible.
