### ISSUE TITLE
Select all messages inside a conversation

### ISSUE THREAD

**Issue by NovaViper** [klinker-apps/messenger-issues#480]
I find it very annoying that I have to select every single manually inside  conversation in order to delete them. Say of there are certain messages I wanted to delete but leave all of the other ones in tact; I'd have to hunt and select every message I don't want (especially when it's a lot of them). It's kinda counterintuitive when you could just select every message and then just deselect the ones you want to keep. Would really appreciate if there's a button to select every message inside a conversation.

**Comment by vealeymatthew09v** [comment]
Ye

**Comment by klinker24** [comment]
This is done.

https://github.com/klinker41/messenger/commit/4eee0c0880c57f485fbbdca795e8da5495220ce2
