### ISSUE TITLE
Recieve 2 notifications

### ISSUE THREAD

**Issue by JariVanBoven** [klinker-apps/messenger-issues#481]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [x] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** Windows 10 running native app
**Primary device:** OnePlus 3t
**App version:** Beta
**Steps to reproduce:**

1. Download and use native desktop app

**Additional information:**

When enabeling notifications from the desktop app, you recieve 2 notifications. When you disable it, only 1 notification is shown.

**Comment by klinker24** [comment]
In the FAQ section, I talk about notifications. https://messenger.klinkerapps.com/help

Each platforms on the computer provides separate notifications.

1. If the web is open, it will have notifications
2. The chrome app and extension each provide notifications
3. The native apps provide notifications

Turn off notifications for the desktop platforms you don't want them on.

**Comment by JariVanBoven** [comment]
I now about this. The thing is that the notifications are in Windows 10 style and NOT in Chrome style... So does the Chrome apps produce Windows style notifications???

**Comment by klinker24** [comment]
The chrome apps should produce notifications in whatever style is normal for the platform you are on.

**Comment by JariVanBoven** [comment]
I know what went wrong: I receive 2 notifications from the Windows app because there was an emoticon in the name of my contact. I deleted the emoticon (a bird) and it works now.
