### ISSUE TITLE
Contact Photos on Group Messages

### ISSUE THREAD

**Issue by c3ccl3ston** [klinker-apps/messenger-issues#482]
- [✓] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.

For group messages, instead of showing a general group icon, even for messages that have contacts with photos, the icon should be some kind of combination of the existing contact photos with icons for those without photos. Android Messages has a similar feature in cases were group messages have contacts with photos.

**Comment by klinker24** [comment]
Sorry, this is not something I plan to do. 

Combining profile pictures looks terrible in my opinion. They are always tiny, bunched together, and just don't look good. This leads to a busy UI that doesn't really provide any extra benefit, since the images are too small to be helpful

**Comment by c3ccl3ston** [comment]
Thanks for the response. I complete understand your point but as someone who has spent a decent amount of time ensuring that my contacts all have photos, showing a default group icon seems to also take away from the UI as well. All of my messages show with their contact photos and sprinkled throughout are default group icons.

With that said, what are you thoughts of allowing a custom group message icon that if not set would just be the default group icon? Something along the lines of what WhatsApp lets a user do with group icons.

**Comment by klinker24** [comment]
Yes: https://github.com/klinker-apps/messenger-issues/issues/133

**Comment by c3ccl3ston** [comment]
Great! Sorry that I didn't search for this before replying. BTW, I really love this application and the features that you have implemented. In the future, if you ever need help with testing please feel free to reach out.
