### ISSUE TITLE
Spell Correction and auto caps

### ISSUE THREAD

**Issue by xlankex** [klinker-apps/messenger-issues#483]
Not sure when this update pushed, but this started happening to me today.  Pulse is stopping my keyboards from correcting spelling errors, inserting a . after double space and blocking autocorrect.

**Comment by klinker24** [comment]
I already fixed it.

**Comment by xlankex** [comment]
Hmmm, showing I'm up to date.  Suggest an uninstall and reinstall?

**Comment by klinker24** [comment]
No. I mean I fixed it for the next version.

**Comment by xlankex** [comment]
Got it.  I'll hold tight then. Thanks for the prompt response.
