### ISSUE TITLE
Contact photo not updating in conversation list

### ISSUE THREAD

**Issue by h20534** [klinker-apps/messenger-issues#484]
**Device with issue:** <Moto X Pure on Android 7.0>
**App version:** <2.5.9.1628>
**Steps to reproduce:**

1. Have picture for contact, Pulse displays it in conversation list
2. Update a contact pic, pulse shows new contact pic in lockscreen notifications, but not in converesation list
3. Tried closing out app completely, and restarting phone with no success

**Comment by klinker24** [comment]
This is here

https://github.com/klinker-apps/messenger-issues/issues/133
