### ISSUE TITLE
Intentional Vibration On App Open?

### ISSUE THREAD

**Issue by DavidCao22** [klinker-apps/messenger-issues#485]
- [X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [X] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** Google Pixel
**Primary device:** Google Pixel on Android 8.0.0
**App version:** 2.5.8.1625
**Steps to reproduce:**

1. Open Pulse SMS app
2. Opening the app causes 2 short vibrations

**Additional information:**
Opening the app makes my phone give 2 short vibration pulses. Is this intended behavior? I have closed the app, opened other apps, then reopened Pulse. It still gives the same vibrations, so I know it is from the Pulse app.

I usually have my phone on vibrate, so this behavior makes me think a new text just came in as I opened the app. It's unexpected behavior, and I was wondering what the reasoning is behind it. Can it be turned off or made optional?

**Comment by klinker24** [comment]
I would imagine that you turned on vibration for some notification channel. You can just go to settings and turn them all off, other than the conversation ones.

**Comment by DavidCao22** [comment]
Hmmm..... it was the notification channels. "General notifications" was on urgent importance. Turning it to medium importance stopped the vibrations. 

What does each notification channel mean? There's failed messages (seems obvious enough), general notifications (?), status notifications (?), message group summaries (?), status notifications (again?), test notifications (for testing example notifications).
