### ISSUE TITLE
Focus on text entry when returning to app

### ISSUE THREAD

**Issue by theepiphany** [klinker-apps/messenger-issues#486]
When using the Mac App you need to actually click where you would type the message which isn't the most obvious place to click due to the seamless nature between it and the conversation. It would be ideal that if you focus the window it defaults to the edit box (or select a new coversation, etc).

**Comment by klinker24** [comment]
It should be doing this already. Does it auto focus on the text entry on the web, for you?

**Comment by theepiphany** [comment]
Apologies: You are correct, when switching conversations the edit box does indeed focus. When you switch out of the window via alt-tab or some other method and switch back the edit box loses focus, however.

**Comment by klinker24** [comment]
This has a web component: https://github.com/klinker41/messenger-web/commit/e966b01ee0139ffbc77bd16e7e0f665eec260427

and a native app component: https://github.com/klinker41/messenger-chrome/commit/c3b1b7c31038736a3175e8e39b76a8608870162f

It will be released with the 5th beta of the native app, when it is ready.
