### ISSUE TITLE
Sign Windows installer

### ISSUE THREAD

**Issue by dcreed** [klinker-apps/messenger-issues#487]
**Device with issue:** <HP ENVY 360x Windows 10 Pro>
**Primary device:** <Samsung S8+>
**App version:** <Beta 4.0 Windows>
**Steps to reproduce:**

1. App downloaded latest update
2. McAfee total protect flagged file as potentially Malicious and quanteened the file.  
3. Ran file through Virus total and received 1 alert.  
4. Downloaded file manually to install and Windows Defender displayed an unknown application error 

**Additional information:**

Screen Shot
![pulse sms screen shot](https://user-images.githubusercontent.com/32619370/31577175-ff72ad1e-b0d7-11e7-8774-dda5481a1a5b.png)

**Possible solution:**

Sign Installer File

**Comment by klinker24** [comment]
I will generate a signing key when the app comes out of beta.

**Comment by dcreed** [comment]
Awesome, thanks for the quick response! Really enjoy the app!

**Comment by klinker24** [comment]
This is done. I will release the signed version of the Windows app with RC3.

This will enable auto updates and will need to be manually installed by anyone that used the `beta` and `rc` versions of the desktop app.

https://github.com/klinker41/messenger-chrome/commit/728e3f8e06a260c0c78533a02b486a00c428e4b1
