### ISSUE TITLE
Desktop apps need version number

### ISSUE THREAD

**Issue by Fammy** [klinker-apps/messenger-issues#488]
**Device with issue:** Windows PC running Windows 10 
**Primary device:** Nexus 6P on Android 8.0
**App version:** Windows Desktop beta 4, I think
**Steps to reproduce:**

1. Open Windows desktop app
2. Click Help
3. Wonder why there is no" About" menu item ;)

**Possible solution:**

Add a Help/About or similar menu item that shows the current version number. Auto-update is working so far, but I am really good at breaking computers—it's my super power. It would be nice to ensure I'm running the latest version of the desktop app.

**Comment by klinker24** [comment]
Added to the 'help' section. https://github.com/klinker41/messenger-chrome/commit/7af697b3a98abed6285c6d66e161334b048eb637
