### ISSUE TITLE
Wrong contact associations with companies

### ISSUE THREAD

**Issue by lalibi** [klinker-apps/messenger-issues#491]
**Primary device:** Nexus 6P
**App version:** 2.5.9.1628
**Steps to reproduce:**

1. Have a contact (or more) with the `Company` field filled, with a value like `Vodafone` or `Eurobank`.
2. Get a message from your mobile carrier, your bank or any other company that sends SMSs that, when the arrive, show up a literal as the phone number (e.g. `Vodafone` instead of something like `1234`).
3. The conversation thread gets associated with one (randomly?) of your contacts that work for this company and have the exact same literal in their `Company` field.

**Additional information:**

I've seen similar (solved) issues, I've even commented in one of them, but this issue in my phone still persists. In those issues the gist is that this association is done upon installing (or when you first open the app rather), so even if you update to a new version, which solves the issue, the problem still exists.

I've already uninstalled and cleared the data several times. I don't have an account, so I don't think it synchonizes the data somehow.

The last couple of days it got even trickier. I have three friends working for `Vodafone`, and the messages I recieve from my carrier show up as sent from my friend `Alice`. Last night I talked to my friend `Bob`, and after that `Bob's` picture and name shows up in that conversation list (association changed after calling?). At some point I had the name of my friend `Alice` and the picture of my friend `Chris` show up in my carriers message thread.

**Comment by klinker24** [comment]
This is definitely different than any other issues around this. I will have to consider how to handle this, thanks.

The issue is that I am just asking your contacts app if any contacts match the message that comes in, using their generic query uri: `ContactsContract.CommonDataKinds.Phone.CONTENT_FILTER_URI`

Those contacts match based on the company as well, I guess. I will see what I can do.

**Comment by klinker24** [comment]
Can you test a new version for me? If you unzip this file and install it, I *think* this issue should go away, but I don't really have a way to verify it. You will want to clear the app data to start from scratch.

[messenger-2.6.2.1721-release.apk.zip](https://github.com/klinker-apps/messenger-issues/files/1458141/messenger-2.6.2.1721-release.apk.zip)

**Comment by lalibi** [comment]
I just did, and it seems to do the trick!
