### ISSUE TITLE
Display notification marker

### ISSUE THREAD

**Issue by davidMGS** [klinker-apps/messenger-issues#492]
Is there an intention to display unread message notification marker on the dock icon similar to how slack and other messaging apps display a red dot? I tried searching through the open and closed issues, but had no luck finding any mention of this.  Pretty happy with the app overall.

**Comment by klinker24** [comment]
This may be relevant. https://github.com/cadecairos/electron-mattermost/blob/c1ea367723f80974de21051cf89bb6262a78ff6f/src/main.js#L108

**Comment by klinker24** [comment]
This is done for Mac and Linux. It cannot be supported for Windows. It will be released in the next version of the desktop app.

The counter is refreshed when messages come in, when conversations are marked as read across devices, or when the app is started

https://github.com/klinker41/messenger-chrome/commit/03d8d65fd410ac7a9c8c0fdd4721d6b797542b13
https://github.com/klinker41/messenger-chrome/commit/871bf507506d238b4d5078862f2be9b93120b884
https://github.com/klinker41/messenger-chrome/commit/fc697ec62f94afbd6c1f602b8c3917cb0fdc3fb6
