### ISSUE TITLE
Clicking desktop notification doesn't mark message as read 

### ISSUE THREAD

**Issue by kirstilynn** [klinker-apps/messenger-issues#494]
**Device with issue:** MacBook Pro on MacOS 10.12
**Primary device:** Pixel XL on Android 7.1.2
**App version:** Mac Desktop v1.0.0-beta6
**Steps to reproduce:**

2. Click on the "New Message" desktop notification when you get a new message
3. The side bar preview shoes the message as unread, even though it should be marked as read.

![pulse_unread_message](https://user-images.githubusercontent.com/6012549/32341188-65b67724-bfc2-11e7-835f-6c752f21527f.png)

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/messenger-web/commit/f93b625c0ae40a2d43915dc8caa7448ef328c615
