### ISSUE TITLE
Photos not displayed

### ISSUE THREAD

**Issue by Skullmonkey** [klinker-apps/messenger-issues#497]
**Device with issue:** Pixel XL Android 8.1
**Primary device:** Pixel XL Android 8.1
**App version:** 2.6.0.1695
**Steps to reproduce:**

1. Open conversation
2. Go to hamburger menu and select "View Media"

**Additional information:**

Some of my MMS that I have sent are not showing up in the view media list or in the conversation. It seems to be random. I have photos that I have sent when I first purchased the app that I can still view but I can't see one that I sent today. In conversation view and in the view media menu, they appear as white squares. They are selectable to open but when I try to, it just opens to a black screen.

View media list: https://imgur.com/zxgheQC
Conversation view: https://imgur.com/BcMj6PS

**Comment by klinker24** [comment]
Did you restore your account from the cloud today, or did they just randomly disappear? I am not sure I fully understand your situation. If the images don't appear in the message list, they will not appear in the media grid either.

There are issues downloading images from the cloud when you log in to the account. It will download some, but it just silently fails on others. I don't know why this is at this time.

**Comment by Skullmonkey** [comment]
I have not restored from the cloud. They seem to be just randomly disappearing. Like I said, I sent a picture message today (~4ish hours ago) and that one has also disappeared. But one that I send back in September in the same conversation does appear and works like normal.

**Comment by klinker24** [comment]
I assume you are talking about the phone app and not a tablet or something.

**Comment by Skullmonkey** [comment]
Correct. I just checked the Chrome version and the images seem to be there. I may try clearing my data in the phone app and relogging in to see if they pop up again.

I am hesitant on resyncing my messages because there is one conversation in particular that I would like to keep all my messages on.

**Comment by klinker24** [comment]
Then you shouldn't use the resync preference, no. Logging in again may get some images and lose others.

**Comment by Skullmonkey** [comment]
Yeah, that is exactly what happened, I guess it is what it is for now. The last time I remember it working correctly is about a week ago.

**Comment by Skullmonkey** [comment]
Any movement on this?

**Comment by klinker24** [comment]
There are changes in an upcoming version on how messages get downloaded from the cloud. I don't have a clue why messages would just disappear on you though and that isn't something I have ever heard from others on. Not sure if you count that as "movement" or not.

**Comment by klinker24** [comment]
I am going to close this. With `2.7.0`, restoring images after logging in on a device is vastly improved. It will not get the entire history, where before it would get random pieces of the history.

Also, in the "view media" section, the app would display blank spaces for some types of media as well as if there was a youtube video or web article that was being previewed. This section is now only for media and it should show very few blank spaces, only if an image actually was deleted.

If you are still having problems, I recommend clearing the app data and logging in to the account again.

**Comment by Skullmonkey** [comment]
So just to clarify, will there be a set limit by actual MMS or is it by total messages? Say if I had 50 picture messages, would it only download 25 of my MMS every time I log in to a device?, or will it go to say last month and only pull those?

Sorry, just trying to get clarification in case I need to play MMS lottery to try and get some of the pictures back so that I can save them to my device.

**Comment by klinker24** [comment]
It will download the latest 250 images when you log in to any device.

**Comment by Skullmonkey** [comment]
Unfortunately, it seems that it still isn't pulling photos consistently. I have 107 that pulled without a hitch and then a blank page worth of media and then spotty downloads. I would say based on the blank spaces that I have about 200 photos from the conversation and none in the rest of my conversations.

**Comment by klinker24** [comment]
Only 20 images are pushed up when you create the account or when you refresh the account. You would never be able to look back further than that on a new device.
