### ISSUE TITLE
Double messages

### ISSUE THREAD

**Issue by gmathisz** [klinker-apps/messenger-issues#499]
**Device with issue:** Dell Precision 7510 with Windows 10 , PluseSMS v1.0.0.-beta6 app
**Primary device:** LG G4 with Android 6.0 Path level 2017-04-01
**App version:** 2.6.0.1695
**Steps to reproduce:**

1. Receive message twice on the windows app but not on the phone.

**Comment by klinker24** [comment]
Sorry I am going to need more detail. That step to reproduce were really just a restatement of the problem.

Some things that might be helpful:

* Is this happening in every conversation?
* Is it happening for every message?
* Does it happen when you open the conversation or when you have the app open and new messages come in to that conversation?
* Does refreshing the page fix it?
* Is it happening in the web?
* How long has this been happening?
* Is this an issue with notifications or the actual content?
* Can you provide a screenshot?

Right now, I don't know enough about the issue to do anything at all. I'm sure there are other relevant things, you should put them here as well.

**Comment by gmathisz** [comment]
I don't know how to reproduce the problem, it happens randomly on the Windows application only, On my phone this is not happening. I don't run the browser extensions on my machine just the application.
![image](https://user-images.githubusercontent.com/33425489/32496741-4519e0ee-c398-11e7-8e5e-5612df4e5529.png)

**Comment by klinker24** [comment]
Even without knowing how to reproduce it, I will need to know the answer to some of my questions:

* Does it happen when you open the conversation or when you have the app open and new messages come in to that conversation?
* Does refreshing the page fix it?
* How long has this been happening?

**Comment by gmathisz** [comment]
- I have seen this happen when the application is open.

- No, refreshing the page did not fix it.

- I have seen this happening in the last week.

**Comment by klinker24** [comment]
1. So has it only been happening in the last week, you hadn't seen this ever happen before, or you are just saying, in general, that this has happened in the past week.
2. You say you see it when the app is open. I am not sure we are on the same page for what I am asking about. Please read my description below, then provide your comments on what you think is happening. Be as specific as you can.

Pulse has two ways to load messages through the web/desktop platforms:

* the first way is by just clicking a conversation. When you open a conversation, it will load all the messages.
* if a conversation is currently open, then messages will get streamed in and loaded in real time. This is why you don't need to press the "refresh" button when a new message comes in. The browser knows when new messages arrive and loads those messages for you, automatically.

So, which of these cases is producing the duplicate messages? Are they just there when you open the conversation for the first time, or do they show up after you have had the app open on your computer, watching a conversation.

--- 

If you can provide me with more detail on the issue and where you are seeing it, that would be helpful. GitHub is a developer-centric site, so to report issues on this bug tracker, I am looking for concrete detail and a way that this can be reproduced. Without that, there is little chance that I will be able to make a real fix. I might be able to make a workaround, but I would like to prevent that and actually fix any issues in the app. 

So, the more detail you can provide, the better. Right now, I have not gotten the information I need to make a recommendation, or a fix, around this issue.

**Comment by gmathisz** [comment]
1. Yes it has been happening in last week, i have not seen this before, it does not happen all the time just sporadically.
2. This happens when a conversation is currently opened while i'm watching the conversation. Pressing refresh will not eliminate the duplicate messages.

**Comment by klinker24** [comment]
Thanks.

**Comment by klinker24** [comment]
This is fixed with: https://github.com/klinker41/messenger-web/commit/f7242aaf86e070b8c7ea8fbe47f3c16e75e2cdec
