### ISSUE TITLE
Group conversations not marked as read or deleted in internal content provider

### ISSUE THREAD

**Issue by klinker41** [klinker-apps/messenger-issues#5]
**Device with issue:** Nexus 6P running Android 7.0
**Primary device:** Nexus 6P running Android 7.0
**App version:** 1.0.180
**Steps to reproduce:**

For reading conversaitons:
1. Receive a group message
2. View it in Messenger
3. Confirm that it has been marked as read in messenger
4. Go to a different SMS app, for example evolve
5. Notice that it has not been marked as read here

For deleting conversations:
1. Receive a group message
2. Delete the group conversation
3. Confirm that it has been deleted in messenger
4. Go to a different SMS app, for example evolve
5. Notice that it has not been deleted here

**Additional information:**

Interestingly, this is one of the few cases where I took working code directly from Evolve and put it into Messenger, however it doesn't seem to be working here. This only applies to group messages, not individual conversations.

**Comment by klinker41** [comment]
fixed with https://github.com/klinker41/messenger/commit/d0d285b82db810695cb419cd0306ab30c016f2ab

**Comment by ghctim** [comment]
i also see this issue with messages that are regular messages.  I also find that random SMS are not marked read in the system database when read in Messanger.
