### ISSUE TITLE
Improve regex for phone numbers

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#50]
**Device with issue:** Any Android
**App version:** 1.1.226
**Information:**

The regular expression from the `android.utils.Patterns` class seems pretty poor. I think we could make one ourselves that is better, or at least looks for the right amount of numbers to highlight

![screenshot_20160901-104652](https://cloud.githubusercontent.com/assets/4874287/18172716/41695170-702c-11e6-83df-9ea1b3ef2e9e.png)

**Comment by klinker41** [comment]
You'll have to be careful with international numbers for this, they don't look like US numbers. Some are longer, some shorter and all formatted differently.

**Comment by klinker41** [comment]
Also need to worry about the difference between `(111) 111-1111` and `111-111-1111` and `111 111 1111` and `+1 (111) 111-1111`, etc. I think you get the picture, this is not an easy regex. I think that maybe the best thing to do would be to take Android's pattern matcher for it and just enforce a length limit of >5 or something like that on it.

**Comment by klinker41** [comment]
I updated this with https://github.com/klinker41/messenger/commit/7cd4213956fbf2daa4cf0b3b1c6fb81a79c53eae.

Original using `Patterns.PHONE`:
![device-2016-09-01-232627](https://cloud.githubusercontent.com/assets/4501322/18192707/3ce6cf36-709c-11e6-93d4-f6adcd257320.png)

New using updated:
![device-2016-09-01-233005](https://cloud.githubusercontent.com/assets/4501322/18192712/4772cd24-709c-11e6-8b0c-f498582e4d9a.png)

I basically added a check that the final part of the number had to contain at least 3 digits, which got rid of a ton of the junk in there. 

Listed on top is the original regex and below is the new one:
`(\\+[0-9]+[\\- \\.]*)?(\\([0-9]+\\)[\\- \\.]*)?([0-9][0-9\\- \\.]+[0-9])`
`(\\+[0-9]+[\\- \\.]*)?(\\([0-9]+\\)[\\- \\.]*)?([0-9][0-9\\- \\.]+[0-9]{3,})`

This seems more appropriate to me.

**Comment by klinker24** [comment]
Agreed. I refactored it a bit with this: https://github.com/klinker41/messenger/commit/55d4befdbd3d0f8ce1edf56c4ccb7c004e60752b
