### ISSUE TITLE
Option to hide message preview but still display the sender on the lockscreen

### ISSUE THREAD

**Issue by NotYourLoginID** [klinker-apps/messenger-issues#500]
The closest related issue I could find was #391, however I'm basically considering that a _bug that **should** have been a feature_ in this ticket.

**Device with issue:** Phone
**Primary device:** Moto G4 on Android 7.0.0
**App version:** 2.6.0.1695
**Steps to reproduce:**

1. Set notifications to "Hide sensitive notification content"
2. Receive a text message

There seems to only be 2 options: 
1. Display all sender names and show a message preview on the lockscreen
2. Show essentially nothing besides "you have a new message" on the lockscreen

**Additional information:**
It would be extremely helpful if there was a way to still show the name of the sender without the message preview. ie:
2 Messages - Mom
1 Message - Bill

**Possible solution:**

Make a toggle option in the app to still show the name/phone-numbers of senders in lock-screen notifications, but without showing the message preview. Below are some possible **System** notification settings and **App** notification setting with desired outcomes:

- _Hide sensitive notification content_ **&&** _Hide message previews_ **->** _show current **hidden** notification info_
- _Show all notification content_ **&&** _Hide message previews_ **->** _show sender + message count for conversation_
- _Show all notification content_ **&&** _Show message previews_ **->** _show current **full** notification_
- _Hide sensitive notification content_ **&&** _Show message previews_ **->** _show current **hidden** notification info (system setting overrides)_

**Comment by NotYourLoginID** [comment]
(I'd add labels if I could, but I don't seem to have permissions)

**Comment by klinker24** [comment]
Sorry, this is not something that I plan on adding. I go into detail on this post: https://plus.google.com/100518007997856267526/posts/311LLHqGxeD

I just want to avoid adding little tweak options throughout the app. For almost everyone, they don't mean anything, don't do anything, and just go to confuse the user. There are times in this app when I do have to make the decision and go with it. Hopefully that makes sense, sorry

Only the owner/collaborators can add labels.
