### ISSUE TITLE
can't receive some rare SMS and can't log in back on Android

### ISSUE THREAD

**Issue by payre** [klinker-apps/messenger-issues#501]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [x] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** <don't receive some rare SMS on Pulse SMS Android">
**Primary device:** <"Archos Diamond Alpha = ZTE Nubia z17 mini on Android 6.0">
**App version:** <2.6.0.1695>
**Steps to reproduce:**

I use Pulse SMS on my Android phone and on Chrome Web (Windows 10).

I really enjoy Pulse SMS both on Android & PC.

unfortunately it seems I don't receive some (rare) SMS, especially those automated from banks (the Orange Bank confirmation SMS took hours to arrive and Credit Agricole Sud Rhone Alpes (a French bank) 3D secure confirmation SMS did not come today).

is 06 23 05 07 72 working when I entered my number when I signed up to Pulse SMS or should I have entered +33 6 23 05 07 72.

I had a look at your FAQ and on yout github but it seems everybody receive all his SMS.
On Google Play Store reviews some people don't receive their SMS but it did not help me.

today I tried to synchronise Pulse SMS app again on my Android but my password associated with guillaume.payre@gmail.com does not seem to work.

**Comment by klinker24** [comment]
I already emailed you back discussing these points. So this doesn't really need to go here...
