### ISSUE TITLE
Open Media in Modal

### ISSUE THREAD

**Issue by gregflynn** [klinker-apps/messenger-issues#502]
Instead of opening picture messages in a new tab in the web UI, open them in an overlay modal. If you guys are using material bootstrap for your UI this should be pretty easy. Low priority obviously.

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/messenger-web/commit/7fd3ff0b4b3b65772840917f0c6769887e37448a

It will roll out throughout today.
