### ISSUE TITLE
Unlimited SMS wait time (block outgoing SMSs)

### ISSUE THREAD

**Issue by rayfoss** [klinker-apps/messenger-issues#504]
**Device with issue:** Moto G3
**Primary device:** Moto g3
**App version:** 2.6.1
**Steps to reproduce:**

1. Look for a way to block outgoing messages while still being able to see incoming messages.
2. Watch your life slip away as you see there is way to do that.

To clarify, I want to stop my self from accidently using the app to send a text message, a one minute lock down is not enough, it needs to be infinite, or have no send box.

**Additional information:**
My device crashes when I send SMS.
I get charged $1 billion dollars per SMS. 
I have multiple personalities and send wierd SMSs to random people.

**Possible solution:**
- Check box to "disable outgoing SMS"
- add an infinite SMS timeout option

**Comment by klinker24** [comment]
I really don't see this option ever coming... The point of Pulse is to be a communication platform, one way communication isn't really what it is designed for. 

I don't see a real use-case where completely preventing outgoing messages would be helpful... You can just choose not to send messages

**Comment by klinker24** [comment]
And I definitely don't understand why you would give one star for this.

**Comment by rayfoss** [comment]
I actually do get charged ridiculous fares for sending texts... I looked at every SMS app for this feature. Please please do it, or let me do it... Even if it's just a button to remove the input box.

**Comment by klinker24** [comment]
I open sourced an old SMS app. You could add it there, this won't be coming to Pulse though, sorry.

https://github.com/klinker24/Android-SlidingMessaging
