### ISSUE TITLE
Search within conversations

### ISSUE THREAD

**Issue by Skullmonkey** [klinker-apps/messenger-issues#505]
**Device with issue:** Pixel XL Android 8.1
**Primary device:** Pixel XL Android 8.1
**App version:** 2.6.0.1695

**Additional information:**
Just putting in a feature request for searching in a specific conversation. I know it is implemented in the main conversation view but it searches all conversations. I have found it very useful in the past that as you are searching, it would scroll to that portion of the conversation so that I could read the messages around the search term.

**Comment by klinker24** [comment]
Maybe in the future. This isn't going to be a priority though, since it is really just duplicating functionality that already exists.

**Comment by Skullmonkey** [comment]
Just another thing to think about:
When there are multiple matches to the search term, could there be a 'jump to next/previous'? The best example I can think of right now is like how the desktop version of Chrome does it. Just an up and down arrow would do.

Loving the app. Keep up the good work!

**Comment by klinker24** [comment]
This is done for `v4.9.0`.
