### ISSUE TITLE
Multiple notifications

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#508]
**Device with issue:** Windows and Linux machines?
**App version:** 1.0.0-beta9
**Notes:**

I have had a few reports that notifications will just continue to show up on the native Windows app. You can dismiss it over and over again, and it will just come back. Weird. 

I am not sure why this is and haven't been able to reproduce this issue yet on my Mac. Maybe I will be able to on Linux.

**Possible solution:**

I tried to just set a timeout for the notifications so that you couldn't get more than one notification every 10 seconds. This didn't make a difference.

I have a feeling that the issue is with multiple instances of the web socket starting. Could it be that every time the window is opened, it is starting a new instance of the main method and creating a new instance of the web socket?

**Comment by daniel-nicholson** [comment]
+1 on this issue. Running Windows 10 (Bootcamp on Macbook pro)

**Comment by Touchdown1119** [comment]
I am also having this issue on Windows 10. I am receiving the message notifications in triplicate.

**Comment by fcusano9** [comment]
I am also getting this error. Every time I receive a text I get 4 notifications. I attached a picture of my task manager screen that shows many instances of Pulse running which can be the issue that OP mentioned in the possible solution.

Also if you click on the notification it opens a new instance of Pulse instead of simply opening the one that is already running. This is probably a separate bug but I figured I would mention it here.

![pulseerror](https://user-images.githubusercontent.com/25214122/33380448-20159b1e-d4e9-11e7-902a-d718531db4f8.PNG)

**Comment by klinker24** [comment]
I am going to change the way that the Windows and Linux apps work in the background.: https://github.com/klinker41/messenger-chrome/commit/8a5ddffe4fc195c207e2a10b0a8c7507682a9415

Before, the app would try to continue to run in the background, which seems to be the issue here. So, the web socket that was providing notifications never would lose its connection. However, when you click the Pulse icon to start the app again, Windows and Linux still start those apps from scratch, so it was opening up a new web socket connection and providing double notifications.

This is a distinct difference from how MacOS apps work and how they manage their background connections. With Mac, it is expected that once you open the app once, its state is saved and restored immediately. So the Mac apps do not get shut down in the background like Linux and Windows do.

So, for now, when the app shuts down, I am also going to shut down the background web socket connections. This means that unless the app is open (and yes, minimized is fine), the app won't display notifications. This isn't ideal, in my opinion, however, hopefully this functionality can change when #493 is finished. More testing will need to be done behind that.

I believe that this is far superior to spamming you with more and more notifications every time you open the app. At least now these apps are usable. I tried to make it so the app didn't spawn up multiple web socket processes, but I could not find a safe way to do that.

These changes will be released with `1.0.0-beta10`.
