### ISSUE TITLE
Check box for mobile numbers only on compose activity

### ISSUE THREAD

**Issue by klinker41** [klinker-apps/messenger-issues#51]
**Device with issue:** Nexus 6P running Android 7.0
**Primary device:** Nexus 6P running Android 7.0
**App version:** 1.1.235

**Information:**

Some users have a lot of numbers in their phone that they wouldn't want to text, home, work etc. We should add a checkbox menu overflow item to the compose activity that allows the user to set whether or not to show all numbers or mobile only. Its easy to actually implement the logic behind this, I already implemented it in the android-chips library that I use. Simply set `adapter.setMobileOnly(true)` and it will only display mobile numbers.

**Comment by klinker24** [comment]
Done with:
