### ISSUE TITLE
Sync contact photos from phone to other devices

### ISSUE THREAD

**Issue by srchulo** [klinker-apps/messenger-issues#510]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [ ] If this is an issue, and not a request, I have verified that this is something that is reproducible

Currently on the desktop application, all of my contacts just have colored circles instead of their contact photos. It would be great if the contact photos could be synced from my phone so the conversations looked the same on other devices.

**Comment by klinker24** [comment]
This will be done with #133
