### ISSUE TITLE
Feature request Chatheads - floating bubble

### ISSUE THREAD

**Issue by aleslukek** [klinker-apps/messenger-issues#511]
Would it be possible to have chatheads (or floating bubbles as it is also known apparently) implemented? The similar way facebook has them. They are i think quite functional. I know there is an ability to reply via notification but this doesn't show me the chat history from a few minutes ago. I know it is a small perk, but I like it :)

Oh and I love the app, use it all the time on multiple devices.
Best,
Aleš

**Comment by klinker24** [comment]
If you are on Nougat+, notifications do show chat history.

Sorry but Chatheads are not going to come to Pulse. While I understand that some people like them, they just really aren't necessary with the crazy amount of improvements that have been made on Android's notification system over the past few years.
