### ISSUE TITLE
Opening Android App opens a seemingly random conversation

### ISSUE THREAD

**Issue by jwkicklighter** [klinker-apps/messenger-issues#513]
After the app has been removed from background (either because the OS wanted to clear it, or from manually closing it) the app seems to resume into a conversation that was not previously open. And it is seemingly random, often owning a conversation that I was using much earlier in the day but definitely did not have open when the app was last closed.

In fact, I generally return to the message list before closing the app. So I would expect resuming to not show any conversation.

**Comment by klinker24** [comment]
I am going to need some steps to be able to reproduce this issue. Maybe you are opening those conversations from the notification or somewhere specific? Right now, I have nothing to go on.

**Comment by jwkicklighter** [comment]
Just happened to me again, I can't really figure out what is causing it to open the specific conversation that it chooses. But this is what I'm doing:

1. Use the app for some conversation.
2. Return to the conversation list.
3. Close the app and remove it from the Recent Apps screen.
4. Wait some unknown amount of time.
5. Launch the app from the launcher icon (not from a notification).
6. The app will open into a conversation from earlier.

I have no idea what sort of remaining activity happens in there somewhere that could cause extra behavior, but the conversation that has opened each time today is one from early this morning that I have not sent/received messages in for hours, nor even opened from the conversation list. I know it's vague, but I haven't found a pattern to it yet... If there is any debug information that I could get you, I would be happy to. My guess is that something gets messed up in the back stack because or maybe there is some way that you store the current conversation in app storage that doesn't get cleared?

Thinking about it, this also relates to an issue that I have seen with Talon, although I have not reported it. I can add an issue in the Talon repo, but briefly: I have used Talon, opened a webpage in the in-app reader view, exited the webpage, then closed Talon... and then after a while when relaunching Talon from the launcher, the webpage view gets opened. Hitting back closes the app, and from that point on the launcher icon will open to the Tweet timeline.

**Comment by klinker24** [comment]
I made a few changes, trying to clear intent extras, with this commit. https://github.com/klinker41/messenger/commit/50aac52f519e2003fb3ec72a7be501ab6fdad0fa

Without being able to reproduce this issue, it will not be something that I can fix. It is too abstract right now.

**Comment by wizard7926** [comment]
Sounds just like my issue (452)! https://github.com/klinker-apps/messenger-issues/issues/452

**Comment by jwkicklighter** [comment]
@wizard7926 you're right they might be the same thing. Did his tweaks take care of the issue for you?

**Comment by wizard7926** [comment]
@jwkicklighter Unfortunately, no, I'm still seeing the same thing happen across multiple devices (just moved from an LG G5 to a Pixel 2 XL)! :(

**Comment by klinker24** [comment]
Well, when you guys can figure out when this is happening, I will be able to fix it for you.

**Comment by wizard7926** [comment]
Hey @klinker24, I had this happen again today, but in a more definable way!

I had searched a term, clicked a message to enter the thread, and then backed my way out to the conversations list. Later on, when I had the "random" conversation occurrence, it returned to that very same spot in the conversation that I had searched earlier!

Being that this is decidedly less "random" than the other occurrences, does this help you out with the intent at all?? Hope so!

**Comment by klinker24** [comment]
I can probably take a look at this case, yes. But is that really the only way that this bug is happening?

**Comment by wizard7926** [comment]
@klinker24 No, it's the first time I've seen it happen this way. I was just hoping that might give some insight as to why it happens when I haven't been searching. I'll continue to monitor any other clues that might help.

**Comment by jwkicklighter** [comment]
I definitely hadn't used the search before, but hopefully this leads you down the right path

**Comment by ammacdonald3** [comment]
This issue has also been happening to me the last couple of days, and it appears to be related to low memory available. Other apps on my phone (Pixel 2 XL) also seemed to "reset" upon reopening (for example, my gym app seemed to lose my active workout history every time I opened it from memory). A restart of my phone appears to have resolved the issue for now.

**Comment by benthuss** [comment]
Can confirm I am having the same issue on a new galaxy s9 running oreo. The app has been set to never go into power save mode. Most times when I open the app it takes me to a random conversation

**Comment by klinker24** [comment]
If you can get me steps to reproduce this, I can continue to look in to it.

**Comment by benthuss** [comment]
Yep sorry I don't have more info to give you. I'm a web developer myself so I know how hard it is to troubleshoot something like this without being able to consistently reproduce the bug. Unfortunately I can't figure out what circumstances are causing it. Sometimes the app opens fine, but often it just takes me to a seemingly random thread. I will try to observe what's happening and report back. In the meantime feel free to email me at benthuss@live.com if there's anything in particular I can help test or try. Thanks for being so responsive!

**Comment by benthuss** [comment]
Have not been able to confirm this 100% but it seems to happen when the app is open, I lock the phone, get a notification a new message has arrived, then unlock the phone going straight into the app.

**Comment by benthuss** [comment]
Yep just happened again, it does seem to be related to having a new notification pending

**Comment by klinker24** [comment]
I feel like if it was just because of a pending notification, there would be many others reporting this. I have never had an email about this issue, only the few people commenting on this thread, and I have never felt that people are shy about emailing me their issues...

I am not seeing any problems when a notification is pending. If you write down some steps (1, 2, 3..) describing what you are doing and what you are seeing, that may be helpful. 

I'm not going to look at this today though, it is Easter

**Comment by benthuss** [comment]
All good, just trying to give you as much information as I can. Due to the nature of the bug it's difficult to provide specific steps to reproduce.

**Comment by benthuss** [comment]
I'm not saying having a pending notification is causing this bug for all users. I'm saying it seems to be a factor in my particular case.

**Comment by klinker24** [comment]
Even if it isn't steps to reproduce, steps describing what you are seeing and your specific case may be helpful.

**Comment by benthuss** [comment]
Sure thing, I will try! For what it's worth it appears I was wrong as far as the pending notification being an indicator. I had the issue happen several times after I posted that last comment both with and without a pending notification. ¯\_(ツ)_/¯

**Comment by klinker24** [comment]
Did anyone ever find a pattern to this, or some way for me to reproduce it? At this point, I have nothing actionable I can use, and haven't heard anything on this issue for a very long time. I am going to close it out. I can re-open it, if someone can provide the steps required to reproduce it.

**Comment by jwkicklighter** [comment]
Seems to have disappeared for me
