### ISSUE TITLE
Replying via notifications is unpredictable on MacOS

### ISSUE THREAD

**Issue by asherrna** [klinker-apps/messenger-issues#514]
**Device with issue:** MacBook Pro on MacOS 10.12.6 - Desktop app
**Primary device:** Pixel XL on Android 8.0.1
**App version:** 1.0.0 - beta 9
**Steps to reproduce:**

1. receive a text
2. reply via the notification with the terminal icon
3. click send. Nothing happens--the notification goes away but the message is not sent (I checked with the recipient) and doesn't show up in the message history.

**Additional information:**
I'm seeing two notifications per text--one (not actionable, aside from simply opening the app) with the pulse icon, and one (actionable) with the terminal icon. This could have something to do with it? I guess?

**Comment by jrmd** [comment]
I can also confirm this behavior, i came to report this issue.

**Comment by asherrna** [comment]
Further info:
When I'm on the same virtual desktop as the app and reply to the notification, it works. But when I swipe over to a different virtual desktop and reply, it does not. This behavior is reproducible.

**Comment by klinker24** [comment]
So it is always reproducible in that way and you are always able to send when on the same desktop?

I assume you are talking about the three finger swipes to go between full screen applications.

**Comment by asherrna** [comment]
Correct. When Pulse is a full screen application and not focused, I can not respond via the notification. If I get the notification, then 3 finger swipe over to Pulse, then reply via the notification, it works.

**Comment by asherrna** [comment]
Unfortunately today I kept trying and had the reverse result. Sorry for the misinformation but it seems as if that was a strangely consistent correlation.

**Comment by klinker24** [comment]
Correlation in the full screen aspect, I assume you mean?

Pulse uses [terminal-notifier](https://github.com/julienXX/terminal-notifier) through [node-notifier](https://github.com/mikaelbr/node-notifier). If I had to make a guess, there is probably an upstream issue here that I will not be able to solve on my own. I will see what I can find.

**Comment by asherrna** [comment]
Yeah. Seems like it had nothing to do with whether or not the app was in focus. Playing around with the app today it seems like it's working 30-40% of the time, regardless of the parameters

**Comment by klinker24** [comment]
Well, if you figure anything out, please feel free to comment back here.

**Comment by asherrna** [comment]
Sure thing, I'll poke around.

**Comment by rsichel107** [comment]
+1 on the additional information, I also get two notifications for every text.

**Comment by klinker24** [comment]
So I have seen the replies not go through from the notification and experienced that, but I have not been able to figure out the pattern or why this is happening. 

- I don't think it has to do with the full-screen status, I haven't used the app in fullscreen at all and still saw this happen
- Could it have to do with how long the message is? I wouldn't have thought so, but I was able to recreate it a few times long message, but have been unable to replicate with that method, since.

It seems totally unpredictable and I cannot seem to put my finger on why. Sometimes that reply callback just doesn't come through. I might need to re-work this notification action to open up a small reply window, instead of using MacOS's built in reply. I am sure that the issue is upstream somewhere, but until I can figure out a real way to reproduce it, I am not going to file any issues with the upstream dependencies.

**Comment by asherrna** [comment]
I've actually had it happen with very short messages as well. It seems unpredictable. How are you porting the native apps?

**Comment by klinker24** [comment]
Ah ha. I may have spoke too soon. I was on the right track, but it isn't the length of the notification, it is how long it sits open. It seems to be getting the timeout callback and after it gets the timeout, it refuses to call the reply callback.

**Comment by asherrna** [comment]
Oh nice, good catch.

**Comment by klinker24** [comment]
Yeah unfortunately it seems to be an upstream bug. I will probably need to go with the windowed reply, until it gets fixed.

**Comment by klinker24** [comment]
This changes the notification-built-in reply to open a smaller reply window to the Pulse page instead. Hopefully in the future, I can re-enable replies directly on the notification.

https://github.com/klinker41/messenger-chrome/commit/0b1861d30e79cfcf8450a6daa90fd7d88a8c0daf
