### ISSUE TITLE
Cannot change a ringtone + change corrupts sending messages

### ISSUE THREAD

**Issue by infernalhope** [klinker-apps/messenger-issues#515]
**Device with issue:** Xiaomi Redmi 3S Global 3/32GB edition, Android 6.0.1, MIUI 8.5.4.0
**Primary device:** Xiaomi Redmi 3S Global 3/32GB edition, Android 6.0.1, MIUI 8.5.4.0
**App version:** 2.6.3.1743
**Steps to reproduce:**

1. Go to app global settings,
2. open notification type,
3. change ringtone.

No matter what i choose as my new ringtone i always end up with the default ringtone. I have tried my own mp3 ringtones and ringtones (.ogg files) from pre-installed Hangout app.

I have also tried to change a ringtone for a specific contact but the result was the same.

- The notification test plays a correct ringtone.

I have had this problem since the first installation of this app which was a year ago. I recently came back to this because i wanted to see if any of the updates solved this problem. Unfortunatelly it does not.

**SECOND PROBLEM**
When i change tthe ringtone app does not send any text message. This problem occurs every time i try to change my ringtone sound (both the global setting and the contact settings).

Only way to make the app functioning is to kill it.

**Additional information:**

- I also tried to set the ringtone in the phone audio settings because i thought that the phone is overriding Pulse app notification settings. No luck with that either.

- I have also the Textra sms app, default xiaomi app and Drupe app for phone calls. Except for xiaomi app (cannot be killed), the rest of them are not running so it should not be the problem, but still...

- A few minutes ago i tried to reinstall the app and it seems that this time changing the ringtone and re-starting the app it ends up with no ringtone playing when i receive a message. Not all the time i try to change the ringtone, but several times it has happened.

**Comment by klinker24** [comment]
I find it very unlikely that changing the ringtone would stop you from sending messages. Those two are completely uncorrelated, the ringtone is only checked and applied when you receive a message. You will need to do further testing there to narrow down what is actually causing that, because it isn't the ringtone. This is how we send messages: https://github.com/klinker41/android-smsmms

Seems to me that your phone is restricting access to ringtones, I would imagine there is a permission related exception there somewhere. If you were able to get a log of changing the ringtone and receiving a message, that would probably be helpful.

**Comment by infernalhope** [comment]
Sorry for delay. I tested the issue a little bit further with no luck. My second best guess was that Omni swipe app is overriding notifications, also with no results. Restarting the phone, etc. didn't help.

**BUT**
Yesterday i updated the Pulse app to ver. 2.6.4.1755 and right now everything seems to work as it should. Proper ringtone plays when i recieve a message. I am still not sure what could cause the problem with no sending messages. If i come across something new, i will post it here :))

**Comment by klinker24** [comment]
I am going to close this issue out then, if/when you find new information about the sending messages, please open up a new issue around that. Thanks
