### ISSUE TITLE
Error when launching native app for the first time

### ISSUE THREAD

**Issue by joshuamking** [klinker-apps/messenger-issues#518]
- [✓] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [✓] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** MacBook Pro (Retina, 15-inch, Mid 2015) on MacOS 10.12.6 (16G29), running Chrome v62.0.3202.94">
**Primary device:** N/A
**App version:** Native Desktop App beta-9
**Steps to reproduce:**

1. Fresh install
2. Launch native desktop app for the first time
3. Error appears (Attached below)

Additionally, it seems to keep coming up at random intervals after pressing ok. All of this is before signing in. I *just* downloaded it and it has come up nine times. It just keeps coming up. But as soon as I logged in, it stops coming up.

![screenshot_2017-11-27 15 23 44](https://user-images.githubusercontent.com/5152470/33287865-1ba9bed2-d388-11e7-94eb-ad7180121d8b.png)

**Comment by klinker24** [comment]
Thanks, it has been fixed for the next version.

https://github.com/klinker41/messenger-chrome/commit/8fd19dc7f840450c32c2952ae371d3e4fb13ca93
