### ISSUE TITLE
Mac Dock Icon Badge always displays 1 unopened message

### ISSUE THREAD

**Issue by rsichel107** [klinker-apps/messenger-issues#519]
**Device with issue:** MacBook Pro 2017 running on Sierra MacOS 10.12
**Primary device:** Pixel 2 on Android 8.0

The Mac dock icon always displays 1 unread message even when everything is opened. 
<img width="282" alt="screen shot 2017-11-29 at 10 17 05 am" src="https://user-images.githubusercontent.com/17985323/33382367-8f1c2a64-d4ee-11e7-915a-a3b8a8dcba55.png">

To get rid of this, you can toggle the setting on and off using the Preferences method but when you get a text again, the badge will remain. When additionally messages come in the number updates to 2 or 3 etc. but upon opening everything, the number goes back to 1.

**Comment by klinker24** [comment]
I would guess that you have an archived conversation that is unread.

**Comment by klinker24** [comment]
This is probably not the expected functionality anyways though. With this commit, I no longer take the archived conversations into this unread count: https://github.com/klinker41/messenger-server/commit/0159c696229f03461c6b75186075624c3ae55b41

**Comment by rsichel107** [comment]
Yeah that seems right to me! 
Nice work,
Rebecca
