### ISSUE TITLE
Onboarding for introducing users to the app and giving them web links

### ISSUE THREAD

**Issue by klinker41** [klinker-apps/messenger-issues#52]
**Device with issue:** Nexus 6P running Android 7.0
**Primary device:** Nexus 6P running Android 7.0
**App version:** 1.1.235

**Information:**

We want to have a bit better introduction to the app for new users, a simple page giving them a little information along with a link to the web app would be appropriate. We could also tell them about the payment structure here (and the trial period) (https://github.com/klinker-apps/messenger-issues/issues/9).

On the website that they can go to on their computer, we can have links to the chrome apps as well and encourage them to download those.

**Comment by klinker24** [comment]
I have added much better visibility to the chrome apps on the website. Hopefully users will start to adopt these over the website once live streaming support is implemented.

**Comment by klinker24** [comment]
With https://github.com/klinker41/messenger/commit/90846f55ef78fee67eb43bd8e45423aeebca7728, I have added a tooltip to the message list to show that there are more options available in the navigation drawer

**Comment by klinker24** [comment]
https://github.com/klinker41/messenger/commit/55d0afe53df9762bf5ce18525b0eb154bfc01404 adds a link to the "Supported Platforms" page on the website, within the apps "About" screen.

**Comment by klinker24** [comment]
I like this library for the onboarding: https://github.com/stephentuso/welcome-android

**Comment by klinker24** [comment]
@klinker41 What information should we display to the user on this screen?

**Comment by klinker41** [comment]
I don't know, link to web page and info about recurring subscription and free week trial.

**Comment by klinker24** [comment]
I finished and commented on the login flow with this commit: https://github.com/klinker41/messenger/commit/a19621bb86957a8938b41e227a7baafbc49db0b8

One thing that can still be improved is the last screen, the one that they choose to start the trial or skip directly to the app. It is plain, nothing is clickable (links), it is just text. This should be improved before the release.

There is a flag at the top of the `MessengerActivity` that should be enabled during the current beta testing. It is just saying that we should skip the onboarding and take them directly to the login screen, when the app is started for the first time. They don't need onboarded and they don't need the choice between trial or not, at this time.

I have tested the following cases for production and they work as described/expected:

```
Tablet:
- Going through the 2 page onboarding and signing into an account
- No other options available

Phone:
- Going through the 3 page onboarding, selecting "Start Trial", and creating a new account
- Going through the 3 page onboarding, selecting "Start Trial", and logging into an existing account
- Going through the 3 page onboarding, selecting "Maybe Later", then loading the app immediately
- Going through the 3 page onboarding, selecting "Maybe Later", then creating a new account from settings
- Going through the 3 page onboarding, selecting "Maybe Later", then signing in to an existing account (see no real world usage for this, but it does work.)
```

**Comment by klinker24** [comment]
Finished with: https://github.com/klinker41/messenger/commit/229cc75288d392b331b478181c5f4dc2381b49cc

![screenshot_20160907-073611](https://cloud.githubusercontent.com/assets/4874287/18312177/1201ec98-74ce-11e6-8154-1f34acc2bf4a.png)
![screenshot_20160907-073624](https://cloud.githubusercontent.com/assets/4874287/18312178/14064034-74ce-11e6-94a2-72fde0b71226.png)
![screenshot_20160907-073635](https://cloud.githubusercontent.com/assets/4874287/18312185/1a1e6802-74ce-11e6-82d9-3071f643240c.png)
