### ISSUE TITLE
Web design suggestions

### ISSUE THREAD

**Issue by fcusano9** [klinker-apps/messenger-issues#520]
**Device with issue:** Windows 10 PC
**App version:** 1.0.0-beta9

**Additional information:**

I love using the desktop app but I really don't like the fact that there is no distinction between the messaging area on the right and the list of messages on the left. I also don't like that there are previews of messages in the list of messages, I feel that it is too cluttered.

![featurerequest](https://user-images.githubusercontent.com/25214122/33383645-e1250314-d4f1-11e7-957f-eed5835b5c89.PNG)

**Possible solution:**

If we had the ability to change the background color for the messaging area only, or for the list of messages that would be great. Even if the background of the list of messages was a little bit darker it would show separation from the messages.

Also, adding the ability to toggle message previews would also be nice.

**Comment by klinker24** [comment]
I'm not going to remove the previews, sorry. With Pulse, I don't want to fill it with little design tweak options like that. That doesn't amount to a good experience for most users and the option would remain unused for almost everyone

I will see about adding a separator between the message list and the navigation area in the future, but I don't know if I want to change the background color of the message list

**Comment by fcusano9** [comment]
I agree that having many little design tweaks is not good for user experience but at the very least it would be nice if the message previews were limited to 1 line. For example the message below is showing 2 lines and the second line is cutoff which is what makes it seem cluttered in my opinion.

![messagepreview](https://user-images.githubusercontent.com/25214122/33385366-67848bc4-d4f6-11e7-9ee3-7c8b8b1692c0.PNG)

As far as separating the messages from the message list, I don't think it is too crazy to give the user the option to change the background. I think just about every messaging app that I have tried has given that option from the basic ones to the advanced ones.

Overall though this is a great app and I am really impressed that you built and maintain this by yourself.

**Comment by klinker24** [comment]
Hmm, the conversation snippets should only be one line. Thanks for the report.

**Comment by klinker24** [comment]
This will make the snippets only one line.

https://github.com/klinker41/messenger-web/commit/f47d2a42335561982aed037a271a0671527fc35c

**Comment by klinker24** [comment]
I added this

![screen shot 2018-03-04 at 2 44 48 pm](https://user-images.githubusercontent.com/4874287/36950376-ab598a16-1fba-11e8-8853-02b89bff74e4.png)

I can't say I am really a fan, but the other options I tried didn't look any better. I am making it an optional web preference and it is off by default.
