### ISSUE TITLE
Add "mute" to the list of notification actions

### ISSUE THREAD

**Issue by wizard7926** [klinker-apps/messenger-issues#521]
Just had this idea in the car when a group text continually popped up over my navigation app. Having a "Mute" option in the Notification Actions would be neat! Just a thought.

**Comment by klinker24** [comment]
I like it, thanks for the idea!

**Comment by klinker24** [comment]
This is finished: https://github.com/klinker41/messenger/commit/3b30944f6c8b678bc255d90098f53859a3e907a4

It will be released with the next feature release `v2.8.0`

**Comment by wizard7926** [comment]
Sweet!
