### ISSUE TITLE
Apply the base theme to the widget

### ISSUE THREAD

**Issue by athompson673** [klinker-apps/messenger-issues#522]
First off, I love your texting app. Keep up the good work! 

I have a feature to request: a dark themed desktop widget for Android phones. I like having widgets to access my texts (and emails) right on the home screen, but the big splash of white across an otherwise dark background is sort of a drag (I set everything possible to dark theme if it's available) . I was somewhat surprised that it didn't just follow the main theme for in the app.

**Primary device:** OnePlus 5T Android 7.1.1
**App version:** 2.6.4.1755

**Possible solutions:**

 - make widgets respect current main theme
 - offer two widgets (one dark one light) 
 - make the widget customized with a widget specific settings menu

**Comment by klinker24** [comment]
I would like to just make the widget follow the main theme. It isn't really ready for that yet, though.

**Comment by Sage222** [comment]
2nd!

**Comment by klinker24** [comment]
This is done. https://github.com/klinker41/messenger/commit/e476f697394cdd7a46493da5be7ec41f7f6145a7

It isn't going to be released yet though, it needs some testing and probably will need some cleanup/tweaking. It is planned to be released for `v2.9.0`.

**Comment by Sage222** [comment]
Can't wait. Thank you!
