### ISSUE TITLE
Persist text if a notification is clicked on after entering text

### ISSUE THREAD

**Issue by jwkicklighter** [klinker-apps/messenger-issues#523]
Steps:
- Receive SMS
- Start typing response in notification text field
- Decide to use a bigger text field/want to see more of the conversation before sending the reply
- Click the notification to open Pulse
- **Expected**: text from notification text field is present in the reply box in-app
- **Actual**: reply box in-app is empty

I don't know what APIs exist for this, but there are a few apps (Telegram for one, I believe) that have that behavior.

**Comment by klinker24** [comment]
On the Android 7.0 direct replies? This isn't possible, sorry. There is no way to get the text that has been entered until the user hits the send button. https://android-developers.googleblog.com/2016/06/notifications-in-android-n.html#directreply
