### ISSUE TITLE
TV app crash when scrolling through conversation list view

### ISSUE THREAD

**Issue by joshuamking** [klinker-apps/messenger-issues#524]
- [`✓`] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [`✓`] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** NVIDIA Shield TV 2017 16GB
**Primary device:** Pixel 2 XL on Android 8.0.0
**App version:** 2.6.4.1755
**Steps to reproduce:**

1. Open TV app, logged into an account
2. In the conversation view, scroll down and immediately scroll back up (before conversation is loaded in right pane). 
3. App crashes

**Comment by klinker24** [comment]
Pretty sure I fixed this crash yesterday actually. I am going to close this, please comment back if it is still happening after the next update. It will be `2.6.5`.

**Comment by joshuamking** [comment]
I will test this evening. I just got around to reporting it here, the actual crash occurred this morning ~2AM.

**Comment by klinker24** [comment]
Like I said, `2.6.5` has not been released yet.

**Comment by joshuamking** [comment]
My bad, I misread it.

**Comment by joshuamking** [comment]
Okay, so I'm running `2.6.5` now and it doesn't crash when I scroll back up, however it does not load the messages for that conversation. And the message box to type a message says "Type message to %1$s". Additionally, when I go to the right to view that conversation, it crashes at that point.

And this may need to be a separate issue, I'm not sure. But the "Type message" EditText, doesn't bring up the keyboard when focused. So I can't send any messages from the Nvidia shield.

**Comment by klinker24** [comment]
Thanks for the follow-up. I will see what I can find.
