### ISSUE TITLE
Opening a searched messages doesn't display it in very long conversations

### ISSUE THREAD

**Issue by eosti** [klinker-apps/messenger-issues#525]
Search through conversations already is good, but it is impossible to jump to the text message you searched for when it is considered part of the history. Currently, when you press a message in the search results that is considered part of the history, it displays the conversation that it is part of, but at the bottom with the most recent texts. I think that it would be much more useful if it instead jumped to the location where the message was, similar to the more recent texts that are not considered history.

**Comment by klinker24** [comment]
Are you sure? It is designed to do exactly as you have described and I have never heard from anyone with issues around that. Pulse has always worked that way.

I assume you are talking about on the Android app, and not the web.

**Comment by eosti** [comment]
I just tested it again with the latest release of Pulse (Android not web) and the latest Android 8.1.0. When I search for a message in a conversation that is dated past what can be displayed in the normal conversation view (without going into history) and tap on it, it shows me the most recent texts and not the message that I wanted to see.

**Comment by klinker24** [comment]
You are talking about conversations that are longer than what is displayed by default. I guess I didn't understand that from your first post. Thanks for the report

**Comment by klinker24** [comment]
This is finished and will be released for the next update: https://github.com/klinker41/messenger/commit/e57a5ec386d8f90b9852903d055339d2f0fa7651
