### ISSUE TITLE
Auto-start on login

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#529]
**Desktop app version:** `1.0.0-beta14`
**Feature Request:**

It would be nice if the desktop apps were able to automatically start when the computer turns on or reboots. Since they have to be running for notifications to come through, we want them running as soon as possible.

Note: I am not talking about waking up from sleep. If Pulse was running when the computer went to sleep, it will continue running after the computer wakes up.

**Possible solution:**

https://electronjs.org/docs/api/app#appsetloginitemsettingssettings-macos-windows

**Comment by roybiv99** [comment]
This would be a very friendly feature.   Coming from "MightyText" I miss this feature.  Thanks!

**Comment by mamaglee** [comment]
I can't even figure out how to launch Pulse once my computer is on.  Computer crashed and Pulse comes up in Chrome, but I want it independent from the browser.  That's possible, correct?

**Comment by klinker24** [comment]
@mamaglee yes, download the desktop app for your platform (Windows, Mac, Linux): https://messenger.klinkerapps.com/overview

**Comment by mamaglee** [comment]
I downloaded it last week and it was working fine on my Mac.  Now I can’t launch it independent from the browser.  When I click on the app icon, it launches Chrome.

**Comment by klinker24** [comment]
If it is launching chrome, then you aren't using the Mac app, it doesn't have any chrome integration? You should download the `dmg` from the releases page on this tracker

**Comment by mamaglee** [comment]
I did that last week and it worked fine.  Now when I click it, it launches Chrome.  I know, it’s ridiculous.  I have taught computers at Colleges since 1996, so I know the diff. between a browser and an app, but I’m stumped Luke.  Every time I go to sign in to download the dmg, it takes me to the web application of my messages.   When I click on the app, it launches the app in the browser, I swear. . . Here’s what happens.  

1. I launch the Pulse SMS.app.  
 

2. This “GET STARTED" screen displays asking me at the top right to Log in or Sign up. . . I Log In, since I’ve already signed up. 


3. I Log In and it goes straight to PULSE in the CHROME BROWSER.  If my browser is closed, it launches Chrome.  I tried this several times by QUITTING CHROME and then logging in from the Pulse SMS.app.  It always launches CHROME.

**Comment by mamaglee** [comment]
Link again for the dmg, which I did install, otherwise I wouldn't be able to have the app in my applications folder...
![findermpgk002](https://user-images.githubusercontent.com/13932912/34445455-9c3d106c-ec88-11e7-9e3d-b791ade33d22.png)

**Comment by mamaglee** [comment]
![launches chrome](https://user-images.githubusercontent.com/13932912/34445469-ac736148-ec88-11e7-8e6c-3e4d99ab6c8c.png)
![pulse smsmpgk001](https://user-images.githubusercontent.com/13932912/34445470-ac9342ce-ec88-11e7-8645-d6d15f50ad0a.png)

**Comment by klinker24** [comment]
Just hit the "log in" button in the top right corner or your second screenshot. That is the pulse app.

**Comment by mamaglee** [comment]
Now I have the app running, but it’s not synch’d with my phone.  It was yesterday but this morning all new messages on my phone are not appearing in the app on my computer.

**Comment by klinker24** [comment]
You can probably email me about these questions, since they don't really relate to this topic. I would like to keep this tracker focused on the issues discussed and try not to stray. Email is a good place to ask questions or go for general troubleshooting, along with my extensive help page https://messenger.klinkerapps.com/help

To fix your issue, just use the "my account" -> "refresh account" option on the phone.

**Comment by mamaglee** [comment]
OK, thank you Luke.  :)

**Comment by DanielKovalevich** [comment]
I did find a workaround on Windows 10. If you type in `shell:startup` into run, i.e. Windows Key + R, and paste a copy of the application .exe into the startup folder, then the application will startup with Windows. I've tried this on both my laptop and desktop and it seems to work well, although it would definitely be great if the feature was integrated into the application.

**Comment by timtimmahh** [comment]
One workaround on Linux is to copy or create a symlink of `appimagekit-pulse-sms.desktop` file to ~/.config/autostart. That will have it run on reboot, the only downside is that it pops up every time you reboot or log out and log back in. I haven't looked into this too much, but it might be possible to do `pulse-sms.AppImage --appimage-extract` and then modify the AppRun file to close the window after starting the payload app by using `wmctrl -c "Pulse"`. I've only skimmed the AppImage docs so correct me if I'm wrong, but once you get it working how you want I think you can then use [appimagetool](https://github.com/AppImage/AppImageKit#appimagetool-usage) to turn it back into an AppImage.
Over the weekend I'll be able to try this out and see if it can work, but creating a symlink to that .desktop file in ~/.config/autostart definitely works as a quick fix.

**Comment by csm10495** [comment]
I submitted a pull request to help a bit here by allow the app to be started and have the GUI not launch (via a command line flag). I'll be using it after putting the exe in the startup folder on Windows.
https://github.com/klinker24/messenger-desktop/pull/1/commits/d2c8c43e3f8fcd060d662d9f58a3449eea2ebd39

**Comment by klinker24** [comment]
@csm10495 cool, thanks for that. Merged

**Comment by CarJem** [comment]
So I guess I'll see this implemented for real in the future. Glad to be able to make a push to make it happen.

**Comment by klinker24** [comment]
I opened the issue myself and haven't closed it, of course I plan to implement it...

**Comment by klinker24** [comment]
This is done with: https://github.com/klinker24/messenger-desktop/commit/08062a4f5b07f9a2bd1818a6d39524b3538dd464

The option is available in the `Preferences` tab in the menu bar, on Windows. Mac users can right click on the dock icon and select "Open at Login", as a system level option, so I have not added it to Mac. This API is unavailable for Linux machines.
