### ISSUE TITLE
Web Vulnerability: Sanitize html from window title

### ISSUE THREAD

**Issue by yumoose** [klinker-apps/messenger-issues#531]
**Device with issue:** Browser
**App version:** Web (https://messenger.klinkerapps.com/)

**Steps to reproduce:**
***Something simply noticed***
1. Edit contact name to include an emoji and sync
2. Open the conversation for that contact
3. Observe tag directly in the tab/window title `<img class...`

***Something really unwanted***
1. Create a new conversation with the recipient`<script>alert("Uh-oh");</script>`
2. Send and try not to cry

**Additional information:**
While this is noticeable with image tags where emoji's have been used, this opens up injection issues with simple JS code in the browser.

**Possible solution:**
Strip html tags from contact names and the window title

**Comment by klinker24** [comment]
I will just run the entity encoding on the conversation title too

https://github.com/klinker41/messenger-web/commit/f3115b81ede15b2072727307ac06b0579d474600

Luckily, the only person ever defining a title for a conversation, is you.
