### ISSUE TITLE
Duplicate messages ignored by app/desktop client.

### ISSUE THREAD

**Issue by thebluemangroup** [klinker-apps/messenger-issues#532]
If you receive a message that is exactly the same as one before it, any message after the first is ignored. The messages appear just fine in other SMS apps, even if they are not set as default, showing that the phone is receiving the duplicate messages just fine, but the Pulse app is ignoring them for some reason.

If this is intended behavior as some sort of spam protection or something, I think it should be an option left open to the user so they can opt out of it and continue to receive "duplicate" messages.

- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [X] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** MacBook Pro on MacOS 10.13, running desktop client 1.0.0 RC1, Galaxy S8+ on Android 8.0, running version 2.6.5.1767
**Primary device:** Galaxy S8+ on Android 8.0
**App version:** 2.6.5.1767
**Steps to reproduce:**

1. Using another device, send a message (I used a single letter, but the same goes for longer messages)
-> Phone and desktop client both receive the message, as expected. 

2. Send the same message (from your second device to the one running Pulse, same as step 1)
-> Neither the phone nor the desktop client receive the message. No notification, and message doesn't appear in the app at all. 
-> Message is received by the phone, and it shows up in other SMS apps, but Pulse appears to be ignoring it.

**Comment by klinker24** [comment]
On `v2.7.0` that is currently in beta, duplicate messages will only be ignored when it is the exact same as the previous message and it is within 1 minute. This is a different behavior and logic from what it was in previous versions of the app and now is working exactly how I would expect this to work.

This isn't something I want to make an option for. Duplicate SMS messages are not at all uncommon, so I want to continue to have logic to sort through them, without the need to add an option that the vast majority of users will not understand.

**Comment by thebluemangroup** [comment]
Couldn't you just put an option under advanced settings so that users who care enough to disable it have the choice, but it's out of the way for those who don't care or wont understand?

**Comment by klinker24** [comment]
Pulse doesn't have an advanced settings screen and that is a section that I do not want to add

I avoid adding little tiny tweak options that few will use or understand, whether that is for the UI or little things that I have made. I don't want it to be the type of app that you have to dig through settings forever to find what you are looking for, that isn't the goal of Pulse and directly takes away from the goal of the app. The goal of Pulse is to provide an awesome feature set, right out of the box, and to provide a cross platform app that just works across your devices, without the configuration overhead.

Obviously the app has customization to it, and pretty powerful customization at that. I enjoy the customization aspect, if it is useful to more than a few users.

I feel as though having a duplicate message within 1 min is acceptable to cover all use cases. Sorry, this isn't something I plan to adjust to have configurable on the user side.
