### ISSUE TITLE
FEATURE REQUEST: incoming call / missed call notification on website

### ISSUE THREAD

**Issue by bcurran3** [klinker-apps/messenger-issues#533]
It would be nice if the website reported "Incoming call" and "Missed call" so users can keep abreast when their phone is not by their side and make a choice to text or call back.

**Comment by klinker24** [comment]
I already responded to your email about this. Right now, Pulse is an SMS app and I am going to be very careful to stray from that focus. I know that some users have integration between SMS and calling, so I won't give it a complete "no" for the future, but right now, this doesn't fit the focus for the app.

I will add a watch tag if anything changes for this, in the future.
