### ISSUE TITLE
Archive blacklisted conversations

### ISSUE THREAD

**Issue by bcurran3** [klinker-apps/messenger-issues#535]
APP: When choosing to "Blacklist contact" it works as expected, the number gets blacklisted and the message gets removed from the conversation view within the app and the webpage.

WEB: When choosing to "Blacklist Contact" the contact gets blacklisted but the message stays in the conversation view on both the app and the web.

SUGGESTION: Make functionality intuitively the same across platforms.

**Comment by klinker24** [comment]
Android archives the conversations that you blacklist. I have made the web do the same: https://github.com/klinker41/messenger-web/commit/aa3f66e4a7dd3260f898be0dc031483201af4714
