### ISSUE TITLE
Suggestion: Ask to sign in before importing messages

### ISSUE THREAD

**Issue by Skullmonkey** [klinker-apps/messenger-issues#536]
**Device with issue:** Pixel XL Android 8.1
**Primary device:** Pixel XL Android 8.1
**App version:** 2.7.0.1800

**Additional information:**
If users sign in to a new device or clear their data, when they open the app again for the setup process, it automatically imports the messages on the device and then when you log in to your account, it deletes those messages and downloads the messages from the cloud. It seems a little counter productive.

**Possible solution:**
Add a dialog to login to your account in the first run process before importing messages. (If that makes sense.)

**Comment by klinker24** [comment]
That isn't planned, sorry. Pulse is an SMS app before anything else. I don't want to force the users into a decision like that before they even have tried or seen the app. That is terrible for new users.
