### ISSUE TITLE
Arch Linux PKGBUILD

### ISSUE THREAD

**Issue by gregflynn** [klinker-apps/messenger-issues#537]
This was my first whack at a PKGBUILD but it works, wanted to post it here before publishing to the AUR in case you guys wanted to manage releases.

```bash
pkgname="pulse-sms"
pkgver="1.0.0"
pkgrel=1
pkgdesc="A native desktop implementation of Pulse"
arch=('x86_64')
url="https://messenger.klinkerapps.com/"

vername="$pkgver-rc${pkgrel}"
source=(
    "https://github.com/klinker-apps/messenger-issues/releases/download/v${vername}/pulse-sms-${vername}-amd64.deb"
)
sha512sums=("7f4c7a14e623f1dd199836a3cc461837859e09a2904ee5fc4ddc3fcaec41cd8f594aa3c99df81c9c4e4cd51b0dd7b14f1be18827cafee3b40ab7b1e4374c8ed6")

package() {
    tar -xvf data.tar.xz -C "$pkgdir"
}
```

Helpful reading if you aren't familiar:
- https://wiki.archlinux.org/index.php/Creating_packages
- https://wiki.archlinux.org/index.php/Arch_User_Repository

Totally cool if you guys don't think you have the time to release on yet another distro

**Comment by klinker24** [comment]
I don't mind if you distribute it, it probably isn't something that I will distribute though

**Comment by gregflynn** [comment]
No worries, if you change your mind, let me know and I can transition it to you.

For anyone that comes across this: https://aur.archlinux.org/packages/pulse-sms/
