### ISSUE TITLE
Message stays in message box after it is sent

### ISSUE THREAD

**Issue by fcusano9** [klinker-apps/messenger-issues#539]
**Device with issue:** Laptop running Windows 10
**App version:** v1.0.0-rc1

**Steps to reproduce:**

1. Open the desktop app
2. Send a text message
3. Observe that the message is sent but the message is still in the input box

**Expected Behavior**

The message should be automatically deleted from the message box so that I don't have to manually do this in order to send another message.

**Additional information:**

This only started happening in the rc1 version. All of the versions before this worked fine.

**Comment by klinker24** [comment]
I already deployed a fix for this on the web, it doesn't have anything to do with the native app. You can use command + R (or ctrl + R) to refresh the desktop app and get the latest web code.
