### ISSUE TITLE
Messages from phone and web not syncing

### ISSUE THREAD

**Issue by ripcitizen** [klinker-apps/messenger-issues#54]
Messages sent by web do not sync to android app (they do not show up on phone).
Likewise, messages sent from phone to not show up on web.  Only the existing messages from app setup show up.

Note 5 Verizon, 6.0.1  & Firefox 47.01

phone restart and web log out/in did not fix.

**Comment by klinker41** [comment]
Same advice as the other issue (https://github.com/klinker-apps/messenger-issues/issues/55). Also doesn't hurt to clear the web page's cache as lots of changes have been made.

Just tested this though and had no issues. Sounds like your phone isn't connected to the internet to me.
