### ISSUE TITLE
Scheduled message doesn't clear the new conversation message

### ISSUE THREAD

**Issue by hudcap** [klinker-apps/messenger-issues#540]
Very minor bug.
If the first message in a conversation is a scheduled message, the conversation retains the "You don't have any messages in this conversation..." message on top.
It goes away once a message is sent normally.

**Comment by klinker24** [comment]
This should do it: https://github.com/klinker41/messenger/commit/bbb01692d68c2314fcf24a018dc25563c7c16f2e

If it isn't fixed in the next update, please follow up and let me know. Thanks for the report
