### ISSUE TITLE
New notifications show the multi-thread icon for a moment

### ISSUE THREAD

**Issue by jwkicklighter** [klinker-apps/messenger-issues#541]
When there are no Pulse notifications in the drawer and a new message comes in, the icon in the status bar begins as the double icon that's used to indicate multiple threads/nested notifications. After about a second, it swaps to the proper single icon.

If you can't reproduce this, it's possible that it happens from getting multiple messages from one contact at the same time. Although I believe I was witnessing it without that case as well. 

App Version 2.7.0.1800

**Comment by klinker24** [comment]
This won't change, sorry. That is Android figuring out that there is only one notification in the notification group instead of multiple.  When it figures that out, it removes the group summary in favor of the individual notification.

**Comment by jwkicklighter** [comment]
Gotcha, thanks for the explanation and quick response as always!
