### ISSUE TITLE
Contact names with emojis don't appear properly in notifications

### ISSUE THREAD

**Issue by fcusano9** [klinker-apps/messenger-issues#542]
**Device with issue:** Laptop running Windows 10
**App version:** v1.0.0-rc1

When I receive a text from someone who has an emoji in their contact the pop-up notification shows the xml information of the emoji instead of just displaying the emoji itself.

**Steps to reproduce:**

1. Create a contact in your phone with an emoji in it
2. Open the desktop app
3. Have that person send you a message
4. Observe that the raw xml data of the emoji is shown

**Comment by klinker24** [comment]
Could you provide a screenshot of what you do see? I honestly don't have a Windows computer handy around right now and my Mac converts them to emojis just fine

**Comment by fcusano9** [comment]
Sure, when I first get a message from somebody I see the first image that is attached below. Then I get a second notification after that which actually displays the message and that one displays just fine, shown in the second image below.

![emoji_bug](https://user-images.githubusercontent.com/25214122/34000060-39f34630-e0ba-11e7-8a4f-ee85a57d18f3.PNG)

![emoji_bug2](https://user-images.githubusercontent.com/25214122/34000397-2d53e0fa-e0bb-11e7-816b-7a2e7b5cc9a2.PNG)

**Comment by klinker24** [comment]
Ok, the first notification is a web notification. Those go off when the web page is open in the background. The second notification is the desktop notification.

**Comment by klinker24** [comment]
This is fixed with: https://github.com/klinker41/messenger-web/commit/62db213f7a5ba12bc8aa8629f045d821f6e8d4e0

I will roll it out later today.
