### ISSUE TITLE
SMS Messages are delayed or not sending at all

### ISSUE THREAD

**Issue by paulva214** [klinker-apps/messenger-issues#543]
**Device with issue:** windows 10
**Primary device:** LG K8
**App version:** <latest update>
**Steps to reproduce:**

1. step 1 send message only using windows interface (RC2)
2. step 2 recipient does not receive message at all or only several hours later

**Additional information:**

Pictures come through (to windows interface) only 50% of time and then rotated incorrectly. (They are correct on senders phone).

**Comment by klinker24** [comment]
Pulse sends messages from the web interface by simply forwarding them to your phone. Your phone is your connection to your carrier and how the app is able to use your personal phone number. Pulse use's Google's Firebase cloud messaging infrastructure to accomplish this. There are really two possibilities here, both upstream issues.

1. The messages make it to the phone immediately. Pulse hands the messages to Android, and Android sends them. All of this is done right away, always. If the messages make it to the phone right away, then the delay is on your carrier's end and has nothing to do with Pulse.
2. The messages don't make it to the phone right away. The fact that they do make it tells me that the Pulse service is working fine and delivering the messages to Firebase. Your phone needs to be turned on to be able to send messages, even when sending from the web. There is a section in the help part of Pulse's phone app to disable battery optimizations, which may help this issue. 

You could try using the "my account" -> "refresh account" option on the phone to invalidate the firebase configuration, as well. After understanding how the process works, do you have any additional information you can provide for this issue? If not, this will have to be closed as an upstream issue with Google Play Services, Firebase, or your carrier

We track MMS issues on #101, for the picture messages not making it to the web. This issue has now been linked in that topic.

**Comment by paulva214** [comment]
Thank you so much... especially for the explanation about systems functions... I did the refresh without success. So it is probably the carrier. FYI the other person uses MYSMS. 
Thanks for all you do!!  

The info on my phone is:
Android V 7.0
Kernal 3.18..31
Build NRD90U
SW Version US21512a
Sec Patch 11-6-2017
Model LGUS215
HW Version 1.0
Carrier USCellular
My Computer Info:
Windows 10 Professional (x64) (build 16299)
Pulse V1.0.0 RC2

Best
Paul

**Comment by klinker24** [comment]
So the messages do show up on your phone? If so, I am going to close this issue.

**Comment by paulva214** [comment]
Yes, and thank you
