### ISSUE TITLE
Attach images to a new conversation

### ISSUE THREAD

**Issue by anatolytkach** [klinker-apps/messenger-issues#546]
**Device with issue:** Windows 10 64bit, running Chrome 63.0.3239.84
**Primary device:** LG G4, Android 6.0
**App version:** 2.7.2.1822

**Steps to reproduce:**

1. Start Crome extension
2. Click on "plus" button
3. There is no "staple" icon allowing to attach an image

**Additional information:**
Obviously, if I'm already in the conversation, there is a "staple" icon allowing to attach an image. The problem occurs if I don't have an existing conversation with the receiver of the message. 

**Possible solution:**
Please, just add a  "staple" icon to the "new message" dialog box

**Comment by klinker24** [comment]
Unfortunately it isn't as simple as adding the attach icon on the new message dialog. Thank you for the feature request.

**Comment by klinker24** [comment]
Todo:

**Backend**
  * [x] accept mime type and a message id with the `forward_to_phone` route: https://github.com/klinker41/messenger-server/commit/9a387f8bcda3950134d1f305740a400901cdad0b, https://github.com/klinker41/messenger-server/commit/0f4dd3dc0be142eb90d4d23d5c58808c0c4b70c0

**Android**
* [x] download the images from Firebase, when they come in: https://github.com/klinker41/messenger/commit/bce536721ffbf6e89b9aae86c26d424607133da8
* [x] apply the image to the conversation: https://github.com/klinker41/messenger/commit/bce536721ffbf6e89b9aae86c26d424607133da8
* [x] Create new conversation, if one doesn't exist: https://github.com/klinker41/messenger/commit/bce536721ffbf6e89b9aae86c26d424607133da8
* [x] Send the image: https://github.com/klinker41/messenger/commit/bce536721ffbf6e89b9aae86c26d424607133da8

**Web**
* [x] add UI around the compose page, to attach the image
* [x] Upload the images to the web, when sending: https://github.com/klinker-apps/messenger-web/commit/7c31b6a4d2a585b5ae3e91c8a7ac1727cd3ef370
* [x] Forward the message id to the phone, to be sent: https://github.com/klinker-apps/messenger-web/commit/7c31b6a4d2a585b5ae3e91c8a7ac1727cd3ef370

**Comment by klinker24** [comment]
This is done. It will be available on the new Pulse web app: https://github.com/klinker-apps/messenger-web

It will require `v3.2.2` of the Android app, which will be released in the coming week.

**Comment by anatolytkach** [comment]
Thank you!
