### ISSUE TITLE
Problem settings WEB version

### ISSUE THREAD

**Issue by GalferOP** [klinker-apps/messenger-issues#547]
Hi, 
I'm on windows 10 and I use the web version of pulse on RAMBOX.
And on the web version I cant' change the settings .. I want the dark theme but i can't change that and that's annoying... :/
Especially when i paid for a lifetime version. I want support you but if you can fix that please :)

**Comment by klinker24** [comment]
The top preference in the web settings page will pull any settings configuration you have done from your phone. You do not configure the settings directly on the web version.

This is also explained in the summary of that preference
