### ISSUE TITLE
Black accent color on compose screen

### ISSUE THREAD

**Issue by CitrusFruits** [klinker-apps/messenger-issues#548]
**Environment**: android app, dark theme

**Steps to reproduce**: open the app, click the + button

**Expected behavior**: the bottom  left icon is the same color as the bottom right (a light/white color)

**Comment by CitrusFruits** [comment]
![](https://i.imgur.com/FkRkspZ.jpg)

**Comment by klinker24** [comment]
The selected item uses whatever accent color you have selected. Guess I never thought black would be used as an accent color. I can probably just switch it to use white or some.

**Comment by klinker24** [comment]
This is done for the next version: https://github.com/klinker41/messenger/commit/55288e537d895abb1aa957b2609292ee77577efa

**Comment by CitrusFruits** [comment]
Awesome!
