### ISSUE TITLE
Web extension has the bottom cut

### ISSUE THREAD

**Issue by Cabeda** [klinker-apps/messenger-issues#549]
- [X ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [X ] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** Windows 10 running Firefox 58
**Primary device:** OnePlus One on 7.1.2
**App version:** 2.7.2.1822
**Steps to reproduce:**

1. Open the window and I see the following

**Additional information:**

![screenshot_1](https://user-images.githubusercontent.com/8181056/34354924-a463d43a-ea29-11e7-8516-092e260d4bc8.png)

**Comment by klinker24** [comment]
You can fix this by turning off the options bar on Firefox. Hit the settings button at the top to find this preference.

**Comment by Cabeda** [comment]
Thanks! It's fixed. It took me some time to understand that the options bar was the one from the extension and not one built in the browser
