### ISSUE TITLE
Contact color setting do not sync to web 

### ISSUE THREAD

**Issue by ripcitizen** [klinker-apps/messenger-issues#55]
Changed contact color on phone and the color of contact on web remains unchanged.

Note 5 Verizon, 6.0.1  & Firefox 47.01

phone restart and web log out/in did not fix.

**Comment by klinker41** [comment]
I'm having no issues with this. Remove your account in the my account section, clear the app data and sign up again.

Closing this due to insufficient information and not following template in the readme.
