### ISSUE TITLE
Links open without query parameters in Android App

### ISSUE THREAD

**Issue by arcastro** [klinker-apps/messenger-issues#550]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [X] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** Samsung Galaxy S8 Plus on Android 7.0
**Primary device:** Samsung Galaxy S8 Plus on Android 7.0
**App version:** 2.7.2.1822
**Steps to reproduce:**

1. Send a link that includes query parameters, such as "http://google.com?query=lol" as an SMS to any recipient
2. Click on the link from your own chat

**Expected:** Link should open to "http://google.com?query=lol"
**Actual:** Link opens to "http://google.com"

**Comment by klinker24** [comment]
This is discussed here, so I am closing this as a duplicate.

https://github.com/klinker41/article-android/issues/24

**Comment by arcastro** [comment]
Thanks Luke, 
I have disabled the `Use Internal Web Browser` for now  to remedy this.
