### ISSUE TITLE
Linux Desktop Client: Add support for back button on mouse

### ISSUE THREAD

**Issue by M-W99** [klinker-apps/messenger-issues#552]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [ ] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** <"HP Pavilion DV7 running Ubuntu 16.04">
**Primary device:** <"Samsung Galaxy S8 running Android 7">
**App version:** <"Linux Client Version: v1.0.0-rc2">
**Steps to reproduce:**

1. Open a Conversation
2. Try to hit the back button on your mouse

This is a feature request for the Linux Desktop client. I would love to have the ability to hit the back button on my mouse to exit out of a conversation and go back to the list of all conversations. Clicking the Conversations button certainly isn't hard, but just being able to hit the back button on my mouse would be easier. :)

**Comment by klinker24** [comment]
I think I will tie this in with #344 for keyboard shortcuts. Thanks for the suggestion!
