### ISSUE TITLE
Delivery reports checkmark sometimes disappears

### ISSUE THREAD

**Issue by M-W99** [klinker-apps/messenger-issues#554]
**Device with issue:** Samsung Galaxy S8 running Android 7.0
**Primary device:** Same as above
**App version:** 2.7.3.1839

This seems to happen at random, but sometimes after I send a SMS message, the checkmark will disappear even though the message sent successfully. I wish there was more info I could provide here, but l like I said it happens at random. If there are any log files or anything else I can provide, I'd be happy to.

UPDATE: This seems to happen after minimizing the keyboard (SwiftKey) . With that in mind I'll have to do some more testing and see if I can figure out how to reproduce it reliably.

**Comment by klinker24** [comment]
I am not sure I understand what you are asking here. Pulse has three states:

* `Sending...`
* `Sent` - which just removes the "Sending..." text from the bottom of the message
* `Delivered` - if your carrier supports delivery reports, a double checkmark appears in the bottom right of the message

So it sounds like you are saying it moves from the `Delivered` to the `Sent` state, which should really never happen. Pulse doesn't respond or have any way to know when your keyboard is open or closed, so I don't think that that is the root cause of this issue.

I assume it holds the state when backing out of the conversation and going back in to it? If you can get a way to reproduce it, I would be happy to see what I can do for this issue.

**Comment by JariVanBoven** [comment]
I've the same problem. The 'V' sometimes disapear. But I didn't have a way to reproduce it as it happens not all the time or not after a specific action.

**Comment by M-W99** [comment]
You can disregard what I said about it happening when the keyboard is lowered. After playing around with it some more, it happens even with the keyboard still up.

I've never seen a double checkmark, only a single. It does retain its state when going out and back in to the conversation. Still can't find a way to reliably reproduce it. Seems to happen maybe 1 out of 10 times.

I did notice that after sending a message, the checkmark will always appear, disappear, and then either stay hidden or reappear again. I can upload a video of this if that would help.

**Comment by klinker24** [comment]
That may be helpful.

**Comment by M-W99** [comment]
Here's a video of the checkmark disappearing and reappearing. For the life of me I couldn't get it to totally disappear on video... I'll keep trying though.

https://www.dropbox.com/s/jnydi890d0povlo/20171229_120846_edited.mp4?dl=0

**Comment by klinker24** [comment]
I don't think that that blink is something that will go away, sorry. That is the layout refreshing itself to update some different statuses.

**Comment by M-W99** [comment]
Ok, the checkmark disappearing then reappearing is fine. Sorry that I haven't been able to provide any better information here. Still haven't been able to catch it on camera haha.

**Comment by Jatarii** [comment]
I've send you an e-mail with a screencast about this issue.

**Comment by M-W99** [comment]
I actually haven't had this happen since my last post. Maybe an update inadvertently fixed it? I have no idea.

**Comment by Jatarii** [comment]
Lucky you! This happens constantly on my phone. There is no 'check' but my contacts recieve my message anyway.

**Comment by M-W99** [comment]
Does the check appear then disappear, or does it not appear at all?

**Comment by Jatarii** [comment]
It appears and several seconds later it moves away. (Sorry, I can't post the screencast here because it contains information I don't want to share).

**Comment by M-W99** [comment]
No problem, I was just curious. Sounds exactly like what was happening to me.

**Comment by Jatarii** [comment]
That's why I was paying attention to this. But I caught it on camera 😅

**Comment by klinker24** [comment]
This will fix the issue: https://github.com/klinker41/messenger/commit/362408adf07fbbcaafceb6f0ed83b4f03e247f37

I will release it with the next version.
