### ISSUE TITLE
Jump to message/delete from media view

### ISSUE THREAD

**Issue by Skullmonkey** [klinker-apps/messenger-issues#555]
**Additional information:**
Just putting in a request to either put a button in to delete a photo from the 'View media' screen or a way to delete a media item from that screen. 

A couple of ideas:
1: Open the photo and add an item in the menu to delete the media item.
2: Long press a photo to select a single media item or multiple others if desired and adding an icon to delete them. (Similar to how you can delete multiple texts within a conversation) (My preferred choice but I realize that might take some work)
3: Open a media item and add an item in the menu where it allows you to jump to that part of the conversation. (Similar to how search works.)

**Comment by klinker24** [comment]
This is what #354 is for.
