### ISSUE TITLE
Don't use enter to submit a scheduled message

### ISSUE THREAD

**Issue by petersg83** [klinker-apps/messenger-issues#557]
**Device with issue:** MacBook Pro on MacOS 10.13.1, running Chrome v63.0.3239.84
**Primary device:** Pixel 2 XL on Android 8.1.0
**App version:** 2.7.4.1848
**Steps to reproduce:**

1. Open pulse website and go to [Scheduled Messages](https://messenger.klinkerapps.com/scheduled_messages.html)
2. Click '+'  button
3. Enter a phone number and a future date
4. Write some text and press enter to create a new line
=> The message is added although it should not yet

**Additional information:**

We can see the packet being sent in the console and the add button goes from "Add" to "Added" and then "Ok"

**Comment by klinker24** [comment]
Enter will no longer submit the scheduled message: https://github.com/klinker41/messenger-web/commit/a47b6553f2ba61026986ce670b5f3ba0d9bb8ba2
