### ISSUE TITLE
MacOS: Notifications in Notification Center

### ISSUE THREAD

**Issue by samuelBB** [klinker-apps/messenger-issues#558]
**Device/App Info** 
MacBook Pro w/ MacOS High Sierra 10.13.2 w/ Pulse Desktop App v1.0.0-rc2
Google Pixel 2 w/ Android Oreo 8.1.0

**Request**

Right now on Mac, Pulse seems to support badge notifications (with unread count) and pop-up alerts with a reply option (via `Show Notifications` option in Preferences dropdown). I was wondering if it would be possible to also support notifications in the MacOS Notification Center. More generally, would it be possible for Pulse to fully interface with the MacOS native notification system, so that an option for customizing Pulse's notifications shows up in the MacOS System Preferences > Notifications menu.

**Comment by klinker24** [comment]
Pulse uses [node-notifier](https://github.com/mikaelbr/node-notifier), which in turn uses [terminal-notifier](https://github.com/julienXX/terminal-notifier) to support posting notifications from a background thread. 

Until these dependencies support it, I cannot support it in my app.

**Comment by thatchrismiller** [comment]
I am still getting the terminal icon on the notification. Is this related?

**Comment by klinker24** [comment]
No, it isn't https://github.com/klinker-apps/messenger-issues/issues/507

**Comment by klinker24** [comment]
With `v1.0.2` of the desktop apps, there were changes around notifications that will satisfy this feature request. Pulse better supports the system level configuration for banner vs alert notifications. Go to `System Settings` -> `Notifications` -> `Terminal Notifier` to configure the notifications:

* When using "alert" notifications, the notifications will be sticky and remain on the screen until you dismiss them. Only one notification per conversation will be displayed at a time.
* When using "banner" notifications, then notifications will be dismissed after a few seconds and will show up in your notification center.

Please note that you configure this through the `terminal-notifier` app on that system settings page, not through Pulse. Hopefully in the future, that can be improved.

**Comment by myessail** [comment]
For anyone trying to change these settings in the future: changing 'terminal-notifier' didn't work for me, I had to change 'mac-notifier' instead.
