### ISSUE TITLE
Rename conversations

### ISSUE THREAD

**Issue by Dispersi0n** [klinker-apps/messenger-issues#559]
**Primary device:** Pixel XL on Android 8.1
**App Version:** 2.7.5.1855

**Feature Request**

Something I really like about Facebook Messenger is the ability to rename conversations, something like "Baseball team chat" instead of a large list of phone numbers or names. Is that something that's possible with this type of client that uses pure SMS?

**Comment by klinker24** [comment]
You can already do this. Open up the "Group settings" section of any group text and the "group name" option is near the top.

Are you looking for something else?

**Comment by Dispersi0n** [comment]
Oh wow, you're right...sigh. I was looking on the Mac app and didn't see anything like that, but I do see it in the Android version. Sorry about that!
