### ISSUE TITLE
Selecting a conversation does not scroll to latest message in conversation

### ISSUE THREAD

**Issue by PlasmaEye** [klinker-apps/messenger-issues#56]
#### Versions
Chrome: 53.0.2785.89m
Primary Device: Nexus 6p on Android 7.0

#### Steps to reproduce:
1. Select a contact that has a long history of messages
2. New pane opens with an older message at the bottom instead of the latest message in the convo

#### Workaround:
Upon clicking into the conversation pane, scroll down to the latest message.

**Comment by klinker41** [comment]
Not seeing this issue, does the list start all the way at the top or just slightly off from the bottom? My guess is that if it is the second one, then the images that get inserted into the conversation after downloading push the messages down slightly.

**Comment by PlasmaEye** [comment]
It starts slightly off from the bottom; about 5 clicks of the scroll wheel from the bottom. The effect is immediate so it doesn't look like it is loading the images from previous messages but I bet that is the cause.

**Comment by klinker41** [comment]
ok figured that was it, images are cached so they load quick, but not immediately. fixed with https://github.com/klinker41/messenger-web/commit/23327009d60cec28017cdc0904d3fa7486117011

clearing your browser cache should fix it.
