### ISSUE TITLE
2 Buzzes with each message

### ISSUE THREAD

**Issue by JaiiR320** [klinker-apps/messenger-issues#561]
on: OP5 Oxygen OS 5.0
Using latest Pulse update

Hi all, Everytime I receive an SMS message, I get 2 buzzes in very fast succession and I am not sure why. I have tried to disable and enable other notification settings but still no luck. Thanks

**Comment by klinker24** [comment]
The default vibration pattern is two fast buzzes. I am not really clear what you are asking me about, sorry. I assume that device is on Oreo, I don't get to control any notification customization on Oreo, all of this goes through Notification Channels, which you can read about on the help page.

https://messenger.klinkerapps.com/help

**Comment by JaiiR320** [comment]
Ok, good to know. I did see that notification about channels but I didn't know what it meant. I am on Oreo, but the buzzes before I updated were those 2 buzzes like you said. But this time I am receiving another set of 2 buzzes before the first set of buzzes finish. Dzz-dzz -> dzz-dzdzz-dzz if that makes any sense :-p

**Comment by klinker24** [comment]
You probably just have turned on a notification channel that isn't necessary.#560 discusses change that I have made to the notification channels to simply them. That should solve your issue.
