### ISSUE TITLE
Attach images

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#564]
**Device with issue:** iOS devices
**App version:** iOS v1.0.0
**Request:**

Right now, the iOS clients do not have a way to attach images. Similar to the web app, we should be able to attach an image to a current conversation.

In the future, we should be able to attach images to brand new conversations, as well.

**Comment by bilzebubba** [comment]
I have friends with iOS phones who cannot receive images sent from my Pulse on Android in their normal (whatever comes standard, I dunno) SMS app on the iPhone -- maybe I should make a separate "Issue" for this

**Comment by klinker24** [comment]
@bilzebubba #101

**Comment by bilzebubba** [comment]
Thanks, I sent them from the windows app, looking for file setting size... Sorry for the newb questions, just getting into the app, love it so far!

**Comment by klinker24** [comment]
This is going to be closed. Since Apple has rejected the iOS app, there is little reason to put time into it. iOS favors the progressive web app.
