### ISSUE TITLE
Bug: MacOS desktop app force closing/crashing frequently

### ISSUE THREAD

**Issue by TimBek2** [klinker-apps/messenger-issues#567]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [x] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** MacBook Pro Mid-2015 on MacOS 10.12.6, running Chrome 63.0
**Primary device:** Pixel 2 XL on Android 8.1.0
**App version:** 2.7.7
**Steps to reproduce:**

1. Open desktop app
2. App force closes itself regardless of interaction, does not serve a crash message (it just closes)

**Additional information:**

Average time is within a few minutes, sometimes it closes in seconds, other times as much as 5 minutes before closing itself. There isn't really enough time to try to do any debugging or figure out where it might be coming from before the app shuts itself down, but if there's anything I can do on my end to investigate further I can help.

**Comment by klinker24** [comment]
I recommend deleting the old version and just installing the 1.0.0 release from scratch.

**Comment by myspivey** [comment]
This was related to the push of the 1.0.0. I can confirm that as soon as you pushed the release the app was trying to update and would fail and restart. Replacing with 1.0.0 does fix the issue.

**Comment by klinker24** [comment]
Ok, I will add that to the release notes for this version of the desktop app.

**Comment by TimBek2** [comment]
👍  thanks for the quick response everyone, all good now

**Comment by klinker24** [comment]
I think the issue was with the auto update support for certain situations. I am going to put up a hotfix for `v1.0.1` to prevent this in future updates.
