### ISSUE TITLE
Quick reply to message

### ISSUE THREAD

**Issue by klinker41** [klinker-apps/messenger-issues#57]
**Device with issue:** Nexus 6P running Android 7.0
**Primary device:** Nexus 6P running Android 7.0
**App version:** 1.1.235

**Information:**

Users that are not on android 7.0 or higher will want to be able to quickly reply to a message from the notification without having to open the app. We should be able to just make a simple activity that displays the last few messages and a text input area. UI wise I don't know what I want from it, maybe something similar to heads up and the quick reply in nougat, but a little taller so you can see some message history on it as well.

**Comment by klinker24** [comment]
Pull request submitted for double checks: https://github.com/klinker41/messenger/pull/15

**Comment by theRealPadster** [comment]
Is there any plans for implementing quick reply in Android 5 or 6? Hangouts and Google Messenger have their own implementation without Nougat's quick-reply.

**Comment by klinker24** [comment]
Merged and finished with https://github.com/klinker41/messenger/commit/9690991a1db8b392b18935d25464b559cfb51f7f
