### ISSUE TITLE
Send button is blocked by scrollbar

### ISSUE THREAD

**Issue by myspivey** [klinker-apps/messenger-issues#571]
**Device with issue:** Mac Pro 10.13.2
**App version:** v1.0.1
**Steps to reproduce:**

1. step 1
open app on mac
2. step 2
click long convo
3. step 3
notice send arrow is partially blocked by scroll.

**Possible solution:**

Move send arrow to the left enough to allow for it to show without being hidden.

**Comment by klinker24** [comment]
A screenshot would be helpful

**Comment by myspivey** [comment]
![screen shot 2018-01-19 at 5 44 13 pm](https://user-images.githubusercontent.com/2472925/35185706-c1695712-fdc5-11e7-8056-96cc6d780274.png)

**Comment by klinker24** [comment]
I should have been clearer, I am interested in a screenshot of the window, to see the size of it. Not just that little part.

**Comment by myspivey** [comment]
![screen shot 2018-01-22 at 6 24 33 am](https://user-images.githubusercontent.com/2472925/35223025-3defe8b4-ff3d-11e7-968e-b92b2afff4c1.png)

**Comment by myspivey** [comment]
![screen shot 2018-01-22 at 6 24 33 am](https://user-images.githubusercontent.com/2472925/35223076-660fb432-ff3d-11e7-8808-385936fba34f.png)

**Comment by klinker24** [comment]
Done with https://github.com/klinker41/messenger-web/commit/11e397ac800a940b547f67d9431523cbb26ad16c
