### ISSUE TITLE
Save images

### ISSUE THREAD

**Issue by lazylionca** [klinker-apps/messenger-issues#573]
Hey guys, love the program. Would love be able to save pictures from the desktop client, and/or open them in a different program.

Thanks all,

Keep up the good work.

**Comment by klinker24** [comment]
You can save them from the web right now. I will look to add this down the road.

**Comment by HellaShine** [comment]
Came here to request this feature. Both the ability to save a picture/video and to send one via drag and drop would be incredibly helpful!

**Comment by klinker24** [comment]
You can already drag and drop pictures to the web.

**Comment by klinker24** [comment]
This is done, with the latest version of the web/desktop apps.
