### ISSUE TITLE
keep receiving the same mms pictures 

### ISSUE THREAD

**Issue by lazylionca** [klinker-apps/messenger-issues#574]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [ ] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** <"Samsung s7">
**Primary device:** <"Samsung s7 on Android 7.0">
**App version:** <"2.7.7.1873">
**Steps to reproduce:**

1. have someone text you a picture
2. wait up to a week
3. picture will appear again

**Additional information:**
I have a few people who regularly send me pictures via mms and they receive fine,
but at random points over the next week, the pictures will show up again for no discernible reason. One of the users has an iphone and the others are Samsumg androids.

My guess would be that there is some sort of 'confirmation of receipt' failure,
but I don't know if that is actually applicable to sms/mms.

I can verify that one user is not deliberately resending them as the iphone user is regularly sound asleep beside me when several repeats happen.

Thanks guys.

**Comment by klinker24** [comment]
We track MMS in #101.

That issue already discusses this, along with the fix. It is also on the help page.

https://messenger.klinkerapps.com/help
