### ISSUE TITLE
Changing device orientation exits conversation

### ISSUE THREAD

**Issue by AD49613** [klinker-apps/messenger-issues#576]
**Device with issue:** LG v20 us996
**App version:** 2.7.5.1855

**Steps to reproduce:**

1. Switch to Pulse's Night Mode/Theme
2. ‎Hold the device in either landscape or portrait orientation
3. ‎Open a conversation
4. Rotate device
5. Rotate device back
6. ‎Do the opposite of what you chose in 2
7. ‎Repeat 3-7 as desired.

**Additional information:**
Different rotations have different results. 
Starting in landscape and returning to normal rotation stayed in conversation when clockwise and not when counterclockwise (or vice versa I forget)

**Comment by AD49613** [comment]
I have a LG v20 us996

**Comment by AD49613** [comment]
I was not able to reproduce this with during the day when the background for the app is white (I have it set to auto-switch).

**Comment by klinker24** [comment]
So it only happened during night mode? Hmm, I am unable to reproduce this issue. 

You say "different rotations have different results". So this is an inconsistent issue then, can you give me more concrete examples of what you are seeing? Android really doesn't care if it is clockwise vs counterclockwise and apps don't know or get that information.

**Comment by AD49613** [comment]
So I was just testing it out and it is inconsistently exiting the conversation. I've been trying it in each direction starting in both portrait and landscape orientation multiple times. I'm not sure if I'm missing something, I was originally thinking you didn't implement whatever you use to save your current view for night mode like you do day mode. 

When I'm holding my phone in portrait orientation and rotate it clockwise it exits the conversation and returns to the conversation list, yet when I do that in reverse it does not. That seems to be consistent.

**Comment by klinker24** [comment]
Hmm, I am still not able to make this happen on my devices. Could it be a timing issue? So if you rotate really fast, it happens, whereas, if you give it a few seconds, it doesn't do this.

**Comment by klinker24** [comment]
Any updates on whether or not this could be a timing issue?

**Comment by klinker24** [comment]
Sorry I am not able to replicate this issue and have not heard back about my question. I am going to have to close this. If you have more information to share on this issue, in the future, please post here and I will continue looking in to this.
