### ISSUE TITLE
Feature: Android Notifications Update

### ISSUE THREAD

**Issue by Dru89** [klinker-apps/messenger-issues#577]
Hi!  Love your app, but I had two suggestions for the Android notifications improvement:

#### HTML entities
I noticed that (it looks like) you strip anything that looks like an HTML entity in the notification.  So if the person messaging me sent `Hello, friend! <3` I'd only see the `Hello, friend!` part in the notification.  I know it doesn't seem like much, but it'd be incredibly useful for me to see these in the notification.

#### Past conversations
When I get a notification from someone I have a long thread going with, I see a lot more in the notification drawer than just the new messages.  I really only need to see the messages I haven't read, though.  I guess this one is more of a preference than anything, but it's sometimes distracting trying to figure out which messages are the most recent when I'm looking at, for instance, a text message from Amazon trying to figure out if my package was delivered.

**Comment by klinker24** [comment]
I don't see the HTML entities changing, sorry. Notifications allow for HTML formatting through a `SpannableString`, and I use that in some situations. The use of that HTML formatting is what is messing up your HTML tags though. I don't strip that out, Android is doing that.

You can tell the app to only show new notifications by simply turning off the notification history in Pulse's settings.

**Comment by Dru89** [comment]
Thanks, @klinker24! Appreciate the response, even if there's nothing that can be done.
