### ISSUE TITLE
Clicking on desktop notification if app is hidden opens the window in fullscreen

### ISSUE THREAD

**Issue by kirstilynn** [klinker-apps/messenger-issues#579]
**Device with issue:** "MacBook Pro on MacOS 10.12, running Desktop Client"
**Primary device:** "Pixel XL on Android 7.1.2"
**App version:** v1.7.8

**Steps to reproduce:**
1. When in the app, click cmd + h to hide the window
2. When you receive a desktop notification click it
3. the app opens up in a fullscreen window

**Additional information:**
Sometimes clicking the desktop notification does not open the window, in that case I have to click on the Pulse icon down in my dock, which then results in opening a fullscreen window as well.

**Possible solution:**
It would be nice if it just opened the window that was hidden, or at least open a smaller window. A fullscreen window is less than ideal when viewing my texts at work ;)

**Comment by klinker24** [comment]
I am not able to replicate this. It opens the window that was hidden whenever I try.

**Comment by klinker24** [comment]
Can you post the version of the Mac app that you are using - I am not actually sure what `v1.7.8` is, I suppose it was supposed to be `v2.7.8`?

If you have any additional information or reliable steps that I can use to reproduce this issue, it would be very helpful to me.

**Comment by kirstilynn** [comment]
It looks like I had two versions of the application installed, one from a few weeks ago and one from back in November. The old one was called "Pulse App" while the new one is called "Pulse SMS". Seems like that was causing some pretty unexpected and strange behaviors. 

I deleted the old application and that seems to have solved this issue.
