### ISSUE TITLE
Delete icon missing when multi-selecting messages

### ISSUE THREAD

**Issue by LeoJT54** [klinker-apps/messenger-issues#581]
**Device with issue:** <"LG V20">
**Primary device:** "LG v20 on Android 7.0"
**App version:** "H91510q" 
**Steps to reproduce:**

1. step 1 Within a few (not all of them) Conversations, Long Hold/Select a Message. 
2. step 2 I only have 3 Option Icons; Share, Copy and Information. 
3. step 3 When I Select a second message, all Icons disappear and there are No Options. 

![lg v20](https://user-images.githubusercontent.com/35548298/35426080-41ba09ea-022e-11e8-81d2-72745184a423.Jpg)

**Comment by klinker24** [comment]
I replied to your email yesterday, there really wasn't any reason to post here too.

The conversation comes back because you are archiving it, not deleting it.

I will look at why the individual messages don't have a delete button. I am not able to reproduce this issue.

**Comment by klinker24** [comment]
Please specify what version of the app you are on, as suggested by the template for the issue. It will be `2.7....`, I don't know what `H91510q` is supposed to be?

**Comment by klinker24** [comment]
Closed with https://github.com/klinker41/messenger/commit/cb25af2f00b4077e2c3dd55677d4680396a812fd

**Comment by LeoJT54** [comment]
I see now your 7 e-mails arrived between 7:30 am (GMT -5) and 8:07 am. 
I also see that while I slept through that 37 minute time period, this case was Closed.
Thank you for your Patients and Consideration of this Seniors sleep requirements.

The version numbers I supplied were the Cell Phone's Android version and the LG V20 model number. 
That model numbers is supplied to Canadian phones that Rogers ordered from LGE.

My Pulse App version is 2.8.0.1885. And I don't know what you mean by Mac App.
As far as Reproducing my problem, al I can say is that it is a Constant & Consistent problem that is only visible (or rather invisible) when I SMS or MMS the same three people. I haven't sent messages to all 105 Contacts on my phone yet. I have only messaged about 12 of those 105 Contacts and so far, the same three (Google Contacts) don't show the Delete option when 1 or more messages are Selected. Maybe you can't reproduce this but I can't change it.

**Comment by klinker24** [comment]
Please follow up with the next release of the app and let me know if you see the same issue. It should be fixed.
