### ISSUE TITLE
Notifications Not Showing Up in Native Desktop App

### ISSUE THREAD

**Issue by Aeroguns** [klinker-apps/messenger-issues#585]
[X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues with this request.
[N/A] If this is an issue and not a request, I have verified that this is something that is reproducible

**Device with issue:** <Desktop PC, running Windows 10 Pro">
**Primary device:** <Samsung Galaxy S7, on Android Version 7.0>
**App version:** <Desktop Client Version 1.1.1 for Windows>

I just recently became an unlimited subscriber and really love this app. I recently downloaded and installed the Native Desktop app for Windows 10 Pro. However, when I receive a message, it does not pop up as a notification at all on my computer. I have unchecked and rechecked the show notifications, uninstalled and reinstalled, took a look around my power settings, but to no avail. The app is updating my conversations in real time, but I simply do not receive the notifications.

**Comment by klinker24** [comment]
Have you installed any of the previous versions of the desktop app to try them? I can't say I have heard of any issues around notifications.

**Comment by Aeroguns** [comment]
Goodness, you're fast! Yes, I have tried 1.1.0 and the previous on before that. I think I might have figured it out. There was something on my computer called Quiet Hours. Turning that off seemed to have made the notifications work.

**Comment by klinker24** [comment]
Great, glad you got that worked out because I would have had no idea what the issue was... Haha

**Comment by Aeroguns** [comment]
Actually Luke, I have a nother question. Is there a way to mute the notification noise on the desktop app? It's not showing up on my Volume Mixer.
 

    On Monday, January 29, 2018 8:13 PM, Luke Klinker <notifications@github.com> wrote:
 

 Great, glad you got that worked out because I would have had no idea what the issue was... Haha—

**Comment by klinker24** [comment]
No, there isn't

https://github.com/klinker-apps/messenger-issues/issues/339
