### ISSUE TITLE
Google voice search will not send text message using Pulese on WiFi only device

### ISSUE THREAD

**Issue by gtxent** [klinker-apps/messenger-issues#586]
- [X ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [X ] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** AOSP based Android 6.0.1 WiFi Only Car Headunit 
**Primary device:**Nexus 6P on 8.1
**App version:**2.8.0.1885 (on device with issue)
**Steps to reproduce:**

1. Either by using OK Google voice command, or Voice Search app icon, say Send a text message to <contact> hello how are you
2. Click send or wait for it to send
3. Google app gives you a message with a grey exclaimation point, "message couldn't be sent"
See screenshot [https://imgur.com/a/gjf87]

**Additional information:**

Device is WIFI only, no 3G or 4G radio.  Can send and receive texts fine using wifi to main Nexus 6p Device.   Logcat shows no error output from either pulse or google apps. 

Works fine on Main Nexus 6p, problem with head unit.

**Comment by klinker24** [comment]
I'm not going to be able to fix this, sorry. That isn't an issue with my app and this process never even touches my app. Google assistant sends messages completely outside of Pulse, there is no integration there.
