### ISSUE TITLE
Can no longer click links on the Chrome App

### ISSUE THREAD

**Issue by Skullmonkey** [klinker-apps/messenger-issues#587]
**Device with issue:** Chrome App
**Primary device:** Pixel XL Android 8.1
**Steps to reproduce:**
Try to click a link on chrome app

**Additional information:**
There is no longer a way to simply click a link on the Chrome App. I believe this changed when the new push to add the delete and close options. I am also unable to select the text to copy/paste the link in to the browser unless I am in the pop up window.

**Possible solution:**
1: Make links clickable again directly from the message
2: Add option to the pop up to "Go to link"

**Comment by klinker24** [comment]
Alternate solution: make the links clickable in the popup.

https://github.com/klinker41/messenger-web/commit/528f80daa12029930e322b7e3ffb6f4d1f1b47d5
