### ISSUE TITLE
Group messages: Issues with editting many recipients

### ISSUE THREAD

**Issue by gbeaguilar** [klinker-apps/messenger-issues#588]
Primary device: Pixel 2 XL on Android 8.1
App version: 2.8.0.1885
Steps to reproduce
1. Start a large group message( I do about 10 frequently, issue also happens with about 6-7 people).
2. Edit recipients
3. Try scrolling up the recipient list to delete a person at the top (add more recipients if scrolling is not needed)
4. Notice how the scroll up does not stay/stick, it will automatically scroll by down, not allowing to edit/delete the top people at the top of the list

I can try to do a quick video/ screen capture if you cannot replicate.

**Comment by klinker24** [comment]
I know of the issue, this is actually something that needs to go in this repo though: 
https://github.com/klinker41/android-chips

I will probably close this and move it over there, tomorrow.
