### ISSUE TITLE
Messages are sometimes sent in an incorrect order

### ISSUE THREAD

**Issue by Soleedus** [klinker-apps/messenger-issues#589]
**Device with issue:** Windows 10 x64 client 1.1.1
**Primary device:** Google Pixel 1 on Teltik/T-Mobile
**App version:** 2.8.1.1896
**Steps to reproduce:**

I sent a series of messages through the Windows client to a buddy and he reported that they were sent in an entirely improper order. My cell signal and wifi are excellent, so I'm not particularly sure what could be causing the issue.

Here's the order I sent him:
![my order](https://soleedus.me/i/2018-02-05_23-38-10.png)

Here's what he received:
![his order](https://soleedus.me/i/2018-02-05_23-49-57.png)

This has also happened on the Chrome extension client and even from the app itself. When switching back to the stock messaging app, the issue no longer persists.

**Comment by allanteliu** [comment]
I have the same issue sometimes with sending texts out of order
Device with issue: Samsung Galaxy S7 / Desktop
Primary device: Samsung Galaxy S7 android 7.0 sprint
App version: 2.8.1.1896
Steps to reproduce: Sending multiple individual texts in quick succession

**Comment by klinker24** [comment]
I doubt that this is something I will be able to change. When sending from the web, I don't get to control the delivery of those messages to your device. I use Firebase Cloud Messaging to send push notification to the device, containing the data that needs to be sent. When the phone receives a push notification to send a message, it will send the message.

On the phone, all I can do is hand off messages to Android to get sent. I do not get to control the latency there either. This is how all third party SMS apps work.

I don't see any way around that, nor do I think that a change will come for this, sorry. This is simply the architecture and limitations that Pulse is built on. I do not and will not be able to communicate directly with the carrier. Everything has to run through push notifications and Android to get sent and delivery times are out of my control in both cases.

**Comment by allanteliu** [comment]
Could there be a way to delay the sending of texts so that there can be a verification of the correct order?

**Comment by klinker24** [comment]
I don't think so. How long would you wait, how would you know when the messages come in? With different connection speeds and even devices that go in and out of an internet connection, it wouldn't be safe to do it that way and there wouldn't be a blanket answer for Pulse's wait times. This would be infeasible
