### ISSUE TITLE
Black theme for OLED screens on the Android app

### ISSUE THREAD

**Issue by PlasmaEye** [klinker-apps/messenger-issues#59]
Have a black theme for phones that have OLED screens (Nexus 6p) that has a pure black background.

**Comment by klinker41** [comment]
This will probably not be coming anytime soon, if ever. Android's AppCompat does not have sufficient functionality to support more than a day and a night theme.

https://medium.com/@chrisbanes/appcompat-v23-2-daynight-d10f90c83e94#.1kqyj13wn

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/messenger/commit/1b68bc0ced408191f34e4fe482bc2dcbbff02ed1
