### ISSUE TITLE
reaction to sms: url intents is inconsistent

### ISSUE THREAD

**Issue by lexelby** [klinker-apps/messenger-issues#590]
I like to automate the heck out of my Android phone.  I use Automagic, which is similar to Tasker.

I'd like to automatically open specific SMS conversations.  I use this in two contexts: shortcuts for people on my home screen and a shortcut to open the conversation of the last person that texted me.

If I send a VIEW intent with url `sms:<number>` it pulls that person's conversation up.  But if I want to pull up a group message and try `sms:<number>,<number>`, the results are inconsistent.  Usually it just pulls up the conversation for one of the two parties, whichever was open last.

I have found a workaround.  If I instead use the SENDTO intent and a url like `smsto:<number>,<number>`, _and send the intent twice_, it reliably opens a group sms.  

This technique does _not_ work reliably to open and individual, non-group conversation.  I have logic to ensure that I use VIEW/sms: for a single person and SENDTO/smsto: for groups.  Kind of a pain, but it works.

Some other sms apps can open a specific conversation with a url like this: `content://mms-sms/conversations/<id>` but Pulse doesn't have an intent filter for that.

**Comment by lexelby** [comment]
Sorry, it doesn't look like I can edit tags as the README asked me to...

**Comment by lexelby** [comment]
It turns out that even my complicated workaround is only about 90% effective.

**Comment by lexelby** [comment]
Cool, no problem, and thanks.  I just wanted to provide context.

**Comment by klinker24** [comment]
This should be fixed: https://github.com/klinker41/messenger/commit/31432c7868fddd5877530474a523e3fd126f0b45

I will release it with `v2.8.4`.

**Comment by lexelby** [comment]
Wonderful, thank you!  I'm happy to test a pre-release if that would be helpful.

**Comment by klinker24** [comment]
You can sign up for the beta through this link: https://play.google.com/apps/testing/xyz.klinker.messenger

**Comment by lexelby** [comment]
Works great, thanks for the fast fix!  Lifetime membership purchased.

**Comment by klinker24** [comment]
Cool, thanks for the follow up and enjoy the app
