### ISSUE TITLE
Keyboard stays visible after exiting app. 

### ISSUE THREAD

**Issue by PostaQ** [klinker-apps/messenger-issues#594]
- [ ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [ ] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** <insert your device: "MacBook Pro on MacOS 10.12, running Chrome v54">
**Primary device:** <insert your phone: "Pixel XL on Android 7.1.2">
**App version:** <insert version: in "My Account" on the phone>
**Steps to reproduce:**

1. step 1
2. step 2
3. step 3

`... more steps`

**Additional information:**

Do you want to provide any other information? Device configuration, unique cases, screenshots, anything that you think may be relevant.

**Possible solution:**

Do you have an idea of how to solve it? If not, that's fine. You can delete this section.

**Comment by klinker24** [comment]
In the future, you need to actually fill in the templates, not just the title for this issue.

This issue is not with Pulse. I'm sure you have a pixel device with the Feb security updates, that is when it started. Individual apps do not control this functionality and I have seen the same issue with Slack.

If you can provide me with real reproducible steps, then I can reach out to Google, on their issue tracker. I have not been able to reproduce it consistently or ever on command. Otherwise, I will need to close this issue as an upstream problem.

I will leave this open for a few days, for discussion, if anyone can provide feedback.

**Comment by PostaQ** [comment]
Sorry about not filling the template. I'm a novice in posting. I have a oneplus 5 with the oreo upgrade. I also have not been able to reproduce it consistently. However, I did not have the issue with Textra or the stock messaging app. If I can figure out what's triggering this I'll update.

**Comment by Skullmonkey** [comment]
I do believe that you are correct on it not being a Pulse issue. I have had it stay open in multiple apps including Google apps with a Pixel XL. And now that you mention it, I believe it did start in the Feb update. (Unrelated side note, I'm just glad that I don't have to unlock my phone to answer a phone call anymore.)

**Comment by klinker24** [comment]
Yes, I started noticing it after that update, across a few apps. I could forcefully close the keyboard whenever the app is backgrounded, but I am not sure if that is really something that should be done. It would solve the issue, but may have other implications. 

I hate having to decide on implementing workarounds for system level issues. I also hate 1 star reviews for system level issues - and there have been a few for this problem.

**Comment by klinker24** [comment]
I went ahead and added something to just forcefully dismiss the keyboard, as a workaround, whenever the user exits the apps. On my end, that is all that is going to be able to be done for this issue.

I will be releasing it to beta, along with some other changes with `v2.8.4`, probably later today.

**Comment by PostaQ** [comment]
Thank you.

On Feb 22, 2018 6:02 AM, "Luke Klinker" <notifications@github.com> wrote:

I went ahead and added something to just forcefully dismiss the keyboard,
as a workaround, whenever the user exits the apps. On my end, that is all
that is going to be able to be done for this issue.

I will be releasing it to beta, along with some other changes with v2.8.4,
probably later today.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/klinker-apps/messenger-issues/issues/594#issuecomment-367689590>,
or mute the thread
