### ISSUE TITLE
Use the Snap Package format

### ISSUE THREAD

**Issue by scoronado12** [klinker-apps/messenger-issues#597]
Hi Luke,

It would be nice to have the Pulse Desktop Client packaged for Linux under the new Canonical [Snap package format](https://snapcraft.io), just so I can have your application contained with its' own set of libraries instead of depending on the system.
Snap works on multiple distros so you're not only targeting Ubuntu as I am using Arch on my machine and do install snaps without issues.

Thanks

**Comment by klinker24** [comment]
Isn't that what the `AppImage` already accomplishes?

**Comment by klinker24** [comment]
Any feedback on why I should be using snap over AppImage? They seem to accomplish the same goal to me. If not, I am going to close out this issue.

**Comment by klinker24** [comment]
Closing due to lack of response. Feel free to comment back with the advantages of snap over AppImage and I can re-open. It just looks to me that they are the same thing.

**Comment by jwillikers** [comment]
@klinker24, many users find it convenient to install direct from Ubuntu's software center. Having a snap package will allow users to easily access your app. I think it would be a good way to increase your user base, and I believe Electron builder supports Snap packages. I would find this convenient. Thanks.
