### ISSUE TITLE
Display sender in group message notification

### ISSUE THREAD

**Issue by PlasticSpaghetti** [klinker-apps/messenger-issues#598]
**Device with issue:** MacBook Pro with macOS 10.13.3
**Primary device:** MacBook Pro, Samsung SM-N950U
**App version:** 1.1.1

**Issue:**
Notifications for group messages do not clearly show the sender of the most recent message.

**Mac Notification:**
![screen shot 2018-02-22 at 10 52 27 am](https://user-images.githubusercontent.com/18074227/36549064-d3b2383a-17bf-11e8-8dec-6dcc31ba1b56.png)

**Additional information:**
On Android, the sender of the most recent message is displayed below the list of group members, beside their respective message. Notifications directed towards smart devices (in my case, SM-R600: Gear Sport), have the same issue.

![screen_20180222_105208](https://user-images.githubusercontent.com/18074227/36549715-70e04060-17c1-11e8-8052-f73360856a21.png)

**Possible solution:**
Prioritize the name of the sender of the most recent message.

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/messenger-chrome/commit/5578ab7084abb957c334658741f9ce30aa3eab33

**Comment by kjohns2489** [comment]
How was this issue solved? I would like to see the sender name when they respond to a group text. Also would like the sender name at the top of a bubble instead of the bottom.
