### ISSUE TITLE
Choosing recipients in group message

### ISSUE THREAD

**Issue by PostaQ** [klinker-apps/messenger-issues#599]
- [ ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [ ] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** <insert your device: "MacBook Pro on MacOS 10.12, running Chrome v54">
**Primary device:** <insert your phone: "Pixel XL on Android 7.1.2">
**App version:** <insert version: in "My Account" on the phone>
**Steps to reproduce:**

1. step 1
2. step 2
3. step 3

`... more steps`

**Additional information:**

Do you want to provide any other information? Device configuration, unique cases, screenshots, anything that you think may be relevant.

**Possible solution:**

Do you have an idea of how to solve it? If not, that's fine. You can delete this section.

**Comment by klinker24** [comment]
Like I said last time, you need to fill in the information on the issue, not just post the template. I am going to close this until you provide more information.. .I have no clue what you are asking for.

* You can edit the recipients in a group message by going to the group settings page
* You can select however many recipients you want, when going through the compose screen
* You can add or remove recipients from groups that are defined in your contacts app, when you select that group in Pulse.

If you aren't asking about any of those things, then I am not clear what you are looking for.

**Comment by PostaQ** [comment]
Strange. I filled in every field you asked for this time; I went through
each field and filled it in.  I'm using an OP5 updated to Oreo. Pulse
version 2.8.2 1934.

   - You can add or remove recipients from groups that are defined in your
   contacts app, when you select that group in Pulse.

When I choose a group the field above is populated with all the recipients
in that group.  I have to click on each individual recipient to delete
them.  That's fine for the recipients on the bottom of the list, however,
when I try to scroll to the top of the list (keep in mind I have over 30
recipients) it automatically scrolls back to bottom.  I can never reach the
top of the list.

I tried creating the mms group and then editing it.  But the same problem
persists when editing an existing group.

I suggested to use a format similar to the stock messaging app.  There are
tick boxes next to each recipient.  I can choose either the entire group or
choose only those members of the group that I need.  It's much easier to
choose who you want than to delete those you don't want.  Also the
recipient names are all in one column and easily distinguishable.

I wrote all this in the fields on github.  Not sure why it didn't upload
properly.

**Comment by klinker24** [comment]
https://github.com/klinker-apps/messenger-issues/issues/588

**Comment by PostaQ** [comment]
Thank you for you patience.  I actually did a search before I posted and
did not find this.
