### ISSUE TITLE
Chrome app: chat window shows "Messenger" instead of contact name

### ISSUE THREAD

**Issue by lament** [klinker-apps/messenger-issues#60]
**Device with issue:** Nexus 6P running Android 7.0
**Primary device:** Nexus 6P running Android 7.0
**App version:** 1.1.255

Maybe this is addressed in the latest Chrome app update (I haven't received it yet because I'm still having to manually refresh my messages), but when you click on a person's name to go into their chat, it says Messenger instead of their name.

**Comment by klinker41** [comment]
fixed with https://github.com/klinker41/messenger-web/commit/11ca971c68eca9293cfe80f9e9f5061120817bf8
