### ISSUE TITLE
When blacklisting a contact, offer option to delete the conversation

### ISSUE THREAD

**Issue by talha131** [klinker-apps/messenger-issues#601]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [x] If this is an issue, and not a request, I have verified that this is something that is reproducible

As per #535, when a conversation is blacklisted, it is archived. If I blacklist a spam sender, then it does not make sense to keep its messages stored in archive. Currently, after blacklisting a contact, I have to go to archive section to delete that conversation.

If you can offer an option in blacklist dialog, a simple checkbox or a third button, that lets you blacklist and delete conversation that would be great.

**Comment by klinker24** [comment]
I don't really see this coming, sorry. With Pulse, I just want simple features, without too many options or choices. I want to have default behavior that just works well for everyone. While this may not be a complicated options, it is just one more thing that the user has to make a choice on, which is not always a good experience.
