### ISSUE TITLE
Add Tooltips To Web Icons/Buttons

### ISSUE THREAD

**Issue by DavidCao22** [klinker-apps/messenger-issues#602]
**Device with issue:** Dell Latitude 11
**Primary device:** Google Pixel
**App version:** 2.8.3.1945
**Steps to reproduce:**

1. Go to web version
2. Hover over any icon or button

**Additional information:**

I think it'd be nice to have tooltips that pop-up when hovering over the buttons/icons on the web version of the app. It's a super small feature request, but it'd be nice to have for usability especially with new users.

Here's an example [https://material.io/guidelines/components/tooltips.html#tooltips-interaction](https://material.io/guidelines/components/tooltips.html#tooltips-interaction)

**Possible solution:**

Javascript? As a suggestion, Bootstrap uses [Popper.js](https://popper.js.org/)

**Comment by klinker24** [comment]
You just talking about the refresh, search, and compose messages on the app bar? Figured those were very self explanatory, to be honest. I guess there is also the emoji and attach buttons on the message list screen.

**Comment by DavidCao22** [comment]
Yeah, those buttons. Again, super small feature request. It's more of a nice touch than a feature.

I only bring it up since I got slightly confused earlier. I'm used to the big floating + button in the bottom corner. Then, when I was in a conversation, I saw it in the app bar and thought it was for adding a message to the current conversation even though there was already a spot on the bottom to type/send a message. I figured it out after clicking it in the app bar. If anything, I didn't expect it to be in the app bar.

**Comment by klinker24** [comment]
Where would you have expected it to be within the message list? Two FABs in a single screen is frowned upon, heavily. It has the same icon and it doesn't make sense to duplicate the functionality that is already so readily available in the reply bar at the bottom.

I can add the tooltips, it's not like they are difficult, but I am curious what you were thinking.

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/messenger-web/commit/3ccee7600073653a06c5b528bd91a38ed8dc3532
