### ISSUE TITLE
Mac app regularly hogging CPU

### ISSUE THREAD

**Issue by myessail** [klinker-apps/messenger-issues#605]
**Device with issue:** MacBook Pro on MacOS 10.13.2
**Primary device:** Pixel 2 Running Android 8.1.0
**App version:** Phone: 2.8.2.1934, Mac: 1.1.1
**Steps to reproduce:**

1. Start the Pulse SMS app on your computer.
2. Receive a message. I usually leave the window closed.
3. Open the window, respond, write a new message, etc, and close it again
4. After a certain amount of time has passed (maybe an hour or so) the app will be using about 70% of my CPU, even with the window minimized and no new messages coming in.
5. Kill all Pulse SMS processes, CPU usage goes back to normal, fans cool down

**Additional information:**

For at least the past few weeks, I've noticed that my laptop battery life has been reduced to around 2 hours (from 6-7) and that the fans are regularly making a lot of noise. I've pinned it down to pulse, as when I hear my fans spinning up, it's using around 70% of my CPU even if the window is closed. When I first start the app, CPU usage is around 2% and it generally gets much worse within an hour of me continually using my computer. I'll try and take better notice of exactly what actions make it worse, and update this post accordingly. The one thing I have noticed is that when I'm in that high CPU usage state, there are multiple "pulse-sms" processes running, not just the ususal "Pulse SMS" and the helpers that it boots up with.

**Comment by klinker24** [comment]
Pulses uses a dependency called [node-notifier](https://github.com/mikaelbr/node-notifier) to provide notifications. This dependency, in turn, depends on [terminal-notifier](https://github.com/julienXX/terminal-notifier). `terminal-notifier` has an issue with this, on the version that is imported in to node-notifier: 

https://github.com/julienXX/terminal-notifier/issues/218

The solution for this probably won't come on my end, `node-notifier` will need to be updated with the latest `terminal-notifier` for this to get fixed. I am not sure why it happens to some people and not others. 

If this is happening to you, the only workaround that I can provide is to turn off notifications on the Mac desktop app. You could install the Chrome extension to provide you with notifications instead. Obviously that is a workaround and not a solution. This is an upstream issue, unfortunately.

**Comment by klinker24** [comment]
I am just going to go away from that dependency, actually. https://github.com/klinker41/messenger-chrome/commit/9e54a65cc52e55409ac5b06ecd25993b82ba4419
