### ISSUE TITLE
Firefox Extension doesn't show notifications

### ISSUE THREAD

**Issue by Cabeda** [klinker-apps/messenger-issues#606]
- [X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [X] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** Asus N56VB on Firefox 59 Developer Edition
**Primary device:** OnePlus One on Android 7.1.2
**App version:** <insert version: in "My Account" on the phone>
**Steps to reproduce:**

I don't receive any notification of new messages from the firefox extension

**Additional information:**

None

**Possible solution:**

None

**Comment by klinker24** [comment]
I always recommend the native apps for notifications, over the browser extensions. I do not get to control their life cycle or how they perform in the background. There is probaby an issue with your Firefox configuration that I will not be able to fix on my end.

So I always recommend the desktop apps for notifications.

https://messenger.klinkerapps.com/overview

**Comment by Cabeda** [comment]
I'm not sure if it helps but it works perfectly if I have the messenger open in a separate tab instead of using the add-on

**Comment by klinker24** [comment]
The webpage will provide notifications whenever you have it open, that doesn't have anything to do with the Firefox extension, no.
