### ISSUE TITLE
pulse-sms-1.2.0-amd64.deb Desktop installation displays 'v1.1.1' in Help menu

### ISSUE THREAD

**Issue by NoOpG** [klinker-apps/messenger-issues#607]
**Device with issue:** <Linux 4.4.0-116-generic #140-Ubuntu x86_64 x86_64 x86_64 GNU/Linux>
**Primary device:** <insert your phone: "Essential on Android 8.0">
**App version:** <pulse-sms-1.2.0-amd64.deb>
**Steps to reproduce:**

1. Install pulse-sms-1.2.0-amd64.deb (sudo dpkg -i pulse-sms-1.2.0-amd64.deb)
2. Open Pulse
3. Click on 'Help' menu - v1.1.1 is displayed instead of v.1.2.0

**Additional information:**

Control in deb appears correct:

```
Package: pulse-sms
Version: 1.2.0
License: Apache-2.0
Vendor: Luke Klinker <luke@klinkerapps.com>
Architecture: amd64
Maintainer: Luke Klinker <luke@klinkerapps.com>
Installed-Size: 155787
Depends: gconf2, gconf-service, libnotify4, libappindicator1, libxtst6, libnss3, libxss1
Section: default
Priority: extra
Homepage: https://github.com/klinker41/messenger-chrome#readme
Description: 
  A native desktop implementation of Pulse
```

![screenshot from 2018-02-25 19-52-15](https://user-images.githubusercontent.com/20523293/36653467-274dc3fe-1a6a-11e8-8f7c-9b80b562e8d4.png)

**Comment by klinker24** [comment]
I think I would be more interested in a screenshot of what shows up under the preferences tab and whether or not you have the new functionality. If It is showing 1.1.1 in the help tab, I imagine that is what is installed and that the installation command failed for you.

**Comment by klinker24** [comment]
I bet that it just didn't shut down the old instance of the app and it is opening that one. You could just restart the computer to shut down the old instance and I imagine that will fix your problem.

**Comment by NoOpG** [comment]
Restarting did the trick, it is now showing 1.2.0. Thanks issue closed.
