### ISSUE TITLE
Blink all the application after receiving a message. 

### ISSUE THREAD

**Issue by ablyes** [klinker-apps/messenger-issues#608]
- [X ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [ X] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Native app version:**  "v1.2.0"
**Primary device:** "Samsung SM-G950F"
**Phone version:** "2.8.5.1953"

**Steps to reproduce:**

1. Launch "Pulse SMS" native application on macOS, go to conversion user "USER1"
2. Ask "USER1" to send you an sms
3. Go the PulseSMS Native app

**Observed**
All the native application blink to refresh all the complete window.

**Expected result**
Only the conversation should be updated to avoid blink result.

**Comment by ablyes** [comment]
Dear developer, 

By avoiding the update of all the window, we will feel the application more "fluent".

**Comment by klinker24** [comment]
Sorry I don't understand what you are talking about. The app doesn't update the window when you receive a message, it adds the new message to the screen. I don't really get what you are describing here

**Comment by ablyes** [comment]
No problem, I will try to explain it differently. 

I mean, after receiving a new sms, and clicking on pulse SMS (native app on mac os),
being in conversation with USER1, than it will refresh the content of all the window. 

For 1 second, all the content of the window will disappear, than will reappear with data updated (old messages + new message). 
This is what i call the BLINK syndrome. Like when you refresh a webpage on a browser. 

I hope it's clear.

**Comment by ablyes** [comment]
ok, i tried it a lot of times.
Sometimes I get the new message without blink effect. 
Quiet strange. 

Are you doing a refresh in background ? 
May be the refresh is not done when I click on the pulse sms app, and than it does the refresh ...

**Comment by klinker24** [comment]
I don't refresh in the background. If your computer allows the web socket connection to remain active on the web page that is within the desktop app, then it will display the new messages without your "blink" effect, since they are already loaded.

If the web socket is lost, then Pulse looks for new messages and conversations when you return to the app. I am not going to be able to fix or change this, in that situation. The app doesn't know what is new and what is old, it just knows that there is new content that was missed while the connection was idle. This is working as expected.

**Comment by ablyes** [comment]
Ok, I understand. That means i'm loosing ofter the web socket. 
Suggestion to avoid blink effect:
IF SOCKET LOST
- keep the old view displayed (do nothing)
- build the new view
- display the new view. 

I think you are doing something like this for the moment ?
IF SOCKET LOST
- erase the view
- build the new view
- display the new view
