### ISSUE TITLE
[Internationalization] Every thing I write in french language is underlined in red

### ISSUE THREAD

**Issue by ablyes** [klinker-apps/messenger-issues#609]
Native app version: "v1.2.0"
Primary device: "Samsung SM-G950F"
Phone version: "2.8.5.1953"

Steps to reproduce:
Launch "Pulse SMS" native application on macOS
Write a new message

Observed: 
Each word wrote in french is underlined in red. 

Expected result:
Underline only words that has a wrong spelling or just do not underline words.

**Comment by klinker24** [comment]
Yes, this would be an issue. Hmm, thanks for the report.

**Comment by ablyes** [comment]
Don't hesitate to ask me for internationalization of the menu in french. 
I'll do it with pleasure.

**Comment by klinker24** [comment]
This commit will fix your current issue: https://github.com/klinker41/messenger-chrome/pull/4/commits/9ed7255fa0c970cbe96cebcc0d1922f7c2cd0f4c

It will roll out with the next version of the desktop app. At this time, spell check should only be applied to English. This is not ideal, of course, hopefully it will be able to expand outside of English, in the future.

Localization is definitely something I would like to add to the web and the desktop apps in the future, but I am not currently prepared to do so, unfortunately. Thank you for the offer though, will definitely keep that in mind, when the time comes!
