### ISSUE TITLE
Lost message history

### ISSUE THREAD

**Issue by ghctim** [klinker-apps/messenger-issues#61]
On Android primary device I was in the contacts App, and selected a person and then share to share the vcard.  I selected Google Messages as my SMS app and shared the contact via Messages.  I changed Primary SMS app to messages temporarily.  I then went back to messenger and changed SMS app back to messenger.  

2 problems:
1) lost pinned messages
2) lost history in one SMS convo.  Only the last 2 messages now appear.

**Comment by klinker41** [comment]
Not sure how either of these 2 things would have happened. If we aren't the default then our database just sits and waits, it won't make any of those changes.

**Comment by ghctim** [comment]
anyway to force a resync?

**Comment by klinker41** [comment]
Remove your account, delete the app data and sign up again.

**Comment by ghctim** [comment]
I think i deleted the thread by accident

**Comment by ghctim** [comment]
Would like to reopen the issue, i figured out how to reproduce this (by accident).  

Received a new message from a contact, held and slide the message by accident.  thread was deleted.  Clicked undo.  When i went back into the thread only an empty thread was shown.  Then I closed and reopen the app and even the empty thread was gone.  Seems like undo isn't undoing with unread messages.

**Comment by ghctim** [comment]
Adding more detail.  When you undo a delete you lose the preferences around pinned, ringtones and color

**Comment by klinker24** [comment]
I cannot confirm any of these things are happening, however, I made a change and will now close this issue: https://github.com/klinker41/messenger/commit/e993e6bf433d6efb0a67bb1be8d754358e12dc30
