### ISSUE TITLE
Touch input issues

### ISSUE THREAD

**Issue by z0oinks** [klinker-apps/messenger-issues#610]
**Device with issue:** <Surface Book Windows Desktop Application">
**Primary device:** <Samsung Galaxy S8 on Nougat">
**App version:** <v1.2.0 on Desktop, App Version 2.8.5.1953 on Phone>
**Steps to reproduce:**

1. Open Pulse
2. Enter a conversation
3. Try to scroll the conversation list with touch

**Additional information:**

Scrolling with a mouse is fine. It just doesn't work with touch.

**Comment by klinker24** [comment]
So are you saying it doesn't respond to touch input at all, or jus scrolling? Does it work on the web app, rather than the Windows app?

**Comment by z0oinks** [comment]
In both the web and desktop clients, all touch inputs work besides scrolling the sidebar conversation list. 
It will scroll the conversation list if you aren't already in a conversation.

**Comment by klinker24** [comment]
Can you provide any updates on this issue? In the past year and a half, the web and desktop apps have both undergone major structural changes to the way that the layout is set up. I was just looking through old issues and was wondering if you are still having problems with this.

**Comment by klinker24** [comment]
I am going to go ahead and close this issue. Please feel free to comment back with an update, if this is still something that needs to be explored.
