### ISSUE TITLE
No Input With Pen

### ISSUE THREAD

**Issue by z0oinks** [klinker-apps/messenger-issues#611]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [x] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** <Surface Book Windows Desktop Application">
**Primary device:** <Samsung Galaxy S8 on Nougat">
**App version:** <v1.2.0 on Desktop, App Version 2.8.5.1953 on Phone>
**Steps to reproduce:**

1. Open Pulse for Desktop
2. Try to do anything with a pen

**Additional information:**

Clicking menu items in the Menu Bar with the pen will darken them as if they've been clicked, but the menu does not open.

When in a conversation and hovering the pen over a conversation in the sidebar, the scroll bar will appear.

**Comment by klinker24** [comment]
Pretty sure that this is the same as #610. Solving one of them would solve the other.
