### ISSUE TITLE
Per-person coloring lost

### ISSUE THREAD

**Issue by kirstilynn** [klinker-apps/messenger-issues#612]
**Device with issue:** MacBook Pro on MacOS 10.12, running v1.2.0 of desktop client
**Primary device:** Pixel XL on Android 7.1.2
**App version:** v1.2.0
**Steps to reproduce:**

1. receive desktop notification from a group converstaion
2. click on notification
3. when the conversation window opens, all texts will be one color, instead of the per person coloring

If you click to another conversation and then click back to the group conversation to force a refresh, this will restore the per person coloring.

**Comment by klinker24** [comment]
Closed with https://github.com/klinker41/messenger-web/commit/0287aa3991b82e36416ac66e64f7e9c0ec31dbfc
