### ISSUE TITLE
Improve the compose screen

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#614]
**Feature Request:**

I want to spend some time re-doing the compose screen on the web version of the app.

1. It should be a bit bigger window. On small screens, it could even be 100%
2. The user should be able to get a list of all contacts somewhere
3. I would like to use a "chips" UI for the contacts: https://www.w3schools.com/howto/howto_css_contact_chips.asp

**Comment by jpwilbur** [comment]
To add to this, it's really not very helpful to select a contact when composing a message and seeing the number pop up. It really should be the contact's name. This is particularly useful when making a group message.

**Comment by klinker24** [comment]
That would be what the chip accomplishes.

**Comment by klinker24** [comment]
This is done: https://github.com/klinker41/messenger-web/pull/24 

![screen shot 2018-05-07 at 12 59 23 pm](https://user-images.githubusercontent.com/4874287/39716671-92fef28a-51f6-11e8-93c7-473b0323ada2.png)
