### ISSUE TITLE
Mark conversation as unread

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#615]
**Feature Request:**

Long click a conversation and have the ability to mark it as unread.

**Additional information:**

I am not going to have room for all of these options on the toolbar, I may have to hide some of them in the overflow menu, for the long click toolbar. That is probably ok, the mute and pin will be more clear if there is text instead of just an icon, anyways.

**Comment by gandalf666** [comment]
Another example of how one might approach this is to have a long press to enable the top toolbar (like you currently handle).  But a single click might present an additional toolbar right above the message bubble with current options for just the individual bubble.

**Comment by klinker24** [comment]
Sorry I am not a big fan of having two different toolbars on the same screen. They would both effectively be doing the same thing, one with different options than the first, which is confusing.

**Comment by klinker24** [comment]
Done with: https://github.com/klinker41/messenger/commit/326c1f27b8e04471b652159e4ab0577c77c103f8

It will be released with v3.0.0.
