### ISSUE TITLE
Conversation list flashes when backing out of conversation settings

### ISSUE THREAD

**Issue by camsteffen** [klinker-apps/messenger-issues#616]
When I open conversation settings and then tap the back button, the conversion list screen flashes for a second before the conversation that I was in opens.

**Comment by klinker24** [comment]
This isn't going to change, sorry. It is just a drawback of the architecture that I have set up for the app. It has to start at the conversation list, then open the conversation.

**Comment by camsteffen** [comment]
I'm surprised you wouldn't want to fix this. Having just discovered the app, I'm impressed by how polished it is otherwise.

**Comment by klinker24** [comment]
It is an unfortunate drawback to the architecture I have set up, which allowed for that polish on the rest of the app. Sorry, I don't see this one changing any time soon. 

I don't see this as a huge deal, to be honest. The rest of the app and the navigation in general are more important to me than this split second
