### ISSUE TITLE
Red X closes app on OSx

### ISSUE THREAD

**Issue by akaBigCat** [klinker-apps/messenger-issues#617]
**Device with issue:** OSX v 10.12.6">
**Primary device:** "Pixel 2 XL">
**App version:** OSX .dmg app
**Feature Request for OSX:**

Issue:
1. Clicking the Red X closes the app.  It would be best if it was only minimized.

Request:
- Clicking the Red X minimizes the app but does not exit it.  This would make it much more reliable as closing the app will prevent notifications, and the (more) natural behavior in OSX is to use the Red X to hide windows for things that should be running in the background.

**Comment by klinker24** [comment]
That is exactly what it does. The app is never closed with Pulse, regardless of what platform you are on. See this topic for info around how it works.

https://github.com/klinker-apps/messenger-issues/issues/493

**Comment by akaBigCat** [comment]
Yep - I'm an idiot - sorry I thought it was actually closed.

Thanks
