### ISSUE TITLE
Display consistent, unique colors per contact in MMS conversation view

### ISSUE THREAD

**Issue by int-a** [klinker-apps/messenger-issues#618]
It would be great if within an MMS thread each contact was assigned a color and it did not change. Currently the same contact can send two messages and their message bubbles would be two different colors.

**Comment by klinker24** [comment]
Haven't heard of this from anyone else. It should just follow whatever color is on their individual conversation. You can try just using the resync contacts option under the account section of the phone app.

**Comment by int-a** [comment]
Hmm, you're right. Going back and looking at my conversations now the colors are consistent. Sorry! Not sure what I was thinking. I'll close this.
