### ISSUE TITLE
Change color for the sender bubble in conversations

### ISSUE THREAD

**Issue by WizZYou** [klinker-apps/messenger-issues#619]
<Samsung Galaxy S8 on Nougat>
<same device>
Version 2.9.0.1964 (latest on PlayStore)

I wonder if it is possible to add the possibility to change "sender" color.
For the moment only the messages you receive can be customized in the settings.
I'm used to the regular Messaging app which displays the colors the other way (grey for others and orange for you). It's quite confusing !

You can make it globally for all conversations or customizable for each one, as you want !

You can allow us to enter HEX colors too (as i saw on your previous post) or just copy previous colors (if we change and want to get them back for example) because i modified it for a conversation and was impossible to find the same again :)

Thanks in advance for your feedback,
WizZYou

**Comment by klinker24** [comment]
This isn't going to come to Pulse, sorry. I am not really looking to make an app where you can tweak every single detail, I want an app that just works out of the box, where you don't have to go digging through settings. I really don't want to add another set of colors to the global configuration, or the per-conversation configuration.

I want Pulse to be about the features, not about the tweak options

You can enter hex colors for a conversation, from the web version of the app. This is not available on Android: https://messenger.klinkerapps.com/help
