### ISSUE TITLE
Android P: Integrate new notification features

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#621]
**Feature Request:**

This page outlines an assortment of new notification features for Android P: https://developer.android.com/preview/features.html#notifications

They all run off of the `MessagingStyle` notification that Pulse already uses, which is great. These new features should be included if the user has not turned off the `Show history in notifications` preference in settings. That preference disables the `MessagingStyle` notifications.

* [x] Display pictures in the preview with the `setData` method: https://developer.android.com/reference/android/app/Notification.MessagingStyle.Message.html#setData(java.lang.String, android.net.Uri)
* [x] Use the [Notification.Person](https://developer.android.com/reference/android/app/Notification.Person.html) class instead of just a name, so that group conversations show a profile picture (when applicable)
* [x] FINALLY: [save messages as drafts](https://developer.android.com/reference/android/app/Notification.html#EXTRA_REMOTE_INPUT_DRAFT) if the user has typed something in to the notification, then closes it (or opens the app).
* [x] If it is a group conversation, [tell](https://developer.android.com/reference/android/app/Notification.MessagingStyle.html#setGroupConversation(boolean)) the notification that. It doesn't say what this actually does for the notification - it may not do anything yet - but it will undoubtably be used in the future.
* [x] Some people were always confused by Pulse's `Read` button in the notification. This button is to "mark as read", rather than "open the conversation". You can now set [semantic text](https://developer.android.com/reference/android/app/Notification.Action.Builder.html#setSemanticAction(int)) to actions, to clarify this. I don't know how it will be used. Hopefully the user can long click the button and it will pop up with a toast, similar to the `AppBar` items.
* [ ] Add reply choices. This is probably something that I want the user to be able to define on their own. Since I cannot do any machine learning against my data set (since it is encrypted), I will probably not be able to provide "smart" suggestions here: https://developer.android.com/reference/android/app/RemoteInput.Builder.html#setChoices(java.lang.CharSequence[])
* [x] Can I make a preference to dismiss notifications after sending the message? I don't really like that "feature" of P.

**Additional information:**

These are some great additions and will be really easy to integrate. I doubt I will do it until the support library integrates them though, there is really no rush. The release of P is still very far off.

**Comment by erik-sv** [comment]
From using the app with Android P beta, something that would be neat to implement is setting an account photo for yourself that will show up next to "you" in the notification. I also agree that the Android P "feature" keeping the notification after sending a reply is a minor annoyance.

**Comment by klinker24** [comment]
This is done. Some notes:

* It doesn't seem like notifications can be dismissed after a reply. At least I couldn't find a way. That "feature" will stick.
* I am holding off on the smart replies, until Google releases the smart reply support into Firebase MLKit.

**Comment by garysahota** [comment]
Hi @klinker24 - Smart replies are officially available via the Firebase MLKit!

https://9to5google.com/2019/04/05/ml-kit-smart-reply/

Can we get this feature added?
