### ISSUE TITLE
Question: Notification changes?

### ISSUE THREAD

**Issue by Skullmonkey** [klinker-apps/messenger-issues#622]
**Device with issue:** Gear S3 Frontier
**Primary device:** Pixel XL Oreo 8.1
**App version:** 2.9.2.1974

**Additional information:**

I was wondering if you changed how notifications work in the recent update. Before, I got my watch to vibrate every time I received a new message and now I do not get the notifications on my watch. I have tried everything I could think of on my end (reset my watch + apps, checked all my settings, restarted everything, etc) and the only other thing I could think of is that the problem started after I updated Pulse last night. If there is a way, is it possible to get an older version of the APK to see if the update is indeed the source?

**Comment by klinker24** [comment]
No, I haven't changed anything. You can grab old versions from apkmirror.com
