### ISSUE TITLE
Link previews don't support Twitter & Instagram

### ISSUE THREAD

**Issue by KitF** [klinker-apps/messenger-issues#623]
- ✅ I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- ✅ If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** Windows 10, Pulse SMS 1.2, Google Pixel (1), Android 8.1, Pulse SMS v. 2.9.2.1974
**Primary device:** Pixel on Android 8.1
**App version:** 2.9.2.1974
**Steps to reproduce:**

1. Receive Tweet link or Instagram link
2. No preview shows

**Additional information:**

From the initial feature request, it looks like Twitter links at least were supported at one time. 

**Possible solution:**
I know Twitter and Instagram have card schemas that this app could use.

**Comment by klinker24** [comment]
We have an issue open here to apply the internal web preview engine to other topics: https://github.com/klinker41/article-android/issues/14

I am going to close this to delegate to that repo.
