### ISSUE TITLE
Toggle swipe-to-close

### ISSUE THREAD

**Issue by BryanDiLaura** [klinker-apps/messenger-issues#624]
**Feature Request - Android Mobile**
I'm not a huge fan of swipe-to-close and would love to be able to toggle it on/off. 

I imagine that it would fit well in the "Look and Feel" section of the customization settings. 

Keep up the great work!

**Comment by klinker24** [comment]
With Pulse, I really want to stay away from little UI tweak options like this. I want to make a layout and UX that works well for the vast majority of people. More settings does not make for a better user experience in almost all cases, they just goes to distract from the features and confuse new users. I want an app that anyone can just pick up and use, without digging through settings. I know that this is just a single setting, but if I open the doors, then where does it stop?

Sorry, disabling this really isn't planned for Pulse... It isn't all that easy to swipe and you have to be at the bottom or the top of the list to close it. At this point, I have to say that this option probably will not come - sorry about that.
