### ISSUE TITLE
Omit Contact Surnames from Conversation Titles

### ISSUE THREAD

**Issue by egocarib** [klinker-apps/messenger-issues#628]
It does not appear that there is any option to show only a contact's first name in the title of a conversation. The contact's last name is always shown. This is particularly problematic for group SMS, because the title of the group conversation includes all my contact's surnames. This results in only being able to see about 2-3 names in the conversation title, and the rest are cut off by the ellipses. It also makes the titles sounds overly formal, when I'm usually just texting with family or close friends.

As a workaround I have been manually renaming my group conversations, but that is very tedious.

**Comment by klinker24** [comment]
To be honest, I don't see an option like this coming. Have you ever used an app that allowed you to customize how contact names get imported? That seems a bit of an over-the-top customization to me. 

With Pulse, I really don't want to add little tweak options all over the app. Things like this distract from the feature set and go to confuse many of the user, who don't understand how they work or why they would want that option.

Right now, Pulse allows you to customize the title of any group conversation, and I think that is all the further I want to go with that... Sorry about that

**Comment by egocarib** [comment]
Fair enough. I understand if you don't implement this.

I wouldn't classify it as"over the top," though. It wouldn't require custom
importing contacts, and other SMS apps I use by default only show the
"first name" field from my contacts in group conversations. For example,
other app would show:

Matt, Dave, Sally, Tom

Instead of:

Matt Michaels, Dave Brownstein...


I often have multiple conversations that are different only by one person
included/excluded. With Pulse, I can't see the full list of people, which
gets truncated, so I can't easily distinguish one conversation from another.

Thanks for considering the issue whatever you may decide to do with it.
