### ISSUE TITLE
Plain text to emoji on desktop

### ISSUE THREAD

**Issue by wtruax** [klinker-apps/messenger-issues#629]
**Device with issue:** Samsung Laptop running Windows 10 home
**Primary device:** Samsung Galaxy S7 edge on Android 7.0
**App version:** 2.9.2.1974

**Steps to reproduce:**

1. If I type ":)", then no smiley emoji is produced when I send from desktop

**Additional information:**

Is there a way to type plain text emojis on desktop to produce its corresponding icon without having to pull up the emoji window icons? 

Thanks

**Comment by klinker24** [comment]
I don't know if this is something that will ever happen, sorry. 

I would rather not auto convert to emojis and it wouldn't make sense to do this just on the desktop/web app, it would need to be applied to Android too. Is there any reason you don't want to just open the emoji input? It is pretty accessable and easy enough to search

**Comment by wtruax** [comment]
Sorry, I'm part of a usability lab and look for efficiency. When you're typing with your hands on the keyboard, it seems inefficient to have to transfer control to a mouse or touchpad. Most people have a set of common emojis they use and know the shorthand by memory.

**Comment by klinker24** [comment]
I think I would be much more inclined to provide a shortcut key combo to open the emoji selection dialog then. Would that fulfill your requirement? I'm against converting plain text to emojis, some people use both.

**Comment by KitF** [comment]
Since the Fall's Creators Update, you can open the Emoji shortcut panel using the Windows key and period "."

WinKey + .

**Comment by wtruax** [comment]
Thank you

**Comment by klinker24** [comment]
I am going to close this issue and add the request to add the shortcut to #344.
