### ISSUE TITLE
Add Fedora rpm install

### ISSUE THREAD

**Issue by TheRoarkster** [klinker-apps/messenger-issues#630]
**Device with issue:** Fedora 27
**Primary device:**  Android 7.0
**App version:** AppImage 1.2.0

This is a feature request to add a Fedora .rpm.  While the appimage works, in Fedora running GNOME at least, it appears as a question mark in the dock.  The app also does not appear in the launcher search and cannot be added to the dock's favorites.  **Note** this is still the case after installing `appimaged` (https://github.com/AppImage/AppImageKit#appimaged-usage), which is supposed to handle this issue.

**Comment by klinker24** [comment]
I have the build configured to start releasing an `rpm` file for the next release of the `2.0.0` version of Pulse: https://github.com/klinker24/messenger-desktop

You can watch for it whenever the next beta version of the desktop app is released.
