### ISSUE TITLE
Critical: Pulse does not notify or display certain texts in group conversations

### ISSUE THREAD

**Issue by jmdodge** [klinker-apps/messenger-issues#631]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [x] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** Repro'd on both Samsung S7 Edge & Samsung S8+
**Primary device:** S7 Edge
**App version:** 2.9.3.1982 (currently), but existed probably 4-6 months ago and possibly longer
**Steps to reproduce:**
(Happens sporadically, cannot reproduce every time)
1. Send a group SMS
2. Get some replies
3. Open a different messaging app.
4. Notice that there are some messages NOT displayed in Pulse that are displayed in the other app.

**Additional information:**
This issue has been happening to me for quite a while since I began using Pulse, but it has been difficult to pin down. Initially I thought it was related to switching carriers (went from Verizon to T-Mobile), but since I have since switched back and still have the problem. Ultimately I determined the issue was Pulse itself, since I could see the missing messages when I went to another app.

- Pulse is set to the default messaging app when messages are received
- For messages that don't appear in Pulse, there is no notification sound/light/tray message to indicate a message was received.
- This issue doesn't happen all the time. It doesn't seem to happen that often. When a message fails to appear in Pulse, it appears to be random, sporadic.
- In the most recent instance, I noticed that the missing messages were timestamped with the same time when I looked at them in the Samsung messaging app. May be irrelevant, and I haven't noticed if this occurred in previous instances. The context of these messages is usually that I am asking players if they are attending our rec soccer games, and it may be that several people respond simultaneously, so this could lend credence to the theory that Pulse fails to register messages when several are received at or about the same time. Again, just a wild theory. There may be other instances where the situation was totally different. Obviously I don't always notice when I don't get a message, usually something leads me to be suspicious that I haven't seen something and I check another app and find the message(s)
- I feel like there may be occasions where someone told me they replied to a group text but I could not find it in Pulse or any other messaging app. So, usually I am able to verify that a message was missed, but not always. This may be a red herring, unrelated, or a mistake from the other person.
- My wife uses Pulse. We have been on the same group text before and both seen different messages. E.g. some messages did not go through to my phone, but did go to hers.
- The messages being missed are unremarkable and just contain text. The latest instance, three people sent the same message: "In". Samsung Messages received all three at 2:51pm. Pulse only notified me of one. It shows the first message but not the others.
- I could make a screenshot to prove the most recent instance of this (would show the convo in Pulse vs the convo in Messages) but my time is short so have not provided for now.
- To my knowledge, Pulse has never failed to notify me or display a message that was sent on a one-to-one basis. The issue is only with group SMS.

Reproduced on T-Mobile Galaxy S8+, Verizon S7 Edge, and I believe my wife has had it on her Google Pixel 2 on Verizon and whatever phone she had on T-Mobile. So it is not limited to one device or one network. Based on this variety I think it's fair to say that it's not related to any specific other messaging app on the phone that is interfering with Pulse or something like that.

I marked the title with "critical" because a text app that doesn't notify you of or show you certain messages is a deal breaking issue for me. In fact, I abandoned Pulse once already because of this issue, but when I switched carriers I wanted to give it another chance, thinking it might have been a T-Mobile problem. As a consumer, it's really not worth it for me to continue using this app when I rely on messaging as a means of critical communication for many things, but I guess I'm somewhat invested now. Just thought it might be worth sharing that (possibly obvious) perspective, I would hate for this bug to be trivialized.

Will do my best to provide follow up info as needed but please understand that my time is limited and this is not one of my priorities. Thanks and good luck!

**Comment by klinker24** [comment]
Thank you for the feedback. We track all MMS issues on #101 as well as our open source library for MMS: https://github.com/klinker41/android-smsmms

The 3 messages that are all the same are an interesting case. I do strip out duplicate messages if they come in within the same minute, but I guess those really aren't duplicate when they come from different people. That is a trivial fix that I can make.

I am going to close this as a duplicate. Your issue has been linked to my MMS issue page.

**Comment by mtoenjes** [comment]
I realize this is an old issue, but I have just experienced it several times in the past few days. It was involving a group text thread. Some messages were skipped and one came in a day late.
