### ISSUE TITLE
Copy and Paste - Failed to Compress Image 

### ISSUE THREAD

**Issue by npicklo** [klinker-apps/messenger-issues#632]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [x] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** <Macbook Pro 10.13.3>
**Primary device:** <insert your phone: Samsung S8+>
**App version:** <insert version: 2.93.1982>
**Steps to reproduce:**

1. Copied image using screen capture short cut on desktop
2. Navigate to Pulse, select text field.
3. Command V to paste screen capture.
4. Receive error that Image Failed to Compress or Failed to Compress Image

This feature has worked flawlessly since I started using the desktop app. But recently it has stopped.

**Comment by klinker24** [comment]
So does the same image work fine if you just save it and select it through Pulse, instead of copy and paste? Pulse fails at compressing some images on the web, due to size restrictions and other various reasons. I would think that this issue has nothing to do with copy and paste, rather it is just an issue with the compression.

**Comment by npicklo** [comment]
So if I hit control 1 for shortcut it allows me to screen capture. I have attached the screen capture below.

Then command v allows me to paste.

There is nothing for me to save and select.

[cid:52EAF6DA-9B79-4EA6-832D-E0991D6A843A]
________________________
Nick Picklo, CGB
Certified Graduate Builder
www.PickloHomes.com<http://www.PickloHomes.com>
713.562.0009

Custom Homes  |  Custom Pools  |  Smart Homes


On Apr 2, 2018, at 12:21 PM, Luke Klinker <notifications@github.com<mailto:notifications@github.com>> wrote:


So does the same image work fine if you just save it and select it through Pulse, instead of copy and paste? Pulse fails at compressing some images on the web, due to size restrictions and other various reasons. I would think that this issue has nothing to do with copy and paste, rather it is just an issue with the compression.

**Comment by npicklo** [comment]
Well shoot.

It is working now.

For two weeks it wouldn’t work.

Then I send ya’ll a message and then try to save the screen shot rather than copy and paste.

And copy and paste is working again.
________________________
Nick Picklo, CGB
Certified Graduate Builder
www.PickloHomes.com<http://www.PickloHomes.com>
713.562.0009

Custom Homes  |  Custom Pools  |  Smart Homes


On Apr 2, 2018, at 12:21 PM, Luke Klinker <notifications@github.com<mailto:notifications@github.com>> wrote:


So does the same image work fine if you just save it and select it through Pulse, instead of copy and paste? Pulse fails at compressing some images on the web, due to size restrictions and other various reasons. I would think that this issue has nothing to do with copy and paste, rather it is just an issue with the compression.

**Comment by klinker24** [comment]
Ok, let me know if it comes up again.
