### ISSUE TITLE
auto-hide menu bar permanently hides menu bar

### ISSUE THREAD

**Issue by RobMielcarski** [klinker-apps/messenger-issues#633]
Windows app v2.0.0 beta 3 on WIndows 10.

Selecting auto-hide menu bar permanently hides the menu bar.

Reinstalling the app does not correct the problem.

**Comment by klinker24** [comment]
It doesn't permanently hide it: 

https://github.com/klinker-apps/messenger-issues/issues/466
https://messenger.klinkerapps.com/help

Tap `alt` to bring it back.
