### ISSUE TITLE
Some message sent to SIM2 does not shows on notification

### ISSUE THREAD

**Issue by Vinsup** [klinker-apps/messenger-issues#634]
**Device with issue:** Sony Xperia X running Android O 8.0.0 February Update
**Primary device:** Sony Xperia X running Android O 8.0.0 February Update
**App version:** 2.9.4.1995
**Steps to reproduce:**

Hi,

I will first explain my issue.

For my work, I can connect remotely to my Office365 environment. When I do this, I am asked for credentials and then a 2 factor authentication system sends me a 6 digit code on my phone.

This is where is my problem. Sometimes I do get a notification for this kind of message. Sometimes not.

it is quite easy for me to reproduce, but you won't be able to do it, as soon as it requires my professional password... But I can tell that the messages is sent from a system which identifies itself as "SMSINFO". I don't know if this is helpful.

I already checked notification settings and I have chosen to set all notification on the default channel with everything on.

**Additional information:**

Here is a screenshot of my notifications settings. Sorry it is in french...
![screenshot_20180404-221841](https://user-images.githubusercontent.com/38085235/38332607-b1b2beb4-3856-11e8-82b8-1cc426f9d8e7.png)

**Comment by klinker24** [comment]
You say it is quite easy to reproduce, so in what cases is the notification missing and in what cases does the notification come through? I don't really have enough information to go off of, from this report. Giving me some real steps toward how you reproduce this problem would be helpful.

Does the message show up in the app, when you open the app?

**Comment by klinker24** [comment]
Please comment back when you have more information and I will re-open the issue. Thanks for the report and any help you can provide in the future.
