### ISSUE TITLE
Heads up notification showing old message

### ISSUE THREAD

**Issue by ematzdor** [klinker-apps/messenger-issues#636]
**Device with issue:** OnePlus 3T, Android 8.1
**Primary device:** Same as above
**App version:** 2.9.4.1995
**Steps to reproduce:**

1. Get a message from one person, and don't read it. The pop-down notification occurs and goes away.
2. Get another message from a different sender. This time, the pop-down notification comes up with the previously received notification again. Only when you pull down the shade do you see the message that was actually new.

**Additional information:**

I would think that the stacked message notifications are okay as-is. The only problem is that the message appears to come through twice, and an entirely different message is missed.

**Comment by klinker24** [comment]
I know about this, and don't know why it does this. Thanks for opening an issue.

**Comment by klinker24** [comment]
I spent more time on this, this morning. I think that this will fix the issue for Android 8.1: https://github.com/klinker41/messenger/commit/95fd35d518a3016c1634a129412d0cb9ac3e91e5

It will be released in `2.9.6`.
