### ISSUE TITLE
Chrome notifications show content while it shouldn't

### ISSUE THREAD

**Issue by MrSnowflake** [klinker-apps/messenger-issues#637]
**Device with issue:** "MacBook Pro on MacOS 10.12.6, running Chrome  V65.0.3325.181 (Official Build) (64-bit)"
**Primary device:** Samsung Galaxy S8
**App version:** Android: 2.9.4.1995/Chrome extension: 1.9.4
**Steps to reproduce:**

1. Uncheck "Show notification Content" in the Chrome extension
2. Receive a couple of text messages
3. Notice some of the messages do show their content in the Chrome notification.

**Additional information:**

Sometimes the new message Chrome notification shows the messages content. Although it should not be shown, as the "Show notification Content" setting is unchecked. The content doesn't show up 100% of the time, it's pretty random.

Most strangely, not only does the content show up, sometimes, the content is hidden within the notification within 1 second after originally showing up.

**Possible solution:**

Don't ever pass the messages content to the notification handler when the "Show notification Content" is unchecked.

**Comment by klinker24** [comment]
I assume you are talking about the Chrome extension and not the app?

**Comment by MrSnowflake** [comment]
Yes , you are correct, the Chrome extension (or plugin). I'm sorry, I wasn't aware of a desktop app.

**Comment by klinker24** [comment]
Thanks. I always recommend the actual desktop apps for notifications, but I will take a look at this. I'm not sure how that could be happening.

https://github.com/klinker24/messenger-desktop
https://messenger.klinkerapps.com/overview

**Comment by MrSnowflake** [comment]
It only seems to happen when I'm sending and receiving a bunch of messages. And might happen when I have unread messages in the same thread.

**Comment by klinker24** [comment]
I will still recommend the desktop app over the Chrome app/extension for notifications, but this fixes this issue: https://github.com/klinker41/messenger-chrome/commit/29b07f9534426367d12babc7a288cae51cf2bfa0

I will roll it out next week. If it doesn't, all the more reason to move to the real desktop app to provide you with the notifications.
