### ISSUE TITLE
MacOS Desktop "Show Unread Count on Icon" Javascript Error

### ISSUE THREAD

**Issue by spencer-grimes-mAx** [klinker-apps/messenger-issues#638]
**Device with issue:** MacBook Pro on MacOS 10.11.16
**Primary device:** Pixel 2 on Android 8.1.0
**App version:** 1.2.0 of the desktop app
**Steps to reproduce:**

1. Open Pulse SMS desktop application on my Macbook
2. Navigate to Preferences > Show Unread Count on Icon
3. Uncheck "Show Unread Count on Icon" 

Error message displays: "A JavaScript error occurred in the main process" with the following error test: 

Uncaught Exception:
ReferenceError: unread is not defined
    at click (/Applications/Pulse SMS.app/Contents/Resources/app.asar/resources/js/menu.js:120:29)
    at MenuItem.click (/Applications/Pulse SMS.app/Contents/Resources/electron.asar/browser/api/menu-item.js:52:9)
    at Function.executeCommand (/Applications/Pulse SMS.app/Contents/Resources/electron.asar/browser/api/menu.js:34:15)
<img width="426" alt="screenshot 2018-04-06 10 57 31" src="https://user-images.githubusercontent.com/33701098/38431272-519592ac-3989-11e8-9b99-2c4dc9407815.png">

**Additional information:**
The function of this button appears to be working, when clicked, the selection is unchecked and the notification badges no longer appear in the desktop Icon.

**Comment by klinker24** [comment]
If you could tell me what version of the desktop app you are on, that would probably be helpful. The Android app version isn't going to do much for me, in this case

**Comment by spencer-grimes-mAx** [comment]
Right, forgot to include that. V 1.2.0

**Comment by klinker24** [comment]
Fixed with: https://github.com/klinker24/messenger-desktop/commit/c243ae1a10782cd8af6a6320795005f3285885a0
