### ISSUE TITLE
Add Option to Use The Old (Pre-Oreo) Notification System?

### ISSUE THREAD

**Issue by TwisX** [klinker-apps/messenger-issues#639]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.

**Primary device:** <Samsung Galaxy S8 on Android 8.0.0">
**App version:** <2.9.5.1999>

After updating to Oreo, I noticed that I was no longer getting my custom vibration pattern from Pulse. From the Pulse help section I understand that any apps using the new notification channels feature now require going through Android to change most notification settings. Unfortunately, it appears that custom vibrations are not something that Google thought anyone would want, and we are stuck with the default vibration pattern. However, apps that aren't using notification channels (eg. AquaMail for one) are still able to use custom vibrations on Oreo.

**My feature request is this: If possible, add a configuration option to use the old notification system.**

Custom vibrations were extremely useful since I keep my phone on vibrate 99% of the time. I doubt I'm the only one who would prefer to have custom vibrations and the other notifications settings back instead of these Oreo notification channels that Google wants us to use.

**Comment by klinker24** [comment]
Sorry, that isn't possible. If an app targets Oreo, then it has to use notification channels. If a notification isn't posted with a channel, it isn't shown at all.

Since Pulse targets and uses Oreos features, it has to use channels. There is nothing I can do here, sorry.
