### ISSUE TITLE
Windows 10 app does not start automatically on startup

### ISSUE THREAD

**Issue by Alanator222** [klinker-apps/messenger-issues#640]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [x] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** <HP Notebook running Windows 10 1709>
**Primary device:** <Moto Play Z Droid Android 7.1.1>
**App version:** <2.9.5.1999>

**Comment by klinker24** [comment]
#529
