### ISSUE TITLE
Latest Desktop Client Forced Logout and will not allow login

### ISSUE THREAD

**Issue by myspivey** [klinker-apps/messenger-issues#641]
- [X ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [X ] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** Mac Pro, Macbook Pro
**Primary device:** Mac Pro
**App version:** v2.0.0
**Steps to reproduce:**

1. Get update notification
2. Install update and restart.
3. App becomes logged out and presents login screen.
4. Only presents username login, no Google OAuth. 

`... more steps`

**Additional information:**

I had originally signed up with Google OAuth I believe so have not defined a password so am unable to login now.

**Possible solution:**

Add back Google Auth? Forgot password suggests I use Refresh Account which is listed under "Danger Zone" so I am weary of jumping to that solution if this is being caused by some other root cause or intentional change. Since 2.0.0 was open sourced my only guess was that this was removed from the build. Understand to close this if it is expected and you can give guidance that the Refresh Account is the accepted solution here.

**Comment by klinker24** [comment]
No, you never signed up with Google OAuth. Pulse doesn't use it and never has. You have a unique email and password combination that is used for the encryption. Use the refresh account to reset your password, as discussed on the help page: https://messenger.klinkerapps.com/help

In the future, this tracker is really meant for issues and requests, this isn't really meant as a support page. You can direct questions like this, to my email: luke@klinkerapps.com
