### ISSUE TITLE
Linux Mint Cinnamon - Pulse SMS 2.0 Screen Cut Off On Bottom

### ISSUE THREAD

**Issue by kcken** [klinker-apps/messenger-issues#642]
**Device with issue:**
Dell E4310 - Linux
RELEASE=18.3
CODENAME=sylvia
EDITION="Cinnamon 64-bit"
DESCRIPTION="Linux Mint 18.3 Sylvia"
DESKTOP=Gnome
TOOLKIT=GTK

**App version:**
pulse-sms-2.0.0-amd64.deb

**Steps to reproduce:**
1. Launch Pulse
2. Compose Message
3. Notice white bar at top, and bottom cut-off.

![screenshot from 2018-04-10 09-27-28-masked](https://user-images.githubusercontent.com/14079407/38560070-c9e60dc4-3ca2-11e8-8614-4b10c97adf6e.png)

**Possible solution:**

Looks like some sort of canvas offset - white bar on top is not used, but bottom is cut off, so it is like the canvas is being painted at the wrong offset from the top.

**Comment by klinker24** [comment]
Looks like the space for the menu bar. Have you hidden the menu bar with the auto hide menu bar option?

**Comment by kcken** [comment]
Interesting - so perhaps another bug... there IS a menu bar there, but you
can't see it - it is all white, but mousing over it exposes that there are
menu items there.   If you mouse over the right hidden menu item, you can
indeed select auto-hide menu bar - and when that is done, the screen is no
longer shifted down.  The option key shows/hides the menu bar, but there is
no text on it.

So, looks like a couple bugs:  Menubar items are hidden and shouldn't be,
and when menubar is shown, display is cut off at bottom.

Ken

**Comment by klinker24** [comment]
I don't know why that would be. Thanks for the report.

**Comment by kcken** [comment]
appears the menu bar is implemented differently than all the other apps.
Other apps the menu bar always shows, and <option> highlights the hot-keys
for the menu items.  The menu bar is also the same color as the border.  In
the SMS app, the menu bar is pure white, and the <option> key shows/hides
the bar.  Perhaps it is a compatibility issue with the UI toolkit you used
for the SMS app as this one does behave differently than all my other apps.

**Comment by klinker24** [comment]
I use Electron: https://github.com/klinker24/messenger-desktop

**Comment by kcken** [comment]
I pulled the latest version of electron, and it renders the hello-world app
fine - looks 100% like native with gray menu bar and menu bar items.


I tried using this version of electron with pulse app directly.  I have to
run it by copying the new electron over pulse-sms dir, then pulse-sms app
won't run, it gets an error (pulse-sms: undefined symbol:
udata_setCommonData_59), but if I run electron directly, it renders the
pulse-sms app... AND... the menu bar renders correctly (not white out):


But, when the menu bar is displayed, we still get the bottom cut-off:


​
I notice hello-world app doesn't allow hiding of the menu bar, so not sure
where that functionality is coming from.​

Maybe I'll take a look at the source if I get a chance, but right now a
little busy on other things... Hopefully this information helps.

Thanks!  Great product - can't wait for auto-response-when-driving...
pretty much everything else works great.

Ken




​

**Comment by jdbeitz** [comment]
Same issue here!!

**Comment by Tjzabel** [comment]
I have the same issue here. Using Fedora 28 with the desktop app. Auto hide fixes the issue of the cut off on the bottom.

**Comment by klinker24** [comment]
Is this still an issue? What i would like to know is:

1. **By default, when you first install the app**, does it show the display as cut off? It shouldn't. That shouldn't happen until you tap the "Auto hide menu bar" option. When that option is turned on, the display will likely be cut off until you use "alt" to hide it. This is the way it is going to have to work, there won't be a way to prevent that cut off, if it is working as i have described here. 
2. Has the menu item visibility been resolved? There have been a number of new Electron updates that have been pulled into Pulse, since this issue was introduced. I haven't changed anything on my end and I am just using the default electron configuration. So, I have to believe the fix is on their end.

**Comment by klinker24** [comment]
I am going to go ahead and close this, for no response. If anyone comes across it and can address my questions, that would be great.
