### ISSUE TITLE
Potential null crash with attachments

### ISSUE THREAD

**Issue by AllanWang** [klinker-apps/messenger-issues#643]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [ ] If this is an issue, and not a request, I have verified that this is something that is reproducible

Not identifiably reproducible

**Device with issue:** OnePlus 3 on Android 8.0.0
**App version:** 2.9.5.1999
**Steps to reproduce:**

I was writing a long message, and pulse just force closed twice half way. Unfortunately, this does not seem to be a fully reproducible error, but I have attached below a screenshot of the log output that may be from your application. If this is unrelated, feel free to close this issue. If this is related, note that I have only typed a message, and have not added any attachments during the process.

**Possible solution:**

Do you have an idea of how to solve it? If not, that's fine. You can delete this section.

Ensure attachment cache is not null, especially if this is related to RxJava mappings.

**Comment by AllanWang** [comment]
![](https://i.imgur.com/ik8dlBb.jpg)

**Comment by klinker24** [comment]
That doesn't seem to have anything to do with Pulse, no. I don't have any attachment cache, which seems to be what is getting thrown here. I do get all the force closes logged to Firebase, and regularly fix them, but I don't really want to keep an issue open for a random force close, without a Pulse stack trace

Pulse is sitting at a 99.7% crash free rate, which is well under the expectations or "bad-behaviour" threshold that Google has set. I will continue to fix force closes, as they come up, in the app.
