### ISSUE TITLE
menu keyboard shortcuts don't work in Windows

### ISSUE THREAD

**Issue by a-singer** [klinker-apps/messenger-issues#645]
### Keyboard keys to access the menu bar don't work

**Device with issue:** Windows 7 Pro SP1 
**Primary device:** Moto G 5 running Android 7.0
**App version:** latest update, unable to access version number due to issue
**Steps to reproduce:**

1. Open the Pulse SMS app.
2. Press alt+h for help, alt+p for preferences, or just alt to try to get to the menu bar. Nothing happens.

**Additional information:**

I don't know if this is a feature request or something that is supposed to work but doesn't, but for those of us who don't use a mouse, it is very helpful to have access to the menu bar according to the usual conventions.

**Comment by klinker24** [comment]
The issue here is that `alt` is used to hide and show the menu bar. This was requested earlier and is the functionality that I will be sticking with. Why can you not just use the mouse to just access it?

#466
