### ISSUE TITLE
Pulse no longer loads properly on desktop version

### ISSUE THREAD

**Issue by Alanator222** [klinker-apps/messenger-issues#646]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [x] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** <Hp Notebook running Windows 10 1709>
**Device App Version** <2.0.0>
**Primary device:** <Moto Z Play Droid Android 7.1.1>
**App version:** <2.9.6.2004>

Several fresh installs have yielded the same result. When I open the program, the program appears as is in the provided screenshot.

![screenshot 67](https://user-images.githubusercontent.com/33383477/38651599-2b5a5bea-3dd0-11e8-95f5-ee2f3b49f765.png)

**Comment by klinker24** [comment]
Why can't you just type in your email and password there?

If you look at the JavaScript console, it would tell you about any errors.

**Comment by Alanator222** [comment]
I'm not using the Chrome version. I'm trying to use the native desktop application.

**Comment by klinker24** [comment]
The desktop version has a JavaScript console, you don't need Chrome or the Chrome app... In the view menu tab, I believe.

**Comment by Alanator222** [comment]
I don't have a view menu tab. If you look at the screenshot, I don't have the top ribbon for some reason.

**Comment by klinker24** [comment]
Tap the alt button if you have hidden it. https://messenger.klinkerapps.com/help

**Comment by Alanator222** [comment]
![screenshot 68](https://user-images.githubusercontent.com/33383477/38652411-d39483aa-3dd3-11e8-99d8-35e526df5b95.png)

Whole lot of errors. 
Sorry, I'm new to all this stuff. Just started taking CS classes, etc.

**Comment by klinker24** [comment]
Looks to me that the app isn't able to access the internet or something. Uninstalling and reinstalling the app isn't going to change anything or invalidate the data for the app. Looks like this will

https://stackoverflow.com/a/44675132

**Comment by Alanator222** [comment]
Did another complete uninstall, but this time I deleted all files under %appdata%. Seems to have fixed everything. Thanks!

**Comment by klinker24** [comment]
Great. The switch to v2 definitely has changes that could affect current installs. I hadn't heard of any issues like that, but will redirect users here, if needed.
