### ISSUE TITLE
Typing on keyboard sometimes does not enter text into compose box

### ISSUE THREAD

**Issue by Skullmonkey** [klinker-apps/messenger-issues#650]
**Device with issue:** Pixel XL Oreo 8.1
**Primary device:** Pixel XL Oreo 8.1
**App version:** 2.9.6.2004
**Steps to reproduce:**

Inconsistent but I notice it when unlocking my phone directly into a conversation. Seems to be random.

**Additional information:**

Sometimes when unlocking my phone directly into a conversation, my keyboard (SwiftKey) pops up like normal and I start typing to find out that none of what I have typed has made it into the message. I typen my message once and hit send to see if the text was just not showing up in the compose box but nothing happened. Simply closing the keyboard by hitting the back button does not fix the problem. I have not tried going back to the conversation list and reentering the conversation again but closing the program completely (from the task manager) and reopening it does fix it. I can not recollect this happening before #594 but has happened once or twice a week since around that time of that version of the app coming out (which in my usage of the app is a really low percentage of it happening). 

If this is a 'just me' case, I can live with it.

**Comment by klinker24** [comment]
I can't say I have heard of it. If you can give me steps to reproduce it, instead of it being random, I can take a look.

**Comment by klinker24** [comment]
I think I am going to close this one, sorry. I have been playing around yesterday and today and I am just not seeing anything happen there. If you have more info about this, let me know and I can re-open it.
