### ISSUE TITLE
Sent message sound option

### ISSUE THREAD

**Issue by hombrefrito** [klinker-apps/messenger-issues#652]
Hello,

Would it be possible to add an option to change the sent message sound to our own choosing?  The default "message_ping.mp3" within the Sound Effects settings is a bit lacking.

I would also like to add that your program is the only one that fixed our family's messaging problems on T-Mobile.  Thanks much for your skills and time.

**Comment by klinker24** [comment]
I will consider adding an option for this, in the future, but admittedly, I don't know if this is something that will come, or not. 

With Pulse, I don't want the user to be able to tweak every little detail of the app, I want to provide the baseline customizations, then focus on the features. I know there are plenty of apps out there that let you tweak every little aspect of it, but that doesn't always amount to a great experience. It is confusing and overwhelming for many users.

I know that one more setting doesn't amount to much, but if I do some "tweak" options and not others, where do I draw the line? For the settings in the app, I really want them to provide value to a large number of users, not just a handful of users - especially if they are a confusing setting or something that others won't understand.

**Comment by hombrefrito** [comment]
No worries.  I appreciate you taking the time to write back.  Thanks again for a great app!

**Comment by klinker24** [comment]
I think that I am going to close this one, sorry. I don't see this option coming to Pulse. With Oreo, I may be able to work it in to a notification channel, but as a standalone setting, this isn't going to be something I expose.
