### ISSUE TITLE
Call button does call the number of the conversation.

### ISSUE THREAD

**Issue by Skullmonkey** [klinker-apps/messenger-issues#653]
**Device with issue:** Pixel XL 8.1 Oreo
**Primary device:** Pixel XL 8.1 Oreo
**App version:** 2.12.0.2026
**Steps to reproduce:**
1. Open a conversation
2. Press on call button on the top of the conversation 
3. Pulse dials one of the numbers (I assume the last number added) in the users contact profile.
Same thing applies for the notification call button

**Additional information:**
Both my girlfriend and I use the 'call' feature that is supplied on the top of our conversation. I believe since that last update, when we hit the call button, it goes to each others work lines instead of to our personal phones when in the past it used to automatically call the number of the conversation that we were in. I went in to my contact for her and set her mobile number as the default and restarted Pulse and my phone and the 'call' button still calls her work phone.

We do have conversations for both personal and work phones. Both conversations call each others work phones instead of whatever conversation we are in. 

**Possible solution:**
Make it so that the call button calles the number of the conversation. (If that makes sense)

**Comment by klinker24** [comment]
I had changed this. Maybe I will change it back. Thanks.

**Comment by Skullmonkey** [comment]
Just out of plain curiosity, what was the reason for changing this behavior?

**Comment by klinker24** [comment]
Sometimes the country code is omitted on the conversation's phone number when it exists within your Contacts app. Different carriers treat incoming phone numbers differently.

**Comment by Skullmonkey** [comment]
Just wanted to thank you for pushing an update to revert it back to the conversation number.
