### ISSUE TITLE
Receiving some texts in stock app

### ISSUE THREAD

**Issue by Shift12H** [klinker-apps/messenger-issues#654]
**Device with issue ** Samsung s7 running Android 7
**App version:** 2.10.2.2029
**Steps to reproduce:**

1. Receive a call from any number. 
2. Receive notification from stock app "messages" that voicemail was received. This also occurs for voice to text service which is received via stock app instead of pulse. PULSE does not receive the voicemail or 'voice-to-text' message. 
3. Sometimes when I open the stock app, random contacts that I have messaged receive "read report for message from..." from me multiple times. 

**Additional information:**

This issue only started occurring around 6-8 months ago. This did not occur before but started happening all of a sudden. I have tried clearing storage memory for stock app and reinstalling pulse. Sometimes for a the first voicemail I receive, it goes through pulse but then reverts back to old behaviour of going to stock up ONLY.

**Comment by klinker24** [comment]
I'm not going to be able to control what shows up in your stock app vs Pulse. As a third party SMS app, Android notifies me when a message comes in and I save it. I don't have any connections to your carrier and cannot integrate with any type of voicemail functionality. 

My help page discusses why some things would appear in the stock app and not Pulse. They are not SMS.

https://messenger.klinkerapps.com/help
