### ISSUE TITLE
Windows desktop app gives error on startup on Windows 10 v1709

### ISSUE THREAD

**Issue by jdrch** [klinker-apps/messenger-issues#656]
- [X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [X] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** Any Windows 10 v1709 device
**Primary device:** Dell XPS 8500 SE running the above
**App version:** 2.1.0
**Steps to reproduce:**

1. Install app
2. Attempt to launch app

Windows will throw an error saying:

> The application was unable to start correctly (0xc000007b). Click OK to close the application

![image](https://user-images.githubusercontent.com/1056759/39224396-ca840e14-480c-11e8-9199-14e82eb1ea63.png)

Of note, my PC running Windows 10 Insider Build Slow Ring doesn't have the same issue.

**Comment by klinker24** [comment]
I'm not going to be able to get any info from an error message like that, unfortunately. The app is open source, any way you can build it and get to the real stack trace for the error?

https://github.com/klinker24/messenger-desktop

**Comment by jdrch** [comment]
I'd be happy to try, but I don't see any Windows build instructions.

**Comment by klinker24** [comment]
https://github.com/klinker24/messenger-desktop/blob/master/SETUP_NOTES.md#preparing-windows-for-electron-development

**Comment by jdrch** [comment]
Ah, thanks. Might be a couple weeks before I'm able to get around to it, but I'll do my best.

**Comment by jdrch** [comment]
I decided to wait for the 1803 update to see if that fixed the problem. This is the error message I'm getting now:

![image](https://user-images.githubusercontent.com/1056759/39677613-bd7bd572-5143-11e8-8725-1ecd1735ec77.png)

Does that help any?

**Comment by klinker24** [comment]
I doubt that is the same. You can restart the computer to fix that, it looks like a permission error.

**Comment by jdrch** [comment]
Update: Trying to launch again worked :) Problem solved!
