### ISSUE TITLE
Widows Desktop Notifications Not Working. 

### ISSUE THREAD

**Issue by supersonicguru** [klinker-apps/messenger-issues#657]
- [ ] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** Widows desktop verstion
**Primary device:** N/A for phone, android if OS is needed
**App version:** V2.1.0 for desktop
**Steps to reproduce:**
everything works fine, just no notifications 

**Additional information:**

i still have to "activate windows" if that's a problems

**Possible solution:**
No clue, I can try to reinstall it? notifications on phone, but not on my pc

**Comment by klinker24** [comment]
The desktop app is open source, so you can build it and it will provide any debug output, or you could add some logging statements to see where it is getting held up. That would tell us where the issue is.

https://github.com/klinker24/messenger-desktop

**Comment by supersonicguru** [comment]
any guide on the widows way to get it to "debug an output"? I have some coding history so I can probably do something to help show whats wrong.

**Comment by klinker24** [comment]
There are notes in the repo about building and running the app. You can use `console.log("some text")` to output to log output to the console, it is just a javascript app. You will need to look through the `websocket.js` file to find where it is getting stuck.

https://github.com/klinker24/messenger-desktop/blob/master/SETUP_NOTES.md#preparing-windows-for-electron-development

**Comment by klinker24** [comment]
Sorry, without any movement, I don't have anything that I can take action on here. If you want to continue investigating, feel free to let me know the results and I can re-open if necessary
