### ISSUE TITLE
[Request] Android Auto support

### ISSUE THREAD

**Issue by Scorcher7986** [klinker-apps/messenger-issues#659]
**Feature Request:**
Android Auto support to fix duplicate notification issues on Android Auto

**Additional information:**
More information and a current workaround comes from an [Android Auto team member post](https://productforums.google.com/forum/#!topic/android-auto/7yo_XZH72k8):
> Some default SMS apps may not have Android Auto support, so Android Auto listens to SMS broadcasts on the phone as well as notifications from supported apps to display your messages.  Since Signal posts notifications for SMS messages, you can stop the double notifications by switching off the SMS permission for Android Auto.

However proper integration/support would be appreciated.

**Comment by klinker24** [comment]
Android Auto is already fully supported and was accepted by the Android auto team. This is why you are able to respond to notifications. Changes around the duplicate notifications issue cannot come on my side. Auto has to accept Pulse as the SMS app, a change that needs to come on their end.

See my help page: https://messenger.klinkerapps.com/help
