### ISSUE TITLE
Support changing font size

### ISSUE THREAD

**Issue by klinker41** [klinker-apps/messenger-issues#66]
**Device with issue:** Nexus 6P running Android 7.0
**Primary device:** Nexus 6P running Android 7.0
**App version:** 1.1.268

**Information:**

We should allow users to be able to change the font size used in the app. In other apps, we've allowed them to choose the actual size in `sp`, but I don't think that is necessary. Instead, it would be better to have a `ListPreference` with 4 different items on it, `small`, `normal`, `large`, and `extra large` with the default being `normal`.

We would need to change the following font sizes based on this setting:

1. Conversation list labels (ie "pinned", "today", "yesterday", etc.)
2. Conversation list item name
3. Conversation list item summary
4. Message list item body
5. Message list item date
6. Message list text entry area

**Implementation Idea:**

I think that it would be best to store a few different font sizes in the `Setting` object and change those according to whether the user choose small, normal, large or extra large.

Right now, those 6 text areas are one of three sizes: `12sp`, `14sp` or `16sp`. So, I think that it would be best to save 3 different font sizes in the `Settings` and modify them according to what size the user chooses. For example:

```java
private int smallFont;
private int mediumFont;
private int largeFont;

...

String fontSize = sharedPrefs.getString("font_size", "normal");
if (fontSize.equals("small")) {
    this.smallFont = 10;
    this.mediumFont = 12;
    this.largeFont = 14;
} else if (fontSize.equals("normal")) {
    this.smallFont = 12;
    this.mediumFont = 14;
    this.largeFont = 16;
} else if (fontSize.equals("large")) {
    this.smallFont = 14;
    this.mediumFont = 16;
    this.largeFont = 18;
} else if (fontSize.equals("extra_large")) {
    this.smallFont = 16;
    this.mediumFont = 18;
    this.largeFont = 20;
}
```

and then change the font sizes in code where needed.

**Comment by klinker24** [comment]
Finished with these 3 commits

Add setting: https://github.com/klinker41/messenger/commit/ab532e66e504eb32f69ea63cbf6d74ac378a1137
Apply setting to conversation list: https://github.com/klinker41/messenger/commit/303fc483d234fb734feccfcb9fcd7e0b42363aea
Apply setting to message list: https://github.com/klinker41/messenger/commit/e1339bc26439670fff9d209bd3ccf7586e2dde9d
