### ISSUE TITLE
Private conversation leaks senders phone number in notifications

### ISSUE THREAD

**Issue by MrSnowflake** [klinker-apps/messenger-issues#661]
**Device with issue:** ANDROID
**Primary device:** Galaxy S8
**App version:** 2.11.0.2045
**Steps to reproduce:**

1. Receive an sms in a private conversations thread. 
2. In the notification tap 'Call'
3. The senders phone number appears in the phone app.

**Additional information:**

This leaks the senders details. The phone number of the sender is visible, while content of the message it self is still hidden.

**Possible solution:**

Don't allow direct calls from notifications of a private conversation thread.

**Comment by klinker24** [comment]
I already fixed this for the next version.

**Comment by MrSnowflake** [comment]
That's fast, thanks :)
