### ISSUE TITLE
Driving mode quick tile

### ISSUE THREAD

**Issue by uudruid74** [klinker-apps/messenger-issues#663]
**Device with issue:**  OnePlus 3T/Oreo
**Primary device:** same
**App version:** 2.11.1.2063
**Steps to reproduce:** Toggle quick setting tile
The quick setting tile and the switch for driving mode aren't in sync, so its hard to tell when it's on.  Twice now its been on unintentionally

**Comment by klinker24** [comment]
So does this happen every time you use the quick tile, just sometimes, is it always getting out of sync when you go from on -> off, or visa-versa? More information will be necessary. I haven't seen any issues with this functionality myself.

**Comment by uudruid74** [comment]
Never.  Not once.  I'm rooted, so if you think there is info in a logcat or something, I can do that.

**Comment by klinker24** [comment]
Try this version and let me know if it works

[messenger-2.11.1.2068-release.apk.zip](https://github.com/klinker-apps/messenger-issues/files/1970943/messenger-2.11.1.2068-release.apk.zip)

**Comment by uudruid74** [comment]
That person is working
