### ISSUE TITLE
Swipe action customization

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#665]
**Request:**

Right now, I allow the user to turn on `Swipe-to-delete`. 

* If that is on, swiping from the right side of the screen will delete the conversation, while swiping from the left side will archive it.
* If that is off, swiping from either side will archive the conversation.

I want to allow the user to define this on their own. They should be able to choose a "swipe from left" action and a "swipe from right" action from settings. They should be able to select from the following choices:

* Archive
* Delete
* Off

I get requests pretty frequently to turn off the swipe functionality completely, so this provides that.

**Additional information:**

Note that the available actions are still destructive actions. I do not currently plan to add "call" or "mark as unread" or anything like that, to this functionality. Swiping is meant to dismiss the swiped item, not perform an action against it.

**Possible solution:**

I just want to delete the "Swipe to delete" switch preference and replace it with a custom preference that allows for customizing these two actions.

**Comment by klinker24** [comment]
Set up an improved system to manage the swipes and the actions they perform: https://github.com/klinker41/messenger/commit/c119cd621ba9066123e7862345f8fb5ebeac7d5f
Allow for no-op, which removes the swipe on that direction: https://github.com/klinker41/messenger/commit/4a77e11c29c36f25ee429fea6312e7a33ff03ba8

Todo: 
* [ ] Create settings page around this
* [ ] Migrate current users who have turned on swipe to delete
* [ ] create feature flag

**Comment by jwulf1092** [comment]
I personally disagree with the thought that "Swiping is meant to dismiss the swiped item, not perform an action against it".
I come from the Samsung Galaxy line, where swiping right on a contact or conversation in any of the stock apps generates a call, and swiping left generates a message to that person.
I REALLY like that feature and want to request it, so I came to your roadmap to search for it, and here I am.
I hope you will reconsider your position and think about adding that feature for the users who DO want a swipe to call option.
JW

**Comment by GitHubJack1182** [comment]
Re: Swipe to call
I also hope you will reconsider this. I sometimes read a message and feel that a call is best to immediately clarify a situation. Swipe to call is nice to have (note: I migrated to Pulse only because Samsung's stock messaging got rid of the delay-send feature. If not, I would still be using it).

**Comment by klinker24** [comment]
Sorry, swipe to call is not planned. Swipe actions should be destructive, you are swiping that conversation off of the screen, getting rid of it. That is why I use delete and archive. Both are destructive actions, removing the conversation from the current list. A call button just doesn't make sense for the swipe gesture. I am really not into the whole idea of "just because xxx did it, everything should".... I really want to consider the UX of the app, rather than throwing in everything that other apps have chosen to do.

You can just open the conversation and hit the call button though. It is two taps vs one swipe. I don't see that as a productivity loss, and it is much more difficult to accidentally tap, than swipe.

**Comment by ccinkk** [comment]
What about swipe to mark as read? I don't understand what you mean that you want the swipe action to be destructive, but with marking it as read you are dismissing it from being in a state that draws your attention. I can click the conversation and click back but I don't want to have to open the conversation at all. (But I still want it in the conversation list.)

**Comment by klinker24** [comment]
When you are swiping something, the gesture is removing it from the screen. It is considered destructive, because you are removing it from the list. Marking something as read is not removing it from the list, it is changing how it is displayed.

> Swipe actions should be destructive, you are swiping that conversation off of the screen, getting rid of it.

Pulse is only going to use destructive actions, for its swipes.
