### ISSUE TITLE
Snackbar hides input field

### ISSUE THREAD

**Issue by AllanWang** [klinker-apps/messenger-issues#666]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [x] If this is an issue, and not a request, I have verified that this is something that is reproducible

**App version:** 2.11.0.2045

If you click "mark all as read", the snackbar seems to stay while the task is running. However, we can't close it, and it blocks the input field when composing a new message.

**Possible solution:**

* Move input field up when snackbar is showing (like how fab moves up in coordinator layouts)
* Allow option to hide the bar, which won't cancel the task
* Hide the bar when composing a message (and show it again in the conversation list if the task is still running)

**Comment by klinker24** [comment]
The snack bar shows up when the action is done. It isn't going to take more than a quarter second to mark everything as read. You can just swipe to dismiss any snackbars in Android, as well.

**Comment by AllanWang** [comment]
Hm. Marking last month as read took me more than 2 seconds so something might be up there, but I wasn't aware of swiping to dismiss snackbars.
