### ISSUE TITLE
Support changing all conversations to the same color

### ISSUE THREAD

**Issue by klinker41** [klinker-apps/messenger-issues#67]
**Device with issue:** Nexus 6P running Android 7.0
**Primary device:** Nexus 6P running Android 7.0
**App version:** 1.1.268

**Information:**

Some users have requested that the same color be used between all conversations. This should not be the default, but would be a simple enough customization to add to the app.

Users should be able to go into settings and see a preference for "Theme Color". This will be a list preference that lists all of the options and allows them to choose one. The list will look like the following

```
Set per conversation
Red
Pink
Purple
Deep Purple
...
Brown
Grey
Blue Grey
```

where "Set per conversation" is the default value and what we have currently implemented (teal in the settings and conversation list, different colors for each conversation that are configurable).

If a different color is picked, this should override both the conversation list, empty pages, settings pages and each individual conversation. However, we don't want to write the new values to the database for each conversation, because if we do this then there's no good way to switch them back to their actual colors if the user returns to the "Set per conversation" option. So, we should store the values in the `Settings`:

```java
private int themeColor;
private int themeColorDark;
private int themeColorLight;
private int themeColorAccent;
```

These theme colors can be filled through the `ColorSet` class.

**Comment by klinker24** [comment]
Done with these 3 commits

Add settings functionality: https://github.com/klinker41/messenger/commit/abf6e848ef73da7d2bd729b2b3bd8edae3e00769
Apply to message and conversation list: https://github.com/klinker41/messenger/commit/6561e8fb14646015995da702150f91af12b38187
Apply to settings pages: https://github.com/klinker41/messenger/commit/cf37cc86a25d142542c7158f4e607218a31219b6
Apply to compose screen: https://github.com/klinker41/messenger/commit/d3741a22c3fcc2497f8e5898f683d8a2cd2b3b53
Take night mode into account: https://github.com/klinker41/messenger/commit/656af068027d9b2e362b9d3c9a45693497a67e45
