### ISSUE TITLE
Widget color issues

### ISSUE THREAD

**Issue by k10ck3r** [klinker-apps/messenger-issues#670]
**Device with issue:** Samsung Galaxy Note 4
**Primary device:** Samsung Galaxy Note 4
**App version:** 2.11.1.2072
**Steps to reproduce:**

Set up widget on phone
Verify text messages are shown
Wait a period of time (exact length isn't known)
The widget will clear out the text messages and show nothing
Send a new text to the phone - it will be shown
Respond to text and the widget clears out the messages again

**Additional information:**

The widget used to always show the most recent text messages.  The widget started clearing out the displayed text messages after the recent widget update to automatically match the base theme.  I have checked several updates since that time, but the behavior persists.  I also looked to see if there was perhaps a widget/ui option to enable the hiding of text messages, but didn't find anything.

**Possible solution:**

If this is a new feature and not a bug, could you please add a setting to disable this - I find it annoying.

Thanks.

**Comment by klinker24** [comment]
I have never seen this happen, or heard of it from anyone else. That doesn't seem like a very good feature though, so it is probably safe to call it a bug. You won't find any preference to disable this behavior.

Could be the launcher you are using, you could try a different one.

**Comment by k10ck3r** [comment]
I am using Nova launcher and haven't had any issues until recently.  I will remove/reinstall to see if that helps and let you know.

**Comment by k10ck3r** [comment]
I have tracked down the specific case that causes text messages not to be shown in the widget, so I am reopening this issue.  

The theme needs to be set to default (day/night) and it needs to be night-time.  At night, with this theme selected, the app uses a white font on a dark background, but the widget keeps the white background.  My guess is that the widget is inheriting the white font from the main app at night, but since it uses a white background, the text msgs seems to "disappear".  

I am able to switch between "Always Light" and "Default(Day/Night)" and see the messages appear and disappear  - provided I test at night-time.

**Comment by klinker24** [comment]
Thanks, can you post a screenshot with it? So it seems like the widget is showing the messages then, the color is just off.

**Comment by k10ck3r** [comment]
Here you go:

**Comment by klinker24** [comment]
Looks like it didn't attach. You won't be able to attach images, from an email response on GitHub.

**Comment by k10ck3r** [comment]
![screenshot_2018-05-16-20-28-12](https://user-images.githubusercontent.com/39198216/40153743-7435813a-5948-11e8-9dfd-4d3b3c639bbc.jpg)

**Comment by klinker24** [comment]
This is fixed. 

https://github.com/klinker41/messenger/commit/6f36f90801d398a7d0eac0ef414ad278d226bbfd
