### ISSUE TITLE
Download data as a backup

### ISSUE THREAD

**Issue by Skullmonkey** [klinker-apps/messenger-issues#671]
**Primary device:** Pixel XL/Windows App

**Feature Request**
As kind of an addon to #655, I would like to request us to be able to download a digital backup of our data to our computer/non cell device. 

Just a few thoughts:
-XML format
-All or specific conversations
-Ability to download MMS (media, long texts, etc)
-Premium feature only? (Makes sense because the cloud service is premium only)
-Web download only?
-Encrypt using password used to log in

**Comment by klinker24** [comment]
I don't see that happening, sorry. The point of Pulse is to keep everything on your account and have it fully transparent. I don't want to have to manage multiple versions of a backup and there is really no need for that when everything is automated already.

You could write a tool for this, yourself, if that is really something you want, but there won't be an official one. You can always download a backup and restore app off of Google play that will run off of your phones database.
