### ISSUE TITLE
Contact color changes in group messages

### ISSUE THREAD

**Issue by jdkula** [klinker-apps/messenger-issues#674]
**Device with issue:** Galaxy Note 8 on Verizon with Android 8.0.0
**Primary device:** (same as above) 
**App version:** 2.11.3.2097
**Steps to reproduce:**

1. Open a group conversation
2. Certain messages change color despite coming from the same number. 

**Additional information:**

Sometimes, it's possible to scroll up and see the color change, then scroll back down and see that changed color on previous messages. It's really weird. It seems to happen with weird contact names, maybe with symbols - I noticed it with a contact that has a name suffix (which renders in Contacts as a comma, and as a space in Pulse), and with just a phone number. The color also changed each time I opened the conversation. 

![screenshot_20180515-021622_pulse](https://user-images.githubusercontent.com/4166625/40048769-e595c4d2-57e7-11e8-867c-e04460f72a4a.jpg)

Note that the first message always stays the same color. (also, this first color does not match the contact color in a one-on-one text -- not sure if this is intended)

This behavior doesn't seem to happen in the web app (although the group/one-on-one disparity is still there -- again, not sure if this is intended)

**Possible solution:**

My best guess would be a missed edge case with contact names containing symbols or obscure name fields.

**Comment by klinker24** [comment]
Thanks. I have seen this before as well, but have been unable to figure out what causes it on some conversations and not others. I will continue to investigate.

**Comment by ppoutine** [comment]
To add to this: I'm having this issue too with certain contacts in a group convo. Their names don't have special characters or anything I can figure out that distinguishes them from the one contact that consistently keeps his color. On the Android app, these other contacts are consistently switching colors.

This bleeds over to the web app a bit too. The one contact that works properly on Android keeps that color correctly on the web app. However for the other, color-switching contacts, on the web app they all appear the same color (the color of the group chat).

**Comment by GITjaks** [comment]
Not sure if this is related or a feature request, but here ya go.

Group Conversation, i can't change the colors per contact without changing the entire app theme. 

One came in bright fuschia that's hard to read and the other gray (chosen accent color) 

If I set the app theme to override conversation settings then both the contacts are the same color. 

Samsung s7 Edge
Android 7.0
Pulse app version 3.1.1.2131

I can move to a feature request if not related.

**Comment by klinker24** [comment]
Just start an individual conversation with that contact and change the color. You don't have to send any messages to the contact to create a conversation and change the color. That doesn't have to do with this, but it isn't a feature request, you can already change the colors to whatever you want.

**Comment by GITjaks** [comment]
Luke,

1) amazingly fast response and I love your app.
2) welp. Silver lining, I have a personal github account now which I'd been
meaning to do
3) it worked.

**Comment by klinker24** [comment]
I have made some changes around this on the Android app. They will be released with `v3.1.3`. If you see issues right off the bat, try going to "my account" -> "resync contacts" to see if that has any affect.

https://github.com/klinker41/messenger/commit/7e933a07d00a60bd10091884aaf4b5e9d1eb4d23
