### ISSUE TITLE
'null' value in Add To Contacts dialog

### ISSUE THREAD

**Issue by JoshuaGarrison27** [klinker-apps/messenger-issues#676]
- [x ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [x ] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** Pixel 2 XL - Stock 8.1.0 - Build: OPM2.171019.029.B1
**Primary device:** Pixel 2 XL
**App version:** 2.11.3.2097
**Steps to reproduce:**

1. Go into a conversation with an unknown contact.
2. Tap the number at the top OR hit the menu dots and click view contact
3. Popup shows 'Add "null" to contacts?'

**Additional information:**

![screenshot_20180517-105558](https://user-images.githubusercontent.com/1706923/40185982-ff22146a-59c1-11e8-9ba4-6d8e0e7ce680.png)

**Comment by klinker24** [comment]
Can confirm I see this on my Pixel, as well. It seems to me that this is an issue with the contacts app, and not Pulse though. I create the intent: 

```kotlin
val tel = "tel:${conversation.phoneNumbers}"
intent = Intent(ContactsContract.Intents.SHOW_OR_CREATE_CONTACT)
intent.data = Uri.parse(tel)
```

I went ahead and added a log for the uri:

```kotlin
Log.v("pulse_contact", tel)
```

and it outputted the expected uri: `tel:40404`.

It definitely seems as though I am passing everything through correctly, and this hasn't changed for a very long time. I also definitely remember this working correctly, in the past.

I can also confirm that it is working fine on a Samsung phone that I use to test.

Devices:

* Pixel 2 (with Google's contacts app): shows `null`
* Essential Phone (with Google's contacts app): shows `null`
* Samsung Phone (with Samsung's contacts app): shows the correct number.

**Comment by JoshuaGarrison27** [comment]
Ah! Interesting! I appreciate all the details in your response. I remember this working before as well. 

According to the Google Play Store (on my phone), the Contacts app was last updated on May 4th, 2018 to version 2.7.2.195464261.

**Comment by klinker24** [comment]
There are numerous ways to insert contacts, I can just switch to a different one.

```kotlin
val intent = Intent(Intent.ACTION_INSERT)
intent.type = ContactsContract.Contacts.CONTENT_TYPE
intent.putExtra(ContactsContract.Intents.Insert.PHONE, phoneNumber)
```
