### ISSUE TITLE
The web app is not great, and the desktop client is even worse

### ISSUE THREAD

**Issue by snaptopixel** [klinker-apps/messenger-issues#677]
As a registered user (and front-end engineer), I'd like to help if at all possible. It seems like a pretty simple web app, but the performance and ux just aren't very good. Is there any way I can contribute?

**Comment by klinker24** [comment]
The desktop app is open source. https://github.com/klinker24/messenger-desktop

In the future, I am hopeful that I can open source the web app, as well. At that time, I will be more than willing to accept contributions.

Feel free to email me with any more questions around this: luke@klinkerapps.com

**Comment by snaptopixel** [comment]
Thanks @klinker24 desktop app is merely a wrapper around the web app, correct? I'll take a look at the third party app. Thanks!
