### ISSUE TITLE
Include Time in Saved Image Name

### ISSUE THREAD

**Issue by fastoy** [klinker-apps/messenger-issues#678]
I would like to have the file names of the images saved from MMSs include the date and time, preferably the date and time taken.

For example: IMG 2018-04-16 12.53.23.jpg

**Comment by klinker24** [comment]
The number at the end of it is already the unix timestamp. Will consider using a more readable version. I haven't because which time do you use: the time you receive it or the time that it is saved. I could make a case for either.

**Comment by klinker24** [comment]
Sometimes more preferences like that really aren't the best solution. There are times when I would rather jut make the choice and stick to it. I want to avoid filling my settings menu with little "tweak" options that only a handful of people will use. For most, they detract and distract from the experience

It is added with this: https://github.com/klinker41/messenger/commit/1d75ec0354eb88d84746b719460967bf6373ff9c
