### ISSUE TITLE
Sending predefined messages through other applications

### ISSUE THREAD

**Issue by tianahailee** [klinker-apps/messenger-issues#681]
**Device with issue:** Google Nexus 6P
**Primary device:** Google Nexus 6P with Android
**App version:** Android 8.1.0
**Steps to reproduce:**

1. Go to any other app that has a send SMS function and try sending the predefined SMS/text/link/etc. (I'm using Setmore Appointments for this issue).

**Additional information:**

It works, but is unintuitive and opens up to the "create a conversation" section in Pulse requesting a number to send the SMS to, which is counterproductive.

**Possible solution:**

The app I'm currently using opens the message as inline reply overtop of other apps (like a quick reply). Or just automatically create a conversation with the provided contact rather than requesting a new one.

**Comment by klinker24** [comment]
To add to this, I received this in an email from another user, sharing from an app called "Radar Scope Pro":

![screenshot_20180606-213751](https://user-images.githubusercontent.com/4874287/41434662-1d84075c-6fe2-11e8-95da-f868a8e2e775.png)

**Comment by klinker24** [comment]
This is fixed and will be released in `v3.1.3`.

https://github.com/klinker41/messenger/commit/2749a3687078ddf4da45b81903cb519ec4f4ea9c
