### ISSUE TITLE
Duplicate messages sent when using scheduling

### ISSUE THREAD

**Issue by wingnut144** [klinker-apps/messenger-issues#682]
I scheduled messages last night for delivery this morning.  When I pull up the conversation, it appears that Pulse had send the messages 2 times.  There are 2 entries (identical) at the scheduled time.

The steps I went through were:

- select my existing sms conversation
- select the 3 dots and use the 'schedule a message' option
- select date and time
- type my message and press 'add' 

When the time comes and the message is sent, when I open the conversation, the message is listed twice, in its conversation list.

I have attached a screenshot of the issue, red stars indicate the duplicate messages.
![text](https://user-images.githubusercontent.com/39835369/40849444-3299cf36-657f-11e8-98fc-0108a77f5728.png)

**Comment by klinker24** [comment]
Is this the first time you have used the scheduled message feature? Has it worked fine in the past or is this reproducible?

**Comment by wingnut144** [comment]
I scheduled another for 12:05pm today, and yes, it does it again.
![pict2](https://user-images.githubusercontent.com/39835369/40856310-a930ff38-6594-11e8-9ee1-ac245ad18128.png)

**Comment by klinker24** [comment]
Do you know if the other person is receiving it twice?

**Comment by wingnut144** [comment]
Yes, the user says she did receive it 2 times.

**Comment by klinker24** [comment]
This should be fixed with https://github.com/klinker41/messenger/commit/3ffd7ffe84d52bb3be037ac5b4c5d1684a253f87
