### ISSUE TITLE
SMS delivery reports not working always

### ISSUE THREAD

**Issue by xrahat2011** [klinker-apps/messenger-issues#683]
**Device with issue:** Xiaomi Mi A1
**Primary device:** Same
**App version:** 3.1.2131
**Steps to reproduce:**

1. Send a text message to a number
2. When text is receieved on that number
3. Delivery report's tick still doesn't appear in Pulse while it does appear in Google messenger official messages app of android

**Additional information:**

This happens with some conversations and not with others, also in conversations where no delivery reports happen, sometimes they start happening.

**Comment by klinker24** [comment]
I made some changes around this that should make it more consistent. They will be released with `v3.1.3`.

https://github.com/klinker41/messenger/commit/bd87a3192c5bb78bc0fde144e883d4e2725d889a
