### ISSUE TITLE
Confirm or cancel scheduled messages

### ISSUE THREAD

**Issue by mcjathan** [klinker-apps/messenger-issues#687]
Please add an optional when scheduling a message: "Send scheduled message with or without confirmation?"

If the user chooses the "confirmation" option, the pop-up confirmation message:
1) Shows who the SMS message is to be sent to.
2) Shows the first 10 to 20 words of the SMS message.
3) Asks the user if they want to send or cancel the SMS message.

If the user does not chose the confirmation option when scheduling the SMS, then the SMS message is sent at the scheduled time without user intervention.

**Comment by mcjathan** [comment]
Hi Luke,

I envisioned this prompt at the scheduled time would be optional. When scheduling an SMS, choose to be prompted or not at the scheduled time.  Perhaps the default at the time of scheduling the SMS would be no confirmation.  Implement it in a way that the user would have to go out of their way to invoke the confirmation prompt, and implement it so for people who aren't interested in this feature there are no extra clicks.  And, in this case, it would work exactly as it does now.

An example of how I would find this feature useful:  Sometimes, I schedule a message to followup with a person for an ongoing conversation.  While the conversation is on my mind, I want to followup in case the other person doesn't responded.  So, I schedule a message to keep the conversation going.  However, if the person responds on their own before my scheduled message, then my scheduled message is moot.  This happens all the time for me. But, I do rely on scheduled messages a lot because I find them extremely useful.

**Comment by klinker24** [comment]
I will look to do this in the future, I don't think it will come soon though, sorry. The issue I have is presenting this preference at all, when the user likely won't understand what it is or how it works, since it goes against how this feature is designed. Even if there are no extra clicks involved, the process is still changed, since there is another decision that has to be made

**Comment by mcjathan** [comment]
Hi Luke,

For what it's worth, I didn't dream up this feature.  I encountered it in the past with another SMS Android app.  Although I don't recall the details off-hand, I do remember this feature being both intuitive and unobtrusive.  When I saw it for the first time, I thought "Oh, cool!".  And, I went on to use it often.

Jeff

**Comment by klinker24** [comment]
I think that, for this, I am going to prefer #805. Improving the visibility of scheduled messages essentially solves the problem that you stated above: when you had a message scheduled, and someone replies, that scheduled message is no longer really valid. 

By displaying scheduled messages in the conversation or adding some kind of indication that one exists, that will act as the prompt for whether or not you are interested in keeping that message.
