### ISSUE TITLE
Support nickname 

### ISSUE THREAD

**Issue by ekrunch** [klinker-apps/messenger-issues#688]
**Device with issue:** MacBook Pro on MacOS 10.13.4, running Pulse Desktop 2.3.1
**Primary device:** OnePlus 6 running Android 8.1.0
**App version:** 3.1.1.2131
**Steps to reproduce:**

1. Create contact with nickname field enabled
2. No nicknames are displayed in Android or Pulse Desktop

**Additional information:**

Would it be possible to have Pulse honor the Google Nickname field (if present in the contact) as the display name in conversations as opposed to real names?

**Comment by klinker24** [comment]
I think that I am going to bundle this request in to #620, actually.
