### ISSUE TITLE
Notification with all messages in the thread when a new SMS is received

### ISSUE THREAD

**Issue by tfKamran** [klinker-apps/messenger-issues#691]
**Device with issue:** Motorola Nexus 6 on Android 8.1.0
**Primary device:** Motorola Nexus 6 on Android 8.1.0
**App version:** 3.1.1.2131
**Steps to reproduce:**

1. Receive messages from a particular number
2. Mark all messages as read
3. Receive a new message from the same number
4. Observe the notification with all messages in that thread rather than just the new one.

**Comment by Skullmonkey** [comment]
In the conversation list screen (default screen), Hamburger Menu (3 horizontal lines stacked on top left corner) > Under "Notifications" section, turn off "Show Conversation History".

**Comment by tfKamran** [comment]
That was so stupid of me.

**Comment by Skullmonkey** [comment]
Happens to the best of us every now and then.

**Comment by tfKamran** [comment]
Thanks for the help.
