### ISSUE TITLE
Usability idea: allow to select and delete multiple items in a conversation

### ISSUE THREAD

**Issue by schittli** [klinker-apps/messenger-issues#692]
Hello

Thank you very much for this great and very useful App!

#### I have just one small idea to improve the usability:
**it would be nice if we could mark (select) multiple items in a conversation to delete them afterward at once.**

At the moment, only one item after the other can be deleted.

Thanks a lot kind regards,
Thomas

**Comment by klinker24** [comment]
You can long click to start the multi-select process, on both the conversation list and the message list. This allows you to delete multiple messages or conversations at once.

Pulse has always had this. If that isn't what you mean, feel free to comment back and give me more information on what you are looking for.

**Comment by schittli** [comment]
Hi Luke, thanks a lot... 
so coool :-), it works great.
