### ISSUE TITLE
Message displays as sending, even though it has already been sent (and recevied)

### ISSUE THREAD

**Issue by cdkozuch** [klinker-apps/messenger-issues#693]
**Device with issue:** Acer Swift 3 Running Ubuntu 18.04
**Primary device:** Samsung Galaxy S9
**App version:** v2.3.0
**Steps to reproduce:**

1. send message from Linux desktop client

**Comment by klinker24** [comment]
I am making a new version of the web app, that the desktop app will use. It has numerous enhancements around the status for the messages. This will already be fixed there.

**Comment by cdkozuch** [comment]
Thanks for the quick response. Looking forward to the new version. Definitely my favorite messaging app/service.
