### ISSUE TITLE
Delayed send interacts badly with voice input

### ISSUE THREAD

**Issue by paulcolleyster** [klinker-apps/messenger-issues#694]
**Primary device:**
Nexus 6
App version:  3.1.2.2138

**Steps to reproduce:**

1. Enter a text using voice (tap the microphone on the keyboard)

2. Hit send

3. The radio or a bystander or TV says something, phone parses it and includes it and sends. For bonus points, it's an expletive. (The extraneous words might happen before hitting send and appear after hitting send, since voice recognition is sluggish)

**Additional information:**

Note that voice recognition's less-than-reliable parsing and tendency to pick up other words from the environment is one of the reasons why delayed send appeals to me.

Due to the delays involved in voice recognition, there is no reliable way to vocally add text during the delayed send, so your justification under the "Won't fix" issue does not apply here --- user is never deliberately making last-second changes with voice input.

**Possible solution**:

Restart timer if a change is made.  (Perhaps just in voice mode)

**Comment by klinker24** [comment]
Unfortunately I have no control at all over how the keyboard interprets voice input. The point of the delayed sending is that you should be able to change the text after hitting the send button, editing it will always be possible and that isn't something that I will disable. 

From my side, I have no clue what type of keyboard you are using or what type of input it is giving, and it doesn't matter to the app, so there is no way for me to disable input when you have the voice keyboard active. In Android, the keyboard is completely separate from the app and it just pushes text to the app, as that text is made available. The keyboard will provide me with the text that you input (through voice or typing), then Pulse displays that text to the open text entry.

I really don't think that there is anything I can do about this, sorry. Do you have any other thoughts or does that clear anything up?

**Comment by paulcolleyster** [comment]
Editing text after hitting send is not the problem - the problem is that
the text sends instantly if edited late. That doesn't seem to match the
point of the timer.  Isn't it to give you time to check what you just wrote?

I think the best solution would be to reset the timer.

- Paul


- Paul Colley
paul@thecolleys.net  Cell: +1 603 233 4197   Work: 603 897 3097

**Comment by klinker24** [comment]
Ok, I didn't understand your request from the initial post. Thanks for the feedback, will see what I can do in the future around this.

**Comment by klinker24** [comment]
The delayed sending timer is now reset, whenever the text changes.

https://github.com/klinker41/messenger/commit/4c848d42b3f390e0d7960206ee26392916072d62
