### ISSUE TITLE
Group messages not showing up in Pulse (but are in the default app)

### ISSUE THREAD

**Issue by NotYourLoginID** [klinker-apps/messenger-issues#696]
**Device with issue:** Nokia 6.1 (2018) TA-1045
**Android Version:** Android 8.1
**Primary device:** Nokia 6.1 (2018) TA-1045
**App version:** 3.1.3.2150
**Steps to reproduce:**

1. Uninstall and Reinstall Pulse SMS on Phone
2. Sign into account/etc.
3. Set Pulse SMS as the default messaging app and allowed all permissions
4. Sent a group SMS to myself and another person using a 3rd persons phone
5A. If Group Conversation already existed: No notification or new message recieved
5B. If Group Conversation did not already exist: Nothing

**Additional information:**

If I check the default Android Messages App the group text and all messages are there.

Group messages can be send from Pulse and are recieved by the recipients, but I get no response back

I have tried this with multiple different groups of people, nothing works.

I have tried turning the battery optimizations on and off

I have tried fiddling with the system APN settings. (I have not put anything in the Pulse APN override)

I have tried refreshing my account and reloading from the internal SMS database. This will sometimes bring up the group conversations in Pulse SMS, **but** there is no message history in the conversation.

**Comment by klinker24** [comment]
Thanks for the report. We track all MMS related issues in #101, this one has now been linked in that topic.

Pulse must be failing to download them, while the stock app is succeeding. They are not brought in to Pulse because Android messages is not able to write them to the shared database when it isn't the default app

**Comment by NotYourLoginID** [comment]
@klinker24 Sorry for the duplicate. I saw the "Add Group Message features" post and thought that was the only post about this recently. 

If it's any help in debugging, I did download the new Android Messages update the other day, I know they released that new "Messages on Web" feature (which doesn't show up on my Nokia, but it shows up on my old Moto G4 even without a SIM). Maybe it made some changes to the messaging protocol? I find it unlikely since that would be a system update, but it's a system app so maybe it's special.

**Comment by NotYourLoginID** [comment]
@klinker24 Also! I installed your EvolveSMS app to see if that was working **and it is!** which is very strange. I did notice that EvolveSMS only shows names and timestamps until EvolveSMS is set as the default SMS app. Maybe there is something there?

**Comment by klinker24** [comment]
Hmm yes that is an interesting report. They both use https://github.com/klinker41/android-smsmms

The only difference between the implementations is that Evolve is not targeting the latest SDK, while Pulse is.
