### ISSUE TITLE
NonPhone Devices Stopped Successful Sends

### ISSUE THREAD

**Issue by DPaden50** [klinker-apps/messenger-issues#697]
Yes - [ ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
Yes - [ ] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** 
 A98 Plus II on Android 5.1.1; Samsung Galaxy 4 phone on Android 5.1.1 (no SIM); Dell Studio 1553 laptop running Windows 10 Home  v1709 on Pulse SMS v2. 3.1. 

**Primary device:** <insert your phone: 
OnePlus 5T on Android 8.1.0 running OxygenOS v5. 1.3"

**App version:**
3.1.3.2150

**Steps to reproduce:**

1. Open the Pulse SMS app on any of the secondary devices and start a new or continue an existing conversation, entering "testing" or other desired text
2. Select the send icon and note the status is displayed as Sending. 
3. Wait or come back to the app the next day and the status is still sending and has never been received by the intended recipient. (did not happen for first weeks I had the app but now is consistently an issue. 
4. Repeat steps 1 and 2 on my OnePlus 5t phone
5. Displayed Sending status is quickly removed and shortly the intended recipients' device(s) receive the expected text message. 

**Additional information:**
None likely needed.

**Comment by klinker24** [comment]
Use the "refresh account" option on the phone app, then log in again on the secondary phone.

https://messenger.klinkerapps.com/help
