### ISSUE TITLE
Notifications reply textbox is tiny on Samsung Galaxy S8+

### ISSUE THREAD

**Issue by xNS5** [klinker-apps/messenger-issues#698]
Apologies for improper formatting, first time opening an issue on github.

**Device with issue:** Samsung Galaxy S8+
**Primary device:** Same as device with issue
**App version:** 3.1.3.2150
**Steps to reproduce:**

1. Receive a push notification from PulseSMS
2. Hit "Reply"

On the S8+ the screen is fairly large and the response box is very small relative to the overall screen. [Screenshot of what I'm seeing.](https://imgur.com/ovhu99g)

**Possible solutions:** 

1. Add a feature which allows the user to decide how big the text box is based on their preferences.

2. Make it bigger straight up without a user customization feature. 

3. Don't do anything. It works perfectly even though it's a tad small and I can still hit send from my keyboard in lieu of hitting send in the textbox.

**Comment by klinker24** [comment]
Sorry, this isn't something that I can control. Direct replies started to be built in to Android with Nougat. Any app that uses the built in replies will have this same UI, it is a system level UI, not something that I made

**Comment by xNS5** [comment]
No worries. Figured that might be the case. Thanks!
