### ISSUE TITLE
When using 3rd party clients like pushbullet, your messages don't show up in app

### ISSUE THREAD

**Issue by Beasto** [klinker-apps/messenger-issues#70]
I didn't add a picture as I thought it was pretty self explanatory. I know about the chrome app but I still wanted to use Pushbullet for it's other functions.

When I reply to a text using pushbullet my reply doesn't show up in Messenger, but the recipient receives the reply.

**Comment by klinker41** [comment]
I'm having no problems with this.

**Comment by Beasto** [comment]
I can shoot a couple of screenshots but this is and has been happening to me in several conversations.
On Sep 5, 2016 2:39 PM, Jacob Klinker <notifications@github.com> wrote:I'm having no problems with this.

**Comment by klinker41** [comment]
No, no need for screenshots.

**Comment by klinker24** [comment]
This one is related to this issue: https://github.com/klinker-apps/messenger-issues/issues/97

Going to close this in favor of that one.
