### ISSUE TITLE
Windows 10 Native Messenger Won't Build

### ISSUE THREAD

**Issue by bmitchinson** [klinker-apps/messenger-issues#700]
- [ X ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [ X ] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:**
Windows 10 AMD Machine

**Primary device:**
Pixel 2

**App version:**
Messenger-Desktop 3.2.1 Master Branch

**Steps to reproduce:**
Run `NPM i` and then attempt to build with 
`./node_modules/.bin/electron-builder build --windows nsis --x64 --ia32`

**Additional information:**
I'm pretty new to open source and this repo in general, so apologies if I missed an obvious step. Spent quite a bit of time looking to see if I was missing something obvious, but couldn't find anything.

![image](https://user-images.githubusercontent.com/33632286/42069714-d5931d42-7b18-11e8-9646-a84d973bcaa8.png)

**Comment by klinker24** [comment]
You should use yarn, not npm, to install the dependencies, as noted in the readme.

```
npm install -g electron
yarn install
npm start
```

Electron builder also recommends this on their readme

https://github.com/electron-userland/electron-builder/blob/master/README.md

**Comment by bmitchinson** [comment]
@klinker24 I used yarn to reinstall all dependencies, but I still can't use `./node_modules/.bin/electron-builder build --windows nsis --x64 --ia32` to get a distribution build as advised in the readme.

**Comment by klinker24** [comment]
Sorry, I don't know. I tried it on two of my Windows machines and both worked fine, after you opened the issue. You could try updating electron builder to the latest version.

Seems like something is off on your dependencies, since it looks like you were able to build the exe without any errors.

**Comment by bmitchinson** [comment]
Well, if anyone in the future takes a look at this or has any advice, it'd be much appreciated. I'll keep looking. Just did a global of electron-builder too and same error upon running the app.
