### ISSUE TITLE
Message templates

### ISSUE THREAD

**Issue by Oublieuse** [klinker-apps/messenger-issues#701]
For work, I use templates to answer quickly to my clients requests. I use it a lot on chompsms. I just miss this feature to definitely migrate to pulse that I like more, but because of this missing feature is tedious to use. Thanks !

**Comment by klinker24** [comment]
Pulse has templates: https://messenger.klinkerapps.com/help

https://github.com/klinker-apps/messenger-issues/issues/135

**Comment by Oublieuse** [comment]
I just saw that this feature exist but is in the attachment menu...
