### ISSUE TITLE
An error occurred where adding this device

### ISSUE THREAD

**Issue by OrekiDawson** [klinker-apps/messenger-issues#703]
- [ ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [ ] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** <insert your device: "MacBook Pro on MacOS 10.12, running Chrome v54">
**Primary device:** <insert your phone: "Pixel XL on Android 7.1.2">
**App version:** <insert version: in "My Account" on the phone>
**Steps to reproduce:**

1. step 1
2. step 2
3. step 3

`... more steps`

**Additional information:**

Do you want to provide any other information? Device configuration, unique cases, screenshots, anything that you think may be relevant.

**Possible solution:**

Do you have an idea of how to solve it? If not, that's fine. You can delete this section.

**Comment by klinker24** [comment]
You need to fill out the template when creating an issue. Pulse will be unable to add the device if there is a configuration error with Google Play Services. This could happen from side loading play services, running a custom ROM, or other custom software.
