### ISSUE TITLE
Search in desktop client

### ISSUE THREAD

**Issue by Maxximus007** [klinker-apps/messenger-issues#705]
- [v] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [v] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** Pulse SMS - Desktop
**Primary device:** Android 7.x
**App version:** 2.3.1
**Steps to reproduce:**

The search in the desktop client is leaving out results that can be found on an Android search. This is a quite severe limitation.

The help on this subject (found in the desktop client) points to an older Issue for the webbased version. It states that the decryption would take too long, although that will be debatable, but now since we have an Electron version, it would be very handy to have a broader search available. Perhaps limit it on dates?

Even if you decide to leave it limited as it is now, perhaps show a message that the desktop app searched xxx messages and found nothing, but check your phone would be helpful.

**Comment by klinker24** [comment]
The same limitations for the search on the web apply to the desktop app. The electron app just wraps the webpage.

https://github.com/klinker-apps/messenger-desktop

At this time, downloading and searching the messages is infeasible.
