### ISSUE TITLE
Duplicate Notifications on WearOS

### ISSUE THREAD

**Issue by owenlejeune** [klinker-apps/messenger-issues#707]
**Device with issue:** Essential PH-1 running P Beta, Asus ZenWatch 3 running WearOS 2.0
**Primary device:** Essential PH-1 running P Beta, Asus ZenWatch 3 running WearOS 2.0
**App version:** 3.2.1.2166
**Steps to reproduce:**

1. Have Pulse installed on phone and watch
2. Have notifications enabled for both
3. When receiving a text message, the watch will vibrate twice, showing the notification card from the phone and the watch app

**Additional Notes**
Disabling Pulse notifications from the phone in the WearOS results in a considerable lag between a message being received and the WearOS app delivering the notification to the watch

**Comment by klinker24** [comment]
Pulse is set up to prevent mirroring (disable bridge mode) for notifications from the Android phone. If that isn't working on your watch, it is an issue with the watch, not my app. It is just a single line for me to add, in the manifest file: https://developer.android.com/training/wearables/notifications/bridger

You can just tell the Wear OS app on your phone to not mirror the Pulse notifications to the watch, though: https://www.howtogeek.com/294009/how-to-block-notifications-from-specific-apps-on-android-wear/
