### ISSUE TITLE
Add text when sharing a picture or link

### ISSUE THREAD

**Issue by klinker41** [klinker-apps/messenger-issues#71]
**Device with issue:** Nexus 6P running Android 7.0
**Primary device:** Nexus 6P running Android 7.0
**App version:** 1.2.283

**Information:**

When sharing a picture or link to the app, the compose screen is pulled up so you can enter the contact you want to send the data to. Then, the next button changes to a send button. There should be a way to add more text to this. 

I think the best way to do this would be instead of changing to a send button, the fab stays as a next button and when clicked, copies the link or image into a draft and then pulls up that conversation so that the user can change it or add to it as they would like and then send it.

**Comment by klinker24** [comment]
Done: https://github.com/klinker41/messenger/commit/c0b38b05e3e51a6267c063dcbdc894fdc210566c
