### ISSUE TITLE
Push notification not working anymore

### ISSUE THREAD

**Issue by misterw97** [klinker-apps/messenger-issues#710]
Android 8.1: Nexus 5 and OnePlus 6
I don't receive push notification when I receive an SMS (it happens when app is closed or background).

**Comment by klinker24** [comment]
I don't understand what you mean. Push notifications are not used in Pulse to display content. You are going to have to give me way more information on the situation...

I discuss how the app works, on my architecture topic.

https://messenger.klinkerapps.com/help

Comment back with more information and I can reopen this issue.
