### ISSUE TITLE
Web App: App bar is white in main conversation list

### ISSUE THREAD

**Issue by leetosc** [klinker-apps/messenger-issues#711]
In a conversation, the app bar is colored correctly according to the theme, but when in the main conversation list, it is white. The buttons which are white are invisible unless hovered over.

Images:
https://imgur.com/a/dYZZLD5

- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [x] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** MacBook Pro on MacOS 10.13.6, running Chrome v67
**App version:** <insert version: in "My Account" on the phone>
**Steps to reproduce:**

1. launch the web app at https://pulsesms.app
2. OR: launch the desktop app

**Comment by klinker24** [comment]
Well.. what color should it be? What color do you have set for it? I will need more info, sorry.

**Comment by leetosc** [comment]
In the old web app (messenger.klinkerapps.com), in settings there is "Use colored toolbar".  With this selected, in the conversations list the app bar is the default Teal.  When not selected, the toolbar is black.

In the new web app (pulsesms.app), this setting is not there, and the app bar is white.

Old: 
![image](https://user-images.githubusercontent.com/13279967/43040576-0be81310-8d0d-11e8-8b2b-a902bb779054.png)

New: 
![image](https://user-images.githubusercontent.com/13279967/43040577-15671436-8d0d-11e8-9a0c-96de6fe168ca.png)

**Comment by leetosc** [comment]
Never mind, I did not know  you could click and change the "Primary Color" on the new web app.

**Comment by klinker24** [comment]
That setting doesn't and won't exist in the new app, sorry. You have the white primary color, so that is what is going to be displayed on the app bar.
