### ISSUE TITLE
Windows 7 emojis appear broken in new web app

### ISSUE THREAD

**Issue by branaugj** [klinker-apps/messenger-issues#712]
**Device with issue:** <Windows 7 Web/Desktop Apps>

**Additional information:**

In the new version of the web app, emojis are no longer being displayed on Windows 7.

Here is a screenshot taken from [messenger.klinkerapps.com](messenger.klinkerapps.com):

![2018-07-23_09h13_59](https://user-images.githubusercontent.com/4073202/43089120-c437a7f4-8e58-11e8-9fd9-b990c8b60ba8.png)

Here is the same message taken from [pulsesms.app](pulsesms.app):

![2018-07-23_09h15_06](https://user-images.githubusercontent.com/4073202/43089197-ea333446-8e58-11e8-8097-c6c4ff61f440.png)

Additionally, the first screenshot is what I saw prior to the 3.0.0 version of the Windows 7 desktop app, and the second screenshot is what I am now seeing in the 3.0.0 version of the desktop app.

**Comment by klinker24** [comment]
You would have to tell me what part of the app those are appearing in. Messages, the conversation titles, or elsewhere.

**Comment by branaugj** [comment]
Sorry about that.

Here are screenshots from the old version of the web app (conversation view and message thread, respectively):
![old2](https://user-images.githubusercontent.com/4073202/43098542-37ee9886-8e74-11e8-8909-c4e7fd953e27.png)
![old1](https://user-images.githubusercontent.com/4073202/43098552-3eac6a2c-8e74-11e8-9e6f-8b28ed7fd4c3.png)
  
  
  

Here are screenshots from the new version of the web app:
![new2](https://user-images.githubusercontent.com/4073202/43098593-638aff48-8e74-11e8-91ad-91aea56fd4a5.png)
![new1](https://user-images.githubusercontent.com/4073202/43098599-66f65240-8e74-11e8-9c28-ffb532c32ee2.png)

**Comment by klinker24** [comment]
Hmm. The new version of the web app should have the same emoji support as the previous version. It uses [emojione](https://github.com/emojione/emojione).  

You say Windows 7, specifically. Should I believe it is working fine on other platforms then, for you? Or does opening it on another computer, or even your phone, produce similar results?

**Comment by branaugj** [comment]
Yes, it is working fine for me on other platforms. No problems on my Android phone or on my Windows 10 PC, only seeing this on my Windows 7 PC. Does the new version of the web app use a newer version of the emojione library?

**Comment by klinker24** [comment]
So, interesting, emojione is actually not working on the deployed version of the app. I can't figure out why that is. Works fine locally. Hmm.

**Comment by klinker24** [comment]
This is fixed and it will be rolling out. 

https://github.com/klinker-apps/messenger-web/commit/e39bfbb5f491c7a304c3753992c83c8f258100da

For my own notes... I had to change the webpack configuration. Apparently, this isn't an uncommon issue with emojione. The minification broke the regex string.

https://github.com/iamcal/js-emoji/issues/46
https://github.com/zeit/next.js/issues/2785
https://github.com/emojione/emojione/issues/557
