### ISSUE TITLE
Windows App blank

### ISSUE THREAD

**Issue by donaldkieu** [klinker-apps/messenger-issues#713]
- [X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [ ] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** Both Desktop and Laptop windows 10 machines
**Primary device:** Samsung Note 8
**App version:** 3.2.2.2170
**Steps to reproduce:**

1.  Windows Startup
2. Pulse launches upon startup
3. Pulse window is blank

`... more steps`

**Additional information:**
`
![pulse blank](https://user-images.githubusercontent.com/40751472/43097207-2cd9edfa-8e70-11e8-80a8-e6189144850c.png)
`
Briefly fixed by reinstalling but the problem returns.

**Comment by klinker24** [comment]
This would probably happen if the app isn't able to access the internet right away. I bet that you could fix it by using the "ctrl + R" shortcut.

**Comment by klinker24** [comment]
I think this will solve your problem. It will be released with the next version.

https://github.com/klinker-apps/messenger-desktop/commit/6c3b2d6dfcd244ed93d5956058d767f66992b2d2

**Comment by donaldkieu** [comment]
Will I have to so this command everytime I use the application? It used to work flawlessly

**Comment by klinker24** [comment]
No. That is why I said I fixed it for the next version.
