### ISSUE TITLE
Can't login on phone or desktop

### ISSUE THREAD

**Issue by MarioZenith** [klinker-apps/messenger-issues#719]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [x] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** LG V20 and Desktop PC
**Primary device:** LG V20
**App version:** 4.0.0.2174
**Steps to reproduce:**

1. Opened Pulse SMS Desktop Client.
2. I saw that it was not syncing (the loading circle was turning infinitely).
3. Tried restarting my phone. No change.
4. Tried refreshing the account. Couldn't login.
5. Tried deleting the account from the forgotten password page, which worked.
6. I try to recreate an account but it says there is already an account linked with that e-mail (I tried a few e-mails, even ones I don't use to test, still said the same thing).
7. I can no longer use the multi-platform aspect of the app... :(

**Additional information:**

I have the lifetime subscription and it recognises it when I try to login or register. I don't have access to the "My Account".

Thanks in advance for the help,

-MarioZenith // Samuel

**Comment by klinker24** [comment]
You will have to send me an email. This isn't really something I can help you with, over GitHub.

luke@klinkerapps.com

**Comment by MarioZenith** [comment]
Hey,
I think it might have been the google play services in some sort of maintenance maybe, because I have just tried redoing what I was doing earlier and it seems to work.
I think it's fixed but if I have the same problem i'll email you :P
Thanks

-MarioZenith // Samuel
