### ISSUE TITLE
Web Version Not Working

### ISSUE THREAD

**Issue by SpartanNews** [klinker-apps/messenger-issues#722]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [x] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** <PC Windows 7/Opera>
**Primary device:** <OnePlus 3T on Oxygen 5.0.4">
**App version:** <4.0.4.2174>
**Steps to reproduce:**

1. As of 24 hours ago. Web version at first did not reload on refresh

2. Have logged out and in...web version loads now, but, does not work. Does not send messages or sync with messages sent from phone. Note: Web version is now https://pulsesms.app

3. Tried different PC and Internet Explorer. Same behavior.

`... more steps`

Note: My Account section in phone app has disappeared. 

Do you want to provide any other information? Device configuration, unique cases, screenshots, anything that you think may be relevant.

**Possible solution:**

Do you have an idea of how to solve it? If not, that's fine. You can delete this section.

**Comment by klinker24** [comment]
If the account section on the phone disappeared, then you are not logged in on the phone. Just go to the "text from any device" section to log in.

In the future, this is probably a question that makes more sense over email. GitHub is for app issues, not account issues.
