### ISSUE TITLE
Prevent certain numbers/conversations to be uploaded

### ISSUE THREAD

**Issue by jkalousek** [klinker-apps/messenger-issues#726]
I wasn't able to find answer here nor in FAQ section...

**Feature Request:**
Function to prevent certain numbers/conversations to be uploaded to cloud.

**Additional information:**
I don't have any reason to not believe in used encryption but I would really like option in phone app that would allow me to disable upload for certain conversations.
Mainly because I do not want to upload MFA codes that some services are sending via. SMS and have them pop up on my dektop - I know that I can use private conversations but even then It's by design that MFA code should not be accessible from same device as service that is being logged into...

**Possible solution:**
Simple switch in contact/conversation setting...

Thank you for considering this request...

**Comment by klinker24** [comment]
I do not know if this is something I will ever do or not, to be honest. Pulse, as a platform is designed to mirror absolutely everything from the phone to the web. Introducing a feature like this would go against that goal/philosophy and could be costly in terms of performance.

While I can understand not wanting 2FA codes on the web.... Any messages that you receive over SMS should never be considered secure. If someone wanted to get to your message history, they definitely do not need to go through Pulse to do so. There are much easier ways for people to intercept your SMS messages than someone trying to decrypt them through my web database

**Comment by jkalousek** [comment]
I would love to tell my Bank or Adobe or Autodesk to stop using SMS and give us better 2FA option but I feel like that's really far away and it's still better option than no MFA.
I will keep using private conversations for MFA SMS. Thanks for consideration anyway.
