### ISSUE TITLE
Desktop app is slow and duplicating messages

### ISSUE THREAD

**Issue by Skullmonkey** [klinker-apps/messenger-issues#727]
**Device with issue:** Pulse Desktop v3.0.1
**Primary device:** Pixel XL Android Pie 9
**App version:** 4.0.2.2188
**Steps to reproduce:**

1. Have desktop app in background
2. Receive SMS on phone
3. Wait 3-5min
4. Notification comes through on desktop
5. Open pulse and enter conversation
6. Notice that messages appear multiple times on desktop but not on phone.

**Additional information:**
The multiple texts only show up on the desktop version. I have tried restarting the desktop app and downloaded the new update (It was happening before the update). Problem persists. I have noticed lately (past week or 2) that notifications on the desktop come more and more delayed sometimes up to 15 minutes after I have received a text on my phone and have responded to it already. When the messages show up, they are duplicated from 2-4 total of the same message. The first occurrence I can find of this is about 9:45pm EST last evening.

Screenshots: https://imgur.com/a/jHYGlkN

**Comment by klinker24** [comment]
I had issues last night and this afternoon. They have since been resolved. 

Use the "refresh account" option on the phone to re-upload everything from the phone to the web.
