### ISSUE TITLE
Produces sound with Do Not Disturb mode active

### ISSUE THREAD

**Issue by sloanstewart** [klinker-apps/messenger-issues#728]
- [✓] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [✓] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** Pixel 2 on Android 9.0
**Primary device:** Pixel 2 on Android 9.0
**App version:** 4.0.2.2188
**Steps to reproduce:**

1. Turn on Do Not Disturb
2. Send or Receive a message via Pulse

**Additional information:**
With sounds and messages turned off in the Do Not Disturb settings, Pulse will continue to make sounds when sending and receiving messages.

**Comment by klinker24** [comment]
All notifications on Android 8.0 and above are done through the system level notification channels. Notification channels have a preference for the functionality you want to use during do not disturb mode. I will not be able to affect this, within the app. 

For more information on notification channels, you can read about them in my help page

https://messenger.klinkerapps.com/help

**Comment by sloanstewart** [comment]
Thanks for the info! This was a recent change after installing Android 9.0 that caught me off guard, since I pretty much keep my phone on DND all day, it's been strange having text sounds again. Will look into it and post my findings!

**Comment by sloanstewart** [comment]
Ok, so it's definitely an Android thing. Do Not Disturb was not muting Ring sounds for some reason. I had to manually set them to vibrate and that took care of it. Still strange behavior, but sorry to bother you with this issue!
