### ISSUE TITLE
Text messages sent by companies don't show contact name

### ISSUE THREAD

**Issue by revanmj** [klinker-apps/messenger-issues#73]
**Device with issue:** Nexus 5X running Android 7.0
**Primary device:** Nexus 5X running Android 7.0
**App version:** 1.2.285

I recently received a text message from a delivery company that I don't have in the contacts list. Yet Google Messenger properly shows its name (InPost) while Klinker Messenger doesn't show any name or number.

**Steps to reproduce:**
1. Receive a text message with contact name set by operator
2. See if this name is displayed in Klinker Messenger

**Screenshots:**

![screenshot_20160906-072011](https://cloud.githubusercontent.com/assets/1777618/18262622/aa7e2ef8-7403-11e6-8944-df7e8878a579.jpeg) ![screenshot_20160906-072025](https://cloud.githubusercontent.com/assets/1777618/18262623/aa877788-7403-11e6-931d-ad3042933eb9.jpeg)

**Comment by revanmj** [comment]
Looks like not only contact name is missing, the app adds all messages of this type into one conversation.

**Comment by klinker41** [comment]
should be fixed with https://github.com/klinker41/messenger/commit/2eac8d1d403332505eb3a769b43736efe305d5d9
