### ISSUE TITLE
Add "Move" action to bulk actions list.

### ISSUE THREAD

**Issue by colinmollenhour** [klinker-apps/messenger-issues#731]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.

Just started using the app but already looking like it's going to be killer! However, I wanted to move some of my conversations to a new folder so I started bulk-selecting them and then was disappointed to find that there is no "Move to folder" action for bulk selection. So, please add a "Move" action to the existing bulk actions list.

Thanks!

**Comment by klinker24** [comment]
Sorry, at this time, it isn't planned to bring this to the conversation list page. 

You can already do bulk movement of conversations into folders though. If you go to "manage folders" page and select a folder, you can choose whichever conversations are in it.
