### ISSUE TITLE
Samsung S8 Max Power Saving Mode

### ISSUE THREAD

**Issue by jackhobbs2** [klinker-apps/messenger-issues#732]
- [x ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [ x] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:*Samsung S8
**Primary device:** Samsung S8
**App version:** Pulse version 4.0.2.2188, Android 8.0.0 Samsung 9.0
**Steps to reproduce:**

1. Set Settings/Device Maintenance/Battery to Maximum Power saver

Pulse is apparently not available, but the default Samsung Apps are.

2. Send a text to the phone.  It didn't get received.
3. Switch Battery back to normal, Pulse appears, but the message doesn't appear for a few minutes.

So, is there a way to use Pulse on a Samsung S8 in Maximum Power Saving mode?

**Comment by klinker24** [comment]
Sorry, no, this is a system level feature that I cannot control. I will not be able to affect this, unfortunately. The goal of their max power saving mode is to only allow you to use applications that they deem appropriate. A third party SMS app would never be appropriate for them.

On my help page, I discuss how Pulse works when you use other apps to send and receive messages, if you search "assistant".

https://messenger.klinkerapps.com/help

**Comment by jackhobbs2** [comment]
Your prompt help reply is appreciated!
