### ISSUE TITLE
emojis kill android app + can no longer cntl/enter send in web app

### ISSUE THREAD

**Issue by rockythebull** [klinker-apps/messenger-issues#738]
1/ every time i put an emoji into a text on my android phone, it shuts the pulse program down and i lose everything i've written up to that point.  it happens every single time i use one.

2/ with the windows web app, if i write a long text, i can no longer send the text manually.  the send button scrolls off the screen.  used to be i could get around this by hitting ctrl/enter (i think it was) to send.  that no longer works for me. 

anything i can do about these two big problems (at least they're big to me).

**Comment by klinker24** [comment]
I don't see any crash reports around emojis. If you can provide a stack trace of the error, that would be helpful.

A screenshot of your second issue would also be helpful.

In the future, please fill out the information on the issue template, rather then deleting it. Please provide the device type and what version of Android you are on, to help troubleshooting.

**Comment by rockythebull** [comment]
so sorry for not filling out info in full.  as re the emojis: that issue seems to have resolved itself, probably doing so upon writing you, which isn't that how it works so often?

as to the second, i've attached two jpgs.  in the first, you can see that the send button, at the top of the screen, is still visible.  in the second, i added a few lines to the text, which pushes the send button up and out of sight.  i can't scroll to get it back.  it's gone.  so, in the past, i've been able to use cntrl/enter to send the text, but that no longer works for me.  can you help?  can i post anything else?

lenovo laptop
windows 10

![0013](https://user-images.githubusercontent.com/42776351/44782303-c6759f80-ab54-11e8-9c57-7601e995962e.jpg)
![0014](https://user-images.githubusercontent.com/42776351/44782304-c6759f80-ab54-11e8-9d61-de4c09cc21a5.jpg)

**Comment by klinker24** [comment]
By default, you can send messages with the enter key. You can turn on enter to send for this, from settings. If you need to insert a new line when this is turned on, you can do so using shift + enter

**Comment by klinker24** [comment]
There has never been a Ctrl + enter feature, I don't know what you mean by that.

To get to the option to use enter to send messages, open the web or desktop app, touch the three dots overflow menu, and go to settings.

When that is turned on, you can use shift + enter to add a new line. That seems to be exactly what you are looking for.

In the future, I will see if I can add a shortcut to use enter to send the message, when the "enter to send" option is turned off.

**Comment by rockythebull** [comment]
hmm.  okay, maybe i'm wrote but i do seem to remember some key combination that could be used to send a text.

i guess i'm having a difficult time explaining what i'm hoping for, but for future use, here's another stab at 1.

1/ i want to be able to use enter to add a new line.  at the same time ...
2/ i want to be able to use some key combination like cntrl + enter to send a text.

thanks anyway, and thanks for your prompt responses.

**Comment by klinker24** [comment]
The desktop app has a three dots overflow button. Please provide the screenshot if you believe otherwise. 

I understand that you are looking for the reverse of what I have already provided.
