### ISSUE TITLE
Day/night base theme isn't working

### ISSUE THREAD

**Issue by redkyng** [klinker-apps/messenger-issues#74]
Hello, with the latest 1.2 update on the 6th September the Day/Night base theme seems broken! I'm having the night mode activated on the Day!

**Comment by redkyng** [comment]
I forget to mention I'm on CM 13 Android 6.0.1 snapshot!

**Comment by klinker24** [comment]
There is a template in the readme that you need to follow for future submissions.

**Comment by klinker24** [comment]
Fixed with: https://github.com/klinker41/messenger/commit/83c567980351d5f73f38f958894e7bb5e4bc605e
