### ISSUE TITLE
Sending a test SMS to oneself

### ISSUE THREAD

**Issue by loldrup** [klinker-apps/messenger-issues#742]
I have just installed pulse sms for the first time. I would like to send a test SMS to myself, using my PC (win7, Firefox, https://pulsesms.app). I can only choose to send to an existing contact. I can't just enter my phone number.
Is the only solution to this to create a 'me' contact on my phone (maybe it's just me, but I can't find a way to create new contacts via the web interface), resync, and then send to this 'me' contact?

**Comment by klinker24** [comment]
You can just type the phone number, then click on the message entry. You do not have to just send messages to an existing contact.

Pulse isn't a contact management app. To create a contact, you will have to do it through the contacts app on your phone. You can immediately upload contact changes, using the "resync contacts" option on Android.

https://messenger.klinkerapps.com/help
