### ISSUE TITLE
SMS not pushed to Android Head Unit connected to internet via Wifi Hotspot.

### ISSUE THREAD

**Issue by bfiset** [klinker-apps/messenger-issues#745]
**Device with issue:** Android Head Unit running Oreo 8.0
**Primary device:** Google Pixel 2
**App version:** 4.1.0.2236
**Steps to reproduce:**

1. Receive plain SMS on phone
2. Witness SMS is not pushed to Android Head Unit

Android Head Unit is connected to internet via Wifi hotspot coming from the same phone that received the SMS.

Paid for lifetime subscription.

The whole point of my purchase is to be able to have SMS and MMS pushed to my Android Head Unit when connected to the internet. It's not working.

**Comment by klinker24** [comment]
This probably isn't something for GitHub. If you reach out over email, I can have more insight in to your account. GitHub isn't really meant as a troubleshooting/help tool

There are two places the issue could be:

1. Messages aren't being pushed from the phone to the web.
2. Messages aren't being pushed from the web to that Android device.

For the first, on my help page in the account debugging section, there is a topic on what is messages aren't being pushed to the web

**Comment by klinker24** [comment]
Sorry, I am going to have to close this for lack of response. Without the above information, there is no debugging that I can do around this issue
