### ISSUE TITLE
The "Sending" flag is stuck on Honor 7 (Android 6.0)

### ISSUE THREAD

**Issue by joanrieu** [klinker-apps/messenger-issues#747]
**Device with issue:** Huawei Honor 7 (PLK-L01) with Android 6.0
**App version:** 4.1.0.2236

**Steps to reproduce:**

1. Send an SMS in any conversation.
2. "Sending" appears under the new message.
3. The recipient receives the message (and can even reply).
4. "Sending" disappears only about a few minutes later (~1min 45s when measured once, but I think it's faster sometimes).

**Additional information:**

This is not the only app with that issue on that phone, for example Android Messages never clears the "Sending" flag at all. The stock Huawei SMS app does not have this problem, though, so it's not impossible to fix.

When multiple messages are sent, the "Sending" text disappears *simultaneously* from all of them.

Killing the app does *not* help.

**Comment by klinker24** [comment]
Unfortunately, as a third party app, all I can do is wait on Android to notify me that a message is sent. I do not have access to your carrier. The fact that another third party messaging app has a similar issue, while your first party one does not, says that this is an issue with the device or your carrier. The first party app can integrate directly with your carrier, something that my app will never be able to do.

**Comment by joanrieu** [comment]
While I agree that this may be a device-specific issue, I do not understand what you mean by "integrate with your carrier". This device is not locked to a carrier. Can you please elaborate?

**Comment by joanrieu** [comment]
Additional information (which I forgot to mention and which might be relevant) : this is a multi-SIM device.

**Comment by klinker24** [comment]
The stock app is a first party app. A first party app could have different tools and ways to talk to your carrier.

**Comment by joanrieu** [comment]
After some digging with LogCat and the Android SDK doc I actually found the root cause of the issue and how to fix it. It has nothing to do with carrier-specific issues.

The Huawei power manager has an option called "Start app. automatically" which is disabled by default. When enabled for your app, then the "Sent" flag behaves correctly. The power manager is probably intercepting the PendingIntent used as callback when the message is sent.
