### ISSUE TITLE
Application crashing on startup

### ISSUE THREAD

**Issue by wingnut144** [klinker-apps/messenger-issues#748]
- [ ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [ x ] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** Google Pixel XL
**Primary device:** Google Pixel XL running Android Pie
**App version:** 4.1.1.2247
**Steps to reproduce:**

1. Click on the app icon
2. App loads, shows conversations, and then crashes

**Additional information:**

Cleared the data storage and cache, same problem

**Possible solution:**

Do you have an idea of how to solve it? If not, that's fine. You can delete this section.

**Comment by klinker24** [comment]
I fixed it and will release a version later today. If you want it fixed now, you can opt out of the beta test and re-install the app, from the Play Store.
