### ISSUE TITLE
Color picker

### ISSUE THREAD

**Issue by JohnL4** [klinker-apps/messenger-issues#749]
**Device with issue:** Chrome, Windows desktop (prolly PWA, too, yay, you wrote a PWA!)
**Primary device:** Samsung Galaxy S8, Android 8.0.0
**App version:** whatever you serve over the web
**Steps to reproduce:**

1. open a particular conversation
2. "three dots" menu, conversation settings
3. color picker

Would be really spiffy if 

(a) We didn't have to enter hex codes for colors; and
(b) (even better) we could easily pick good related colors for "dark" and "accent".

Desktop web UI will probably be my primary use of Pulse, since I like chat apps (ability to use a computer keyboard) but my kids (on iPhone, btw) insist on sticking w/SMS.

**Comment by xrahat2011** [comment]
Would love to put in custom hex colours.

**Comment by klinker24** [comment]
The web allows for hex colors. Hex colors will not be coming to the Android app.

**Comment by xrahat2011** [comment]
> The web allows for hex colors. Hex colors will not be coming to the Android app.

Alright, but more colour options, can they me made available?

**Comment by klinker24** [comment]
The Android app has a crazy amount of options already. If you need more than that, you will have to use the hex color support on the web, sorry.

**Comment by xrahat2011** [comment]
> The Android app has a crazy amount of options already. If you need more than that, you will have to use the hex color support on the web, sorry.

No problem at all, but how can you do that?
Wait! What? I didn't know you can go to the conversation settings of each conversation and set custom colors from there, hah! It would be amazing to see hex support in android app but this is okay too, why isn't there one in android though?

**Comment by xrahat2011** [comment]
Have you developed all pulse by your own self only?

**Comment by klinker24** [comment]
Some parts of Pulse are open source and have received contributions from others. Most of platforms are just me, yes.

There isn't one in Android because I want to keep it simpler.

**Comment by xrahat2011** [comment]
> Some parts of Pulse are open source and have received contributions from others. Most of platforms are just me, yes.
> 
> There isn't one in Android because I want to keep it simpler.

Good.
Yeah, I am a developer/script-kiddie too, been about 3 years now, my mind keeps expanding. I get you, just start from a joke and your mind and your application keeps expanding with features and features and only you managing it is amazing as corner-to-corner it's like omg so big and dang, no documentation. I'm dead! But when you go back to your 2 years old writted code, eventually, you get to know it back and what it's doing haha. It's quite nice experience haha
