### ISSUE TITLE
Manage contacts from desktop

### ISSUE THREAD

**Issue by ContemplativePanda** [klinker-apps/messenger-issues#750]
- [ X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [ X] If this is an issue, and not a request, I have verified that this is something that is reproducible

It would be nice to be able to manage contacts from the desktop app. I was just trying to add a contact I started a message thread with using their phone number and searched around for a while because it seemed like I should be able to add them. It would definitely make the whole experience feel more cohesive.

**Comment by klinker24** [comment]
Sorry, I don't see this happening. Pulse isn't a contact management app, so it doesn't have any type of integration with the Contacts app on your phone or Google contacts. 

It is just meant to be a messaging app. It simply pulls contact information from the Contacts app on your phone. It doesn't have a way to write back to that app/service and I don't think that that is something that I want to mix in with Pulse, sorry
