### ISSUE TITLE
Pulse Icon showing 2 sms's when only 1 sms is received.

### ISSUE THREAD

**Issue by poyda31** [klinker-apps/messenger-issues#751]
- [x ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my issue/request to verify that there aren't any open or closed issues around this request.
- [x ] If this is an issue, and not a request, I have verified that this is something that is reproducible

**Device with issue:** Samsung S9+
**Primary device:** Samsung S9+ V8.0
**App version:** 4.1.1.2242
![screenshot_20181004-181624_samsung experience home](https://user-images.githubusercontent.com/43843145/46461880-2a018580-c803-11e8-80a8-fdd6faa35a76.jpg)

**Additional information:**

I have disabled Android Auto "SMS" app permissions.
When i receive 1 sms the app icon shows 2, when i open the app there is only 1 sms.

**Comment by klinker24** [comment]
There is an unread message somewhere, then. Searching "badge" on the help page woll solve this issue: https://messenger.klinkerapps.com/help

**Comment by poyda31** [comment]
Thank you.
