### ISSUE TITLE
Pulse not showing internal SMS after login

### ISSUE THREAD

**Issue by Hangman228** [klinker-apps/messenger-issues#752]
- [X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [ ] I have verified that this is something that is reproducible.

**Device with issue:** XZ1 Compact - Android 8.0
**Primary device:** XZ1 Compact - Android 8.0
**App version:** 4.1.5.2260

**Describe the bug:**
Here is my problem, when I install the app, all my message stored on my phone appears on app, but right after login a message says "No message".
Problem still occurs after update my account and still after resync my account (where I lost all my message on my account)
I tried to uninstall and everything is great (my internal message are shown) until I login again...

**Comment by klinker24** [comment]
Whenever you log in, the app downloads what is on the web to the device. Just delete the account, clear the app data, then create a new account.

https://messenger.klinkerapps.com/help
