### ISSUE TITLE
Web version of application will not remember my turning off the setting "Use Enter to Send Messages"

### ISSUE THREAD

**Issue by SeriousTube** [klinker-apps/messenger-issues#754]
I have scrolled through all issues for my problem to verify that there aren't any open or closed issues around this behavior.

I have verified that this is something that is reproducible.

**Device with issue:** Windows 10 Laptop with Chrome Browser version 69

**Primary device:** My phone is a moto g6 play however this bug report is for the pc

**App version:** This pertains to the pc web version of your app which doesn't have a version number as far as I can tell, however the version number on my phone is 4.1.5.2260

**Describe the bug:**
There is an option "Use Enter to send messages" which defaults to on, but which I want off. It reverts back to on usually after a day or two.

**Steps to reproduce:**
I don't know exactly what triggers it in my case. I don't clear my cookies frequently. However if I clear all cookies in my browser this seems to trigger the bug every time. The setting will have reverted back to on.

**Expected behavior:**
I expect that when I make a change to a setting that the change is remembered. In this case, if I set Use Enter to Send Messages to off, it should remain off.

 
**Additional information:**
I am a paid pulsesms user. My login name there is pulse@sallydown.com.

**Comment by klinker24** [comment]
The web specific settings are stored locally on the machine. Clearing cookies will definitely clear this preference. At this time, those web specific settings are not going to be tracked anywhere other than locally on the machine

**Comment by SeriousTube** [comment]
OK. That's unfortunate. I still don't know why it is clearing my choice every day or two as I only clear my cookies maybe twice a year.

**Comment by klinker24** [comment]
I would have to have more information on when it happens and how I can reproduce it, to be able to tell you much... I do not see this issue happening on my side, unfortunately.

**Comment by klinker24** [comment]
I have not heard back on this and have been unable to reproduce it. At this point, the issue is closed. Please feel free to follow up with more information, if it becomes available.
