### ISSUE TITLE
Starting Pulse-SMS desktop on linux only as tray icon

### ISSUE THREAD

**Issue by Wicoucou** [klinker-apps/messenger-issues#756]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues around this behavior.

**Describe your request:**
Offering the possibility to start the linux desktop version without opening the main pulse window. This could be done via a command-line parameter like : 
~$ pulse-sms --tray-only

**Describe alternatives you've considered:**
I haven't found a simple way to do it, I don't have alternatives. 
Maybe I am missing it (?)

**Additional information:**
The objective is, since auto-startup is unsupported on linux versions, to allow user to add the "tray-only" version of the command line into their startup applications and have an automatic and silent startup of the app.

Thank you for your consideration.

**Comment by klinker24** [comment]
Duplicate: https://github.com/klinker-apps/messenger-issues/issues/684

This functionality has already been implemented.
