### ISSUE TITLE
Other Notification Support

### ISSUE THREAD

**Issue by csm10495** [klinker-apps/messenger-issues#757]
**Describe your request:**
Can there be support for passing non-message notifications back to the various frontends for Pulse?

**Describe alternatives you've considered:**
I mean I could use Pushbullet also, though it would be nice for this functionality to also be in Pulse

**Additional information:**
NA

**Comment by klinker24** [comment]
Sorry, no. Pulse is going to just remain an SMS app, I really want to keep it focused on this goal. 

That just really isn't part of what Pulse is designed to be. Obviously the infrastructure and everything is available for it, but it isn't something I would build directly into this app.

**Comment by csm10495** [comment]
Fair enough. Thanks for the reply.
