### ISSUE TITLE
Chrome notifications not working

### ISSUE THREAD

**Issue by Emorich** [klinker-apps/messenger-issues#758]
I seem to be having the same problem as this guy: https://github.com/klinker-apps/messenger-issues/issues/379 - Notifications aren't coming through for new texts on the chrome app. I can see and texts, but I'm not getting notified on the PC when they come in.

Except that I tried what he did and it didn't work. I have the extension and the app, notifications are enabled, and I hit the re-register for notification button. 
Nada.

The bug started when I got a replacement phone. Mine was damaged and the insurance sent me a replacement. I re-installed the Pulse app on my phone, and from that point forward I'm not getting anything.

**Comment by klinker24** [comment]
I recommend the native apps for Mac, windows, or Linux, for notifications over the Chrome versions. The lifecycle and notifications are much more in the apps control.

https://messenger.klinkerapps.com/overview
https://messenger.klinkeraps.com/help

**Comment by maguscorvin** [comment]
Same here I am not getting them via the chrome app or the chrome extension.
