### ISSUE TITLE
Can not send multiple images

### ISSUE THREAD

**Issue by Jacques57000** [klinker-apps/messenger-issues#759]
**Device with issue: Huaway P20  Pro CLT-L09
**Primary device:** Android 8.1
**App version:** Ex: v4.1.5.2260

**Describe the bug:**
Can not send multiple images in the same MMS while it is possible with Android message (which cuts into several messages at the time of sending)

**Comment by klinker24** [comment]
Sorry this is working the way I have designed it. With Pulse, images will be sent in separate messages to avoid the MMS size limits from your carrier.

This is not something that is planned to change, sorry

**Comment by Jacques57000** [comment]
Ok I understood. I have increased the maximum size of the image and the problem seems solved. Thank you
