### ISSUE TITLE
Support live updates and notifications with Service Workers

### ISSUE THREAD

**Issue by klinker41** [klinker-apps/messenger-issues#76]
**Device with issue:** Mac Pro running OSX 10.11.6 and Chrome v53
**Primary device:** Nexus 6P running Android 7.0
**App version:** 1.0.180

**Information:**

We need to update the client live when possible. Polling the server is easy, but it uses power and server resources and this isn't what we want to spend our time on. We added FCM support for the chrome extension and app, however this does not include any web users who prefer to only use the website. For this, we'll need to create a websocket api. Websocket are very well supported in rails 5.

**Comment by klinker41** [comment]
Adding to back burner as this isn't immediately necessary.

**Comment by klinker24** [comment]
May also be able to use `ServiceWorkers` to listen for FCM notifications. Although I do not know how to implement that.

**Comment by klinker24** [comment]
Finally did some more research into this topic. Chrome, through the `ServiceWorker` standard, is able to receive push notifications from FCM.

Works basically the same as the FCM receiver on the chrome app and extension, the service worker is alive in the background and can grab `push` events sent from the server. The browser also creates a registration_id (just like the android or chrome app/extension registration_ids). 

Once we have the `registration_id` for the `ServiceWorker`, sending them notifications is the exact same as sending notifications to android, from our backend, we simply include the `registation_id` in the list of ids that we already have for their devices. Woohoo.

https://developers.google.com/web/updates/2015/03/push-notifications-on-the-open-web

One problem is that you cannot include any data along with the push notification, so we would need to store the data on the server with a `GET` endpoint for the user to hit when the `ServiceWorker` receives the push notification. Or, we could simply create a `message#find_latest` route that the browser can fetch the newest timestamped, received, message from. This would probably be the simplest way to do this.

**Comment by klinker24** [comment]
For now, I do want to implement a polling feature. 

So every 30 seconds, javascript will check for new messages, if there are new messages, then it will update the list. Otherwise, it will do nothing

**Comment by klinker24** [comment]
This commit will auto update the list every 30 seconds, if there is a new one: https://github.com/klinker41/messenger-web/commit/09e461264c350294f4755d2f4d677e55c7a861a6

I don't want to stay with this forever, but for now, it should work ok. Our backend will be able to handle the increased load just fine, and rate limiting won't be an issue.

The script basically just saves the latest timestamp, then, every 30 seconds, it will check to see if a new message exists by getting only the latest message from the conversation and looking at its timestamp. If it is newer, then forcefully refresh the list.

**Comment by klinker24** [comment]
For some information on the web socket implementation, we can look at rails `action-cable`. Here is a headstart on the rails end: https://blog.heroku.com/real_time_rails_implementing_websockets_in_rails_5_with_action_cable

Here is a javascript implementation that we will be able to use on the client: https://github.com/mwalsher/actioncable-js

**Comment by klinker24** [comment]
Here is a FCM implementation for service workers: https://firebase.google.com/docs/cloud-messaging/js/receive

Looks like this can manage things in the background, and while the app is running in the foreground, effectively removing he need for web sockets and just running off of our existing infrastructure?

**Comment by klinker41** [comment]
I created an initial websocket implementation with https://github.com/klinker41/messenger-server/pull/24. Needs tested and verified, deployed to prod and then included in the web app.

**Comment by klinker24** [comment]
Communicating between electron and background web socket, if that is the route we end up going: https://github.com/116356754/wsobserver

**Comment by klinker24** [comment]
I am not pretty comfortable closing out this issue. With the web sockets, we have full support for live updates on the web app, as well as any native apps we create.
