### ISSUE TITLE
Answer on a group

### ISSUE THREAD

**Issue by Jacques57000** [klinker-apps/messenger-issues#760]
**Device with issue:** Huaway P20 Po
**Primary device:** Android 8.1
**App version:** v4.1.5

**Describe the bug:**
The correspondent's response to an MMS I sent from Pulse often returns as being addressed to a group (me and the correspondent). In fact, the answer is not in the same discussion and it is a problem

**Screenshots:**
In the screenshot: I posted an MMS to Eliane and the answer was made to "Jacques Hervé, Eliane Herve"
![pulse](https://user-images.githubusercontent.com/44142041/46920823-1ec50b80-cff4-11e8-94a8-7861ec5f74af.JPG)

**Comment by Jacques57000** [comment]
I add that the problem is only on the mms (and not the sms), and not all the time (I have not managed to identify why it works in some cases and not in others)

**Comment by klinker24** [comment]
This exact issue is discussed in the MMS section of the help page:

https://messenger.klinkerapps.com/help
![screen shot 2018-10-14 at 2 05 51 pm](https://user-images.githubusercontent.com/4874287/46920882-45665080-cfba-11e8-8ec0-e5673bb698de.png)
