### ISSUE TITLE
No reciprocity

### ISSUE THREAD

**Issue by Jacques57000** [klinker-apps/messenger-issues#761]
**Device with issue:** Huaway P20 Pro
**Primary device:** Android 8.1
**App version:** v4.1.5

**Describe the bug:**
MMS sent from PULSE are seen by Android message. In contrast, MMS sent from Android message are not seen by PULSE.  In fact, if I change my mind and give up PULSE (because of the discovery of a bug or a missing and essential feature or other...), I will not find my conversations in Android message anymore.

**Comment by klinker24** [comment]
This isn't going to change, sorry. Pulse is designed to be the default app. When it isn't, not everything will work.

Pulse makes any messages you send or receive while using it, available to other apps. I cannot manage how or when other apps will import those messages though, obviously. That is completely up to them.

Pulse will import SMS that you send from other apps, it will not import MMS you send from other apps, other than the very first time you set it up.

If you were to send a message from the web, when Pulse isn't the default messaging app, that message would never be available in other apps. Android only let's the default messaging app write to the shared database. 

Sorry but there will not be able to be any changes around how these things work.
