### ISSUE TITLE
See all images ready to be sent

### ISSUE THREAD

**Issue by Jacques57000** [klinker-apps/messenger-issues#763]
**Describe your request:**
Currently, if you select multiple images for an MMS, only the last one appears as a thumbnail with an "X" to delete all and the number of images. I would like to find the solution adopted by Android message: see all the images and be able to delete them individually.

Thank you for all your work and your very fast answers

**Comment by Jacques57000** [comment]
I said that I noticed that the pictures are checked in the gallery. Unfortunately, if these images are far apart from each other in this galery, it can become problematic. The solution of Android message is therefore more ergonomic.

**Comment by klinker24** [comment]
This is done and will be released with the next version of the app (`v4.12.0`).
