### ISSUE TITLE
Snooze!

### ISSUE THREAD

**Issue by junkbondtrader** [klinker-apps/messenger-issues#764]
I love the snooze feature in Gmail and would love to see it in Pulse.

(Full disclosure: what sold me on using Pulse in the first place over my in-box messenger app was the archive functionality (everybody does sync). This makes me realize that maybe I just want Pulse to be an SMS/MMS version of Gmail :p)

**Comment by klinker24** [comment]
Sounds like #244, closing as duplicate. Glad you like the app!

**Comment by junkbondtrader** [comment]
Quite right! I only searched for snooze before creating this :3 Thanks for the attentiveness!
