### ISSUE TITLE
Hover between title bar and main pane to find hidden menu bar in Windows native app

### ISSUE THREAD

**Issue by junkbondtrader** [klinker-apps/messenger-issues#766]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues around this behavior.

**Describe your request:**
Once I've hidden the menu bar, I can't get it back unless I know Alt is the shortcut. (Thanks for mentioning that in #642 😄)

**Describe alternatives you've considered:**
Alt does the job for me, but others may not be so fortunate.

**Comment by klinker24** [comment]
This is actually something that is built into Electron, it isn't something I control on my own and is pretty standard behavior on Windows. 

I don't think that this is something that I will be able to invest my time in, sorry. If Electron were to add something around this, I could bring it in, of course, but it isn't something I want to add directly to Pulse.

This alt shortcut is also on my help page

https://messenger.klinkerapps.com/help

**Comment by junkbondtrader** [comment]
Fair enough!

**Comment by junkbondtrader** [comment]
Though I think there is a case to be made that you should do what Slack does and hide the menu bar by default and make the useful settings you have there integrated into the app's settings view. Potentially a lot of work for minimal benefit, admittedly.
