### ISSUE TITLE
Problem with resizing images

### ISSUE THREAD

**Issue by Jacques57000** [klinker-apps/messenger-issues#767]
**Describe your request:**
When entering an MMS, when I attach an image, two symbols appear: a cross to delete it and a pencil to resize it.
If I enclose a second image, the pencil is replaced by the number 2. If I enclose a third image, it is the number 3. In the case of several images, it is no longer possible to resize the images. If I use the cross, all the images are deleted at once.
On the other hand, if I resize the first image (while there is only one image of joint), this one is removed if I add new images.
In conclusion :
- Or we can send a resized image (and only one)
- Or we can send several images, but complete
The problem is that if we started by resizing an image and it is necessary to add others, we do not realize that the first one will not be sent.
Sorry to get bored with these details but the MMS is a very useful communication tool for me and I am looking for the ideal application.

**Describe alternatives you've considered:**
The ideal solution would be to be able to resize each of the images. Otherwise, it should be noted that the image that has been resized is deleted when adding a new image.

**Comment by klinker24** [comment]
This will come for free when #763 is done.
