### ISSUE TITLE
Lost message when adding my Google Maps location

### ISSUE THREAD

**Issue by Jacques57000** [klinker-apps/messenger-issues#768]
**Device with issue:** Huawei P20 Pro
**Primary device:** Android 8.1
**App version:** v4.1.5

**Describe the bug:**
If I start writing a message like "Hello, I'm here", then I add my position on Google Maps, all the text I wrote disappears.
It's annoying because I have to retype it ...

**Comment by klinker24** [comment]
This is done.

https://github.com/klinker41/messenger/commit/aa0a7f40726fda891344a6c57c727eb9df4df918
