### ISSUE TITLE
Desktop version is not showing any information only gray screen

### ISSUE THREAD

**Issue by cam8169** [klinker-apps/messenger-issues#769]
- [yes ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [ yes] I have verified that this is something that is reproducible.

**PC running windows 7 64 Bit :
**Samsung S9+ running Andriod 9.0:** Ex: "Pixel XL on Android 9
**App version:** V3.1.2

**Describe the bug:**
The desktop version is not showing any information just a grey screen.

**Steps to reproduce:**

`... more steps`

**Expected behavior:**
Should show the text messages

**Additional information:**
Add any other context about the problem here. Device configuration, unique cases, anything that you think may be relevant.

**Comment by klinker24** [comment]
`View` -> `Reload` or pressing `ctrl` + `R` will fix this, I'm sure.
