### ISSUE TITLE
Message Scheduler: Contact search not scrollable

### ISSUE THREAD

**Issue by ghctim** [klinker-apps/messenger-issues#77]
**Device with issue:** Nexus 5x running Android 7.0
**Primary device:** Nexus 5X running Android 7.0
**App version:** 1.2.285
**Steps to reproduce:**

1. Go into the message scheduler section
2. search for a name that is common 
3. Try to scroll the names list and it doesn't scroll and half the list is covered by the keyboard

**Additional information:**

**Possible solution:**

Implement same scrollbar that you have in the regular message screen.

**Comment by klinker24** [comment]
Added adjust_resize to dialog window: https://github.com/klinker41/messenger/commit/ef54ddbe9acd2e523f09cdf022d063f7206bc548
