### ISSUE TITLE
A warning is missing when creating a template

### ISSUE THREAD

**Issue by Jacques57000** [klinker-apps/messenger-issues#770]
**Describe your request:**
By continuing to discover the functions of PULSE, I tested the creation of template (interesting idea). Entering template content on a Google keyboard allows you to embed text and emojies. But if we try to integrate a GIF, the application automatically switches to message entry, without warning that we left the template creation mode.
I note that curiously, it is then asked the recipient while the creation of a template seems to be able to be done only when entering an SMS ...

**Describe alternatives you've considered:**
Two proposals:
- The creation of the template could be done from the menu, like Signatures
- If the user tries to integrate incompatible elements with a template, the application signals it but does not engage another process

**Comment by klinker24** [comment]
I'm not going to move it to the settings menu. Template creation is going to be done in the context of where they are used. They are not the same as signatures, nor do they have the same design and implementation. 

Thanks for letting me know on this.

**Comment by Jacques57000** [comment]
Okay, I understand your logic. So there is more to manage the warning, I think. It is indeed disturbing to leave the mode "Template" as currently.

**Comment by klinker24** [comment]
Or you could just not use the attachments. I don't think "disturbing" is at all the right way to describe a small, one-off, bug.

It honestly doesn't seem like that huge of an issue. Pulse has had templates for over a year and no one else has brought up this issue.

**Comment by Jacques57000** [comment]
It's true that after the first surprise, I do not get trapped a second time !
My goal was only to bring you an artifact knowing that sometimes a small problem can hide another, more worrying one.
But you probably have other cats to whip (I do not know if this French expression makes sense in English ...).

**Comment by klinker24** [comment]
This is no longer relevant. Tapping a GIF or sticker from Gboard will now prompt you to open the compose screen. It doesn't paste anything into the message field.
