### ISSUE TITLE
Can you please add a feature for Dual Sim card support ?  can see belongings of the message 

### ISSUE THREAD

**Issue by cougar999** [klinker-apps/messenger-issues#771]
Hi there,

I know we can't select sim card for sending messages from the desktop client,  but can u add a feature to display which card received the message?

Like Person A sent a message "hello" to Sim 1,  then I can see a small label "sim1" near the message or somewhere of the message on the desktop client.

Can it work?

Thanks.

**Comment by klinker24** [comment]
Just tap any message, the SIM stamp is right next to the timestamp on dual sim phones.
