### ISSUE TITLE
The dual sim card support has a issue....

### ISSUE THREAD

**Issue by cougar999** [klinker-apps/messenger-issues#772]
![20181018205305](https://user-images.githubusercontent.com/1323406/47146820-90fd5f00-d318-11e8-81b3-d79ce3524975.png)

Received a message on sim card 2, after replying the user sent another message to sim card 2.

I'm using the Redmi Note 5A, Android version 7.1.2 N2G47H.

Also, I didn't find the sim card note on the windows client.

![20181018162506](https://user-images.githubusercontent.com/1323406/47133052-ae1f3700-d2f2-11e8-9831-2cebb39d13cd.png)

_Originally posted by @cougar999 in https://github.com/klinker-apps/messenger-issues/issues/771#issuecomment-430879628_

**Comment by klinker24** [comment]
This topic contains the request to show the SIM information on the web/desktop apps: https://github.com/klinker-apps/messenger-issues/issues/649

Pulse is going to report whatever SIM card received the message. When the message comes in, Android will tell me which slot it came in to, and provides an interface to read which number is associated with which slot. If it didn't show the correct one, unfortunately there will be nothing on my end that can be done about this
