### ISSUE TITLE
Edit contacts on desktop app

### ISSUE THREAD

**Issue by thumper01** [klinker-apps/messenger-issues#775]
I have several users and not everyone has access to the physical phone to add and edit contact info. 

- It would be great to be able to edit contacts from the windows app.

**Comment by klinker24** [comment]
Sorry, at this point, that isn't planned. Pulse really isn't a contact management system and doesn't have the integrations required for this. Pulse is going to just remain a messaging app, and it's online functionality will remain in that scope. You can always just go to contacts.google.com and manage the contact information from there, though.

For example, when adding a new contact from the Android app, all it is really doing is opening the Contacts app on your phone.
