### ISSUE TITLE
New Contact not available in compose

### ISSUE THREAD

**Issue by robertjory** [klinker-apps/messenger-issues#779]
I added a new contact in MS outlook exchange a day ago.
It shows up OK in my native android phone contacts
It shows up when composing a message in PULSE on my Android 
It does not show up when composing a message in PULSE on my desktop.
I don't see any kind of refresh contacts list on the desktop as there was in MighytText.

**Comment by klinker24** [comment]
When searching for contacts, the last item in the auto complete is "can't find your contact", which links to this topic: #740 

That topic has information on how to refresh the contact list.
