### ISSUE TITLE
Color profile of display changes when viewing MMS images

### ISSUE THREAD

**Issue by aizakow** [klinker-apps/messenger-issues#780]
**Device with issue:** OnePlus 6T (ONEPLUS A6013)
**Primary device:** OnePlus 6T (ONEPLUS A6013)
**App version:** Ex: v4.2.1.880

**Describe the bug:**
Just got a OP6T, and immediately noticed an issue where as soon as I open an image in a group MMS conversation, the color profile of the entire display changes to be much darker and lower saturation. It immediately switches back when I leave full screen view. The color change visibly affects the whole display e.g. the app itself is still visible as the zoom-in animation plays and it effects everything, not just the image. I am coming from a Pixel 1 XL, which did not have this issue. I do not really have a means of testing for this on any other devices.

**Steps to reproduce:**

1. On a OnePlus 6T, tap on any image in a conversation

**Expected behavior:**
I would expect the image to display normally

**Screenshots:**
The issue is not captured in screenshots. Any screenshot I take ends up displaying the colors correctly.

**Additional information:**
I have tried changing the system color profile in settings from "default" to sRGB and DCI-P3. The results are not identical across color profiles, but the general trend of getting darker and less saturated is consistent.

**Comment by klinker24** [comment]
I use this, and have since the app was created. I haven't had anyone else reach out about this, sure it isn't an issue with your devices screen?

https://developer.android.com/training/wide-color-gamut/

I definitely have plenty of users on that phone.

**Comment by klinker24** [comment]
I am just going to disable the wide color gamut, for OnePlus phones. They must have messed something up with their screen configuration.

**Comment by aizakow** [comment]
Seems like a reasonable solution. FWIW I have now tested it on a second OP6T and the issue persists, again across every screen calibration setting. I have not noticed the issue anywhere else, but I have not done a thorough check.

Anyway, disabling the feature seems like an easy enough solution, and better than me having to go to alternate apps to view MMS attachments correctly.

Thanks.

**Comment by aizakow** [comment]
Just wanted to leave a quick note to thank you for the extremely prompt turnaround on this. Got an update yesterday that fixed this issue. Great work! I'll stop commenting now.
