### ISSUE TITLE
Add Contact Image in Conversation View

### ISSUE THREAD

**Issue by MattB1994** [klinker-apps/messenger-issues#782]
- [X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.
- [X] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.

Request:
Adding the Contact's image to the conversation view, either next to each message similar to what Android Messages does, or beside their name in the header of the conversation, similar to what Textra does.

**Comment by klinker24** [comment]
#45 is what we went for around this. It is not currently planned to put them in the message list, that isn't the style that we are going for.

#159
