### ISSUE TITLE
Message notifications are often showing completely blank

### ISSUE THREAD

**Issue by DarkWolf7** [klinker-apps/messenger-issues#783]
I haven't found any specific cause, but I am often having a case where notifications are showing up with just a contact name and nothing else. This happens with both sms/MMS messages with a single contact and group messages.

**Comment by DarkWolf7** [comment]
Sure will, thanks. I'll grab a screenshot next time it happens. It started
just a few releases ago. Is there any debug logging that I can turn on as
well?

**Comment by DarkWolf7** [comment]
Here are some samples. Really don't know how to reproduce it, as it seems almost entirely random. 
Notification, unexpanded:
![point blur_nov152018_095114](https://user-images.githubusercontent.com/16918633/48560585-24946200-e8bc-11e8-8a08-82c6d9aeb9bd.jpg)
Same one expanded. Note the text vanishes when the notification is expanded. 
![point blur_nov152018_094935](https://user-images.githubusercontent.com/16918633/48560651-57d6f100-e8bc-11e8-9ee4-2dbd32894919.jpg)
A couple of stand alone notifications. Note that these don't even show the names of the senders:
![screenshot_2018-11-15-08-22-34 2](https://user-images.githubusercontent.com/16918633/48560725-7b9a3700-e8bc-11e8-868d-136d2ba1e355.png)
![screenshot_2018-11-14-18-17-35 2](https://user-images.githubusercontent.com/16918633/48560761-92408e00-e8bc-11e8-8fd1-460fa00c4a86.png)

**Comment by klinker24** [comment]
Sorry, this is definitely something on Android's side, not mine. I do not control how notifications look. I simply provide the text to fill the notifications with.

You could try forcing Android to use the legacy notification style, by unchecking the "show conversation history" option in settings.

Unfortunately this is not something I will be able to affect on my side.
