### ISSUE TITLE
Always Show Timestamp?

### ISSUE THREAD

**Issue by online-stuff** [klinker-apps/messenger-issues#784]
Is it possible to have an option in setting for always displaying the timestamp?

The feature of tapping/clicking the message to display the timestamp is a great start, but it isn't saved as 'show' after tapping the message.

So, can a display setting/option be added that will display the timestamp on all messages, all the time?

**Comment by klinker24** [comment]
Sorry this is not planned. For more information one when timestamps are shown and when they are hidden, there is a "timestamp" topic, on my help page

https://messenger.klinkerapps.com/help
