### ISSUE TITLE
Recently added contact not updating, still showing number

### ISSUE THREAD

**Issue by DavidMoksha** [klinker-apps/messenger-issues#785]
I've noticed this several times.
1. Send a text message to a phone number for which I have no contact
2. Add a contact for that number (I've added it to a Google account)
Several days later, pulse is still showing the number and has not updated to pick up the name.
Note, I have about one thousand contacts in Google.

**Comment by klinker24** [comment]
Open the conversion to refresh the title. If it isn't reflected on the conversation list, just close the app.
