### ISSUE TITLE
Interface Opening View

### ISSUE THREAD

**Issue by fotodok** [klinker-apps/messenger-issues#787]
Perhaps I'm missing something...

When I open Pulse, it often opens in a previous conversation. Is there a way for the default to be always open in the conversation list view? Also, when it does open in conversation list view it is often not at the top of the list. I'd like to always be at the top looking at the chronologically most recent text...

**Comment by klinker24** [comment]
Android, as a platform, is designed to hold the app state across different sessions. This is not something that I want to change for Pulse, sorry. When you return to the app from doing something else, Pulse should be where you left it. This is the typical and expected behavior of any application.
