### ISSUE TITLE
Notification dot with android 8.0 not working

### ISSUE THREAD

**Issue by Deaninvic** [klinker-apps/messenger-issues#793]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [x] I have verified that this is something that is reproducible.

**Device with issue:** Ex: MacBook Pro on MacOS 10.12, running Chrome v54
**Primary device:** Ex: Pixel XL on Android 9
**App version:** Ex: v4.1.5

**Describe the bug:**

**Steps to reproduce:**

`... more steps`

**Expected behavior:**

**Screenshots:**

**Additional information:**
Add any other context about the problem here. Device configuration, unique cases, anything that you think may be relevant.

**Comment by klinker24** [comment]
The notification dot is completely out of Pulse's control. Notification dots are controlled by your launcher and system. They just run off of active notifications.

If they aren't working, you can verify that you have them turned on through the notification channel settings in your system settings. Otherwise, you would have to reach out to whoever makes your launcher

**Comment by Deaninvic** [comment]
Hello
The notification is working on other apps okay and is turned on for Pulse. It is the only app not working.
The launcher is standard Motorola.

Dean B, Victoria BC

________________________________

**Comment by Deaninvic** [comment]
Hello
 So I did a factory reset on my moto Z2 Android 8.0 phone and set it up as new.
The notification dot works on the phone and google msg app, However it does not work on the pulse app.

Dean
Victoria BC
Sent from my iPad

On Nov 26, 2018, at 4:25 PM, Luke Klinker <notifications@github.com<mailto:notifications@github.com>> wrote:


I have no control over notification dots. No developers do, sorry.

**Comment by klinker24** [comment]
I'm sorry, I  cannot affect the notification dot, as I have said. You will have to reach out to someone else. I cannot provide help with feature of your launcher. 

My notification dots work just fine, across all of my devices.
