### ISSUE TITLE
Toolbar Notifications won't clear macOS

### ISSUE THREAD

**Issue by kopechcr** [klinker-apps/messenger-issues#794]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [x] I have verified that this is something that is reproducible.

**Device with issue:** iMac Retina 5K Late 2015, macOS 10.14.1; Chrome Version 70.0.3538.110 (Official Build) (64-bit)
**Primary device:** Pixel 3, Android 9, Nov Patch
**App version:** macOS v 3.1.2

**Describe the bug:**
Conversations are all read, but toolbar notifications says there are 12 unread conversations.

![screen shot 2018-11-27 at 11 30 50 am 2](https://user-images.githubusercontent.com/20321690/49096547-c317b000-f238-11e8-8282-b318a2e3e0ef.jpg)

![screen shot 2018-11-27 at 11 30 55 am](https://user-images.githubusercontent.com/20321690/49096551-c57a0a00-f238-11e8-8032-51024321fd05.png)

**Comment by klinker24** [comment]
I have tips around the badges and how to clear them, on my help page: https://messenger.klinkerapps.com/help

> If this badge is showing that you have an unread conversation and you do not think that you do, you can mark all conversations as read from the phone app. To do this, hit the double checkmark button on each of the date sections within the conversation list. If you have done this, it is still showing unread messages, and you are sure there aren't any unread messages on the phone app, you can use the Refresh Account option on the phone app.
