### ISSUE TITLE
Not receiving notifications on Tizen OS

### ISSUE THREAD

**Issue by AEM7** [klinker-apps/messenger-issues#797]
Notifications are going through the default messaging app instead of Pulse on Galaxy Watch. Not sure if this is intended or if Pulse is supposed to handle notifications once installed.

And thanks for the making the app for Tizen!

**Comment by klinker24** [comment]
The tizen app will mirror notifications through the phone, like any other app on your phone. Notifications are not and will not be generated on the watch.

You have to configure the watch to mirror the notifications from the phone, from the Galaxy Wear app on your phone. This is standard behavior for tizen apps, and outside of the control of what my app provides.

https://messenger.klinkerapps.com/overview/platform-tizen.html
