### ISSUE TITLE
macOS app won't refresh automatically

### ISSUE THREAD

**Issue by kopechcr** [klinker-apps/messenger-issues#798]
**Device with issue:** iMac 5K Late 2015 running 10.14.1
**Primary device:** Pixel 3 on Android 9
**App version:** macOS 3.1.2

**Describe the bug:**
Conversation list doesn't auto-refresh on send or after receiving messages. Must be forced to refresh using the circle-arrow button

**Expected behavior:**
Messages populate and conversations refresh automatically

**Additional information:**
I have already re-synched my account, and messages multiple times on the Android app. This has been an issue for some time.

**Comment by klinker24** [comment]
It is likely an issue with your network, with nothing to do with Pulse. Some networks will prevent a web socket connection from being activated. You can right click on the page and go to the "inspect" menu to see what errors come up in the console.

If it is a network issue (404, connection refused, ect), there will be nothing I can do for you, on my side.

**Comment by kopechcr** [comment]
So, that would explain this:

![screen shot 2018-11-28 at 9 53 10 am](https://user-images.githubusercontent.com/20321690/49159871-75ac4900-f2f3-11e8-8410-81bdc98047ca.jpg)

If so, oh well. At least we know. Thanks for following up!

**Comment by klinker24** [comment]
If you can copy the URL for the request that is failing, I can tell you what the issue is.

**Comment by klinker24** [comment]
It seems like you need to log out and back in.

There is no Pulse account for the ID provided in that URL. I cannot imagine that you are seeing any conversations come up at all, when you open the website.

**Comment by kopechcr** [comment]
Odd...I logged out and back in and here's the link:

https://api.messenger.klinkerapps.com/api/v1/accounts/settings/?account_id=1c2f4e0b58b1ea847ed98643ac48afc3831fc343d0b39b731fdbd8bc0eb78d01

It's the same, as you can see. I also logged out and in on the web app.

**Comment by klinker24** [comment]
Please tell me your email so that I can get more information on your account. I cannot do anything else with the information provided.

**Comment by kopechcr** [comment]
my bad 

kopechcr@gmail.com

**Comment by klinker24** [comment]
Thanks, that is more helpful for me. I can confirm from the logs that I am seeing the request to start the web socket, and that it is being accepted. It looks like that is the point where your network is losing it. It should start to show some pings if it is active, and those never come in. It just throws up another request to start the connection, after a backoff period.

Unfortunately, it seem as though the issue is on your side, whether with the network configuration, firewalls, or restrictions on the machine.

**Comment by kopechcr** [comment]
Oh well. Thanks for the update and the great work on the great app!
