### ISSUE TITLE
Cannot Remove or Replace Contact Photo

### ISSUE THREAD

**Issue by earthnugs** [klinker-apps/messenger-issues#799]
As title says, I'm trying to alter a contact photo, but it's stuck on the first image I selected in my contact manager. Removing that photo or selecting a different one is not reflected in the app, even if I select the "resync contacts" option in the Pulse app settings. I also tried deleting and reinstalling the app and a reboot, but that also didn't help. Is there an easy way to refresh it that I'm missing or something else I could try?

**Comment by klinker24** [comment]
Clear the app cache through system settings

https://messenger.klinkerapps.com/help
