### ISSUE TITLE
Images not always synced to secondary devices

### ISSUE THREAD

**Issue by klinker41** [klinker-apps/messenger-issues#8]
**Device with issue:** Nexus 6P running Android 7.0
**Primary device:** Nexus 6P running Android 7.0
**App version:** 1.0.180
**Steps to reproduce:**

(inconsistent)
1. Send a picture from either your phone or tablet
2. View that message on the other device and see if the image synced

**Additional information:**

Sometimes an image doesn't seem to get synced to the tablet and the message box just shows a blank message. When looking at the message data, there is a file path for it but the file either doesn't exist or doesn't hold anything.

This seems to happen with larger images and data. Looking at Firebase, the some of the images with issues upload with a size of around 50 bytes, which obviously isn't correct. There is potentially some type of upload issue that goes uncaught in the android client. Could also be due to slow internet.

**Comment by klinker24** [comment]
This should fix this issue. It improves the async nature of the firebase upload and download methods.

It also improves GIFs. GIFs were getting downloaded correctly, but they always had trouble playing in the actual message list. I took that out for now and play them in the image viewer instead :/
