### ISSUE TITLE
Improve some color schemes

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#80]
**App version:** 1.2
**Additional information:**

Some of the color schemes are not great, for example, the lime is a bit weird, as well as the light grey.

**Comment by klinker41** [comment]
Some colors that need changed:

Lime:

![screenshot_20160909-102717](https://cloud.githubusercontent.com/assets/4501322/18407404/6bf5333e-76c4-11e6-9440-4bbf358e4de1.png)

Grey:

![screenshot_20160909-102815](https://cloud.githubusercontent.com/assets/4501322/18407405/7130c610-76c4-11e6-90d6-c12ee10a791c.png)

Orange:

![screenshot_20160909-102730](https://cloud.githubusercontent.com/assets/4501322/18407407/78475b12-76c4-11e6-9850-85b2adebc627.png)

**Comment by klinker41** [comment]
Updated the lime, grey and yellow themes with a little better colors. Also added an all black theme.

![device-2016-09-09-200704](https://cloud.githubusercontent.com/assets/4501322/18407568/24daf43e-76c9-11e6-8c7e-1b427c531235.png)

![device-2016-09-09-200722](https://cloud.githubusercontent.com/assets/4501322/18407569/2a9184ec-76c9-11e6-9193-f0333e7ef8f1.png)

![device-2016-09-09-200648](https://cloud.githubusercontent.com/assets/4501322/18407571/3f5a14c0-76c9-11e6-8a0d-90e6bc80f90a.png)

![device-2016-09-09-200741](https://cloud.githubusercontent.com/assets/4501322/18407572/438033b8-76c9-11e6-9be4-d6d7809eecdf.png)
