### ISSUE TITLE
Full Datetime sim stamp for messages missing sometimes.... 

### ISSUE THREAD

**Issue by 4evermaat** [klinker-apps/messenger-issues#800]
In a thread, if a date is less than 1 week old, it will only state the day of the week.

`Tues 08:38 SIM xxxxx`

Buy it should say:

`Tues Nov 25, 08:38 SIM xxxxx`

![screenshot_20181208-201203_1](https://user-images.githubusercontent.com/830306/49686356-c575e600-fb25-11e8-916d-e9bb4685b062.jpg)

In fact, every message, including older ones, should have `weekday Month, day #, time, sim #`
The coding is already there, just ability to apply it to every message. 

I sometimes must go to a calendar to see the date (or the day of the week) .  But that is unnecessary as the date/day of week should be clearly printed.  Message dates should not be ambiguous. 

Also, correct, full date/time/sim stamps should be for **both** incoming and outgoing messages. 

I cannot find it in the options menu.  It was annoying enought after a while to report it. 

---

Possibly related #351, #137 . Date time stamps should have no ambiguity.   It's one thing to have a different style of showing the stamps, and another thing to not have an option for full info. Maybe after tapping the full info can be revealed. 

---

Also, when the year changes, the last message that has the previous year and the first message of the new year should show the year for clarity.

**Comment by klinker24** [comment]
Sorry but this isn't something that I plan to change. You can long click different messages and hit the "info" button to get the full timestamp. 

As messages get older, the timestamp will show increased information to help you place them, such as date instead of day-of--the-week
