### ISSUE TITLE
Reading message on pc doesn't clear notification from phone

### ISSUE THREAD

**Issue by 11e01** [klinker-apps/messenger-issues#801]
**Device with issue:** Lenovo Yoga ,Windows 10, Firefox 64
**Primary device:** Moto E4 on Android 7.1.1
**App version:** 4.2.3.2288

**Describe the bug:**
When I view a new message in the destop client or the web browser, the notification doesn't clear from my phone

**Steps to reproduce:**

1. Receive new message
2. open windows client or desktop browser
3. click on conversation

**Expected behavior:**
notification on android should go away, as the conversation is read

**Comment by klinker24** [comment]
I am not able to reproduce this and haven't had anyone else mention issues, so I will probably need more of a description. Does this happen every time, and in what cases does it happen?

**Comment by klinker24** [comment]
Sorry I am going to have to close this as no response. Please feel free to comment back with more information and I can re-open it.
