### ISSUE TITLE
SMS delay doesn't work outside of primary device

### ISSUE THREAD

**Issue by AllanWang** [klinker-apps/messenger-issues#802]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [x] I have verified that this is something that is reproducible.

**Device with issue:** Macbook (problem shouldn't be device specific)
**Primary device:** OnePlus 6t
**App version:** 4.3.2.2298

**Describe the bug:**

With sms delay enabled, sending an sms through the chrome extension still sends immediately.

**Steps to reproduce:**

1. Set sms delay to 5 seconds
2. Open chrome extension and text self

**Expected behavior:**

Extension should allow the option to delay the sms

---

Note that when I tried the first time, there did seem to be some loading bar in the view. However, I didn't see a way to cancel it. Sending test sms messages again happened immediately.

**Comment by AllanWang** [comment]
as a note, this does work on a secondary android device. So just on other platforms

**Comment by klinker24** [comment]
Duplicate https://github.com/klinker-apps/messenger-issues/issues/725

**Comment by AllanWang** [comment]
My bad. Didn't show up in the [search](https://github.com/klinker-apps/messenger-issues/issues?utf8=%E2%9C%93&q=sms+delay+).

If I have time and am able to I may take a look at this during my winter break.
