### ISSUE TITLE
View an emoji in a web link

### ISSUE THREAD

**Issue by Jacques57000** [klinker-apps/messenger-issues#804]
- [ ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [ ] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [ ] I have verified that this is something that is reproducible.

**Device with issue:** Huawei P20 Pro : CLT-L09
**Primary device:** Android 8.1.0
**App version:** 4.3.2.2298

**Describe the bug:**
Hello
I sent a link to a page of a forum. This page contained an emoji and the result is amazing on my device. [Here is the link](Http://forum-jardinier-bio.com/thread-628-post-4655.html#pid4655) :

**Screenshots:**

![screenshot_20181216-093948](https://user-images.githubusercontent.com/44142041/50051674-dff82280-0116-11e9-8dea-dfbaf4c70999.jpg)

**Comment by klinker24** [comment]
Thanks, I am going to move this over to the repo that manages the link previews: https://github.com/klinker41/article-android/issues/30
