### ISSUE TITLE
Improve scheduled messages visibility

### ISSUE THREAD

**Issue by ssssamstrup** [klinker-apps/messenger-issues#805]
Problem: The planned messages feature is genius and works nicely, but sometimes I forget to use it and my friends (who haven't figured out how to put their phone on silent at night) get annoyed when I send them messages at night or late in the evening.

Feature idea: Be able to set a schedule for when Pulse should prompt me and ask if I want to send the message as a planned message or right away.

Optimally you should be able to set and change the schedule to your preference.

**Comment by klinker24** [comment]
Have you tried Pulse's delayed sending feature? It is really designed for your type of use case. 

You can enable it from advanced features, within the Android app. When it is on, and you press the send button to send a message, it will start a timer. That timer gives you time to edit the message, second guess yourself, or cancel it entirely. While it is more of a generic feature than the specific one that you are suggesting, it seems to me that it would fit your use-case and give you the second chance that you are requesting.

I do not know if I would implement a specific feature like this one, to be honest. I don't think that very many people would use it. Scheduled messages are already a very under-used part of the app.  Only about 5% of users have ever even visited the scheduled messages screen, or clicked that button from within a conversation.

**Comment by ssssamstrup** [comment]
I use that feature, but I simply forget the planned messages feature since
it's hidden in the menu. Sometimes when I've written planned messages in
the night to be send later next day, I've forgotten it and written before
the planned text has been send, because there isn't any notice of the
planned message in the message thread.

Maybe what could be useful was a more visible implementation, so users are
aware of the feature? Cause it's goddamn useful, but a bit hidden away.

Is the planned messages feature enabled by default for new users btw?

-Sune

ons. 19. dec. 2018 00.49 skrev Luke Klinker <notifications@github.com>:

**Comment by ssssamstrup** [comment]
If it was more visible it would also eliminate the need for the prompt I
suggested.

All the best, Sun

ons. 19. dec. 2018 08.44 skrev Sune Amstrup <suneamstrup@gmail.com>:

**Comment by klinker24** [comment]
I am going to change this request to be more about the visibility of the scheduled messages, then.

**Comment by ssssamstrup** [comment]
To add further to the idea, some ways to make it more visible:

1. It could be nice if you could write a message, then hold the send button down to delay and get a popup asking you to pick a date and time for sending.

2. When a message is planned, either show the message in the conversation with the planned send time, or show a banner telling you there is planned messages for the conversions. fx. View planned messages.

**Comment by RLCassidy** [comment]
When I used Chomp as my SMS app I used the schedule-a-message feature daily as it's scheduling feature was up front as a clockface https://photos.app.goo.gl/R6qHqTrtqseEVf577 I moved from that app for multi-platform texting (a feature I'm testing between Pulse & Pushbullet & Join).

There are so many times where I want to schedule a message for the next morning, and I forget that it is a feature of Pulse.

**Comment by klinker24** [comment]
@RLCassidy I don't think that that implementation is much different than what Pulse has. It isn't as though that button is immediately available to you or more exposed than what Pulse has. It is only available after touching another button. Pulse is the same way. You tap the three dot overflow button and there is an option to "schedule a message".

**Comment by klinker24** [comment]
I opened up #825 with more information and implementation details on what I would like to do here. I am going to close this issue, in favor of that one.
