### ISSUE TITLE
message timestamp

### ISSUE THREAD

**Issue by Jacques57000** [klinker-apps/messenger-issues#807]
- [ ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.
- [ ] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.

Device with issue: Huawei P20 Pro : CLT-L09
Primary device: Android 8.1.0
App version: 4.3.3.2302

**Describe your request:**
Hello
I regret not seeing the timestamp of all messages but only some. I have not found the rule that you apply, however the one you give in a response from a previous request (# 365) is not respected: "It will display timestamps if the message is more than 15 mins newer than the previous message ". For proof the attached screenshot: the screen shot was made at 17:12, the first message sent at 15:34, the next at 16:37 and the last one at 16:54.
Would it be possible to do better?
Thank you in advance.

![capture](https://user-images.githubusercontent.com/44142041/50296828-9d6a7900-047b-11e9-8a8f-a3d78f9039fd.JPG)

**Comment by klinker24** [comment]
You can simply tap any message if you want to see the timestamp.

https://messenger.klinkerapps.com/help

**Comment by Maxximus007** [comment]
Although it is true the you can easily find the timestamp,  it makes it difficult to have them shown in a screenshot or printout for that matter. Besides that, the 15 minute rule is irregularly respected.

So please reconsider this, at least as an option to always show the timestamp below the message.
