### ISSUE TITLE
Pins Disappeared

### ISSUE THREAD

**Issue by ShayzBardo** [klinker-apps/messenger-issues#808]
12/27 suddenly lost pin categories (now by date again) and previous message histories for conversations both on phone app and desktop app.  Jumped back to my old text app to see those old conversations.

**Comment by klinker24** [comment]
"My account" -> "Resync messages".

Pulse wouldn't have deleted them automatically. It might have happened in your pocket or something.

**Comment by ShayzBardo** [comment]
Did not work.  Messages still gone.
"Pin" option also gone, it seems.
__________________

Shay Jones
        e-mail: ShayzBardo@gmail.com
	cell/home:  412-592-7880
__________________

**Comment by klinker24** [comment]
That option would go through the initial import again. Anything that is in your shared database on the device would be imported, just like when you set it up the first time. You would have to repin the conversations that were deleted.

**Comment by ShayzBardo** [comment]
OK, but conversation histories are gone.  Your reset suggestion did not work.
__________________

Shay Jones
        e-mail: ShayzBardo@gmail.com
	cell/home:  412-592-7880
__________________

**Comment by klinker24** [comment]
Then they were deleted from the shared database too.. There won't be a way to recover them if they were deleted from the device. You either deleted them in Pulse, or something else deleted them and they propagated to Pulse

**Comment by ShayzBardo** [comment]
I can see the same conversations full history on my Verizon Messenger App.  So they are on some shared database
__________________

Shay Jones
        e-mail: ShayzBardo@gmail.com
	cell/home:  412-592-7880
__________________

**Comment by klinker24** [comment]
That app has its own database, it doesn't read from the shared database.

**Comment by ShayzBardo** [comment]
Interesting that you accuse me of erasing the database since I was doing nothing with the app and it just wiped itself.  I guess you just assume it must be water-ware error.
__________________

Shay Jones
        e-mail: ShayzBardo@gmail.com
	cell/home:  412-592-7880
__________________

**Comment by klinker24** [comment]
The app won't delete conversations automatically. Enjoy the rest of your day.
