### ISSUE TITLE
Every 5 minutes reminder to send a new text!!!

### ISSUE THREAD

**Issue by cb301** [klinker-apps/messenger-issues#811]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [x] I have verified that this is something that is reproducible.

**Device with issue:** Samsung g9+
**Primary device:** Ex: Android
**App version:** Ex:

**Describe the bug:**
App keeps suggesting to send a new text message. Don't need extra notifications for anything. Need to turn off!

**Steps to reproduce:**

`... more steps`

**Expected behavior:**

**Screenshots:**

**Additional information:**
Add any other context about the problem here. Device configuration, unique cases, anything that you think may be relevant.

**Comment by klinker24** [comment]
You likely turned on the "Quick Compose" notification in the advanced features. It is off by default. 

That is the only time that the app would give you a notification to create a new message.

https://messenger.klinkerapps.com/help

**Comment by cb301** [comment]
Thank you. That was annoying.  Very happy with the app. 
⁣CB
