### ISSUE TITLE
Add additional swipe actions 

### ISSUE THREAD

**Issue by abhubbart** [klinker-apps/messenger-issues#812]
First off, great app! Would be awesome to have some additional options when swiping. Move to folder would be awesome, once swiped, it would prompt with all folders to choose one.

**Comment by abhubbart** [comment]
Appreciate the quick response.

Yeah, found the mass move after I sent this.  I would recommend removing
conversations that are already in another folder from the list as opposed
to noting they are in another folder, would make the process cleaner, IMHO.

**Comment by klinker24** [comment]
Sorry, I don't really agree. By opening that up and allowing users to select those conversations, it will give them the impression that conversations can be put in more than one folder. That really isn't how I want the folders to work, I really just want each conversation to be able to be put in a single folder. 

So, if I opened that up, I would have to provide a warning/confirmation dialog to the users, which kinda defeats the purpose of this view (to quickly organize the conversations with a single click). It would take away from that speed. You can always open the individual conversation's settings menu, to switch the folder from there.
