### ISSUE TITLE
Notifications and Gear S3 / HTC Vive

### ISSUE THREAD

**Issue by z0oinks** [klinker-apps/messenger-issues#816]
Scenario 1: No unread text notifications on phone (Galaxy S8, T-Mobile). Get text message.

- Gear S3 Outcome: Vibrates. If raise-to-wake, new text message is shown.

- HTC Vive (using Zephyr app): Notification is shown with contents of new message.

Scenario 2: One or more unread text notifications on phone. Get another text message.

- Gear S3: Does not vibrate. If raise-to-wake because I felt my phone vibrate, my oldest unread message is shown.

- HTC Vive: Notification is shown listing all missed messages. When that notification disappears, each missed text appears as its own notification, one after the other.

I believe that scenario 2 should not occur. If there are multiple missed messages, my watch should still be vibrating and showing the newest message. I included the part with the HTC Vive as it may be related in the way notifications are handled.

If you need any more info, please let me know.

**Comment by z0oinks** [comment]
Sorry if it was kinda confusing, I wasn't sure how to explain it.

But yeah, both things in scenario two were bugs. When I have multiple unread messages, the Vive gets sent a list like "[Person 1] sent you (blah blah blah), [Person 2] sent you (blah blah)". Once that notification disappears, I get a notification saying "[Person 1] sent you (blah blah)", and then once that disappears, a notification saying "[Person 2] sent you (blah blah)"

I was thinking that it should only be forwarding the newest notification, but on both the Vive and the Gear, it looks like it's sending *all* unread notifications again.

**Comment by klinker24** [comment]
Pulse isn't generating the notifications after the original is dismissed. The original is the messaging style notification that I referenced. 

I will not be able to do anything about the watch and the notifications that it receives or alerts you for. That is up to Samsung, as discussed.

**Comment by z0oinks** [comment]
I'm saying if the original notifications aren't dismissed.

I'm probably doing a horrible job explaining this, I really do apologize. Let me try sending a video, maybe that would explain it

**Comment by z0oinks** [comment]
Here's a video: https://streamable.com/feja0

When I send the first text, my watch vibrates and shows the message. When I send the second text, my watch does not vibrate, and my watch pulls the first message up again.

 I wanna point out that this isn't just resuming the previous screen, as this happens even if I use my watch between the texts. It will also pull up the first text even if I get a third, fourth, fifth, etc text message.

**Comment by klinker24** [comment]
Sorry I am not going to be able to affect that. That is your watch choosing which of the grouped notifications to show. When you have multiple unread conversation notifications, they are grouped together.

**Comment by z0oinks** [comment]
Alright, no problem then. Just wasn't sure if it was expected behavior or not.

Thanks!
