### ISSUE TITLE
Read message becomes unread in message list

### ISSUE THREAD

**Issue by lament** [klinker-apps/messenger-issues#82]
**Device with issue:** Nexus 6P on 7.0
**App version:** 1.2.293

**Steps to reproduce:**

1. Receive a message
2. View it within Messenger
3. Swipe up on the message to return to the list of messages
4. Notice that the current message is marked as read (not bolded, no dot)
5. Scroll down your list of message so the current read message is off the screen, then immediately scroll back up to the top of the message list
6. Notice that message you just read is now bolded with a dot, indicating a new message that you haven't read

This can't be reproduced all the time, but also happened with the last version.

**Comment by klinker24** [comment]
Please try on the latest version of the app, it was released tonight and this has been fixed.
