### ISSUE TITLE
Assign and sort using Groups

### ISSUE THREAD

**Issue by nhwalton** [klinker-apps/messenger-issues#820]
As a user with a lot of group chats, I would like to be able to assign a certain Group Label to a message thread from within the app and view that label (and search) from my list of messages so that I can tell if the members in a group thread are the same as the label.

**Comment by klinker24** [comment]
I don't really understand your request, sorry. You can already name group conversations, from their settings page

**Comment by nhwalton** [comment]
Looks to be user error on my part. Sorry about that. Was testing with a group that had one extra user sneaking in that was making the group name not populate.
