### ISSUE TITLE
Adding photo sends 2 copies of the same image

### ISSUE THREAD

**Issue by maddentim** [klinker-apps/messenger-issues#824]
This is a little strange and maybe something you will have to ignore, but I thought I should report it anyhow. 

I have a oneplus two running a pixel clone custom rom with Android 9. If add a photo with the default camera app, it works fine. If I use my preferred camera (Open Camera) as the default camera app, then when I add a photo to a message, Pulse send 2 copies of the photo. 

Maybe it is a problem with the ROM or the camera app...

**Comment by klinker24** [comment]
I just tried this and I am not seeing the same thing, with that app. It seems to be something with your ROM
