### ISSUE TITLE
Improve scheduled messages visibility

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#825]
**Describe your request:**
I want to expose currently active scheduled messages, as well as give the user a quicker way to schedule messages from within a conversation.

**Implementation Todo:**

* [x] If a conversation has a message that is scheduled for it, add a button to the left of the "attach" button. 
  * Clicking that button will open a menu that is similar to Pulses attach menu, but it will just contain the scheduled messages for the conversation
  * If the device is dual SIM... I don't want to show that button. that would make 3 buttons on the left of the text entry, which is less than ideal.
  * The user should have the option to disable this menu, though. Within that list, there will just be a button: "not interested in seeing scheduled messages here? Click to turn it off."
  * Pressing that will remove this scheduled messages view.
  * In terms of the actual implementation, I don't think I need to do anything fancy here. 
    * I can just work it in as a new element (-1) or something into the `AttachmentInitializer` flow. That will allow me to re-use the attachment view, animations, ect. There is really no reason to re-do any of that.
    * I can probably just re-use the scheduled messages fragment that I already have.
* [x] Long clicking the send button will allow the user to schedule the current message, instead of send it immediately.
  * Long clicking used to send the message without the signature. If the user has a signature, present them with the option to schedule the message or send without the signature
  * I will want a way to tell the user about this new functionality, too, the first time that they send a message.
  * A banner coming up below the message entry, after they hit the "send" button, should work.

In terms of implementing this:

* Phase 1: 
  * long clicking the send button will prompt for a scheduled message
  * Display the scheduled message button, as noted in the first item above
* Phase 2 (if I feel we need it, after implementing phase 1)
  * Notify the user of the long-press-to-schedule functionality, in some way
  * Allow the user to enable/disable displaying that scheduled message button within the conversations

**Comment by ssssamstrup** [comment]
Sounds like a good and thoughtful way to implement the changes as discussed in #805 .

If the user disable the messages view, there should be a way to reset or re-enable the option in options. :)

**Comment by klinker24** [comment]
This is done. If I feel that phase 2 is necessary, I will open a new issue for that, down the road. At this time, I do not believe that it is necessary or would add much.
