### ISSUE TITLE
Phone numbers included in contact search

### ISSUE THREAD

**Issue by mrmattster** [klinker-apps/messenger-issues#829]
**Describe your request:**
When starting a new conversation, would be nice if the contacts search selection included phone numbers even if a contact name is input. 

**Describe alternatives you've considered:**
Obviously the workaround is to type in the contact name instead of phone number but I've ran into a situation a couple times where the contact was input something like "mom" so difficult to find but I know the area code of the phone number.

**Comment by klinker24** [comment]
Are you asking for this on the web or what platform? Android should already do this.

**Comment by klinker24** [comment]
Actually, the web already does this too. I guess I am not really sure what you are asking me for?

https://github.com/klinker-apps/messenger-web/blob/master/src/components/Compose/RecipientBar.vue#L166

**Comment by mrmattster** [comment]
Ah, yes I guess I'm referring to search not new thread creation.

**Comment by mrmattster** [comment]
Example, if I search in either platform for 2270 when I have contact with name "mom" whose phone number ends in 2270 I get nothing.

**Comment by klinker24** [comment]
This is done.

The web version will come with the next deployment. The Android version will come with `4.6.1` of the Android app.
