### ISSUE TITLE
Fix android auto production issues

### ISSUE THREAD

**Issue by klinker41** [klinker-apps/messenger-issues#83]
**Device with issue:** Android Auto Head Unit
**App version:** 1.2.308
**Information:**

After submitting an APK to the play store, we get the following email from the support team about android auto:

```
Hi Developers at Luke Klinker,

Thanks for submitting your app for Android Auto. We accepted Messenger (Text Messaging), with package name xyz.klinker.messenger, into the Android Auto program on Google Play with a Provisional Pass.

During review, we noticed the following issues that would usually fail for a production state app:

- The message sending and receiving functionality on your app doesn't work as expected.

Version Name: 1.2.308
Version code: 308
Current track: BETA
Please correct these issues before submitting your app to PRODUCTION.

For more details on how an app can qualify for Android Auto, you can review the Android Auto App Quality Guidelines.

Thanks for supporting Google Play,

The Google Play Team
```

If not fixed before submitting the production app for public use, the play store will reject the app and no one will be able to download it. We'll need to install the head unit emulator and test this to see what the issue is since the email isn't very descriptive.

**Comment by klinker24** [comment]
Looks like you have to use a `BroadcastReceiver` to get the Android auto replies, kind of like the problem with the dismissing notifications from earlier.

Implemented with: https://github.com/klinker41/messenger/commit/2b033755020baecd499e7eb40cc992c16a25b65f

Next time we upload to beta, we will have to wait and get the response back from Google to close this, but it should be done.

I tested with the head unit simulator and was able to send messages just fine.

**Comment by klinker41** [comment]
Did not get any emails from them about this, so I'm guessing that it was now excepted fully and working.
