### ISSUE TITLE
Dual SIM enumeration inconsistency in icons 

### ISSUE THREAD

**Issue by Mahnas92** [klinker-apps/messenger-issues#830]
The SIM enumerated as nr 1 in system (and in Pulse pop-up window) is marked as "2" in the icon/button, and vice versa.

Also the pop-up lists SIM 1 after SIM 2. Maybe that has some correlation with this bug.

**Comment by klinker24** [comment]
The popup is going to list the SIM cards in whatever order your phone provides them. The icon is just going to list the index of the option you have selected. Thanks for the report.

**Comment by Mahnas92** [comment]
Yes, but the program can correctly identify which is SIM 1 and which is SIM 2, so maybe have the icon show the system identifier number instead of the index of the string being listed in the popup?

**Comment by klinker24** [comment]
That would be the assumed fix, yes.

**Comment by klinker24** [comment]
Please download and try this version of the app:

[messenger-4.6.1.2377-release.apk.zip](https://github.com/klinker-apps/messenger-issues/files/2841979/messenger-4.6.1.2377-release.apk.zip)

If it is not working as expected, please provide me with screenshots and the steps you are taking to get to those points, by copying and filling out the issue template below. 

You were presented with this template when creating the issue as well. In the future, please use the template when creating issues, it is not just there for looks

```
**Device with issue:** Ex: MacBook Pro on MacOS 10.12, running Chrome v54
**Primary device:** Ex: Pixel XL on Android 9
**App version:** Ex: v4.1.5

**Describe the bug:**
A clear and concise description of what the bug is.

**Steps to reproduce:**

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

`... more steps`

**Expected behavior:**
A clear and concise description of what you expected to happen.

**Screenshots:**
If applicable, add screenshots to help explain your problem.

**Additional information:**
Add any other context about the problem here. Device configuration, unique cases, anything that you think may be relevant.
```

**Comment by klinker24** [comment]
Closing for no response. Feel free to comment back, if that version does not work.
