### ISSUE TITLE
Stuck in media-view

### ISSUE THREAD

**Issue by Normanator** [klinker-apps/messenger-issues#833]
Sometimes when I tap on an image in a conversation, the media-view mode supercedes the conversation mode thereafter.  Switching back to all-conversations view and attempting to (re-)enter this or other conversation, still shows the prior media-view.

**Comment by klinker24** [comment]
Sorry, I do not understand what you mean. The media view is full screen. If you open it, you have to close it to do anything else.

Please provide some screenshots and a detailed list of steps, as requested by the bug report issue template.

**Comment by Normanator** [comment]
Sorry, I don't have 100%-reproducible steps.  Randomly and infrequently I enter media-view and both the back arrow (top-left) and back button (Android bottom left) take me back to the Conversation List instead of to the Conversation.  Thereafter the issue's as described above, selecting any individual conversation doesn't take me to the Conversation's view, rather to the last-displayed Media View.  

This cycle gets repeated as I retry: back to Conversation List, conversation jumps to Media View.  
Sadly I'm never sure which of my efforts breaks the cycle or if it just recovers on its own in time.  

I'm on App Ver 4.6.1.2379 on my OnePlus 6 (A6003), Android 9 / Oxygen 9.0.3.  
HTHs.
