### ISSUE TITLE
Add support for notification dots in Oreo

### ISSUE THREAD

**Issue by pluton-house** [klinker-apps/messenger-issues#834]
Version 8 Oreo introduced notification dots on the home screen icon. When the app has a notification, such as an unread message, the icon should show a small dot on its icon. This issue is a request to add support for this in pulse. For details, see https://developer.android.com/training/notify-user/badges

**Comment by klinker24** [comment]
Pulse has support for notification dots, there is nothing for me to do. They simply run off of active notifications. All apps support them, that use notification channels. You can turn them on or off, through the system level notification channel settings.

**Comment by pluton-house** [comment]
Hi Luke,

 

Thanks for looking at my issue. Does it work OK on your phone? It definitely isn’t on mine. When a message arrives, there’s a notification in the Notifications pull-down, but the icon does not show a dot. Other apps are showing the dot correctly. A long tap on the icon does show up the last few messages, though not specifically the unread one.

 

Kind regards,

Clive
