### ISSUE TITLE
Include option to hide the call button

### ISSUE THREAD

**Issue by rogerval** [klinker-apps/messenger-issues#838]
When composing a reply to a text, the call button is displayed, which could be taped by accident in some circumstances. (I've done it myself, with the stock messages app.)
Would it be possible to have an option to hide this button?
Thanks, Roger V.

**Comment by klinker24** [comment]
With Pulse, I really want to stay away from little "tweak" options like this. Ultimately, filling up the settings menu with this type of thing just makes a larger overhead for new and existing users. Some people don't like that I don't allow you to customize every single inch of the UI. There are plenty of apps that do, but I have made apps both ways, and Pulse's way has definitely proved to be the better user experience. 

Sorry, this isn't something that I plan to include in Pulse.
