### ISSUE TITLE
Mark as Unread

### ISSUE THREAD

**Issue by Plotketo** [klinker-apps/messenger-issues#839]
**Describe your request:**
I would like to be able to mark conversations as unread in the Windows 10 desktop app. I sometimes read texts on the desktop, but am not ready to respond to the request. On the app, I can mark it as unread to keep the notification, but can't do that on the PC as of now. You could make a long mouse click mark it as unread, or have a right click option that has other menu capabilities as well.

**Describe alternatives you've considered:**
Using the app on the phone to mark it, but then I have to pull out my phone every time.

**Comment by Plotketo** [comment]
Oh, I do mean this on the native Windows client by the way! But other clients may like it too.

**Comment by klinker24** [comment]
The windows app simply displays the web app. Adding it to the web adds it to Windows.

**Comment by Plotketo** [comment]
Oh, didn't know that! Great.

**Comment by klinker24** [comment]
I am going to close this one, and just add this request to #719, since that is how it will be implemented.
