### ISSUE TITLE
Implement Direct Share for individual conversations

### ISSUE THREAD

**Issue by marcuscbey** [klinker-apps/messenger-issues#84]
Device with issue: Nexus 6P running Android 7.0
App version: 1.2
Steps to reproduce:

Share content from any app
Messenger shows in general share list but not in the direct share list

Additional information:

I'm pretty sure this worked on the initial version, so I don't know if you removed it or if it is not being prioritized against other apps I have on my phone. My experience with this feature in the past is that if I have a text conversation that is the most recent thing I have shared to it will show up first in the direct share menu.

**Comment by klinker41** [comment]
This is completely up to android to actually choose which apps get to display them to you, Messenger provides a list of direct share contacts already so there isn't anything more that we can do for this.

**Comment by marcuscbey** [comment]
Is there not a way to prioritize it? I know with Textra for example my conversations always make it to the direct share view but with messenger it seems things like twitter, inbox and hangouts are taking priority. Not criticizing, just thought i'd bring it up and see if it is something you would be able to look at

**Comment by klinker41** [comment]
Nope.
