### ISSUE TITLE
Wrong date in conversation listing

### ISSUE THREAD

**Issue by aminsol** [klinker-apps/messenger-issues#841]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [x] I have verified that this is something that is reproducible.

**Device with issue:** Windows and Android and Web
**Primary device:** Galaxy S7
**App version:** v4.6.3.2

**Describe the bug:**
I use Desktop version of pulse and my Desktop clock was ahead by 24 hours when I sent a text via my Desktop. The text showed up under `This Month`. My Windows is set to automatically adjust date and time but I have Linux installed on my machine and when I switch between two this will happen.

**Steps to reproduce:**

1- Change date on your windows to a future date
2- Send a text
3- Fix your windows date
4- Restart the application

**Expected behavior:**
The text must show up under today's text not this month

**Screenshots:**
As you see `This Month` is above `Today`
![capture](https://user-images.githubusercontent.com/5069526/53382066-ce59a500-3927-11e9-8a42-0dcf23344990.PNG)

**PHONE**

![phone-pulse](https://user-images.githubusercontent.com/5069526/53382597-be42c500-3929-11e9-855d-02c2afb24813.jpg)

**WEB**
![capture](https://user-images.githubusercontent.com/5069526/53382949-c64f3480-392a-11e9-8b56-e383830fa2a8.PNG)

**Comment by klinker24** [comment]
I don't really think that this specific case is something I will look to fix. There is an open issue on here about not trusting the date on the web/desktop app, which I would prefer over fixing a one-off case, such as this one

#791
