### ISSUE TITLE
Windows native Pulse: Scheduled Message to Group Isn't Received

### ISSUE THREAD

**Issue by mcjathan** [klinker-apps/messenger-issues#845]
When I schedule a message in the Pulse Windows native app to two contacts, neither receive the message.  However, the message DOES show up in the Android Pulse as a group message that was sent.

If I send the same message to the same two contacts in the Pulse Windows native app but don't schedule the message, the message is received by both contacts.

**Comment by klinker24** [comment]
Scheduling the message doesn't change how the messages get sent. If they are showing up within Pulse, as a group conversation, then the app sent them that way. #101 has some recommendations around what you can try if MMS messages are not being sent or are inconsistent

**Comment by mcjathan** [comment]
Hi Luke,

I know that the bug I'm reporting sounds implausible.  Please hear me out.

I'm very familiar with the MMS problem many phones have -- I've had phones in the past with this problem, and I've had to tweak the MMS settings in both my phone's APN and the text message Android apps I used at the time.  However, my current phone has been rock-solid both with MMS messages in general, and with MMS group messages -- except for scheduled group messages sent from the Windows native Pulse app.

After reporting this bug to you, I've replicated this bug 100% of the time using 12 different contacts (6 different group pairs). In every case:

1) I schedule a group message to 2 contacts in the Windows native Pulse app and ask them to reply with "test1".  After the scheduled time, I can see the outgoing message in Pulse's Conversations both in the Windows app and the Android app.  However, my contacts simply never see it.

2) I send a group message to the same 2 contacts in the Windows native pulse app (not scheduled), and ask them to reply with "test2".  Everybody responds.

3) I followup with phone calls asking about the "test1" message I sent.  Nobody receives the scheduled "test1" messages and everyone receives the "test2" messages.

4) Repeat these steps for the other 10 contacts (5 other group pairs).

Will you please try to reproduce this error for yourself?

Also, what other information can I provide to convince you?

Jeff

**Comment by klinker24** [comment]
I use scheduled messages frequently and I cannot reproduce this issue. 

It does not matter what platform the messages are scheduled on. If you go to the "how-it-works" topic on my help page, I go in to more detail on this. This will give you insight into why the platform does not matter. So saying that it only happens on the Windows desktop app is simply not possible. The desktop app is simply a UI. It did it's job if the messages show as sent.

https://messenger.klinkerapps.com/help

If the messages show up within Pulse, then the app has attempted to send them. The web and desktop apps simply forward messages between your devices, they do not send anything, nor do they manage the scheduled messages and when those are triggered to be sent

**Comment by mcjathan** [comment]
On 3/19/2019 3:03 PM, Luke Klinker wrote:
> So saying that it only happens on the Windows desktop app is simply not possible. The desktop app is simply a UI. It did it's job if the messages show as sent.
It only happens for me on the Windows desktop app with _/*scheduled*/_ messages.

I believe I reported the same bug in 2018 and you found a problem and fixed it.  Perhaps a reversion?

**Comment by mcjathan** [comment]
Luke, I want to try over-riding my Android APN settings inside Pulse to see if this will solve my problem.  I know the values to use for MMSC URL, MMS Proxy, and MMS Port.  

However, I'm unfamiliar with User Agent, User Agent Profile URL, and User Agent Profile Tag Name.  I see that Pulse fills in defaults for the 1st and 3rd but leaves the 2nd (User Agent Profile URL) blank.  Do I need to fill in that blank for the Pulse MMS overrides to work properly?  If I shouldn't or can't leave it blank, can you offer a URL for "User Agent Profile URL"?
