### ISSUE TITLE
Special Character Issue

### ISSUE THREAD

**Issue by PreetiPeshwani** [klinker-apps/messenger-issues#846]
I  am using pulse sms to send and receive sms through my crm. My customers are facing issues with special characters in sms. If there are some special characters like I'm then sms are not going to send via pulse.

If anyone has the solution please let me know.

**Comment by klinker24** [comment]
I would need some examples or screenshots or just more information to be able to do anything with this. Pulse should handle any unicode characters just fine, but I cannot speak for other apps or systems.

**Comment by klinker24** [comment]
Sorry, without more information, I am going to have to close this. Feel free to comment back with the requested screenshots or examples if you would like to re-open it.
