### ISSUE TITLE
Add the option to turn on/off date category view

### ISSUE THREAD

**Issue by msbmmc** [klinker-apps/messenger-issues#847]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.

![Screenshot_2019-03-14-02-22-40-1](https://user-images.githubusercontent.com/48546095/54338544-2d920780-4600-11e9-984b-5dee6ef6f571.png)
Come on! Seriously.... Please give us the ability to turn it off. It looks terrible... I've had this app for about 20 minutes and I love it already, but that is driving me insane... We should have the option between date category view and a normal list like any other messaging app. You can keep the date inside each conversation instead of putting in the list view so you don't have to change anything.

**Comment by klinker24** [comment]
Sorry, this isn't planned. Their style might change in the future, but the categories are not going to be removed, for the reasons that you have already posted.
