### ISSUE TITLE
Window can be resized arbitrarily small

### ISSUE THREAD

**Issue by kylrth** [klinker-apps/messenger-issues#849]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [x] I have verified that this is something that is reproducible.

**Device with issue:** Lenovo Yoga 710 running Elementary OS Juno with Chrome 73.0
**Primary device:** Samsung Galaxy S9 on Android 9
**App version:** Ex: v3.3.0, AppImage

**Describe the bug:**
When the Pulse window is open and I unplug an external monitor, the Pulse app window resizes to become unnoticeably small, in the upper-left corner of the screen.

**Steps to reproduce:**

1. Open Pulse SMS
2. Drag the bottom-right corner up to the upper-left corner
4. Observe the fact that the window is tiny

**Expected behavior:**
There should be a minimum size that the app can have.

**Screenshot:**
![hidden-pulse](https://user-images.githubusercontent.com/5044802/54574959-f59c1300-49b7-11e9-919a-60043cb81cd1.png)

See if you can spot the app in the upper middle of the screen.

**Comment by klinker24** [comment]
Thanks for the suggestion. This is done for the next version.
