### ISSUE TITLE
Crash when sharing image from conversation view

### ISSUE THREAD

**Issue by marcuscbey** [klinker-apps/messenger-issues#85]
Device with issue: Nexus 6P with Android 7.0
App version: 1.2.308

Steps to reproduce:
Send an image
Click on the image in the conversation view or click on view media from the menu drawer
Click overflow menu
Click share

Additional information:
Crashes every time on images or gifs. I sent feedback the last time this happened so it should have a log

**Comment by klinker41** [comment]
@klinker24 you said you were going to be adding a content provider for the files, I'm guessing that isn't done yet and this is caused by that?

**Comment by klinker24** [comment]
Looks like I had just messed up one part. Fixed: https://github.com/klinker41/messenger/commit/aa1140f36d24a8d98d2299178585f877949053a7
