### ISSUE TITLE
Wear OS slow with app.

### ISSUE THREAD

**Issue by peter11star** [klinker-apps/messenger-issues#850]
Ok so I noticed without the pulse SMS app on my watch, my text notifications come in. But with it, sometimes they come, but most of the time, they don't come at all. Is there a reason why?

**Comment by klinker24** [comment]
Here is the topic from my help page, describing how the notifications work, why they can be slow, and my suggestions around them:

![Screen Shot 2019-03-19 at 8 04 54 AM](https://user-images.githubusercontent.com/4874287/54607982-bc968980-4a1d-11e9-8655-fae75fdf2ed3.png)

https://messenger.klinkerapps.com/help

**Comment by peter11star** [comment]
Hello Luke,

But also keep in mind, with Android messages, it's never that slow. In fact
it's almost instantly.

-Peter

**Comment by JetRocket11** [comment]
It is hard to always have a WearOS device connected to WiFi. If you are saying that Bluetooth connection is unreliable for notifications to work then perhaps this feature should be redesigned. As OP has mentioned, Google Messages notifications come through immediately even without WiFi and allow you to reply.
