### ISSUE TITLE
Duplicate messages in large group conversations

### ISSUE THREAD

**Issue by klinker24** [klinker-apps/messenger-issues#851]
**Device with issue:** Android Phones
**App version:** v4.7.2

**Describe the bug:**

By default, Pulse only shows the latest 7,000 messages in a conversation, when you open it. You can access the rest of the history, from the "conversation information" menu.

With group conversations that have hit this size limit, some users have started to report that as they send and receive new messages, the conversation gets garbled and messages are duplicated.

**Steps to reproduce:**

An example posted in #517 

![54637974-eec4dd00-4a57-11e9-90dc-c38cb13c2755](https://user-images.githubusercontent.com/4874287/54685599-3180c680-4ae5-11e9-9071-7c4669c91d2b.png)

**Expected behavior:**

The messages will not show as duplicated. As messages are sent and received, the new messages should just appear like in any other conversation.

**Additional information:**

The quick fix would just be to remove the size limit on group conversations. As these conversations start to grow larger, it might take more time to load them, though.

**Comment by klinker24** [comment]
This should be closed with https://github.com/klinker41/messenger/commit/a52f5b9ab629012e046f2093cd1c990ee897d477

**Comment by egocarib** [comment]
Thanks for addressing this! Everything seems to be working great now.
