### ISSUE TITLE
Press Hold on phone number in conversation for options

### ISSUE THREAD

**Issue by dsteinschneider** [klinker-apps/messenger-issues#852]
In a new group SMS conversation in my Pulse there were 6 numbers I didn't have as contacts on my Google Pixel 2 XL. It would be great if it was possible to press and hold a phone number and have the option to copy it into the clipboard so I could then create a contact and paste it in. 

Right now I can press and hold on the message "balloon" and copy the entire text but that is difficult to paste into a phone number field. The number is also under the message - press and hold on that to copy would be really useful. I know there are restrictions in Android about how to do things like this. If I could press and hold to highlight number and then go to the top of the screen and click on the share icon and go from there that would be fine. 

Thanks,

**Comment by klinker24** [comment]
If you just tap the contact in that dialog, it will open your contacts app to allow you to add that contact. You don't have to manually copy and paste anything, so this seems like a better solution

**Comment by dsteinschneider** [comment]
Thanks for quick response - I didn't try pressing and holding the numbers at the top of the conversation. I see all the options now - thanks,
