### ISSUE TITLE
It can't sending msg via web app, chrome extension and Windows Destop App, Since upgrade Android to 7.1.2

### ISSUE THREAD

**Issue by cougar999** [klinker-apps/messenger-issues#853]
- [ ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behaviour.
- [ ] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [ ] I have verified that this is something that is reproducible.

**Device with issue:** Ex: Dell Inspiron, running Chrome 72.0.3626.121 (Official Build) (64-bit)
**Primary device:** Ex: RedMi Note 5A MIUI Global 10.2  / Android 7.1.2 N2G47H
**App version:** Ex: v3.0.0

**Describe the bug:**
Including Web App, Chrome Extension, Windows Desktop App.
They both can't send SMS now, just can get what I send via Android App.

**Expected behaviour:**
Please have a look, how to resolve this, otherwise, I have to swap to another App. I bought a permenent membership.

**Screenshots:**
![微信图片_20190322130905](https://user-images.githubusercontent.com/1323406/54796296-c5988c80-4ca3-11e9-9ce5-90fa7aec2b3f.png)

**Additional information:**
 I tried "Refresh Account" option. That won't work. I deleted the App from the Phone, then, installed the new version and sync the data, still not working.

**Comment by cougar999** [comment]
I delete the account, reinstall again, then logged in, sync the data, then it works well, but 1 hour later, it is not working again...I got 9408 messages, 252 dialogue, does it cause the problem?

**Comment by klinker24** [comment]
We do not need this issue opened in both repos.
