### ISSUE TITLE
Search bar  in left side conversation list

### ISSUE THREAD

**Issue by Spiz** [klinker-apps/messenger-issues#854]
**Describe your request:**
A conversation (not message) search bar above the conversation list in the message view (like: https://imgur.com/a/xDR07MQ )

**Describe alternatives you've considered:**
Clicking to conversation view and then clicking the search button is much less convenient, it'd be great to just have a search bar always open that can easily be tabbed into.

**Additional information:**
https://imgur.com/a/xDR07MQ - an always-open bar instead of a button would be great

Just purchased today, thank you!

**Comment by klinker24** [comment]
This is done with https://github.com/klinker-apps/messenger-web/commit/313067fda7e3bd9d1ef72097ea921e3b7c34cb60
