### ISSUE TITLE
Icon not set correctly on Fedora 29 with Gnome Shell

### ISSUE THREAD

**Issue by aia832003** [klinker-apps/messenger-issues#859]
- [ x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [ x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [ x] I have verified that this is something that is reproducible.

**Device with issue:** Dell XPS 13 Running Gnome Shell Fedora 29
**Primary device:** Pixel 3 XL running latest Android Pie 9
**App version:** pulse-sms-3.3.1-x86_64.rpm

**Describe the bug:**
Latest install breaks proper icon showing on the Gnome Shell Desktop for Fedora 29.

**Steps to reproduce:**

1. Updated from pulse-sms-3.2.1-x86_64.rpm to pulse-sms-3.3.1-x86_64.rpm.
2. App goes from showing properly to showing a system placeholder icon instead of the Pulse icon.
3. Reinstalling pulse-sms-3.2.1-x86_64.rpm restores Pulse icon.

Screenshot with an installation of pulse-sms-3.2.1-x86_64.rpm:
![image](https://user-images.githubusercontent.com/11007827/55924387-55f52d80-5bcf-11e9-85c0-708f5faf35ef.png)

Screenshot after upgrade to pulse-sms-3.3.1-x86_64.rpm:
![image](https://user-images.githubusercontent.com/11007827/55924340-1c242700-5bcf-11e9-8120-09820f35cb3e.png)

Screenshot after downgrading back to 3.2.1:
![image](https://user-images.githubusercontent.com/11007827/55924392-58f01e00-5bcf-11e9-86f0-8ea63e4e244c.png)

**Comment by klinker24** [comment]
Looks similar enough to #781 that we can track it there.

Sorry, I am not sure why this is happening right now. The desktop app is open source, if you have any insight.

https://github.com/klinker-apps

**Comment by aia832003** [comment]
Hmm. I've tried all the normal hiccups on that issue and actually suggested the fix there. Let me do some more digging and see if I can nail down a difference.
