### ISSUE TITLE
Confusing navigation for archived conversations

### ISSUE THREAD

**Issue by klinker41** [klinker-apps/messenger-issues#86]
**Device with issue:** Nexus 6P with Android 7.0, Google Chrome 53
**App version:** 1.3.311

**Chrome App Steps:**

1. Go to the archived conversations list
2. Click on one of them
3. Press the back button
4. See that you've returned to the conversation list, not to the archived conversation list

1. Go to the archived conversation list
2. Click on one of them
3. See the "Archive Conversation" menu item
4. Should be "Unarchive Conversation" menu item

**Android App Steps:**

Same as the second set of chrome app steps above.

**Comment by klinker24** [comment]
Android fix: https://github.com/klinker41/messenger/commit/971dfbbba1d45cdc80d4794745f1a72dc0e99ca7

**Comment by klinker24** [comment]
Web fix: https://github.com/klinker41/messenger-web/commit/f52ca417e88b1528fb9f929dff9bf9d0900d4078
