### ISSUE TITLE
Feature Request: Option to open links in native apps

### ISSUE THREAD

**Issue by JetRocket11** [klinker-apps/messenger-issues#862]
Requesting to have an option to open links in text messages with native apps if available.

Example: Link to Amazon or eBay

Current State: Link opens up within a browser in Pulse or Chrome

Future State: Provide an option to open link in Chrome or app that is related to the link. For example an Amazon link would launch the Amazon app if installed.

When I was using Google Messages I noticed that was a feature in that app.

Thanks for the consideration

**Comment by klinker24** [comment]
There is already an option for whether or not to use the internal browser, in the advanced features menu.

**Comment by JetRocket11** [comment]
I was referring to option like in the attached screenshot when clicking on
the link

**Comment by klinker24** [comment]
There is no screenshot.

My app doesn't control how things get redirected to native apps vs the browser. This is controlled by Android, and that is not something I plan to change.
