### ISSUE TITLE
Add a button to go back to conversations.  I'm using keyboard/mouse/tablet

### ISSUE THREAD

**Issue by mattehicks** [klinker-apps/messenger-issues#864]
I'm using Pulse on a tablet, next to my primary work PC.  Currently, there's no way to get back to conversation list, without using my device back button.

Thanks!

Picture attached: 
![0422191312](https://user-images.githubusercontent.com/859222/56526051-ab4f0a00-6500-11e9-87fa-1bd2c623dbc4.jpg)

**Comment by klinker24** [comment]
You can swipe upwards from the bottom of the message list, to return to the conversation list. It works the same as the phone app

Sorry, a button to go backwards is not currently planned for the tablet app.
