### ISSUE TITLE
Dummy/decoy password for private messages

### ISSUE THREAD

**Issue by jedisb** [klinker-apps/messenger-issues#865]
- [ ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.
- [ ] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.

**Describe your request:**
A clear and concise description of what you would like to see, and why.

**Describe alternatives you've considered:**
A clear and concise description of any alternative solutions or features you've considered. There may already be something that is built into the app, or the platform, that is very similar.

**Additional information:**

**Comment by jedisb** [comment]
I would like to see a decoy password that would be used to protect the private messages in the event that you were coerced to display them. Entering the decoy password would simply display an empty private messages list. I've seen this implemented in other chat program specifically meant for private messaging and I've seen it in other apps for hiding photos, etc.

**Comment by klinker24** [comment]
I don't think this is something I would add to Pulse, sorry. I really want my features to be clear, concise, easy to use, and easy for everyone to understand. Misdirection like this isn't something that I am really interested in adding

I think that if this is something that you are really worried about, an SMS app probably isn't the medium that you should be using to communicate with those contacts. SMS is unencrypted, intercept-able, and other apps on your phone can definitely get at those messages anyways. If secrecy is your number one concern, an app that focuses on privacy would probably be a much better bet
