### ISSUE TITLE
Typing contact name glitch when hitting the spacebar

### ISSUE THREAD

**Issue by hoopahmadness** [klinker-apps/messenger-issues#87]
Issue on the LG Nexus 5X
App version 1.3.310
When I attempt to open a conversation with a contact, I am unable to type the full name. When I hit SPACE it just accepts what I have as a contact. This might not have been noticed before because your contact picker is very good (but I have a ton of people with the string "tim" in their names)

**Comment by klinker41** [comment]
fixed with https://github.com/klinker41/android-chips/commit/a4ce823aabdda7fae0975a574e711bc5d07fb02d

@klinker24 can you update this on maven and then update the version number in Messenger to `1.1.0` when you get the chance?
