### ISSUE TITLE
⌘H to Hide Desktop Window

### ISSUE THREAD

**Issue by jcsosia** [klinker-apps/messenger-issues#870]
Most of the time I want the Desktop Pulse window to be ready and active, but I don't want it open behind my other windows or minimized. On other apps like Chrome I can use the shortcut ⌘H to hide a window, but that isn't available yet on Pulse for Desktop. Is that an easy feature request? Or maybe even allow it to act like Spotify where you can close the window, but the app is still running in the dock until you tell it to "quit." Either way!

Thanks!!

![Screen Shot 2019-05-21 at 10 48 08 AM](https://user-images.githubusercontent.com/26373530/58106442-1e0ddc80-7bb6-11e9-9c41-6902d121d46a.png)

**Comment by klinker24** [comment]
Using ⌘W will close the window and the app will continue running, just like you are suggesting. Maybe I don't understand what you are asking for.

Pulses ⌘W does the same thing that Chrome's ⌘H does.

**Comment by jcsosia** [comment]
I guess what I'm meaning is quick access without going to the status bar and clicking "Show Pulse." I didn't want the Pulse icon to live in the dock even after I tell it to quit. Right now when I use ⌘W it closes the window and removes the icon from the dock. I think I'm asking if the icon can stay after ⌘W, but then go away if I use ⌘Q? Not sure if that makes sense.

**Comment by jcsosia** [comment]
Never mind.. figured out my problem. Had the menu bar icon active and you can't do both. Thanks
