### ISSUE TITLE
wrong importation of the contacts groups from phone to  cloud

### ISSUE THREAD

**Issue by xavierdes** [klinker-apps/messenger-issues#873]
AhOh !!!

- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [x] I have verified that this is something that is reproducible.

**Device with issue:** Ex: MacBook Air on MacOS 10.11.6 , running Firefox 67.0 or Chrome Version 74.0.3729.169 
**Primary device:** Samsung J510FN, 2016, on Android 6.0.1
**Pulse version:**  5.1.0 (5.1.0.1337)

**Describe the bug:**

I had groups contact in my Apple contacts app, and in my smartphone, they both sync very well since years.
But… When I use Pulse to write a message to one of these groups, 
- I discover that Pulse shows 2 or 3 groups with the same name where I had just one !
- some of my previous groups don’t appear in Pulse.

**Steps to reproduce:**

1.1 On the smartphone: Hit the + button on the conversation list then navigate to the Groups tab at the bottom. This will display all groups from your Contacts app. Some of them will have the same name !!
1.2. On the computer : Tapp the + button in the bottom right corner of desktop apps  to open the compose page. Type the title of the group, like "drome" to search for it and ... discover the same problem
1.3. On the web:  Tapp the + button in the bottom right corner of Pulse website to open the compose page. Type of the title of my groups ,and discover the same no group appears...!

To be sure, 
I have Re-upload my contacts to the cloud. By "my account" -> "resync contacts".
And I have Re-download the contacts from the cloud, to the computer. From Chrome apps (by hitting the + button in the bottom right corner) and tapping the "refresh" button in the top right corner.  

**Expected behavior:**
I wish I
- could get ALL my groups
- could get each group complete and not divided in 2 or 3 sub-groups

**Screenshots:**
yes, 3 of them
they show the previous group exist in my computer, sync each day to my phone but not in Pulse app.
they show the Pulse app presents sometimes 2 groups with the same name.

![Capture d’écran 2019-05-26 à 22 21 46](https://user-images.githubusercontent.com/51059502/58387182-195c8480-800b-11e9-934a-ebcf7ea9fa3e.png)
![Capture d’écran 2019-05-26 à 22 21 59](https://user-images.githubusercontent.com/51059502/58387183-19f51b00-800b-11e9-8bd4-ad020bcf4ff5.png)
![Capture d’écran 2019-05-26 à 22 23 35](https://user-images.githubusercontent.com/51059502/58387184-19f51b00-800b-11e9-9989-3872d18d8ff5.png)

**Comment by klinker24** [comment]
I already said that this is a duplicate issue and that that is why I closed it. The details of your report have been linked in the original issue. Please do not re-open another. I will continue to close duplicates as they distract from distinct reports. 

Thank you for the information and the help with reporting this bug.

**Comment by xavierdes** [comment]
what is the problem with you??

I gave you in the last issue all the details you need !!

**Comment by xavierdes** [comment]
You asked me more details, but you had first CLOSED the issue ! That's I had to create new one ! It's a mad situation

**Comment by klinker24** [comment]
You did create a new one already. I already told you in #872 that you had the right amount of information and provided details on why I closed it. Please read my replies before just opening a third issue. My replies have all be explicit.

**Comment by xavierdes** [comment]
isn’t crazy to close and issue if you think the informations are ok ??
