### ISSUE TITLE
link color is always white. When bg-color also white - link invisible

### ISSUE THREAD

**Issue by karakum** [klinker-apps/messenger-issues#875]
**Device with issue:** PC on Windows 10
**Primary device:** PC
**App version:** 3.4.4

**Describe the bug:**
Link color is always white. When bg-color also white - link invisible

**Expected behavior:**
Links are visible with any bg-color

**Screenshots:**

![изображение](https://user-images.githubusercontent.com/12033941/59343853-f209f500-8d36-11e9-9257-f84497030674.png)

![изображение](https://user-images.githubusercontent.com/12033941/59343879-01893e00-8d37-11e9-97db-8b630a575265.png)

![изображение](https://user-images.githubusercontent.com/12033941/59343915-136ae100-8d37-11e9-9faf-cbd73b7ed17a.png)

**Comment by klinker24** [comment]
Fix with https://github.com/klinker-apps/messenger-web
