### ISSUE TITLE
Spell checking doesn't work in Windows Native Pulse SMS v3.4.4

### ISSUE THREAD

**Issue by mcjathan** [klinker-apps/messenger-issues#879]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [x] I have verified that this is something that is reproducible.

**Device with issue:** Window 7 Pro x64
**Primary device:** 
**App version:** Windows native Pulse SMS v3.4.4

**Describe the bug:**
Spell checking doesn't work in v3.4.4.  When I downgrade to v3.3.1, spell checking works.

**Steps to reproduce:**
See above

**Expected behavior:**
See above

**Screenshots:**
n/a

**Additional information:**
n/a

**Comment by klinker24** [comment]
There are other issues with the Windows app as well. I guess it didn't like the Electron update. I am going to downgrade electron and release a new version of it, at the beginning of next week. Not sure what the upstream issue is.
