### ISSUE TITLE
Unable to show full contact picker, hidden behind keyboard

### ISSUE THREAD

**Issue by hoopahmadness** [klinker-apps/messenger-issues#88]
Problem with LG Nexus 5X
App version 1.3.310

![screenshot_20160910-141546](https://cloud.githubusercontent.com/assets/7513897/18412637/9b1373d6-7761-11e6-9622-f333986bd9d8.png)

If I'm typing a name and want to scroll through the suggested contact names, the keyboard gets in the way. Hitting the Back button dismisses the name suggestions but not the keyboard. Hitting Back again will dismiss the keyboard but then I can't pick suggestions. I'm referring to the suggestions that appear while typing, NOT the suggestions that appear in this screenshot.

**Comment by klinker24** [comment]
This is working as expected for me. 

The contacts are scroll-able in the popup window (when you are typing a contact), as well as the "top contacts" section that is displayed in the screenshot.

**Comment by klinker41** [comment]
Not having this problem either.

**Comment by klinker24** [comment]
Going to go ahead and close this one. If @hoopahmadness has any additional information, feel free to reopen.
