### ISSUE TITLE
Disable Suggest Smart Replies on specific convos

### ISSUE THREAD

**Issue by 1PhoenixFox1** [klinker-apps/messenger-issues#880]
I really like the Suggest Smart Replies feature. It saves a lot of time and keystrokes. However I have quite a few "convos" that are basically one way, incoming. Stuff like:
- your prescriptions are ready
- the train is arriving on time
- here are today's deals
- here's your 2FA code

Either they don't accept replies or only specific ones (for example, press R to renew now).

I find I often hit the suggested replies by accident. With delayed send (another great feature), I can cancel them of course. It would just be nice to disable them entirely on those convos where they do not apply.

Definitely a nice to have, not need to have, feature.

**Comment by klinker24** [comment]
Sorry, I don't think that this is something that will come to Pulse

With Pulse, I really want to stay away from creating little "tweak" options. There are some situations that I really just want to make a decision on and stick with it. I know there are plenty of apps that make preferences for every little thing you can think of. I have done that with past apps, and Pulse's way has been much more successful, to be honest. Some people like customizing every aspect of an app, but I have found that, for the majority of people, more settings just leads to more confusion for current users and a much higher overhead for new users. I don't really want to just fill out my app's settings menu. For something like this, a global toggle is all the further I am willing to go. There are so many different options within the app that could be on a per-conversation basis, that I just don't think are necessary for that context. 

Hopefully you can understand where I am coming from. Sorry to say "no" to your request

**Comment by 1PhoenixFox1** [comment]
Thanks for the explanation. That's fair.  I'll keep it in mind going forward.
