### ISSUE TITLE
Rounded bubble display density is off

### ISSUE THREAD

**Issue by dstaley** [klinker-apps/messenger-issues#882]
**Device with issue:** Samsung Galaxy Tab A 10.1 (2019)
**App version:** v4.10.2.2535

**Describe the bug:**
Messages are comically large; text overflows message bubble.

**Steps to reproduce:**

1. Make sure "Message Bubble Style" is "Rounded".
1. Open conversation

**Expected behavior:**
Messages are rendered at a reasonable size, with a reasonable number of messages displayed.

**Screenshots:**
![Screenshot_20190624-173212_Pulse_edit](https://user-images.githubusercontent.com/88163/60060723-e27b9c00-96a6-11e9-9bd1-815c9d57029a.png)

**Additional information:**
Issue does not occur with the Squared and Circle Message Bubble styles.

**Comment by klinker24** [comment]
Fixed with https://github.com/klinker41/messenger/commit/2bd48eb29cbb376888846f2a52995ed6db8be04a

It will be released with `v4.11.1.2550`.
