### ISSUE TITLE
Delayed Sending does not cancel from Editing message

### ISSUE THREAD

**Issue by mschlitz-trux** [klinker-apps/messenger-issues#883]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [x] I have verified that this is something that is reproducible.

**Device with issue:**  Galaxy S10, Android 9
**Primary device:**  Galaxy S10, Android 9
**App version:** 4.10.2.2535

**Describe the bug:**
The **Delayed Sending** feature does not cancel itself when editing a message, but instead restarts the delay with each keystroke.

**Steps to reproduce:**

1. Type a text message
2. Hit Send
3. Type any changes
4. Note that the progress delay does not cancel, but restarts

**Expected behavior:**
The **Delayed Sending** should be cancelled, and not restarted from 0.

**Additional information:**
Normally I use the cancel send button, so I don't know if this bug is recent or not. I use a 1-second delay, so editing is not realistic, but cancel is just 1 quick tap.

**Comment by klinker24** [comment]
This is not a bug, this is the way that I have decided to do it. This If you want to cancel sending, that is what the cancel button is designed for.

**Comment by mschlitz-trux** [comment]
Interesting. Okay, thanks for the response.
