### ISSUE TITLE
Bug: Searching for dollar sign ($) crashes the app

### ISSUE THREAD

**Issue by wizard7926** [klinker-apps/messenger-issues#884]
My guess is that the symbol is somehow used in the search string, but I was looking for a specific dollar amount and it crashed the app. This happens in both global and individual search.

**Comment by klinker24** [comment]
I am not able to replicate this issue. Can you please go through the template that GitHub presented you with, when you went to submit it? Device information and steps to reproduce would be helpful. 

I simply clicked the search button, entered a dollar amount $10 and saw the texts come up that contained this search. It was working as expected for me.

**Comment by wizard7926** [comment]
Sure thing, sorry Luke. Android 9 on Pixel 2 XL.

Looks like it only crashes when I type "$" and nothing else. Unrelated, when it does take a full value (such as $10), it doesn't highlight it in the text as it would for a text phrase.

**Comment by klinker24** [comment]
I am still not able to make it crash by typing a "$". Hmm. It probably has to do with the contents of the database, rather than what you are searching. 

I will see if I can find anything out or if I can find the crash reports for your phone.

**Comment by klinker24** [comment]
I do see a crash from a pixel 2 XL, coming from accessibility services. Could that be yours? I am not seeing much else over the past few days.

**Comment by klinker24** [comment]
Sorry, but without more information or a way to reproduce this, I will need to close it. I am not able to find any crash reports, other than the one that I have referenced. Since I have not heard back, I cannot investigate this any further.
