### ISSUE TITLE
Take "Search conversation" out of the three-dot overflow menu and put a search icon next to the Phone, so that there is continuity between the Conversations search and the individual search

### ISSUE THREAD

**Issue by wizard7926** [klinker-apps/messenger-issues#885]
- [X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.
- [X] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.

Thought it would be cool to have continuity between searching in the conversation list, and searching in an individual thread, by having the search magnifying glass icon appear in the top right rather than within the overflow menu. It would be fluid and natural because of how the search bar appears in that same space.

**Comment by klinker24** [comment]
The reason that I put it in the overflow menu, is because the message lists already have two icons on the app bar (call and overflow). At this time, I do not want to add a third button to that section and want to keep the search within the overflow menu, as a secondary option.
