### ISSUE TITLE
Copying and pasting an image let the web app stuck

### ISSUE THREAD

**Issue by alexgallotta** [klinker-apps/messenger-issues#887]
**Device with issue:** Dell precision 5520, arch linux 5.1.8, firefox 67
**Primary device:** Ex: Honor 10 on Android 9
**App version:** Ex: v4.10.2

**Describe the bug:**
Copying an image (not URL but the image itself) and sending via web browser make the web app stuck.

**Steps to reproduce:**

1. Go to pulsesms.app
2. Open a chat
3. Copy an image from the web (copy image, not copy image location/url)
4. paste it in the web app
5. image is always in "Sending..."
6. image is never received/sent
7. any other following message (even text) are not sent (always "Sending...")
8. closing/reopening, refreshing the page didn't solve the issue
9. mobile phone app still works and send messages, but can't see pictures sent from the web app or text messages sent from the web app after the image

**Expected behavior:**
Image should be sent, or fails to be sent. Other messages should be sent properly

**Screenshots:**
-

**Additional information:**
Image was only 30 kbs. I have send attachment before from both android app and web app but never tried to copy and paste directly there

**Comment by klinker24** [comment]
Is this something that you can replicate? I just tried it out and it appeared to send perfectly fine by copying and pasting an image into the web and the desktop apps.

**Comment by klinker24** [comment]
Without more information or a reply, I am going to have to close this as not reproducible, sorry. Feel free to let me know if this is something you can replicate and if there are specific images that trigger it, or any additional information you can provide, and I can re-open the issue.
