### ISSUE TITLE
Messenger Desktop Fails to Sync Scheduled Messages to Android

### ISSUE THREAD

**Issue by mcjathan** [klinker-apps/messenger-issues#888]
- [X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [X] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [X] I have verified that this is something that is reproducible.

**Device with issue:** Windows 7 Pro x64
**Primary device:** Samsung S5 (SM-G900T) running Android 9
**App version:** Windows Pulse Messenger-Desktop v3.5.0, and Android Pulse v4.11.0.2544

**Describe the bug:**
Scheduled messages entered into the Windows Pulse Messenger-Desktop don't sync to the Android Pulse app.  And, scheduled messages entered into the Windows Pulse Messenger-Desktop are never sent and never cleared from the Windows Pulse Messenger-Desktop.

On the other hand, scheduled messages entered into the Android Pulse app do sync to the Windows Pulse Messenger-Desktop, and are properly sent, and properly cleared from both apps after being sent.

**Steps to reproduce:**

1. Enter scheduled message in the Windows Pulse Messenger-Desktop app.
2. Goto the scheduled message screen in the Android Pulse app and the scheduled message does NOT appear.
3. Wait until the scheduled message time has passed.
4. The scheduled message has not been sent and is still "stuck" in the Windows Pulse Messenger-Desktop app.

**Expected behavior:**
Already explained.

**Screenshots:**
n/a

**Additional information:**
n/a

**Comment by klinker24** [comment]
Have you tried refreshing the account from the phone app, and retrying the process? This is the easiest way to fix sync issues.

https://messenger.klinkerapps.com/help

I am not able to replicate your issue with these steps, nor have I heard from others having this issue. If the messages don't show on the phone, they won't be sent.

**Comment by mcjathan** [comment]
Refreshing my account fixed the problem.  I'll remember Refreshing for future sync problems. Thank you!
