### ISSUE TITLE
Doesn't respond to Android auto

### ISSUE THREAD

**Issue by livinginMD** [klinker-apps/messenger-issues#889]
On Android Auto I can receive a SMS and it'll read it to me just fine over Bluetooth.  Then AA prompts you on if you wish to respond and it will not recognize any voice commands saying yes.

If I switch to Android Messenger as the default app AA reads and receives the prompt without issue.

4.11.0.2544

**Comment by klinker24** [comment]
Pulse is definitely not going to be able to control the voice recognition in Android Auto.. That doesn't have anything to do with my app, that is part of the system level functionality. There is nothing that I can change around that

**Comment by livinginMD** [comment]
Facebooks messenger app also works fine

**Comment by klinker24** [comment]
You will have to bring this up with the Android Auto team, there isn't anything that an app developer can do to to affect how Android Auto recognizes your voice.

**Comment by livinginMD** [comment]
Given other non-google apps support the functionality I'm not going to bring up jack.  You're the developer selling support.  Support it or refund my life subscription that I bought for a supported product

**Comment by klinker24** [comment]
Android Auto has nothing to do with what you purchased. And you are correct that other apps do it. In fact, my brother uses Pulse with Android Auto, every day. If you are having issues, it isn't with the app. Have a great day.
