### ISSUE TITLE
Forced out of app when permission for camera denied

### ISSUE THREAD

**Issue by mck3** [klinker-apps/messenger-issues#89]
If you click the attachment and tap camera you are presented with the permission request as expected but if you deny the permission access to the camera the app will close itself instead of returning you to the conversation. This kind of breaks the exsperence when using the app

**Comment by klinker41** [comment]
Please use the provided template in the future for filing issues.

**Comment by klinker41** [comment]
fixed with https://github.com/klinker41/messenger/commit/1f2a24f6898656c800920f07ab11840f387fecd6
