### ISSUE TITLE
Feature Request: Jump to Date

### ISSUE THREAD

**Issue by GitHubJack1182** [klinker-apps/messenger-issues#890]
Within the conversation thread, would it be possible to have an option to jump to a particular date within the thread? At the moment, there is a search function for text, but not for date.

If this is a feature that you might want to consider in future, one possible treatment would be when we are scrolling up on the message, we get a calendar dropdown at the top of the message that we can then select the date.

**Comment by klinker24** [comment]
Pulse already has this. If you are scrolling, you can grab the scroll handle on the right side of the screen, to jump to any date.
