### ISSUE TITLE
Need "Mark All as Read" / Can't get to all messages marked as read / # of messages indicator always >=1

### ISSUE THREAD

**Issue by cdcv** [klinker-apps/messenger-issues#891]
MacBook Pro on MacOS 10.14.1
Primary Device Pixel 3XL, Android recent
**App version:** Ex: v4.1.5
App version: up to date

**Describe the bug:**
On my Mac screen icon on the dock, the number of messages to read is always >=1.  In other words, I can never get rid of the little red "1" on the icon indicating that I have a message to read.  This is distracting.

Have tried, numerous times, to mark everything as read in each conversation. Can't find any that appear 'unread'.  No unread messages showing on my pixel device -> appears to be a bug.

Need a "Mark All Messages as Read" feature (and or a fix for this bug).

Don't have a good way to reproduce it, but it's been happening for weeks (ever since soon after I first installed).

**Comment by klinker24** [comment]
You can hit the double checkmarks in the "today", "yesterday", etc sections on the phone app, to mark everything as read within those sections. There isn't going to be a global "mark all as read", sorry. If the indicator still doesn't go away, you can use the "refresh account" option to re-upload everything from the phone to the web.

https://messenger.klinkerapps.com/help

**Comment by cdcv** [comment]
Thanks, but this did not work.  I presume by 'refresh account' you mean the circle arrow at the top right of the app.  I pressed it, problem unchanged...

**Comment by klinker24** [comment]
Refreshing the page does not upload anything from the phone to the web. There is a preference called "Refresh Account" on the phone app. Please see the help page, through the link that I posted, for details on this preference.

https://messenger.klinkerapps.com/help

**Comment by cdcv** [comment]
Hmmm.  OK, I tried that.  Now on the Mac, there are no messages/threads/anything displayed.  I tried hitting the refresh button, restarting the app, looking at My Account (where it says 0 everything), etc.

**Comment by klinker24** [comment]
You need to log out and back in, after using any of the danger zone options. Please be sure to follow the instructions when using them, as noted by the danger zone toggle that you enabled. As I noted earlier, please see this preference on my help page for more information about what it does and how it works. 

Github  is not meant as a support page for Pulse, hence my lack of detail. Sorry for the confusion. My help page has all of the details that you need to solve this issue, as well as a topic that addresses your initial question about clearing the unread count and marking conversations as read.

<img width="697" alt="Screen Shot 2019-07-12 at 9 00 34 AM" src="https://user-images.githubusercontent.com/4874287/61133692-8fb22a80-a483-11e9-95b1-a13f0bc865e5.png">
