### ISSUE TITLE
Android App intermittently ignores theme settings

### ISSUE THREAD

**Issue by xNS5** [klinker-apps/messenger-issues#892]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [ ] I have verified that this is something that is reproducible.

**Device with issue:** Samsung Galaxy S8+ on Android 9
**Primary device:** Same as above
**App version:** 4.11.0.2544

**Describe the bug:**
Every once in a while Pulse appears to ignore the base theme. I have mine currently set to "Always Dark". It first starts by turning my most recent message white, then it changes the base theme on that conversation white. 

**Steps to reproduce:**

I don't fully know what happens to trigger the bug, so I haven't been able to consciously reproduce the error. It usually happens after I send a message, but it happens inconsistently. 

**Screenshots:**
[Screenshots of the issue](https://imgur.com/a/rkE6wI5)

**Comment by klinker24** [comment]
Unfortunately, without a way to replicate this issue, I am not sure if I am going to be able to fix it. I really have no idea why that would be happening or where I could start to explore this issue

**Comment by xNS5** [comment]
I figured. The only time I've noticed it happen is right after I hit send. Then the message I just sent goes white, then the entire conversation.

**Comment by klinker24** [comment]
Without a consistent method to reproduce this, I am going to have to close it for now. I will continue to keep it in the back of my mind. If I find anything, I can re-open the issue.
