### ISSUE TITLE
Attach Image no thumbnail and images are blank - Android Q Beta 5

### ISSUE THREAD

**Issue by trippin7464** [klinker-apps/messenger-issues#893]
**Device with issue:** Pixel 2 XL on Android Q Beta 5
**Primary device:** Pixel 2 XL on Android Q Beta 5
**App version:** Ex: v4.11.0.2544

**Describe the bug:**
When trying to attach an image in a conversation by clicking the paperclip, the first "tab" is images on the device. All of the squares are blank where there would normally be a thumbnail. If I tap one of the squares, the blank image attaches and can be "sent" but the recipient never receives the image. I can tap the first box which is colored with an image icon (like normal), and select an image from there and it will be sent perfectly fine. 

All other attachment tabs work as expected, taking a picture from within the app, gifs, etc all work fine.

This persists after uninstall/reinstallation of Pulse. Before I uninstalled Pulse, pictures I had BEFORE i upgraded from Android Pie to Android Q Beta 5 were still there, but I did not try to send any, after the upgrade only new pictures showed up blank. After I reinstalled, all thumbnails were blank. I also verified that Pulse had all permissions in the App Info screen, and the pictures are available in the stock Messages app, and also in facebook, FB Messenger, instagram and photos.

Not sure if this helps, but a [reddit post](https://www.reddit.com/r/android_beta/comments/cc71sf/bug_i_still_cant_see_my_screenshots_and/) said this, maybe it points in the right direciton? Although I don't have the same issue with facebook or any other app.

> It's a Facebook/WhatsApp scoped storage thing, the app needs to request access in order to see it properly. I've been using messenger lite as a workaround.

**Steps to reproduce:**

1. On any conversation, tap the paperclip in the bottom left
2. All of the thumbnails are blank, can be tapped, but cannot be sent

**Expected behavior:**
Open the attachments, and all thumbnails show, with the ability to send them.

**Screenshots:**
https://imgur.com/haZcf6D

**Additional information:**
_I understand I'm using a beta version of Android. I don't expect a fast fix as it's a minor inconvenience at the moment_

**Comment by klinker24** [comment]
I am very confused by this issue. I am also on the beta for Q and have not experienced any issues with attaching images, nor have I heard from others on this yet, although I have to expect others are having the issue, if you are. I have around 7,000 users that are on the beta version of Android. Seems really weird

Pulse should work with scoped storage just fine, already. I use the `MediaStore.Images` query to expose them.

https://developer.android.com/preview/privacy/scoped-storage

I will probably just wait for future betas, before taking any action on this. I could disable the scoped storage completely, but I would rather not.

**Comment by tedbower** [comment]
Confirming I also have this issue on beta 5, Pixel 3. I don't think it was present on beta 4.

**Comment by klinker24** [comment]
They allow you to opt out of it. I don't want to opt out of it until the final release though, if that is the route I have to go down. Testing what Google has changed and how it affects the app is definitely the purpose of the OS beta test.

**Comment by ohhhgreat** [comment]
I have Samsung Galaxy Note 9 stock Android Pie and I am experiencing this issue. Have been for the past week

**Comment by klinker24** [comment]
I highly doubt that it is the same issue. This is specific to Android Q and the scoped storage architectural changes that are causing it, are well documented. 

I would recommend reinstalling the app to invalidate any permission or changes you have made.

**Comment by ohhhgreat** [comment]
I reinstalled the app and I'm still facing the issue. To clarify, when I click the attachment button none of my photos show up. Even when I click the gallery option it doesn't show any photos there.

**Comment by klinker24** [comment]
Then that is an issue with your gallery exposing the images, not with Pulse.

**Comment by ohhhgreat** [comment]
Do you have any suggestions of what I should do to fix this since it's a gallery issue?

**Comment by klinker24** [comment]
Sorry, I do not make a gallery app, so I would not be the person to ask for advice on this. Pulse does not control the data that is loaded by your gallery app, it is completely separate from my app.

**Comment by klinker24** [comment]
I have tested Pulse on the latest release of Android 10 and everything is working as expected. 

If anyone is still having issues, it may require you to reinstall Pulse, if you were previously on the beta test for Android Q.

**Comment by tedbower** [comment]
Yay! Thanks!
