### ISSUE TITLE
Notifications not consistently displaying on Android

### ISSUE THREAD

**Issue by Serubin** [klinker-apps/messenger-issues#894]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [x] I have verified that this is something that is reproducible.

**Device with issue:** Pixel 2XL, Android 8
**Primary device:** Pixel XL on Android 8
**App version:** Ex: v4.11.1.2550

**Describe the bug:**
Notifications don't display in status bar, often don't send notification alert/vibration, and lastly are collapsed as if they are "minimized" notifications.

**Steps to reproduce:**

1. receive new message

**Expected behavior:**
Normally notifications are top and center, expanded, and display an icon in the status bar. Notification chimes/vibrations also occur.

**Screenshots:**
![photo5008560646509406213](https://user-images.githubusercontent.com/1234465/61492625-900c6300-a966-11e9-9569-46b4a99b3439.jpg)

**Comment by klinker24** [comment]
Yeah this is fixed in the current rollout. Everyone will get it within the next few days.
