### ISSUE TITLE
Envoi mode conduite 

### ISSUE THREAD

**Issue by danimusicos** [klinker-apps/messenger-issues#896]
Bonjour, j'ai constaté un problème :
J'ai mis un message automatique précisant que je conduisais. PayPal qui m'envoie un code de validation reçois du coup mon message en boucle tant que je ne desactive pas la fonction. Y a-t-il un moyen de contourner celà ou de filtrer ? [ ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [ ] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [ ] I have verified that this is something that is reproducible.

**Device with issue:** Ex: MacBook Pro on MacOS 10.12, running Chrome v54
**Primary device:** Ex: Pixel XL on Android 9
**App version:** Ex: v4.1.5

**Describe the bug:**

**Steps to reproduce:**

`... more steps`

**Expected behavior:**

**Screenshots:**

**Additional information:**
Add any other context about the problem here. Device configuration, unique cases, anything that you think may be relevant.

**Comment by danimusicos** [comment]
Bonjour, j'ai constaté un problème :
J'ai mis un message automatique précisant que je conduisais. PayPal qui m'envoie un code de validation reçois du coup mon message en boucle tant que je ne desactive pas la fonction. Y a-t-il un moyen de contourner celà ou de filtrer ?

**Comment by klinker24** [comment]
Not at this time. Driving mode will be improved in the future, to take situations like this into account.
