### ISSUE TITLE
Cannot login on android 5 tablet

### ISSUE THREAD

**Issue by jsseidel** [klinker-apps/messenger-issues#897]
I realize the way I use Pulse is out of the norm, but I'm running the latest Play Store version on a new Fire 8" tablet with a side-loaded Google Play store. I used to use (an older) Pulse on (an older) Amazon Fire 7" with no trouble at all. I was disappointed to discover that the latest Pulse will not run on the new tablet.

The behavior is that upon startup, when I try to login, it says I can only have 1 main device and would I like to use the Fire as my new main device? When I click No, it goes into a loop, repeatedly asking me to abandon my main device, eventually stalling out on "Connecting to server..." which hangs indefinitely.

Weirdly, however, in the background (underneath the persistent login dialog), it tells me it is Optimizing and retrieving my messages and that my subscription is detected. When I let that finish, I can back out into the normal screen. I see the Text from any device box, but it still insists on my abandoning my main device when I try it.

The expected behavior is that Pulse should let me login on this device without insisting it become a main device. I suspect that this is some new side effect of the latest Google Play that isn't surmountable, but I thought I give reporting it a shot.

**Comment by klinker24** [comment]
Pulse is not going to work on an Amazon tablet, whether you have installed the Play Store or not, sorry. Pulse relies heavily on internal Android services that Amazon does not provide. The login is not going to be successful. This is why I have not distributed the app on the Amazon app store. 

I also make this note in my help page, if you search "amazon" or "fire"

https://messenger.klinkerapps.com/help

**Comment by jsseidel** [comment]
I can certainly appreciate not supporting the Fire. I wouldn't either. It used to work on my older Fire in any case, so I thought all it needed was the Play Store. The web interface is good enough in any case.
