### ISSUE TITLE
Contacts do not sync properly to either the Win10 or Linux client

### ISSUE THREAD

**Issue by ejwastaken** [klinker-apps/messenger-issues#898]
- [x ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [x ] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [ x] I have verified that this is something that is reproducible.

**Device with issue:** Intel/AMD based PCs (one Win10 Pro, one Ubuntu 18.04
**Primary device:** Samsung Galaxy S9
**App version:** 3.5

**Describe the bug:**
The contacts do not properly sync to either the Win10 or Linux (Ubuntu 18.04) clients.  I have looked at issue 460, and have properly followed the steps to re-sync my contacts from my phone, then download them to my desktops.  The behavior is erratic, sometimes finding a contact if I have an active sms conversation, but not always.

I do not keep any archived conversations, and I often have no conversations stored (I clear them out when the conversation is over).  If I start a new conversation from my phone (which has no problems with contacts), then I can continue it from a desktop client, but if I want to start a conversation from the desktop, 

**Steps to reproduce:**

1. Go to Pulse SMS app on desktop.  Steps 2/3 are from Issue 460 on re-sync of contacts
2. Sync contacts from phone to clound
3,  Start new conversation by clicking (+) on desktop client.
4. Start typing contact name, contact never shows, no matter how old or unchanged the contact data is.

**Expected behavior:**
I expected it to find the contact, and allow me to start the conversation.

**Additional information:**
I seem to be an outlier where I keep my conversations pruned, and I never archive conversations.  I don't know if it is able to find contacts from 'active' conversations that are available to the desktop client.

Because this happens on 2 different OSs, I believe this is not a porting issue.  If you need any other information, please let me know.

**Comment by klinker24** [comment]
The OS really doesn't matter at all. The desktop app reads the contacts stored in the web, which are uploaded from Android. The desktop apps simply display the web UI. It lets you search active conversations, or from the stored contacts list.

This is the same as #840. We will track this bug with that issue. It isn't specific to contact groups. I do not currently know why the contacts refuse to be uploaded for some, or the cases that cause this. 

I have run statistics against the database in the past. Less than 1% of Pulse users have under 30 contacts stored on their account. The rest of the Pulse accounts have had their contacts uploaded just fine. That makes it very clear to me that there is probably a very specific case causing them to fail to be uploaded. If I figure out more or what could be causing this problem, I will post any other updates or fixes on the referenced issue.
