### ISSUE TITLE
sending drafts don't clear actual message from text box

### ISSUE THREAD

**Issue by ghctim** [klinker-apps/messenger-issues#90]
Device with issue: Nexus 5x running Android 7.0
App version: 1.3

Steps to reproduce:
1. compose a message but don't send it
2. close the message thread
3. reopen the message thread and send it.

Expect to have compose box be cleared after sending but it sends the message text and leaves the same text in the compose box.

Possible solution:

**Comment by klinker41** [comment]
This is not happening to me.

**Comment by klinker41** [comment]
Probably a threading issue with this, made some changes to delete the draft before reloading data with https://github.com/klinker41/messenger/commit/b1fcd3c8408d079be399fe2d152225e49a8b3abe
