### ISSUE TITLE
Messages aren't syncing from phone to PC

### ISSUE THREAD

**Issue by are-dev** [klinker-apps/messenger-issues#900]
- [ ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behaviour.

- [ ] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.

**Device with issue:** running Chrome v54
**Primary device:** Sony E2363
**App version:** Ex: v4.11.2.2553

**Describe the bug:**
When I delete messages from my android phone, they don't get deleted from the web app. Even after repeatedly pressing the sync button on the web app, the status is the same.
Add any other context about the problem here. Device configuration, unique cases, anything that you think may be relevant.

**Comment by klinker24** [comment]
You can probably just use the "refresh account" option on the phone app to re-upload to the web. It will track everything after that.

You need to be using Pulse as the default SMS app on your phone, for it to work across devices, as well.

**Comment by are-dev** [comment]
I hope by "refreshing account" on the phone may not lose my all or a few messages.

Also, Pulse is the default SMS app on my phone.
