### ISSUE TITLE
"Sending" sound doesn't honor notification volume settings

### ISSUE THREAD

**Issue by eater** [klinker-apps/messenger-issues#901]
**Device with issue:** Pixel XL on Android 9
**Primary device:** Pixel XL on Android 9
**App version:** 4.11.5.2569

**Describe the bug:**
The volume and mute settings on my phone successfully control the volume of notification sounds, including received message. But the sound when I SEND a message is always the same volume, regardless of how I set the notification volume on my device.

**Steps to reproduce:**
1. Enable "Sound Effects" in Pulse settings.
2. Use volume keys or Do Not Disturb settings to set notification volume to 0.
3. Send a message from the Pulse app.
4. The "sent" sound is played at full volume.

**Expected behavior:**
According to the Pulse Help page, "The volume for this sent sound should match your notification volume."

**Additional information:**
I have read the "sent-sound" and the "notification-channels" section of the Help pages, and I have read issue #728 but I still don't know how to make the "sent" sound behave like other sounds on the device. I know how to disable it entirely, but that's not what I want. 
Just as a point of comparison, Textra (another Android SMS app) has a "sent" sound as well, and that one does behave the way I expect.

**Comment by klinker24** [comment]
Thanks for the report. It is fixed and will release with `v4.11.7.x`.

https://github.com/klinker41/messenger/commit/42899d7f7381eb848a77c2b7dd53d96857d26c0e

**Comment by eater** [comment]
I am now running 4.13.0.2618 and just turned on Sound Effects again for the first time since creating this issue. But it does not seem to be fixed.
