### ISSUE TITLE
Vertical spacing is still high

### ISSUE THREAD

**Issue by midenok** [klinker-apps/messenger-issues#902]
Please make vertical spacing in all lists for small font lower or configurable.

**Comment by klinker24** [comment]
Sorry, at this time, changing the font spacing (or adding a preference around it), is not planned.

With Pulse, I am going to stay away from these little "tweak" options. More options throughout the app does not amount to a better experience for the vast majority of users. If an option isn't immediately clear what it is for, then it probably will not be useful for those users. While everyone can understand "font size", people will not understand "font spacing".

I know that there are other apps that let you tweak every part of it, but that just isn't the goal for Pulse. There are times when I just need to select a default, and go with that choice

**Comment by midenok** [comment]
I see you have some knowledge about theoretical users but ignore requests from real users. Strange but sadly common situation.

**Comment by klinker24** [comment]
My knowledge about real users comes from feedback around my previous apps. Sliding Messaging, EvolveSMS, and Talon for Twitter were all based around customizing every single piece of the app. 

So thank you for your input, but your conclusion is simply false. I have been researching and exploring this topic for over 10 years. Pulse's success is a glowing example of putting this philosophy into place and the impact that it has on growth. 

Please do not assume that I have no evidence or experience to back up my thoughts. That is just incorrect. The best interest for one user is not always what is best for the rest of the users.
