### ISSUE TITLE
Text not centered.

### ISSUE THREAD

**Issue by BruynoogheMatthias** [klinker-apps/messenger-issues#903]
- [ x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [x ] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [~ ] I have verified that this is something that is reproducible. (I don't have multiple phones, but I did reinstall"

**Device with issue:**  Samsuns SM-G960F (S9)
**App version:**  V.4.11.5.2569

**Describe the bug:**
Text is not centered in text bubble.

**Expected behavior:**
Centered text

**Screenshots:**
![Screenshot_20190813-232513_Pulse](https://user-images.githubusercontent.com/26546613/62979759-f335cc00-be24-11e9-87c6-1c2a5cc1960c.jpg)

**Comment by klinker24** [comment]
Is this a new issue and have you changed the display density on the phone or anything? I have not seen this on my S9.

**Comment by BruynoogheMatthias** [comment]
When you mentioned display density, I remembered I always put my phone in battery saving mode. This drops resolution from WQHD+ to HD+.  I disabled battery saving mode and the text was centered now. I still want to enable battery saving tough, I get  a lot of hours out of it.

**Comment by klinker24** [comment]
Very interesting. Thanks for the report

**Comment by klinker24** [comment]
I have made changes around this for the next version of the app. I hope that it is fixed, but please report back here, if it is not.
