### ISSUE TITLE
Win64:Malware-gen antivirus warning

### ISSUE THREAD

**Issue by karakum** [klinker-apps/messenger-issues#905]
Firstly, Avast remove already installed version.
After full uninstall pulse-sms, download windows-app from https://messenger.klinkerapps.com/overview/platform-windows.html, run installer and got same warning:

![изображение](https://user-images.githubusercontent.com/12033941/63128625-9a5e6300-bfdf-11e9-8a98-58ead9653c18.png)

**Comment by klinker24** [comment]
The app is open source, you can verify for yourself that it does not have any viruses: https://github.com/klinker-apps/messenger-desktop

Thanks for letting me know. I will reach out to them to tell them that this is an inaccurate report.

**Comment by klinker24** [comment]
AVG has informed me that this report was in error and that they have removed it. I submitted the same false positive report to Avast and they have not replied yet.

I have not heard of any other anti-virus software that is flagging Pulse as malware and will update this comment when Avast replies.
