### ISSUE TITLE
Blacklist phrase for sender only

### ISSUE THREAD

**Issue by nogos** [klinker-apps/messenger-issues#908]
- [X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.
- [X] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.

Could a feature to blacklist phrases strictly for the contact's address be added? I've been getting a lot of messages from spammers using email addresses as their reply-to's. Just blocking the TLDs would be sufficient in stopping their attempts, but I don't want to be prevented from receiving texts with URLs.

Pretty much everything I've seen to combat the issue is dubious, shady, or just doesn't work. I really don't want to switch to a completely awful app just because android won't let me block the flood of spam.

**Comment by klinker24** [comment]
I don't think that I really understand what you mean, sorry. How would blocking by phrase be applied to a senders address (email or phone number)? Are you just trying to block all messages when the sender is an email address? For example, you would blacklist `@`?

I don't know if that is something that I would want to bring to Pulse... If you are trying to block all email senders, I understand what you are looking for, but there has to be a safer way to block these spam messages, via some phrase within the messages or something. Perhaps if you are getting that many of them, it is something that you should contact your carrier about?

**Comment by nogos** [comment]
Sorry I wasn't very clear: I'd been too long without sleep when I wrote it. I get a bunch spam messages from domains that are clearly random and bought on the cheap or spoofed. Something like "jsyyowk.us". They change the user and domain they use both on every message. It's getting really out of hand when I get six or so a day. Blocking email address senders entirely would be a problem since I like to send messages to my phone via my email: it's a quick way to transfer info and keep it someplace I can easily reference.

**Comment by klinker24** [comment]
I am not sure I understand what you are looking for, then. How would your request help prevent these spam messages, if they are random and change all the time?

**Comment by klinker24** [comment]
Sorry, without more understanding around how this would work or help, I am going to close this issue. Feel free to comment back, with the requested information, and I can re-open if required.
