### ISSUE TITLE
Resetting Account Password

### ISSUE THREAD

**Issue by JRAllen72653** [klinker-apps/messenger-issues#909]
- [x ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [x ] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [ ] I have verified that this is something that is reproducible.

**Device with issue:** Windows Desktop and Windows Browsers
**Primary device:** Samsung S7 edge
**App version:** v2.1.0
**Describe the bug:**

**Steps to reproduce:**

`... more steps`

**Expected behavior:**

**Screenshots:**

**Additional information:**
Add any other context about the problem here. Device configuration, unique cases, anything that you think may be relevant.

**Comment by klinker24** [comment]
Pulse is down. Both AWS and Heroku are having outages and there is nothing I can do on my side to fix this downtime. We just have to wait for it to be resolved.

**Comment by JRAllen72653** [comment]
Thany You!

Joe Allen, N5JRA
