### ISSUE TITLE
Able to schedule messages in the past

### ISSUE THREAD

**Issue by ghctim** [klinker-apps/messenger-issues#91]
Device with issue: Nexus 5x running Android 7.0
App version: 1.3

Steps to reproduce:
1. go to scedule message
2. Select a contact
3. Pick a date in the past.

Expect to only be able to pick today or future dates.

Possible solution:
Don't allow scheduling of messages in the past

**Comment by klinker41** [comment]
fixed with https://github.com/klinker41/messenger/commit/69d72c6a7a3a543deefc03eba06d31625e54efaa
