### ISSUE TITLE
Contacts not showing in group conversation after recently added

### ISSUE THREAD

**Issue by jasekiw** [klinker-apps/messenger-issues#910]
- [ x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [x ] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [x ] I have verified that this is something that is reproducible.

**Device with issue:** Samsung Galaxy S9+
**Primary device:** Samsung Galaxy S9+
**App version:** 4.11.7.2579

**Describe the bug:**
I was in a group chat and didn't have anyone's number. So I went through and added each as a contact. I was sad to see that the contact would not show up next to their messages but will show in the list if you press the contacts button at the top right of the group.

**Steps to reproduce:**

1. Start a group chat with a few messages.
2. Click on the contacts icon at the top right
3. Add someone as a contact (using google contacts app)
4. To make sure it is not https://github.com/klinker-apps/messenger-issues/issues/790 or 
https://github.com/klinker-apps/messenger-issues/issues/785 , close and restart the app.

**Expected behavior:**
The contact's name will show next to their messages

**Comment by klinker24** [comment]
Duplicate #360

**Comment by jasekiw** [comment]
@klinker24 Thanks! I missed that one!
