### ISSUE TITLE
Unread Messages in Conversation List aren't very noticeable

### ISSUE THREAD

**Issue by GhostmanPFA** [klinker-apps/messenger-issues#911]
- [yes ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.
- [ yes] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.

**Describe your request:**
A clear and concise description of what you would like to see, and why.

- I would like for unread messages in the conversations list to be more noticeable.

**Describe alternatives you've considered:**
A clear and concise description of any alternative solutions or features you've considered. There may already be something that is built into the app, or the platform, that is very similar.

- I realize that unread messages show with bold text, but it really isn't that noticeable and if the last sent text was a emoji or image it's even less noticeable.

- My initial thought is to make the background color of the unread conversation line a contrasting color of the read conversations.

- Another option could be to have an icon to the side of the conversation with an unread message.

**Additional information:**

**Comment by klinker24** [comment]
There is already an indicator icon, right next to the title of the conversation
![Screenshot_20190906-082429](https://user-images.githubusercontent.com/4874287/64454337-55928d00-d0b0-11e9-8f6e-730afbe12bef.png)

**Comment by GhostmanPFA** [comment]
I’m sorry, I’m not sure how I missed that.   Maybe I had the colors too similar or something.  Thank you for the response!  I’m just getting used to the app and figuring out all of the features.  I like the ability to name groups, customize colors, access from other devices, and pin groups to the top.  I’m sure there are a lot of other features I’ll discover as well.  Thanks again.

Sincerely,

Mark Kirkman

________________________________
