### ISSUE TITLE
Picture messages sent to wrong contact when changing conversations during send

### ISSUE THREAD

**Issue by elipriaulx** [klinker-apps/messenger-issues#913]
**Device with issue:** Windows 10 Pro, 1903 (18362.356)
**Primary device:** Pixel 3
**App version:** 4.11.8.2591 (Android), 4.0.1(PC)

**Describe the bug:**
If I compose a message on PC including some text and an image I paste in the message box, this is usually instead sent as 2 messages. If when I send it, I then change conversations immediately, the picture is instead sent to the new conversation I have changed to, and not the one I intended to send it to.

**Steps to reproduce:**

1. Open Pulse on PC.
2. Select a conversation.
3. Compose a message including a pasted image and text.
4. Send message.
5. Immediately change conversations/contacts and start composing a new message.
6. Observe that image is sent to currently selected contact, not intended contact.

**Expected behavior:**
Image and text should be sent to original target conversation, but instead image is sent to latest conversation.

**Screenshots:**
NA

**Additional information:**
NA

**Comment by klinker24** [comment]
I will keep digging into this. As of now, I have not been able to reproduce this issue. Different hardware could amount to different race conditions, though.
