### ISSUE TITLE
Major issue when switching from Pulse back to Android default Messaging app

### ISSUE THREAD

**Issue by crazysaguaro** [klinker-apps/messenger-issues#915]
- [x ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [ x] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [ x] I have verified that this is something that is reproducible.

**Device with issue:** Samsung Galaxy S10 with Android 9 on AT&T, Samsung Galaxy Tab S5e with Android 9
**Primary device:** Samsung Galaxy S10 with Android 9 on AT&T
**App version:** 4.11.8.2591

**Describe the bug:**
Pulse has been the default messaging app on my Samsung S10 phone since approximately Feb 2019.  Last week, it was not receiving all messages from users - some messages would be received in my default messaging app instead of Pulse even though it was not the default app.  These messages never appeared in Pulse and I only could reply to them by switching the default messaging app back to Messages and replying to them there.  

I got frustrated so decided to stop using Pulse and switch back to the Android default Messages app.  When I did this change, my phone freaked out and started sending a massive amount (hundreds) of MMS texts that had come from my other Pulse device (my Samsung Galaxy Tab S5e).  Hundreds of photos went out when I switched the default app back to Messages - one of my friends got over 100 texts.  I had to factory reset the phone to stop it from resending all these texts out and now am afraid to reinstall Pulse even though I paid for the app.

**Steps to reproduce:**

1. Switch phone from Pulse as the default messaging app back to Messages (the Android default messaging app).  Then that is when this happened.  The phone only resent text messages that *originated* on my tablet - no text pics or messages that originated on the phone (the default device) were resent.  A selection of messages that originated on my tablet we resent when I switched the default app back - not all messages.

**Expected behavior:**
I did not expect my phone to send out 100s of text messages to my contacts without my knowledge.  These texts seemed to be "stuck" in the system somehow between my tab and phone - and when I switched the default app back to Messages on my phone, they all automatically were re-sent out.

**Screenshots:**
No screenshots

**Additional information:**
My carrier is AT&T.

**Comment by klinker24** [comment]
I have an "RCS" topic on my help page that discusses why some messages would be appearing in the default messaging app and not Pulse: https://messenger.klinkerapps.com/help

When you switch away from Pulse as the default messaging app, I can no longer control what is being sent or what is happening on your device. When you switched to the stock messaging app, that app is what is sending the messages. Whatever bug caused this is not in my control. Reinstalling Pulse will not resend any messages and setting Pulse as the default messaging app would never resend any messages. My app just doesn't do that

**Comment by crazysaguaro** [comment]
Hi, thanks for the reply. Yes, the items in the RCS area do probably explain why those messages were appearing in the Messages app and not Pulse even though Pulse was the default (they were from another Samsung Galaxy S10 user - I can see her 'read' and 'delivered' receipts on messages).  We both did have advanced messaging enabled - but now I will turn it off.

Is it possible that after disabling Pulse on my default device (the S10 phone) that the app on the tablet somehow triggered these texts to be sent out with the default Android Messages app on my phone via the Pulse server? I did not uninstall Pulse on my tab or PC (web/Firefox) when I disabled Pulse on my main device (the Samsung S10 phone).

I'm just trying to understand how/why this happened - if I can get a good understanding, I may reinstall Pulse as it was great when it worked.

**Comment by klinker24** [comment]
No, that isn't possible. The tablet has no clue if your phone is set as the default messaging app or not. Pulse has no logic to resend messages, ever. Whatever happened, it didn't happen from my app. The app that you switched to resent those messages.

**Comment by crazysaguaro** [comment]
OK - thanks for your replies - I know your time is valuable. :)
