### ISSUE TITLE
Messages sent from other apps/devices not syncing to Pulse app

### ISSUE THREAD

**Issue by e-t-l** [klinker-apps/messenger-issues#916]
- [X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [X] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [X] I have verified that this is something that is reproducible.

**Device with issue:** Ex: Pixel 3 on Android 9
**Primary device:** Ex: Pixel 3 on Android 9
**App version:** Ex: v4.11.8.2591

**Describe the bug:**
Messages sent from other apps/devices (in this case, using the Your Phone desktop app on Windows 10 PC, with the Your Phone Companion app on the Pixel 3) do not sync to the Pulse SMS app on the phone. 

**Steps to reproduce:**

1. Connect Android phone to Windows 10 PC with Microsoft's "Your Phone Companion" and "Your Phone" apps, respectively.
2. In "Your Phone" on PC, click "+New Message" and send an SMS to a recipient.
3. Open the Pulse app on the Android phone.
4. See that the sent message has not synced to the relevant conversation.

**Expected behavior:**
When sending a message through "Your Phone," users expect the message to appear in their default SMS app. (Although the SMS _is_ successfully sent, and it _does_ appear in the OEM Android Messages app, it does not appear in Pulse. Restarting the phone, force-stopping and restarting Pulse, and clearing Pulse's app cache have no effect).

**Additional information:**
I understand that Pulse has a dedicated desktop client that you prefer users use in order to text from a PC, however not all users a) can or want to pay for premium, and b) prefer Pulse's layout/features over other desktop SMS clients. The fact that Pulse is unable to accurately reflect the messages sent from the device it is installed on is troublesome and may be indicative of greater underlying issues. (To be clear, the "Your Phone" app simply sends an intent to the linked Android device, telling it to send an SMS/MMS to a recipient. I have confirmed that this is working as designed, and as previously mentioned, the sent messages do appear correctly in other texting apps like Android Messages. This is true even when Android Messages is not set as default texting app. Hence why I'm describing this as an issue with Pulse accurately reflecting the SMS data on the phone, rather than an issue with a specific Windows build or program.)

**Comment by klinker24** [comment]
I discuss how Pulse works with other messages sent by other devices, if you search "assistant" on my help page

https://messenger.klinkerapps.com/help

Sorry, at this time, there are no plans to expanding this support or exploring alternative options for pulling in these messages.
