### ISSUE TITLE
Auto Save MMS not Working

### ISSUE THREAD

**Issue by im-nolan** [klinker-apps/messenger-issues#917]
- [x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [X] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [X] I have verified that this is something that is reproducible.

**Device with issue:** BlackBerry KeyOne & Sony Xperia XZ Premium 
**Primary device:** BlackBerry KeyOne
**App version:** 4.11.8.2591
**Describe the bug:**
Currently I have Auto-Save Media set up and when a new MMS comes in, nothing is saved. Tried changing directory of save but still no go.

**Steps to reproduce:**
Turn on Auto-Save Media, have an image sent to yourself. 

**Expected behavior:**
Expected the image to be saved to the designated directory

**Comment by klinker24** [comment]
Hmm, it appears to be working fine for me. Images are saved to the default directory on Android 10 and 9: `Pictures` -> `Pulse`. What version of Android are these phones on?

**Comment by im-nolan** [comment]
I swear to you it wasn't working. I'm so sorry to have wasted your time.
