### ISSUE TITLE
More advanced setup for auto replies

### ISSUE THREAD

**Issue by toxpal** [klinker-apps/messenger-issues#918]
Searching for simple SMS solution with auto-respond option for small business' needs, and Pulse caught my attention, so I gave it a try.

Auto respond worked well, but I miss few features:

1. Option to set time interval between auto responses. For example, if I set interval to 24 hours, Pulse should only auto-respond to the same number once every 24 hours. It will prevent SMS "spam" when someone sends multiple messages to you. If that's too much too ask, can you at least add an explanation in app that says what is "hardcoded" interval? I ask so because if I try to send another SMS right after receiving auto-response, Pulse doesn't send auto-response again. Which is good. If I do the same after an hour or so, Pulse does send the same response again. So I guess there's some interval hardcoded already?

2. Option to only respond to local messages. It could work by allowing user to specify area code or "extracting" user's area code from the phone (SIM). I think it would be extremely useful because while testing auto-response, I got some SMS from other countries (like various verification SMS to activate accounts, etc.), and sure enough, Pulse auto-responded to them properly, which will end in some higher than usual monthly bills :)

Thank you for your consideration.

**Comment by klinker24** [comment]
I will link this with #673, which is currently set up to track requests around the auto reply system. Thanks for the suggestions!
