### ISSUE TITLE
Drafts are not always saved

### ISSUE THREAD

**Issue by jwulf1092** [klinker-apps/messenger-issues#919]
**Device with issue:** LG V30 ThinQ phone
**App version:** 4.11.9.2596

**Describe the bug:**
There have been 20 to 30 times, or more, over the past 3 or so months that I have written text in a conversation, not sent the message as I was not done with it. Left that conversation, come back and some of the text I typed is gone.

Things I know:
* I have to LEAVE the text conversation for the typed text to be lost. I can not determine what causes typed text in a conversation to be lost or not lost.
* When I loose text, it is ALWAYS only part of the text message. It is ALWAYS a latter part of the text message, with the first part (sentence, half sentence, or maybe a paragraph) still there.
* It often seems like I start a message, leave the text, come back, continue the message, leave again, and then when I come back the third time, the second part I typed is now gone.
* The problem most often seems to happen when a popup causes me to leave the message, but not always, sometimes it is via the square apps list button (which minimizes the open app, gives me a scrolling view of all apps open).

**Steps to reproduce:**
I can not give you those as I can not figure out any steps that are consistently reproducible to cause the issue. I just know that it has happened on so many occasions, that it can't be my fat fingers, or a surge from the sun LOL.

I am sharing this in the hopes that it helps, but I do realize i am not giving you the amount of info you would like. I truly am sorry about that, as I would like to see it fixed!

**Expected behavior:**
I expect all text that was typed in a conversation, but not sent, to still be in that conversation when I return to the conversation.

**Comment by klinker24** [comment]
GitHub is a website owned by Microsoft and is used by almost every developer around the world. Sorry that you forgot your password, but that has nothing to do with me, or Pulse. I have removed that comment, from your issue.

Thank you for the report on this. If you get any reliable steps to reproduce this issue, it would be helpful. As it is now, I do not really have a way to start looking at this or a way to verify if it is fixed. I am not experiencing this issue myself, and I have not heard from anyone else, but that doesn't mean it isn't happening.

**Comment by jwulf1092** [comment]
Luke,

Thanks for your reply.

Microsoft, that explains a lot… I totally understand you removing that part of the report.

And to clarify I didn’t lose it, I knew it, but was FORCED to change it to something more complex.

 

It does seem close to issues #816, but when reading it, I could not figure out how you resolved that issue.

JW

**Comment by klinker24** [comment]
#816 does not appear to have anything to do with this. That is an issue on notifications

**Comment by klinker24** [comment]
With the next release, I have changed the way that drafts are managed. I am going to close this. If you continue to have issues, please comment back here with more reliable steps to reproduce the issue, and I can re-open it.
