### ISSUE TITLE
Conversation Icon shows ( when texting a #, not a contact

### ISSUE THREAD

**Issue by ghctim** [klinker-apps/messenger-issues#92]
**Device with issue:** Nexus 5x running Android 7.0
**App version:** 1.3

**Steps to reproduce:**
1. compose a message to a phone number that isn't a contact
3. send the message

In the message list the conversation list shows the icon as (

**Possible solution:**

Maybe pick the first digit of the phone number and ignore the ( char

**Comment by klinker41** [comment]
Fixed with https://github.com/klinker41/messenger/commit/cc8ed2fd3e393f70eb12eca07bf16ae9001285e6.

Nothing will be displayed in the circle when there isn't a name available.
