### ISSUE TITLE
Android: First-time importing and/or "resync" of existing, on-device messages doesn't work

### ISSUE THREAD

**Issue by mitchware-cfa** [klinker-apps/messenger-issues#922]
- [X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [X] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [ ] I have verified that this is something that is reproducible.
  - I'm _not quite sure_ if this is reproducible, or local to my device, or an Android 10 issue, but I've provided my reproduction steps as best as I can

**Device with issue:** Pixel 3, Android 10
**Primary device:** Pixel 3, Android 10
**Pulse App version:** 4.11.9.2599
**Messages App version:** 4.8.058

**Describe the bug:**
I see zero messages in pulse after importing my existing, on-device messages that are visible in the default "messages" app. I was using Messages for a while, without issue, and switched back to Pulse. I have a lifetime subscriber account, and I set Pulse to be my Default SMS app. I went into My Account > Resync Messages to do the re-import/replacement of the server messages with what's local on my phone and after it completed, I see zero messages in pulse. If I switch the default back to Messages, I still see all my messages show up as I expect them to. If I then uninstall Pulse, re-install and start fresh with the initial sync/import phase, my messages import into Pulse as expected. However, once I log in and enable the server-side sync/upload, Pulse goes back to inbox zero and shows no messages.

**Steps to reproduce:**

1. Start with Messages set as the default SMS app & have some existing SMS messages saved locally.
2. Install Pulse, set as default SMS app, and go through initial import phase.
  - See that the messages are imported into Pulse correctly.
3. Log in with lifetime subscriber account in an attempt to sync local Pulse messages with the server
4. Login succeeds and messages in Pulse inbox go away. 
5. Switch default SMS app back to Messages and notice the messages still exist locally as expected.

**Expected behavior:**
Logging in with my account to do the server upload shouldn't modify the inbox locally.

**Screenshots:**
N/A

**Additional information:**
Happy to provide more on-device or debugging information, if it would be helpful! Android dev. here - familar with debugging tools and side-loading APKs. Let me know if there's additional info or on-device logs I can pull for you.

**Comment by klinker24** [comment]
Logging in to your account on any device is always going to download what is in the cloud, to that device. That is working as expected and how it is designed to work. It does not wipe your devices database, it downloads the messages to Pulse.

To solve your issue, you can delete the account, reinstall the app, then recreate the account. Google will restore your purchase automatically, to the new account.

**Comment by mitchware-cfa** [comment]
Ahh okay, I see. Thanks for the clarification! 

Given how non-obvious that process is (I certainly wouldn't have thought to delete my entire account and make a new one, for fear of losing my purchase), this might make sense to add as a new FAQ item :)

**Comment by mitchware-cfa** [comment]
> Restoring the account does not wipe your device's internal SMS database or affect what is available within other SMS apps. It just downloads the messages to Pulse.

Is it possible to add a new option to that same My Account page that essentially does this, but uploads the internal SMS database to Pulse and replaces what's previously saved? I basically have my local SMS database serving as the source of truth and I want that to replace what Pulse thinks is its _own_ source of truth (which I thought "restore my account" would do). Does that make sense?

**Comment by mitchware-cfa** [comment]
(also I see now that this is called out in the FAQ under "delete account" - which is super helpful! but again, slightly non-obvious for my "how to I upload my local SMS into the cloud and replace whats there" scenario)

**Comment by klinker24** [comment]
Topic on how downloading works and what you can do for your issue

![Screen Shot 2019-09-24 at 1 37 15 PM](https://user-images.githubusercontent.com/4874287/65540203-87895900-ded0-11e9-8b70-5a3d331f25e8.png)

Another topic around the different debug options within the app

![Screen Shot 2019-09-24 at 1 37 31 PM](https://user-images.githubusercontent.com/4874287/65540316-bf909c00-ded0-11e9-8b98-3ca2691d5e71.png)
