### ISSUE TITLE
Edit the title of individual conversations

### ISSUE THREAD

**Issue by JoshuaGarrison27** [klinker-apps/messenger-issues#924]
**Describe your request:**
It would be nice to be able to specify what format you want a contact name to show up in. So for example, I have some people who I have their First, Middle, and Last name. They show up that way in the messages list and in notifications. 

Example:
If you have John Dorian Doe as a name in your phone than it will show up that way in the conversations. Maybe there could be an option to show a certain format like 'John Doe' (without the middle name)

**Describe alternatives you've considered:**
Maybe add an options to choose from a list of formats in settings to show contacts as. Such as:
- First Middle Last
- Last, First Middle
- First Last
- Last, First
....etc.....

**Additional information:**
N/A

**Comment by klinker24** [comment]
I'm not sure if that is a preference I want to add. For the vast most people, it just wouldn't be useful. I could probably allow you to edit the title of a conversations, though. Pulse already has this for group messages and I don't see why I couldn't apply it to individual conversations, too. 

I will consider this for the future. Thanks for the request.

**Comment by JoshuaGarrison27** [comment]
That is fair. I only have a few contacts that have a middle name. I appreciate you taking this feature into consideration. I believe you are right that changing the title of a conversation would be better in this case. Thanks!

**Comment by JoshuaGarrison27** [comment]
Thank you @klinker24. Looking forward to the update.
