### ISSUE TITLE
Support Slack style emoji notation - :word:

### ISSUE THREAD

**Issue by rnhurt** [klinker-apps/messenger-issues#925]
**Describe your request:**
It would be nice to type my emoji using something like the Slack or GitHub "standard".  
1. type a colon character
1. have a popup/dropdown window appear with most recent emoji's
1. start typing a word (ie. smile, heart, water, etc.) and have the emoji's change
1. choose an emoji and hit <ENTER> to insert that emoji into the text

**Describe alternatives you've considered:**
There is a smiley face icon on the left hand side of the text input window that works just fine.  However, it forces me to take my hands off the keyboard and mouse around.  :disappointed: 

**Additional information:**
Obviously, this is more important for the desktop clients, as the mobile clients usually have a "keyboard" that exposes these types of things.

**Comment by klinker24** [comment]
This isn't really something that I am interested in adding to the Android app, but I think it would be great in the web app. If you want to contribute, the web app is open source

https://github.com/klinker-apps/messenger-web
