### ISSUE TITLE
Sender id not showing from short number (1010)

### ISSUE THREAD

**Issue by evkolot** [klinker-apps/messenger-issues#932]
Hello, thank you for the great app.
I have a slight annoyance, though. When I receive message from certain short number (1010 to be precise) sender id is not showing in all versions (web, wear is, Android version)
![IMG_20191022_141404](https://user-images.githubusercontent.com/3210989/67281073-50aa6100-f4d7-11e9-92a4-4882937e9270.jpg)

**Comment by klinker24** [comment]
This could happen if you had this number stored in your contacts and removed it, or your phone didn't provide Pulse with the contacts permission.

You could delete the conversation, and it would show a title the next time you received a message from them. Or, you can go to the settings menu for the conversation and set the title yourself, from the top preference.
