### ISSUE TITLE
Set as default notification shows up even if default 

### ISSUE THREAD

**Issue by SonOfDiablo** [klinker-apps/messenger-issues#933]
The notification about the new policy that says sms apps has to be set as default to access messages shows up every time Pulse is opened, even when Pulse is the default sms app.

On a Oneplus 7T Pro, Android 10, Oxygen OS 10.0.3.HD01BA.

**Comment by klinker24** [comment]
If that message is showing up, then Android is telling the app that it is not the default. This isn't something that I can control. I have not had anyone else report this issue and I don't know what else I can say about this, unfortunately...

You could try just reinstalling the app.

**Comment by SonOfDiablo** [comment]
I reinstalled the app and it seems to be working fine now...
