### ISSUE TITLE
Default settings

### ISSUE THREAD

**Issue by ulriad01** [klinker-apps/messenger-issues#934]
- [x ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.
- [x ] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.

**Describe your request:**
A clear and concise description of what you would like to see, and why.

Open messages at top of page when a new message is recieved instead of previous location in the app. This is the default in most messaging services. I know this is nitpicky, but I love the app so I thought I'd share.

**Describe alternatives you've considered:**
A clear and concise description of any alternative solutions or features you've considered. There may already be something that is built into the app, or the platform, that is very similar.
I haven't found a way
**Additional information:**
On Android 10

**Comment by klinker24** [comment]
I don't think that this is the "default in most messaging services", and it definitely isn't the default for Android. Android, as a platform, is designed to hold app state across different sessions. That is why, when you close any app and re-enter it, you are still in the same place. 

For example, in Gmail, you open an email on the phone. Then on the web app, you archive or delete that email. When you open Gmail again on your phone, you will still be viewing that email. 

Another example from Gmail, closer to what you are describing... 

1. go to your list of "all mail" on the phone app
2. scroll down a ways and close the app
3. Send yourself an email from the web app
4. When you re-enter gmail on your phone you are still in the same place on the list, despite a new email having arrived. 

Like I said, Android, as a platform, is designed for you to come back directly where you left off. I really do not want to change this functionality within Pulse, sorry. I would very much like to stick with the system-designed functionality, where possible.
