### ISSUE TITLE
Contact Picture not showing in Notifications

### ISSUE THREAD

**Issue by JoshuaGarrison27** [klinker-apps/messenger-issues#935]
- [X] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [X] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [X] I have verified that this is something that is reproducible.

**Device with issue:** Google Pixel 3 XL
**Primary device:** Google Pixel 3 XL
**App version:** 4.13.1.2623

**Describe the bug:**
Contact photos are not showing up in notifications.

**Steps to reproduce:**

1. Install application from Play Store
2. Get a text message from someone
3. Pull down notification drawer and view notification.
4. See only a color with contacts initial but not their contact photo

**Expected behavior:**
The notification should have the contact's photo in the notification beside their message.

**Additional information:**
Things that I have tried to do to fix the issue:
- My Account > Resync Messages
- My Account > Resync Contacts
- Clear Cache (Android Settings)
- Clear Storage (Android Settings)
- Uninstalled and Reinstalled

**Comment by klinker24** [comment]
Thanks for the report. I had noticed this, but hadn't thought about it. 

It is fixed and will be released with `v4.13.3`.
