### ISSUE TITLE
Create message management rules like Outlook. ie. Route Messages From X Sender To Folder Y

### ISSUE THREAD

**Issue by brycebba** [klinker-apps/messenger-issues#936]
- [ X ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my request to verify that there aren't any open or closed issues similar to this behavior.
- [ X ] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that there are not any topics discussing similar behavior.

**Describe your request:**
Add the ability to create message routing rules for purposes of managing messages and notifications from those messages. The blacklist is already a great start to this at deleting messages, now I'm suggesting automatically routing messages to certain folders. Some sample use cases are below and the words in caps would be options for the rule

Route Messages from SENDER X to FOLDER Y
Route Messages with PHRASES ("blah blah blah", "foo bar blah") to DELETE MESSAGE
Route Messages from NUMBERS ("%%%%%", 52146, 9876) to FOLDER Y
Route Messages from CONTACTS (Jim Brown, Mike Stuart) to FOLDER Y *I realize this one already exists but just showing how it could be implemented as a rule type statement

I understand that I am talking within the Context of Messages and NOT necessarily Conversations which makes me think these are really filtered views of Conversations List. If one message does not meet matching criteria then the full conversation should be show in the Conversation List view which I would consider almost an All directory but if ALL messages from that sender match a rule then the only place to see the entire conversation would be within the folder it was routed to or something like that. But the filters would keep messages out of the Unread Conversations view if they are destined to be deleted or routed to a Folder with "Show Folder Messages In Unread" (new setting) in OFF where ON would keep them in the Unread view. Another new setting would be to trigger a notification or not trigger a notification for FOLDER Y.

This would help users keep their Unread Messages to the important items instead of potential spam or unwanted stuff. 

**Describe alternatives you've considered:**
I currently use the Blacklist to manage phrases I want deleted (iOS message reactions for example) but this doesn't handle moving messages around that I want to keep or conditionally delete in an easier way to enter.

**Comment by klinker24** [comment]
I really don't think that this is something that is going to come to Pulse, sorry. I just don't think that it really makes sense when everything is managed in conversations, while emails are managed in a thread. They are just a very different style of messaging, meant for different purposes.

You can already place a conversation from a contact or phone number into a folder, then all messages from that person will be routed there. That is half of what you are asking for, but I don't think that changing the way that it is displayed so that it is a "rule" statement changes or improves the functionality in any way. I just don't think that routing based on the contents of individual messages really makes sense for an SMS app

**Comment by brycebba** [comment]
> I really don't think that this is something that is going to come to Pulse, sorry. I just don't think that it really makes sense when everything is managed in conversations, while emails are managed in a thread. They are just a very different style of messaging, meant for different purposes.
> 
> You can already place a conversation from a contact or phone number into a folder, then all messages from that person will be routed there. That is half of what you are asking for, but I don't think that changing the way that it is displayed so that it is a "rule" statement changes or improves the functionality in any way. I just don't think that routing based on the contents of individual messages really makes sense for an SMS app

No worries at all. I still love your app!
