### ISSUE TITLE
Unable to receive vCards

### ISSUE THREAD

**Issue by ghctim** [klinker-apps/messenger-issues#94]
**Device with issue:** Nexus 5x running Android 7
**App version:** 1.3.321
**Information:**

Unable to receive contact vCards.

**Steps to reproduce:**

1. Receive message with vCard attachment
3. vCard shows in native messages DB but not in your app.

**Comment by klinker41** [comment]
Don't see how that could be happening, the app receives messages and saves them to both databases. Unless you mean that the initial import does not grab those messages. If that's the case, you'll need to be more descriptive, there's nothing I can do with this issue as it stands.

**Comment by ghctim** [comment]
What I mean is when someone sends me a vCard your app doesn't display the
message.  When I open the default messages app the message and vCard are
there. Try it. Have someone text you a vCard

**Comment by klinker41** [comment]
Working fine for me.

**Comment by ghctim** [comment]
Could it be a Verizon issue?

**Comment by klinker41** [comment]
No. If Messenger is your default app, then it will save the message to its own database and then to the internal database. If it fails to save to its own database then it will not save it to the internal database either, making it impossible for Messenger to save it only to the internal database.

**Comment by ghctim** [comment]
So odd. I can share screenshots of it happening 2x.

**Comment by skelitonlord** [comment]
![sep 14 2016 6 26 47 pm](https://cloud.githubusercontent.com/assets/6839836/18532290/38dfd736-7aa9-11e6-9f08-be8f24661cc0.png)

I actually have the opposite issue, when sending a vcard, the other person gets some random .MMS file that doesn't open anything, but when receiving it works fine. Consistently happens on an iPhone, but every once in a while on Android. 

Nexus 6P Android Nougat
App version:  1.3.335

**Comment by klinker24** [comment]
Duplicate here: https://github.com/klinker-apps/messenger-issues/issues/101
