### ISSUE TITLE
Screen Auto-Rotation Occasionally Deletes Text in the Input Field

### ISSUE THREAD

**Issue by MrHallows** [klinker-apps/messenger-issues#940]
- [ ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [ ] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [ ] I have verified that this is something that is reproducible.

**Device with issue:** Ex: MacBook Pro on MacOS 10.12, running Chrome v54
**Primary device:** Ex: Pixel XL on Android 9
**App version:** Ex: v4.1.5

**Describe the bug:**

**Steps to reproduce:**

`... more steps`

**Expected behavior:**

**Screenshots:**

**Additional information:**
Add any other context about the problem here. Device configuration, unique cases, anything that you think may be relevant.

**Comment by klinker24** [comment]
You will need to fill out the issue template, please. It really isn't just there for looks.... 

I am unable to replicate any issues with this on my devices, so some set of steps to reproduce it consistently will be required for me to be able to fix this issue.

**Comment by MrHallows** [comment]
Luke,

I appreciate the dry humour, but I did not submit the template
intentionally. I was attempting to fill it out on my mobile, but was
experiencing loading issues. I will be submitting the completed form once I
get home. My apologies for the hiccup and any inconvenience it may have
caused you.


Kind Regards,

Andrew Gibson

**Comment by torzsmokus** [comment]
I can confirm this issue; I am also experiencing this on my Wileyfox phone, and this is very annoying.
I just came here to file a bug on this. Please reopen.

**Comment by torzsmokus** [comment]
Or should I file a new one, with the template filled correctly?

**Comment by klinker24** [comment]
I will need steps to reproduce this issue, to be able to fix it. I do not experience this on any of my devices.

**Comment by torzsmokus** [comment]
According to my experience, a quite full RAM is prerequisite for reproducing the issue, so it is not straightforward. Will try to come up with reliable steps.
