### ISSUE TITLE
Sending SMS with Your Phone app on PC doesn't show text in Pulse

### ISSUE THREAD

**Issue by srchulo** [klinker-apps/messenger-issues#941]
- [ x] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [x ] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue.
- [x ] I have verified that this is something that is reproducible.

**Device with issue:** Samsung Galaxy S10+
**Primary device:** Samsung Galaxy S10+
**App version:** v4.14.1.2642

**Describe the bug:**
When I use the Windows Your Phone desktop app to send texts, those texts to do not show in Pulse and the conversation is not moved to the top. Once someone responds, then any previous texts that I sent appear above their response and the conversation is moved to the top.

**Steps to reproduce:**

1. Link your PC with the Your Phone Companion app.
2. Send a text using the PC app to someone not at the top of your conversation list.
3. Go to Pulse
4. Note text not in conversation and conversation not moved to the top of conversations.

**Expected behavior:**
Text that I sent should appear in the conversation, and conversation should be moved to the top of conversations as if I sent the text from Pulse.

**Additional information:**
It's possible this may occur for anything on device that sends a text and is not Pulse, not just the Your Phone app.

**Comment by klinker24** [comment]
I have a help topic that discusses how Pulse works with messages sent from different apps. It is under the "assistant" topic on my help page

https://messenger.klinkerapps.com/help

This is not something that I plan to put any time into, right now. Pulse already provides a desktop application to use and that is what I am going to continue to push.

**Comment by srchulo** [comment]
Ah, thanks! I missed that.

**Comment by srchulo** [comment]
I definitely understand you not wanting to put in time on this (not pushing for that), but isn't this on the help section wrong?

> Google Assistant doesn't provide any callbacks or methods to notify third party apps that a message was sent.

Maybe Google Assistant doesn't, but can't you just have a content observer on `content://sms` and inspect the type of SMS?

https://stackoverflow.com/a/34694953/834140

Not a big deal, but may be confusing in the help section. I believe I've used other SMS apps that have updated when the system or a third party app sends an SMS.
