### ISSUE TITLE
Disable, cancel pop up sms - Flash sms class 0

### ISSUE THREAD

**Issue by rancidfrog** [klinker-apps/messenger-issues#942]
Is there a way to cancel, disable, block Flash SMSes, class 0 sms without user interaction and without displaying pop-up?

Network provider send them a lot asking to subscribe to service (Okay, Cancel), which appear anytime, i.e. while watching video.
It is easy to click okay by mistake

Thank you

**Comment by klinker24** [comment]
Pulse has a blacklist. You can blacklist by phrase to block these messages, or by whatever phone number they are coming in from.
