### ISSUE TITLE
Login issue Samsung Galaxy Watch Active 2

### ISSUE THREAD

**Issue by lovesarahh** [klinker-apps/messenger-issues#943]
After installing PulseSMS app on the watch, you are brought to a login screen to which you are allowed to type your email but not your password. There is no way to enter text into the password section. 

Please fix this issue, I am looking forward to using Pulse as my default sms application.

**Comment by klinker24** [comment]
I have been in discussion with Samsung on this issue. It is happening across more apps than just Pulse and the fix will need to come on their end.

**Comment by lovesarahh** [comment]
Thank you for your prompt reply!

Is there any way to sync the app through the pre-existing login from the
phone?

Sarah

**Comment by klinker24** [comment]
Sorry, no. The app requires the login information to be typed directly on the device for the end to end encryption.

**Comment by lovesarahh** [comment]
Understood, thank you for the update.

**Comment by klinker24** [comment]
I have confirmed the issue with my contact at Samsung. The problem is on their end and specific to the Galaxy Watch Active 2 (Bluetooth model). They have a fix planned. The software update is scheduled for December 23rd.

**Comment by lovesarahh** [comment]
Hi Luke,

I have waited patiently for the update, however, it has been several days
and the promised update has not appeared. I would really appreciate it if
you could refund my one - time subscription.

Thank you and happy holidays!
Sarah

**Comment by klinker24** [comment]
I cannot control Samsung's update schedule and can only pass along the information that they provide to me. I have reached out again to check on the status of the update. I will post here when I hear back about it.

I am not going to provide a refund based on a delay that I have no control over. They have told me that they fixed it and that an update will be released. That is all that I can pass on to you.
