### ISSUE TITLE
Beta: SMS messages show sending for "long" period of time. 

### ISSUE THREAD

**Issue by brycebba** [klinker-apps/messenger-issues#944]
- [ X ] I have [searched](https://github.com/klinker-apps/messenger-issues/issues), by keyword, for my problem to verify that there aren't any open or closed issues around this behavior.
- [ X ] I have [searched the help page](https://messenger.klinkerapps.com/help) to verify that it does not have any topics relevant to this issue. **it does but I have restarted several times and this started at the same time as I did a beta update for Pulse but I gave it time to see if it would go away**
- [ X ] I have verified that this is something that is reproducible.

**Device with issue: Note 8 on Sprint**
**Primary device: Note 8 on Sprint**
**App version: 4.14.4.2662 (I'm on Beta)**

**Describe the bug:**
Every SMS I send shows "Sending" for probably 30 seconds and I don't know if it actually sent earlier than that and it's just a display issue or if it's actually taking that long to send

**Steps to reproduce:**

1. Go to 'Conversations'
2. Click on 'any thread'
3. Type any message 'ex:Hello' (Length doesn't seem to matter)
4. See it stays in 'Sending' status for extended period of time where it used to almost go immediately to 'Now'

**Expected behavior:**
SMS messages should send quickly when you have adequate service

**Screenshots:**
None as they just say Sending which I think is pretty basic and really it just looks like that for extended periods

**Additional information:**
It does this whether I am on LTE 5 bars or LTE 2 bars or while connected to WiFi for data using LTE or whatever for SMS. This seems to be farely new, within the last maybe 2 or so beta releases

**Comment by klinker24** [comment]
Hmm. This is not something that I control, nor is it something that a Pulse update could affect.

Android provides a Broadcast when the message is marked as "sent" by the system, which Pulse receives. My app does not send messages at all. All that Pulse can do is hand off messages to Android and wait for the status. That is how all third party apps work.

You could try just restarting the phone, or reinstalling the app. Both would invalidate any carrier connections that could be causing issues. Unfortunately, I do not have any other recommendations. This just isn't something that an app can control or manage. All message sending is done at the system level, not the app level. Android simply has APIs built in to manage it.

https://stackoverflow.com/a/10384800

**Comment by brycebba** [comment]
Very good to know, thanks for the info!
