### ISSUE TITLE
Web App Visual Clean Up

### ISSUE THREAD

**Issue by iKermitKiller** [klinker-apps/messenger-issues#96]
The drawer has a white border on the right for some reason (Issue with MDL rather than with Messenger), it looks far better without them, so something like:
`.mdl-layout__drawer{ border-right: none; }`

I also think that .send-bar-content should be full width of the messaging area, something like this:
` max-width: calc(100% - 272px);`

Also it seems that number formatting is incorrect for any numbers which aren't US numbers.

**Comment by klinker24** [comment]
Number formatting comes directly from your contacts app, that should not be an issue

Thanks for your other suggestions

**Comment by iKermitKiller** [comment]
Numbers when messaging someone isn't an issue actually. When on the home page though, my own number isn't formatted correctly. I don't have my own number stored in my contacts so it's not pulling from my own contacts.

**Comment by klinker24** [comment]
It pulls it from your SIM card and allows you to type it when you sign up for an account.

**Comment by klinker24** [comment]
I have deployed your two CSS changes: https://github.com/klinker41/messenger-web/commit/7596ce12539c92b1be98e88fa09aa5c3257e1e55

Thanks for the help!
