### ISSUE TITLE
Messages sent from other apps aren't always saved

### ISSUE THREAD

**Issue by BlackScorpion3** [klinker-apps/messenger-issues#97]
_Edited by @klinker24_

**Device with issue:** Primary Devices
**App version:** 1.4
**Steps to reproduce:**

(inconsistent)
1. Set another app as your default app, or test using pushbullet.
2. Send a message
3. Open up our app and see that the message didn't get saved.

**Additional information:**

We use a `ContentObserverService` to listen for new messages that get inserted into the database. See comments below for issues with this.

**Possible solution:**

Fix the service so that it does not shut down.

**Comment by klinker24** [comment]
Please use the template specified in the readme for future submissions.

I agree that there should be a way to pull in the latest messages from the internal sms/mms database if you do not have our app set as the default. This is something that may come later in the future.

**Comment by klinker41** [comment]
Or better yet, don't add crappy workaround options that just inflate the app and make it more complicated than it needs to be and instead fix the actual issue in the `ContentObserverService`.

**Comment by klinker24** [comment]
I would imagine that the service is just shutting itself down, since it isn't (and won't be), a [foreground service](https://developer.android.com/guide/components/services.html#Foreground).

I think I just need to find a way to check to see if it is running or not, and if not, restart it. Need to come up with a good timeout to check to see if it is running, and restart it. Maybe every 15 mins or something. Would have no effect on battery

**Comment by klinker41** [comment]
Make sure that you also check out the logic in that service, it is a little wacky and could use some cleanup. Don't remember what I was really going for when I wrote it, it's just tough to see if a message already exists in our database or not when it's text is not unique.

**Comment by klinker24** [comment]
Implemented with: https://github.com/klinker41/messenger/commit/b3505c03a39d68564aea1b02899abd24beec47a1

@klinker41 if you want to check it out and make sure it looks ok, go for it. Hopefully this will do the trick.

**Comment by klinker41** [comment]
I doubt that all of the issues were coming from the service not running all the time, I would make sure that you look in the logic too if you didn't already.

**Comment by klinker24** [comment]
I don't see any problems with your logic itself, that is straightforward. Checking to see if the exact same message exists or not, if it doesn't, insert it.

The only thing i am curious about is the 10 second timeout, what is that for?

I do think that most of the issues are coming from the service getting shut down though. I have found, with talon, that devices have a vast range of shutdown times on service. It really just depends on how heavy the user is, how many apps they have, and what the system deems as acceptable run time.

**Comment by klinker41** [comment]
I think that was for making sure that the message was saved in our database
before checking to see if it was there.

**Comment by klinker24** [comment]
Gotcha. I am going to turn that down a bit then, just because rapid messages might hit that 6 seconds pretty quick. Might feature flag it though, just in case
