### ISSUE TITLE
Message Not Found MMS 

### ISSUE THREAD

**Issue by officiallybob** [klinker-apps/messenger-issues#98]
Received 2 MMS from my security camera. First one came through fine. Second one was sent 1 minute later and the Messenger App created a thread titled "Message not found" that contained a single "Message not found" message (see picture).

However, I still have Textra installed as a backup since I just installed Messenger yesterday and hadn't uninstalled it yet. Textra shows both messages from my security camera properly.

I have attempted to replicate this by manually sending multiple MMS from the camera and haven't been able to make it happen again yet. I will keep trying. However, I can say that I have experienced this before with other SMS apps like EvolveSMS and the built in Samsung messaging app. So this might have something to do with how AT&T handles MMS.

This is on an AT&T Galaxy S7 running Android 6.0.1.
App version is 1.4.371

![screenshot_20160920-110107](https://cloud.githubusercontent.com/assets/2945906/18675963/0e9aa38e-7f22-11e6-9dd3-05a9d18716db.png)

**Comment by klinker24** [comment]
If it is happening across different apps, then I would say that this is not an issue with this app, I am going to close this one, sorry.
