### ISSUE TITLE
GIFS don't show for me once sent/received. Also, GIFS show up as image_0.mms on iPhone

### ISSUE THREAD

**Issue by bammeh** [klinker-apps/messenger-issues#99]
Whenever receiving/sending a GIF to anyone(even Android users(, it shows as a blank bubble on the app for me. Using a nexus 6P with Nougat. 

Also, my sent GIFs show up as image_0.mms for iPhone users. Tested and it only happens with this app :(

**Comment by klinker24** [comment]
Please follow the requested issue template in the future.

**Comment by klinker24** [comment]
Duplicate here: https://github.com/klinker-apps/messenger-issues/issues/101
